- api/kie-api/src/main/java/org/kie/submarine/rules/DataSource.java
- api/kie-api/src/main/java/org/kie/submarine/rules/RuleUnit.java
- api/kie-api/src/main/java/org/kie/submarine/rules/RuleUnitInstance.java
- api/kie-api/src/main/java/org/kie/submarine/rules/Unit.java
- api/kie-api/src/main/java/org/kie/submarine/rules/impl/AbstractRuleUnit.java
- api/kie-api/src/main/java/org/kie/submarine/rules/impl/AbstractRuleUnitInstance.java
- api/kie-api/src/main/java/org/kie/submarine/rules/impl/ListDataSource.java
- drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/CanonicalModelKieProject.java
- drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/ModelSourceClass.java
- drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/ModelWriter.java
- drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/PackageModel.java
- drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/ProjectSourceClass.java
- drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/generator/ModelGenerator.java
- drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/generator/ModuleSourceClass.java
- drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/generator/RuleUnitInstanceSourceClass.java
- drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/generator/RuleUnitSourceClass.java
- kie-maven-plugin/pom.xml
- kie-maven-plugin/src/main/java/org/kie/maven/plugin/CanonicalModelWriter.java
- kie-maven-plugin/src/main/java/org/kie/maven/plugin/GenerateModelMojo.java
- kie-maven-plugin/src/main/java/org/kie/maven/plugin/ResourceFileWriter.java
API we discussed together:
- `RuleUnit<T>/RuleUnitInstance<T>`
- one KieSession per RuleUnitInstance
- generated Module class with  code-generated `create${T}RuleUnit()`
- refactored Maven plugin
see examples for reference https://github.com/kiegroup/submarine-examples/pull/5
> DROOLS-3763: New API codegen prototype

- kie-maven-plugin/src/main/java/org/kie/maven/plugin/GenerateProcessModelMojo.java
Previously: the KieBuilderImplWhatever infrastracture is slow to boot (lots of classes, lots of dynamic loading, assemblers, kie.confs etc etc etc) and also hard do customize. In this case we want to just run *only* the BPMN process builder, but our infrastructure requires DRL files to be processed as well. This is useless work (there's a different MOJO for DRLs) and it's also the root cause of some weird behaviors (DRL evaluation might error out even though the file is correct only because the KieBuilder is misconfigured).
In short: instead of using `kieBuilder`, I am bypassing the building API completely and just using XmlProcessReader because all of the KieBuild* infrastructure is already provided by Maven. So, bye-bye assemblers, KieServices and all their friends 👋👋👋
I see no …
> DROOLS-3834: Process generation in jBPM Mojo should not cause DRL compilation

- Jenkinsfile
This PR serves as a test PR for new automation.
> Build submarine-examples with user changes in PRs

- submarine-codegen/pom.xml
- submarine-codegen/src/main/java/org/kie/submarine/codegen/ApplicationGenerator.java
- submarine-codegen/src/test/java/org/kie/submarine/codegen/ApplicationGeneratorTest.java
- submarine-codegen/src/test/java/org/kie/submarine/codegen/ConfigGeneratorTest.java
- submarine-codegen/src/test/java/org/kie/submarine/codegen/GeneratedFileTest.java
- submarine-codegen/src/test/java/org/kie/submarine/codegen/GeneratorInterfaceTest.java
- submarine-codegen/src/test/java/org/kie/submarine/codegen/metadata/ImageMetaDataTest.java
- Adds first few unit tests
- Fixes writing image metadata file in ApplicationGenerator - it failed to create the file when any of its path directories was not created 
Please squash if merging.
> DROOLS-3978 Add first bunch of unit tests for submarine-codegen

- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/DummyKnowledgeRuntime.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/LightProcessRuntime.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/LightProcessRuntimeContext.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessRuntimeContext.java
kruntime is there for legacy purposes. This PR removes useless API from ProcessRuntimeContext (getWorkItemManager()) because it's already in the ProcessRuntimeServiceProvider, which is already consumed by LightProcessRuntime, and returns the workItemManager instance that its in the service provider.
kruntime delegates to LightProcessRuntime
Rule of thumb: new code should not rely on kruntime, because that's a legacy interface that should go away. The dummy kruntime (if necessary) should only delegate to LightProcessRuntime
> JBPM-8437: LightProcessRuntime should not pull WorkItemManager from kruntime

- jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/ServiceTaskHandler.java
- jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/canonical/ActivityGenerationModelTest.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/LambdaSubProcessNodeVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessMetaData.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/WorkItemNodeVisitor.java
- jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcess.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/ApplicationGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/GeneratedFile.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/Generator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ModuleGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/ModuleSourceClass.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/RuleCodegen.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/AbstractCodegenTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/ApplicationGeneratorTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/GeneratorInterfaceTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/data/HelloService.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/ServiceTaskTest.java
- kogito-codegen/src/test/resources/servicetask/ServiceProcess.bpmn2
- kogito-codegen/src/test/resources/servicetask/ServiceProcessDifferentOperations.bpmn2
- kogito-codegen/src/test/resources/servicetask/ServiceProcessSameOperations.bpmn2
Adds support for service tasks that allow to call java classes/methods. It does allow to call cdi beans when running in quarkus so it make it really easy to use application code inside the process. No reflection involved. Each service task will get generated and auto registered work item handler that can also be injected and thus can receive other beans like the service class.
See the jbpm-quarkus-example for details how it makes use of the cdi beans as service task in a process.
depends on https://github.com/kiegroup/kogito-bom/pull/27
> JBPM-8533 - Service task support (java invocation)

- archetypes/kogito-quarkus-archetype/README.md
- archetypes/kogito-springboot-archetype/README.md
- archetypes/kogito-springboot-archetype/src/main/resources/archetype-resources/src/main/java/KogitoApplication.java
@mswiderski the kogito-maven-plugin already generates Application.java under target/generated-sources. This clashes with the Application.java for the spring-boot app, so thats why I renamed it to KogitoApplication.java. 
I think maybe its better to have the kogito-maven-plugin generate under a different name, but maybe this is a valid option as well. Either way we need something to change in order for the spring-boot archetype generated project to compile and run properly.
> fixes for quarkus and springboot archetypes

- pom.xml
@mareknovotny could you please take a look
> add missing pom.xml configuration to meet release rules for repository

- archetypes/kogito-springboot-archetype/src/main/resources/archetype-resources/pom.xml
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/GenerateModelMojo.java
MAKE CODEGEN GREAT AGAIN 💣
- enable model generation by default.
contextually rename properties as follows:
- `kogito.codegen.rules` : boolean -- enable codegen for rules. Defaults to null, meaning that codegen is enabled iff DRLs are found
- `kogito.codegen.processes` : boolean -- enable codegen for processes. Defaults to null, meaning that codegen is enabled iff BPMNs are founds 
- `kogito.sources.keep` : boolean -- keep DRL files in the generated artifact. Defaults to false.
- `kogito.di.enabled` : boolean  -- generate dependency injection annotation. Defaults to true.
> DROOLS-4160: Enable DRL codegen by default, rename config properties

- kogito-codegen/src/main/java/org/kie/kogito/codegen/AbstractApplicationSection.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/ApplicationGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/ApplicationSection.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessesContainerGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/RuleUnitContainerGenerator.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/AbstractCodegenTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/ApplicationGeneratorTest.java
Verified that this work by adding the following to my local copy of https://github.com/quarkusio/quarkus-quickstarts/tree/development/using-kogito
```
<dependency>
<groupId>org.kie.kogito</groupId>
<artifactId>kogito-codegen</artifactId>
<version>8.0.0-SNAPSHOT</version>
</dependency>
```
new release? @mswiderski @mariofusco
> DROOLS-4242: NPE in Kogito Quickstart: broken codegen

- kogito-codegen/pom.xml
- kogito-codegen/src/test/java/org/kie/kogito/codegen/ApplicationGeneratorTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/ConfigGeneratorTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/GeneratedFileTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/GeneratorInterfaceTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/RuleUnitCompilerTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/metadata/ImageMetaDataTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/BusinessRuleTaskTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/CallActivityTaskTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/ServiceTaskTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/SignalEventTest.java
This is fairly straightforward. All tests passing before, all tests passing now.
> KOGITO-4: Migrate codegen to JUnit 5

- Jenkinsfile-sonarcloud-daily
- drools/drools-compiler/pom.xml
- drools/drools-core/pom.xml
- jbpm/jbpm-flow/pom.xml
- pom.xml
Brings:
- code coverage measurements
- daily static code analysis in SonarCloud for a master branch
- PR analysis
Depends on https://github.com/kiegroup/kogito-bom/pull/33
The Jenkinsfile-sonarcloud-daily has been tested via a job located in KIE/Test-jobs/sonarcloud/kogito-runtimes-nightly.
> BAQE-975 Enable SonarCloud analysis for kogito-runtimes

- archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/pom.xml
Applying the same dependencyManagement from kogito-examples/pom.xml. It may not be fully required for the test-process but aligning with kogito-examples sounds good to me.
> [KOGITO-70] kogito-quarkus-archetype pom dependencyManagement

- kogito-codegen/src/main/java/org/kie/kogito/codegen/metadata/ImageMetaData.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessExecutableModelGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/RuleCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/RuleUnitSourceClass.java
very simple change. Add rule unit labels to the collection, should be written in the output file, like processes.
> KOGITO-101: Add Kube labels for rule endpoints

- data-index/data-index-service/src/main/resources/application.properties
Super simple change that makes this work:
```
export MP_MESSAGING_INCOMING_KOGITO_PROCESSINSTANCES_EVENTS_BOOTSTRAP_SERVERS=999999
```
And then the server is correctly set:
```
java -jar data-index-service-8.0.0-SNAPSHOT-runner.jar 
2019-08-27 19:10:41,092 INFO  [io.sma.rea.mes.ext.MediatorManager] (main) Deployment done... start processing
2019-08-27 19:10:41,097 INFO  [io.sma.rea.mes.imp.ConfiguredChannelFactory] (main) Found incoming connectors: [smallrye-kafka]
2019-08-27 19:10:41,098 INFO  [io.sma.rea.mes.imp.ConfiguredChannelFactory] (main) Found outgoing connectors: [smallrye-kafka]
2019-08-27 19:10:41,098 INFO  [io.sma.rea.mes.imp.ConfiguredChannelFactory] (main) Stream manager initializing...
2019-08-27 19:10:41,103 WARN  [io.sma.rea.mes.kaf.KafkaSource] (main) No `group.id` set …
```
> [KOGITO-196] Setting default bootstrap server to handle env vars

- drools/drools-core/src/main/java/org/drools/core/ruleunit/impl/ListDataStore.java
- jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/BusinessRuleTaskHandler.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/AbstractVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/LambdaSubProcessNodeVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessToExecModelGenerator.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/RuleSetNodeVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/xml/processes/RuleSetNodeHandler.java
- jbpm/jbpm-flow-builder/src/main/resources/class-templates/RuleUnitFactoryTemplate.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/RuleSetNodeFactory.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/validation/RuleFlowProcessValidator.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/node/RuleSetNode.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/node/RuleUnitFactory.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/RuleSetNodeInstance.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/RuleCodegenProject.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/RuleUnitContainerGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/RuleUnitSourceClass.java
- kogito-codegen/src/main/resources/class-templates/rules/RuleUnitTemplate.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/BusinessRuleUnit.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/BusinessRuleUnitTest.java
- kogito-codegen/src/test/resources/org/kie/kogito/codegen/tests/BusinessRuleUnit.bpmn2
- kogito-codegen/src/test/resources/org/kie/kogito/codegen/tests/BusinessRuleUnit.drl
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/GenerateModelMojo.java
Initial implementation for runtime logic of https://github.com/kiegroup/kogito-examples/pull/72. this is still **WIP**
- refactored BusinessRuleTask implementation so that it includes a RuleType, which may be RuleFlowGroup, RuleUnit, Decision, with respective parameters.
- added code-generation:
```java
org.jbpm.ruleflow.core.factory.RuleSetNodeFactory ruleSetNode2 = factory.ruleSetNode(2);
ruleSetNode2.name("Evaluate person");
// no longer a lambda, the RuleUnit is given
ruleSetNode2.ruleUnit("PersonValidationService", 
app.ruleUnits().createPersonValidationServiceRuleUnit());
ruleSetNode2.inMapping("persons", "person");
ruleSetNode2.outMapping("persons", "person");
...
ruleSetNode2.done();
```
- added handling logic for runtime
```
} else if (ruleType.isRuleUnit()) {
RuleUnitMemory> …
```
> KOGITO-102: jBPM Rule Unit integration 

- data-index/data-index-service/src/main/resources/META-INF/hotrod-client.properties
- data-index/data-index-service/src/main/resources/META-INF/kogito-cache-default.xml
- data-index/data-index-service/src/test/resources/META-INF/hotrod-client.properties
- data-index/data-index-storage/data-index-storage-infinispan/src/main/java/org/kie/kogito/index/infinispan/cache/InfinispanCacheManager.java
- data-index/data-index-storage/data-index-storage-infinispan/src/main/java/org/kie/kogito/index/infinispan/cache/KogitoCacheDefaultConfiguration.java
externalize authentication options
See:
https://issues.jboss.org/browse/KOGITO-222
In this PR:
1. We can now leverage from the externalize authentication options. Unfortunately we have to use the `hotrod-client.properties` with system property substitutions. I'll update the kogito-data-index image to also have those properties set on the start up
2. Create the cache if not exists in the remote server. Even if the **template** does not exist. In the cloud, will be impossible to manage the Infinispan configuration and caches that the application needs. So, if the template or the cache are not configured, we have now a default option
> [KOGITO-222] Add support for creating cache programmatically and

- drools/drools-compiler/src/main/java/org/kie/kogito/rules/InterpretedRuleUnit.java
- drools/drools-compiler/src/main/java/org/kie/kogito/rules/InterpretedRuleUnitInstance.java
- drools/drools-compiler/src/test/java/org/kie/kogito/rules/HelloWorld.java
- drools/drools-compiler/src/test/java/org/kie/kogito/rules/InterpretedRuleUnitTest.java
- drools/drools-compiler/src/test/resources/org/kie/kogito/rules/HelloWorld.drl
This is the exact equivalent of [BpmnProcess](https://github.com/kiegroup/kogito-runtimes/blob/79cec20bd06195840671d1528f07d18e8d5ec695/jbpm/jbpm-bpmn2/src/main/java/org/kie/kogito/process/bpmn2/BpmnProcess.java#L35-L34) but for rule units. See test for example usage.
> KOGITO-245: Rule Unit implementation for non-codegenerated use cases

- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/RuleSetNodeVisitor.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/node/RuleSetNode.java
- kogito-codegen/pom.xml
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/BusinessRuleUnit.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/BusinessRuleUnitTest.java
- kogito-codegen/src/test/resources/org/kie/kogito/codegen/tests/BusinessRuleUnit.drl
- kogito-codegen/src/test/resources/org/kie/kogito/codegen/tests/BusinessRuleUnitAlternateSyntax.bpmn2
- use correctly `add` or `append` method when using different kinds of data sources (store and stream respectively)
- add back support for ruleFlowGroup="unit:fully.qualified.ClassName" for interim compat with editors
> KOGITO-304: Rule Unit fixes for BPMN integration

- kogito-codegen/src/main/java/org/kie/kogito/codegen/AbstractGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/ApplicationGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/metadata/Labeler.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/metadata/PrometheusLabeler.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegen.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/ApplicationGeneratorTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/metadata/PrometheusLabelerTest.java
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/GenerateModelMojo.java
See:
https://issues.jboss.org/browse/KOGITO-290
In this PR we added the support for the Prometheus labels in the  `image_metadata.json` file. The final result is going to be like this:
```json
cat rain-forecast-process/target/image_metadata.json 
{
"labels" : [ {
"org.kie/rainforecast" : "process",
"prometheus.io/path" : "/metrics",
"prometheus.io/scheme" : "http",
"prometheus.io/port" : "8080",
"prometheus.io/scrape" : "true"
} ]
}
```
**TODO:**
[x]  - Unit tests
> [KOGITO-290] - Adding Prometheus label metadata to codegen

- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessToExecModelGenerator.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/WorkItemNodeVisitor.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/ServiceTaskTest.java
- kogito-codegen/src/test/resources/servicetask/ServiceProcessInferMethod.bpmn2
Currently it looks like the parameter type for the WorkItem generated handler is taken from the type of the input `Parameter`. However, if the input `Parameter` is not a variable (e.g. a constant or an expression) it is just defaulted to `java.lang.Object`
This modification does a bit of reflection *at compile time* attempting to look up the given interface and operation; for a given interface X and operation y, it looks up method `X#y(T)` and tries to infer `ParameterType` to `T` when `ParameterType` is `java.lang.Object` instead of relying on the type declaration of the inputType.
> KOGITO-412: Infer parameter type for workitems (processes)

- kogito-codegen/src/main/java/org/kie/kogito/codegen/ApplicationGenerator.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/ApplicationGeneratorTest.java
now it throws if the package name is invalid. On a slightly-related note, we found out about this bug because a user was using dashes inside their groupId. I was wondering whether we really need to use a packageName == groupId instead of a default package name like quarkus. Doing so could simplify a few assumptions we make sometimes (e.g., where `Application` class is)
> KOGITO-388: ApplicationGenerator breaks when packageName contains hyphens

- drools/drools-model/drools-mvel-parser/pom.xml
depends on https://github.com/kiegroup/kogito-bom/pull/64
> KOGITO-463 - Move to javax.annotation-api instead of jsr250-api

- kogito-codegen/src/main/java/org/kie/kogito/codegen/metadata/PersistenceLabeler.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/metadata/PersistenceLabelerTest.java
See:
https://issues.jboss.org/browse/KOGITO-496
Now we are compressing the protobuf file content as a workaround for the OpenShift labels limit size until we finish the new solution to those files during runtime.
Related:
https://github.com/kiegroup/kogito-cloud-operator/pull/99
> [KOGITO-496] Writing compressed labels for protobuf files

- data-index/data-index-service/src/main/resources/META-INF/hotrod-client.properties
- data-index/data-index-service/src/main/resources/META-INF/kogito-cache-default.xml
After having this PR (https://github.com/quarkusio/quarkus/pull/4502) merged, we don't need to rely on properties override in the hotrod-client.properties in the classpath.
For more info see:
https://quarkus.io/guides/infinispan-client-guide#quarkus-infinispan-client_configuration
> [KOGITO-309] - Removing custom hotrod-client.properties

- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/MissingDecisionTableDependencyError.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/RuleCodegenError.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegenTest.java
- kogito-codegen/src/test/resources/org/drools/simple/broken.drl
An helpful error message is now printed when XLS are present, but the DTABLE dependency is missing
```
2019-11-26 10:56:33,120 [main] ERROR A Decision Table resource was found, but a necessary dependency is missing. 
Verify you have added decision table support to your project dependencies: 
<dependency>
<groupId>org.kie.kogito</groupId>
<artifactId>drools-decisiontables</artifactId>
</dependency>
```
> KOGITO-641: Build fails processing dtable, when no drools-decisiontables

- addons/pom.xml
- data-index/pom.xml
- pom.xml
otherwise it will bring an older version of kogito-runtimes
as a transitive dependency
> KOGITO-639: kogito-runtimes pom should not depend on quarkus

- addons/jobs/jobs-service/pom.xml
@cristianonicolai the `runner` jar artifact was not being published on maven, see http://repo2.maven.org/maven2/org/kie/kogito/jobs-service/0.6.0/ and comparing to the data-index http://repo2.maven.org/maven2/org/kie/kogito/data-index-service/0.6.0/ that was published.
So, comparing the `quarkus-maven-plugin` I inserted the configuration for uberJar, and now it is being published.
> Jobs service - publish the jobs-service-runner.jar on maven

- archetypes/kogito-springboot-archetype/src/main/resources/archetype-resources/src/main/resources/application.properties
- archetypes/kogito-springboot-starter/pom.xml
I added "http*" for archetype application.properties so that generated DMN REST classes can be scanned. A package name of a DMN REST class is generated from its namespace. So this configuration works when DMN namespace starts from "http" or "https". According to DMN spec, namespace is anyURI. So it's not constrained to http/https but it's a reasonable default value for archetype?
> namespace: anyURI [1] | This attribute identifies the namespace associated with this Definitions and follows the convention established by XML Schema.
I manually tested by dropping TrafficViolation.dmn (https://github.com/kiegroup/kogito-runtimes/blob/master/drools/kogito-dmn/src/test/resources/org/kie/kogito/dmn/TrafficViolation.dmn) into the generated project and confirmed that the generated REST endpoint …
> [KOGITO-336] Include DMN inside of Spring Boot archetype

- jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/BoundaryEventHandler.java
For this PR I am following what I read in the BPMN XSD[1] for cancelActivity attribute:
~~~
<xsd:complexContent>
<xsd:extension base="tCatchEvent">
<xsd:attribute name="cancelActivity" type="xsd:boolean" default="true"/>
<xsd:attribute name="attachedToRef" type="xsd:QName" use="required"/>
</xsd:extension>
</xsd:complexContent>
</xsd:complexType>
~~~
Where:
* It is required (hence why the null checking)
* default is true
This solved the issue from KOGITO-831.
[1] https://www.omg.org/spec/BPMN/20100501/Semantic.xsd
> KOGITO-831: NPE when cancelActivity is marked in editor

- drools/kogito-ruleunits/src/main/java/org/kie/kogito/rules/units/annotations/When.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/AnnotatedClassPostProcessor.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegen.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/AbstractCodegenTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/AnnotatedRuleUnitCompilerTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/unit/AnnotatedRules.java
An annotation processor is provided to pre-process a Java class and generate a corresponding DRL file (in the future we should skip the intermediate DRL file)
```java
public class AnnotatedUnit implements RuleUnitMemory {
private final DataStore<Person> persons = DataSource.createStore();
public void adultRule(
@When("/persons[ age >= 18 ]") Person adult,
@When("/persons[ age != 0 ]") Person anotherBinding) {
System.out.printf("%s is an adult\n", adult.getName());
}
...
```
The DRL file contains one rule per annotated method;
- the method name is the rule name
- each annotated parameter is a condition
- the parameter is the binding for that condition  
- the RHS of the rule **delegates** to the method, passing the matched variables
e.g., consider the generated code for the rule above: …
> KOGITO-183: Explore annotation-based rule definition

- addons/jobs/jobs-service/src/main/resources/application.properties
@ricardozanini as we talk on the chat, this PR is disabling by default the log color on the console to follow the same pattern as the other services.
One other point that maybe it is worth to discuss is the log format, it could be the same pattern on all services.
@mswiderski ^
> [Jobs Service] - disable quarkus log console color

- addons/jobs/jobs-service/pom.xml
- addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/events/JobDataEvent.java
- addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/stream/KafkaJobStreams.java
- addons/jobs/jobs-service/src/main/resources/application.properties
- api/kogito-api/src/main/java/org/kie/kogito/event/AbstractDataEvent.java
- api/kogito-services/src/main/java/org/kie/kogito/services/event/AbstractProcessDataEvent.java
- api/kogito-services/src/main/java/org/kie/kogito/services/event/ProcessInstanceDataEvent.java
- api/kogito-services/src/main/java/org/kie/kogito/services/event/UserTaskInstanceDataEvent.java
Modifications needed for the Jobs Service and Data Index integration.
- Unique event UUID
- Source based on the service URL configuration
-  Process metadata on the event attributes + refactoring on the `AbstractProcessDataEvent` to share the common attributes on all events.
@cristianonicolai here are the modifications we talked to regarding the jobs-service and data-index integration.
@mswiderski
> [Jobs Service] Refactoring events structure

- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/AbstractResourceGenerator.java
`org.kie.kogito.codegen.process.AbstractResourceGenerator` was refactored to use fileSeparator instead of forward slashes, causing windows build to break.
- compilation on quarkus extension goes through in-memory file system which assumes forward slashes
- if we do not mix forward and back-slashes it's ok, since Windows allows for forward slashes in paths
> KOGITO-929: Fix mixed-up slashes in code generation

- drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/rest/DMNDecisionInfo.java
- drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/rest/DMNDecisionResultSQ.java
- drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/rest/DMNDecisionServiceInfo.java
- drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/rest/DMNInputDataInfo.java
- drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/rest/DMNItemDefinitionInfo.java
- drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/rest/DMNMessageSQ.java
- drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/rest/DMNModelInfo.java
- drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/rest/DMNModelInfoList.java
- drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/rest/DMNResult.java
- drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/rest/DMNUnaryTestsInfo.java
Dropped all @JsonProperty from kogito-dmn classes to rely on field names. I think it's safe because:
- kogito-dmn is depended only by kogito-codegen for templating REST endpoint classes. Thus, dropping @JsonProperty doesn't affect kogito-codegen (and no other project).
- According to https://github.com/kiegroup/kogito-runtimes/pull/136 discussion, we don't/won't need to keep consistency between XML and JSON format. Indeed, Kogito consumes/produces only JSON at the moment.
I tested the change using dmn-quarkus-example:
~~~
$ curl -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' -d '{"DriverXX":{"Points":2},"Violation":{"Type":"speed","Actual Speed":120,"Speed Limit":100}}' http://localhost:8080/Traffic%20Violation …
> [KOGITO-223] DMN review serialization annotations

- kogito-codegen/pom.xml
- kogito-codegen/src/main/resources/class-templates/MessageConsumerTemplate.java
- kogito-codegen/src/main/resources/class-templates/MessageProducerTemplate.java
- kogito-codegen/src/main/resources/class-templates/ProcessesTemplate.java
- kogito-codegen/src/main/resources/class-templates/ReactiveRestResourceTemplate.java
- kogito-codegen/src/main/resources/class-templates/RestResourceTemplate.java
master is currently broken (not sure why), this change also removes usages of such annotations in some places where it's not necessary (e.g. PostConstruct can be usually substituted by a generated constructor)
> KOGITO-1015: Fix usages of javax.annotation.{PostConstruct, ...}

- api/kogito-api/src/main/java/org/kie/kogito/conf/Clock.java
- api/kogito-api/src/main/java/org/kie/kogito/conf/ClockType.java
- api/kogito-api/src/main/java/org/kie/kogito/conf/EventProcessingType.java
- api/kogito-api/src/main/java/org/kie/kogito/rules/RuleConfig.java
- api/kogito-api/src/main/java/org/kie/kogito/rules/RuleUnitConfig.java
- api/kogito-internal/src/main/java/org/kie/internal/ruleunit/RuleUnitDescription.java
- drools/drools-core/src/main/java/org/drools/core/config/StaticRuleConfig.java
- drools/kogito-ruleunits/src/main/java/org/kie/kogito/rules/units/AbstractRuleUnitDescription.java
- drools/kogito-ruleunits/src/main/java/org/kie/kogito/rules/units/GeneratedRuleUnitDescription.java
- drools/kogito-ruleunits/src/main/java/org/kie/kogito/rules/units/ReflectiveRuleUnitDescription.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/GeneratorContext.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/config/NamedRuleUnitConfig.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/rules/config/NamedRuleUnitConfigTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/unit/AdultUnit.java
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/GenerateModelMojo.java
add support for config properties in `application.conf`
```
kogito.rules."my.rule.Unit".event-processing-type = [CLOUD | STREAM] # default = CLOUD
kogito.rules."my.rule.Unit".clock-type" = [REALTIME | PSEUDO] # default = REALTIME
kogito.rules."my.rule.Unit".sessions-pool = [>1] # default = null
```
> KOGITO-888: Use properties to configure rules

- kogito-codegen/src/main/java/org/kie/kogito/codegen/ApplicationGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/KogitoPackageSources.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/DeclaredTypeCodegen.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/rules/DeclaredTypeCodegenTest.java
- kogito-codegen/src/test/resources/org/kie/kogito/codegen/declared/declared.drl
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/GenerateDeclaredTypes.java
- kogito-maven-plugin/src/main/resources/META-INF/plexus/components.xml
add a new "generator" that processes declared types separately from the rest of the rules
note: this is sort-of a "hack". 
The same internal "knowledge builder" is used to first process the declared types, skipping the rest; then it processes the full rule base, now including rules as well. 
Declared Types are therefore processed *twice*: first by this processor, then by the "regular" processor. We can fix this later, by actually separating the two processing phases, but, because the operation is basically idempotent (even if it runs twice, it will produce the same results and overwrite) we can get the benefit of separate compilation with little effort.
> KOGITO-894: Allow separate compilation of declared types

- data-index/data-index-service/pom.xml
- data-index/data-index-service/src/main/resources/application.properties
- data-index/data-index-storage/data-index-storage-infinispan/pom.xml
- data-index/data-index-storage/data-index-storage-infinispan/src/main/java/org/kie/kogito/index/infinispan/InfinispanHealthCheckProducer.java
Adding the health check for kafka and infinispan in the same way as the jobs-service.
> KOGITO-458 Add health check for Data Index service

- addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/model/ScheduledJob.java
- addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/repository/ReactiveJobRepository.java
- addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/repository/impl/InMemoryJobRepository.java
- addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/repository/impl/JobRepositoryDelegate.java
- addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/repository/infinispan/InfinispanJobRepository.java
- addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/repository/infinispan/marshaller/BaseMarshaller.java
- addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/repository/infinispan/marshaller/ScheduledJobMarshaller.java
- addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/scheduler/BaseTimerJobScheduler.java
- addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/scheduler/JobScheduler.java
- addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/scheduler/JobSchedulerManager.java
- addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/scheduler/ReactiveJobScheduler.java
- addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/scheduler/impl/VertxJobScheduler.java
- addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/utils/DateUtil.java
- addons/jobs/jobs-service/src/main/resources/application.properties
- addons/jobs/jobs-service/src/test/java/org/kie/kogito/jobs/service/repository/impl/BaseJobRepositoryTest.java
- addons/jobs/jobs-service/src/test/java/org/kie/kogito/jobs/service/repository/impl/InMemoryJobRepositoryTest.java
- addons/jobs/jobs-service/src/test/java/org/kie/kogito/jobs/service/repository/infinispan/InfinispanJobRepositoryTest.java
- addons/jobs/jobs-service/src/test/java/org/kie/kogito/jobs/service/resource/InfinispanServerTestResource.java
- addons/jobs/jobs-service/src/test/java/org/kie/kogito/jobs/service/scheduler/BaseTimerJobSchedulerTest.java
- addons/jobs/jobs-service/src/test/java/org/kie/kogito/jobs/service/scheduler/JobSchedulerManagerTest.java
- addons/jobs/jobs-service/src/test/java/org/kie/kogito/jobs/service/scheduler/impl/VertxJobSchedulerTest.java
- addons/jobs/jobs-service/src/test/resources/application.properties
Schedule and load jobs in chunks, expressed in a period of time that can be configured, for instance, next 10 minutes, 30 minutes,  60 minutes...
The scheduler just handles the jobs in the current chunk in this way it is not necessary to schedule jobs that are supposed to be executed in a long time in the future.
Besides, it was added the jobs load prioritization.
> KOGITO-855 - [Jobs Service] improve persisted jobs loading

- Jenkinsfile
- Jenkinsfile-sonarcloud-daily
- pom.xml
The change in reporting coverage is similar to https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1186.
Other than that, this PR also:
- redefines how the code coverage is measured - by using jacoco maven plugin to construct an argument line for surefire instead of defining it manually
- binds the reporting to an earlier phase (validate) to avoid unnecessarily triggering some other maven plugins
> BAQE-1054 Enable cross-module coverage for XML reports

- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/AbstractVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/HumanTaskNodeVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/RuleSetNodeVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/RuleUnitHandler.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/RuleUnitMetaModel.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/WorkItemNodeVisitor.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/node/RuleSetNode.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/RuleUnitPojoGenerator.java
- kogito-codegen/src/test/resources/ruletask/Generated.drl
We have introduced the SingletonStore: a data store for single-values. In this PR we use it for workflow-generated rule units; i.e. rule units that transparently "see" process variables
> KOGITO-893: Use Singleton DataSource in processes+rules

- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ModelMetaData.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/KogitoCodeGenConstants.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/context/QuarkusKogitoBuildContext.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/context/SpringBootKogitoBuildContext.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/AbstractResourceGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/InputModelClassGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ModelClassGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/OutputModelClassGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ReactiveResourceGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ResourceGenerator.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/AbstractCodegenTest.java
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/AbstractKieMojo.java
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/GenerateModelMojo.java
- kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
- kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoCompilationProvider.java
This PR brings support for validation api to enhance the generated REST api
In general it allows to use validation api annotations on model classes and then the generated api will enforce this validation. See some details in jira
So an example here could be to use following model
```
import javax.validation.constraints.Email;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
public class Person {
@NotNull
@Size(min = 2, max = 30)
private String name;
@NotNull
@Min(value = 2, message = "Age must be higher than 5")
private int age;
@NotNull
@Email
private String email;
private boolean adult;
```
and this will then generated following input data model for process that references this type as variable
```
public …
```
> KOGITO-1264 - Allow to use Validation API to enhance generated REST api

- archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/pom.xml
- archetypes/pom.xml
apparently last PR broke (at least locally) the archetype installation in some cases.
This should fix everything and bring in the correct dependencies
> KOGITO-1298: Update quarkus archetype to use our new bom (fix properties)

- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/RuleCodegenError.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegenTest.java
- kogito-codegen/src/test/resources/org/kie/kogito/codegen/brokenrules/brokenunit/ABrokenUnit.drl
see ticket for details https://issues.redhat.com/browse/KOGITO-1262
the problem was in Drools core we are throwing an exception, but really we should stop building earlier because earlier errors prevent the rest of the DRL from being processed meaningfully.
I have implemented a workaround to collect exceptions and print them as errors, but we should probably fix this in Drools core as well.
> KOGITO-1262: Unclear error message when using oopath + units

- Jenkinsfile.deploy
the deploy job for kogito (maybe not at the best place here in kogito-runtimes) is triggered right now so it doesn't have to be fired manually. When our Jenkins is upgraded to a version >= 2.176.1 wo shoudl use ciBuildTrigger instead the cron. Right now it is not supported.
> added trigger for deploying kogito

- addons/events/kogito-events-reactive-messaging-addon/pom.xml
- addons/jobs/jobs-management-springboot-addon/pom.xml
- addons/persistence/infinispan-quarkus-health-addon/src/test/resources/application.properties
- archetypes/pom.xml
- kogito-quarkus-extension/bom/pom.xml
- kogito-quarkus-extension/pom.xml
- pom.xml
Unifying quarkus version , jackson on kogito-runtimes. In this way all kogito will use this version.
Adding the bom to specify netty version on all dependencies, change was made on kogito-quarkus-bom replacing the explicit dependencies that were added to fix the issue.
Related https://github.com/kiegroup/kogito-apps/pull/91
@evacchi 
@mariofusco 
@cristianonicolai
> KOGITO-1216 Bump services to Quarkus 1.3.0.CR2

- drools/kogito-ruleunits/src/main/java/org/kie/kogito/rules/units/AbstractRuleUnitDescription.java
- drools/kogito-ruleunits/src/main/java/org/kie/kogito/rules/units/GeneratedRuleUnitDescription.java
- drools/kogito-ruleunits/src/main/java/org/kie/kogito/rules/units/UndefinedGeneratedRuleUnitVariable.java
- drools/kogito-ruleunits/src/main/java/org/kie/kogito/rules/units/UndefinedRuleUnitVariable.java
- drools/kogito-ruleunits/src/test/java/org/drools/core/ruleunit/RuleUnitDescriptionTest.java
- drools/kogito-ruleunits/src/test/java/org/drools/core/ruleunit/TestRuleUnit.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/RuleUnitHandler.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/DeclaredTypeCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegen.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/BusinessRuleUnitTest.java
- kogito-codegen/src/test/resources/ruletask/ExampleGeneratedWrong.bpmn
- kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
Current error messages are misleading or side-effects from other errors (e.g. NPEs)
- a process tries to use a wrong variable input in a generated rule unit (e.g. declared process var Foo, io Map Foo to Bar -> NPE); it should say something useful
- a process tries to use a wrong variable *output* in a generated rule unit (e.g. declared process var Foo, io Map Foo to Bar -> NPE); if there is some input mapping, then we should *not* do automatic mapping
- we should also *log* to ERROR in case of exception, instead of just throwing
> KOGITO-1534: Better error messages when unit variables are undefined

- archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/pom.xml
remove --allow-incomplete-classpath from archetype
> KOGITO-1557: Remove --allow-incomplete-classpath from examples and archetypes

- kogito-quarkus-extension/runtime/pom.xml
add io.quarkus.arc:arc-processor to extension
so that dep ver is correctly overridden
verified via custom build https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/custom%2Fevacchi%2Fcustom-quarkus-snapshot/detail/custom-quarkus-snapshot/3/pipeline
related https://github.com/kiegroup/kogito-examples/pull/164
> KOGITO-1555: Make sure Quarkus snapshot works with examples and runtimes

- kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
kogito-runtimes: cloud events are empty in native mode (persistence and events)
> KOGITO-1564 kogito-runtimes: cloud events are empty in native mode

- kogito-quarkus-extension/integration-test/src/test/java/io/quarkus/it/kogito/drools/HotReloadTest.java
- kogito-quarkus-extension/integration-test/src/test/java/io/quarkus/it/kogito/jbpm/HotReloadTest.java
- kogito-quarkus-extension/integration-test/src/test/resources/application.properties
- pom.xml
Update Kogito to Quarkus 1.3.1.Final +  align versions on POM
Integration tests: http port change to avoid conflicts (instead of 8080)
I tested the Kogito Apps and Travel Agency, it seems all are working fine with Quarkus 1.3.1
> KOGITO-1635 Update Kogito to Quarkus 1.3.1.Final 

- drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/DMNKogito.java
- drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/rest/DMNResult.java
- kogito-codegen/src/main/resources/class-templates/DMNRestResourceTemplate.java
Hi, 
For accountability purposes we need the modelName and modelNamespace properly set in the DMNResult, this is a small PR to do that. 
Best
> KOGITO-1781: set modelName and modelNamespace in DMNResult

- archetypes/kogito-springboot-archetype/src/main/resources/archetype-resources/pom.xml
fix archetype -- it is pointing an outdated version of spring boot; use property so it is always up-to-date
> KOGITO-1892: Spring Boot Archetype: use version property (0.9.x)

- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/util/MojoUtil.java
- kogito-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
JIRA Ticket: https://issues.redhat.com/browse/KOGITO-1786
Description:
These changes are about to configure the kogito maven plugin to be used within Eclipse using M2E. 
In order to check that these changes are working fine now with Eclipse, I did:
- Removed [the lifecycle-mapping plugin](https://github.com/kiegroup/kogito-examples/blob/bc72d5e7934c8e3581eec4f630cfdc8336ee9e4a/pom.xml#L224) to ignore errors in Eclipse from the kogito-examples parent module. (I provided this [PR](https://github.com/kiegroup/kogito-examples/pull/228) to remove this plugin once these changes are merged)
- Compile and install the new version of the maven plugin. 
- Configure the [process-springboot-example](https://github.com/kiegroup/kogito-examples/tree/master/process-springboot-example) to use the version …
> KOGITO-1786: Cannot run Kogito Tests using Eclipse

- Jenkinsfile
- Jenkinsfile-sonarcloud-daily
- Jenkinsfile.deploy
- Jenkinsfile.quarkus
- README.md
- addons/persistence/infinispan-persistence-addon/pom.xml
- addons/persistence/infinispan-persistence-addon/src/test/java/org/kie/kogito/infinispan/CacheProcessInstancesIT.java
- addons/persistence/infinispan-persistence-addon/src/test/java/org/kie/kogito/infinispan/InfinispanServerContainer.java
- addons/persistence/infinispan-quarkus-health-addon/pom.xml
- addons/persistence/infinispan-quarkus-health-addon/src/test/java/org/kie/kogito/infinispan/InfinispanServerTestResource.java
- addons/persistence/infinispan-quarkus-health-addon/src/test/java/org/kie/kogito/infinispan/health/InfinispanHealthCheckIT.java
- pom.xml
Moving tests depending on docker images to integration phase using maven failsafe plugin (in case of 'infinispan-persistence-addon' also enabling previously disabled test).
> [KOGITO-1644] Move docker-based test cases to maven-failsafe

- Jenkinsfile.deploy
https://issues.redhat.com/browse/KOGITO-2156
Build all (runtimes, apps and examples) before deployment of artifacts to nexus repository to avoid incompatibilities between deployed snapshots
> KOGITO-2156 Nightly: Deploy after builds passed

- kogito-codegen/src/main/java/org/kie/kogito/codegen/GeneratedFile.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/DeclaredTypeCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegen.java
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/AbstractKieMojo.java
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/GenerateDeclaredTypes.java
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/GenerateModelMojo.java
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/ProcessClassesMojo.java
- kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
@evacchi I had to rebase the old PR so instead I closed the old one, made the changes you suggested and open this one.
It is true that (except a minor thing to exclude generation of the rest service in the unlikely case that also the ws annotation are not available on the classpath) I didn't change much on the plugin itself. In particular I did the change to generate the sources in different folders depending on the type of the source file as we discussed but then I found it inconvenient and I undid it. In fact by doing so the user, in order to use the programmatic API and compile his project has to add as source folders in his project all the different folders where we put our code instead of just one. I'm open to discuss this but I didn't find this reasonable (and now I wonder if other …
> [KOGITO-1768] allow code scaffolding in kogito-maven-plugin

- jbpm/jbpm-bpmn2/src/main/java/org/kie/kogito/process/bpmn2/BpmnProcess.java
- jbpm/jbpm-bpmn2/src/main/java/org/kie/kogito/process/bpmn2/BpmnProcessCompiler.java
- jbpm/jbpm-bpmn2/src/main/java/org/kie/kogito/process/bpmn2/BpmnProcessInstance.java
- jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/canonical/ActivityGenerationModelTest.java
A small enhancements to the `BpmnProcessCompiler` to allow extensions and a bug fix for `BpmnProcess` when used with business key
> KOGITO-2232 - Externalize method of BpmnProcessCompiler to allow extensions, KOGITO-2231 - Can't use business key with BpmnProcess

- .github/pull_request_template.md
- CONTRIBUTING.md
- README.md
I have reworked our "traditional" contribution guidelines, [shamelessly copying from those for Quarkus.](https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md)
I started with a copy, but I customized it with stuff from our old contribution guide, wherever it made sense; e.g. I left out all references to first-time setup of Maven and Git (I think we can give them for granted); I left out considerations on style guide (let's avoid (some) bike-shedding for now) but I have included a few of our best practices. 
Quarkus also include a reference to [a contribution agreement (the DCO)](https://developercertificate.org/) that we may re-introduce here if it makes sense.
Let the bike-shedding begin! :fire:
> KOGITO-1645 Update contribution guidelines

- pom.xml
https://issues.redhat.com/browse/KOGITO-1372
remove redundant config (e.g. osgi bundles, useless plugins etc)
> KOGITO-1372 Cleanup POM in kogito-runtime

- kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java
Hi,
tryGenerateStronglyTypedInput method could be simpler if it uses storeFile method helper.
we can reuse storeFile into forEach call from allTypesSourceCode variable.
JIRA link : https://issues.redhat.com/browse/KOGITO-2389
> KOGITO-2389  Simplify tryGenerateStronglyTypedInput with better implementation

- Jenkinsfile.deploy.new
https://issues.redhat.com/browse/KOGITO-2148
To be able to run both pipelines in parallel for some time, I just copied `Jenkinsfile.deploy` to `Jenkinsfile.deploy.new` and removed triggers and notifications (as that will be part of the nightly pipeline).
`Jenkinsfile.deploy` is still used by currrent deploy pipeline.
That `Jenkinsfile.deploy.new` file will be called by [kogito.nightly](https://github.com/kiegroup/kogito-pipelines/pull/5).
Once the nightly pipeline is stable on master, there will be a new PR to replace `Jenkinsfile.deploy` by `Jenkinsfile.deploy.new` and the current deploy pipeline will be deleted in favor of the new nightly pipeline.
> KOGITO-2148 Adjustments for nightly pipeline

- pom.xml
https://issues.redhat.com/browse/KOGITO-2026
add the java version enforcer rule for build to be jdk 11 (build will still target bytecode version java8)
> KOGITO-2026 Enforce JDK 11 version

- kogito-codegen/src/main/java/org/kie/kogito/codegen/GeneratedFile.java
https://issues.redhat.com/browse/KOGITO-2483
Currently process *Model classes (e.g. MyProcessModel.java) are generated under target/ because they are not classified as "customizable". We should allow "scaffolding" to generate these classes in a custom location. This is also required to have a correct build order.
The fix is a oneliner, and it is used in #567
> KOGITO-2483: Classify generated Process Model classes as "customizable"

- integration-tests/integration-tests-kogito-plugin/src/it/integration-tests-kogito-plugin-it/invoker.properties
- integration-tests/integration-tests-kogito-plugin/src/it/integration-tests-kogito-plugin-it/pom.xml
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/GenerateModelMojo.java
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/ScaffoldMojo.java
https://issues.redhat.com/browse/KOGITO-2482
Add `kogito:scaffold` to use with scaffolding, with updated default values for source directories.
This is a very minimal (and a bit ugly) refactoring to reuse the logic in `kogito:generateModel` an improved refactoring will follow.
Usage:
```
mvn compile kogito:scaffold
```
default output directory is `src/main/java`. You can override with:
```
mvn compile kogito:scaffold -Dkogito.codegen.sources.directory=your/output/dir
```
there is also a new boolean configuration parameter `onDemand` (also usable with property `kogito.codegen.ondemand`). When this is true, the "usual" `kogito:generateModel` won't execute, even if it's bound to a phase (normally, it defaults to being bound to `compile`), so that it does not conflict when users run …
> KOGITO-2482 Add `kogito:scaffold` Mojo

- jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/canonical/ActivityGenerationModelTest.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ServiceTaskDescriptor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/WorkItemNodeVisitor.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/data/HelloService.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/ServiceTaskTest.java
- kogito-codegen/src/test/resources/servicetask/ServiceProcessOverloaded.bpmn2
https://issues.redhat.com/browse/KOGITO-2472
the problem is actually _subtler_. The handlers that are internally generated are named using the `interfaceName_methodName` template, which causes them to overwrite each other in the case of overloading. The solution is to use a _mangled_ name instead, including type parameters. Now the template is ``SomeClass_doSomethingHandler_my$Type1$$my$Type2`` which should be more reliable
> KOGITO-2472 Codegen does not create handler for ServiceTasks with overloaded methods

- pom.xml
Jira: https://issues.redhat.com/browse/KOGITO-2643
The mongodb module was introduced to testcontainers since version 1.14.2.
So upgrade the testcontainers version and add new dependency management for the mongodb module.
> [KOGITO-2643] upgrade testcontainers version and add dependency management for the mongodb module

- pom.xml
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/607
- https://github.com/kiegroup/kogito-examples/pull/290
- https://github.com/kiegroup/kogito-apps/pull/305
> KOGITO-2639 Follow up upgrade dependencies aliging with Quarkus 1.6.0

- kogito-codegen/README.md
- kogito-codegen/src/main/java/org/kie/kogito/codegen/AddonsConfig.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/ApplicationGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DMNRestResourceGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionContainerGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/QueryEndpointGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/RuleUnitGenerator.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/AddonsConfigTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/ApplicationGeneratorTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/decision/DecisionCodegenTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegenTest.java
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/GenerateModelMojo.java
- kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
Hi,
I'd like to propose the following refactoring of the injection of the addons configurations. Since atm the addons are injected one by one with a simple boolean, I thought that using an object would make it much more easier to extend and maintain. 
Just as a side note: I'm working on a component that needs to know if the `tracing` and the `monitoring` addons are activated, and I would have had to inject both of them with some redundant code for the reason above. 
Let me know what do you think :) 
> KOGITO-2737 - refactoring injection of addons configuration

- pom.xml
Snapshot pipeline is not using this mechanism anymore ( see https://github.com/kiegroup/kogito-runtimes/blob/master/Jenkinsfile.drools#L35 )
> Remove unused profile

- drools/drools-core-static/pom.xml
- drools/drools-core-static/src/main/java/org/drools/statics/StaticComponentsSupplier.java
- drools/drools-core-static/src/test/java/org/drools/statics/DummyByteArrayClassLoaderTest.java
Add a descriptive error message to the UnsupportedOperationException that gets thrown by the Dummy classloader implementation.
> KOGITO-2729 Better error message if DRL is compiled at runtime and drools-core-static is in the classpath

- jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ActivityTest.java
Add assumption so that the test is skipped when GraalJS is detected -- currently exact match on Class name. May break in the future.
> KOGITO-2597  Some tests fail when testing with GraalVM because of JS support

- kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/DecisionTablesCompilationProvider.java
- kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
See `BuildStep`'s javadoc
```java
/**
* This no longer has any effect, and will be removed in future.
*/
@Deprecated
boolean loadsApplicationClasses() default false;
```
@mariofusco @evacchi @radtriste
> Removed deprecated loadsApplicationClasses param

- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/GenerateDeclaredTypes.java
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/GenerateModelMojo.java
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/ProcessClassesMojo.java
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/ScaffoldMojo.java
JIRA: https://issues.redhat.com/browse/KOGITO-2735
Description: 
Make kogito-maven-plugin threadsafe in parallel.
I reviewed all the MOJOs and I think they are already thread safe, so I marked them as so and checked that maven is not warning about it when building the project in parallel.
> KOGITO-2735: Make kogito-maven-plugin threadsafe

- bom/pom.xml
Add `explainability-core` to `kogito-bom` so that it can be used as a dependency in other modules.
See [KOGITO-2750](https://issues.redhat.com/browse/KOGITO-2750) and https://github.com/kiegroup/kogito-apps/pull/324.
> KOGITO-2750 - add explainability-core to kogito-bom

- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/UserTaskModelMetaData.java
- jbpm/jbpm-flow-builder/src/main/resources/class-templates/TaskInputTemplate.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/humantask/HumanTaskTransition.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/util/JsonSchemaUtil.java
- kogito-codegen/src/main/resources/class-templates/RestResourceSignalTemplate.java
- kogito-codegen/src/main/resources/class-templates/RestResourceTemplate.java
- kogito-codegen/src/main/resources/class-templates/RestResourceUserTaskTemplate.java
- kogito-codegen/src/main/resources/class-templates/spring/SpringRestResourceSignalTemplate.java
- kogito-codegen/src/main/resources/class-templates/spring/SpringRestResourceTemplate.java
- kogito-codegen/src/main/resources/class-templates/spring/SpringRestResourceUserTaskTemplate.java
Reducing generated code size by using map and orElse ( I think orElse(null) should be orElseThrow (()-> new ProcessInstanceNotFound(id)), I have opened https://issues.redhat.com/browse/KOGITO-2875 to change that) 
ToMap() method call cannot be removed unless xxx_TaskOuput implements Model (method fromMap of Model interface does not exist for xxx_TaskOuput, the same than toMap does not exist for xxx_TaskInput)
A set of static initializers has been added for HumanTaskTransition (constructors has been left for backward compatibility)
xxx_TaskInput generated fromMap method now accepts a WorkItem rather than three parameters
The JIRA was asking for return pi.workItem(Travels_6_TaskInput.class, policies(user, groups)); rather than Travels_6_TaskInput.fromMap(pi.workItem(workItemId, …
> [KOGITO-2756] Hide Implementation details of WorkItemHandler

- pom.xml
We are using test containers so we can keep just
<dependency>
<groupId>org.infinispan</groupId>
<artifactId>infinispan-remote-query-client</artifactId>
<version>${version.org.infinispan}</version>
</dependency>      
<dependency>
<groupId>org.infinispan</groupId>
<artifactId>infinispan-query-dsl</artifactId>
<version>${version.org.infinispan}</version>
</dependency> 
<dependency>
<groupId>org.infinispan.protostream</groupId>
<artifactId>protostream</artifactId>
<version>${version.org.infinispan.protostream}</version>
</dependency>
and the container image
> KOGITO-2923  Remove unnecessary Infinispan dependencies from bom

- addons/tracing/tracing-decision-api/src/main/java/org/kie/kogito/tracing/decision/event/model/ModelEvent.java
- addons/tracing/tracing-decision-api/src/test/java/org/kie/kogito/tracing/decision/event/model/ModelEventTest.java
- addons/tracing/tracing-decision-common/src/main/java/org/kie/kogito/tracing/decision/BaseModelEventEmitter.java
- addons/tracing/tracing-decision-quarkus-addon/src/test/java/org/kie/kogito/tracing/decision/QuarkusModelEventEmitterTest.java
- addons/tracing/tracing-decision-springboot-addon/src/test/java/org/kie/kogito/tracing/decision/SpringBootModelEventEmitterTest.java
- api/kogito-api/src/main/java/org/kie/kogito/decision/DecisionModelType.java
- api/kogito-internal/src/main/java/org/kie/internal/decision/DecisionModelResource.java
- drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/BaseDecisionModelResource.java
- drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/DecisionModelJarResource.java
- drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/DecisionModelRelativeResource.java
- drools/kogito-dmn/src/test/java/org/kie/kogito/dmn/DecisionModelJarResourceTest.java
- drools/kogito-dmn/src/test/java/org/kie/kogito/dmn/DecisionModelRelativeResourceTest.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionModelResourcesProviderGenerator.java
See https://issues.redhat.com/browse/FAI-240
This PR relates to the _receiving_ end of the `ModelEvent`s published from the tracing addon.
Receipt is actually in `kogito-apps/trusty` however there were a few changes needed here too.
This is part of an ensemble:
- https://github.com/kiegroup/kogito-runtimes/pull/667
- https://github.com/kiegroup/kogito-apps/pull/357 
> FAI-240: Model definition endpoint - trusty-service

- drools/drools-core/src/main/java/org/drools/core/KogitoWorkItemHandlerNotFoundException.java
- drools/drools-core/src/main/java/org/drools/core/process/instance/impl/KogitoDefaultWorkItemManager.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/LightWorkItemManager.java
https://issues.redhat.com/browse/KOGITO-2968
We delete the exception and create a new exception that extends the one in v7.
Future work: remove all dependency from v7-age APIs from processes. https://issues.redhat.com/browse/KOGITO-2972
> KOGITO-2968: Duplicate WorkItemHandlerNotFoundException causes native-image to break

- api/kogito-api/src/main/java/org/kie/kogito/MapInput.java
- api/kogito-api/src/main/java/org/kie/kogito/MapOutput.java
- api/kogito-api/src/main/java/org/kie/kogito/process/ProcessInstance.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ModelMetaData.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessToExecModelGenerator.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/UserTaskModelMetaData.java
- jbpm/jbpm-flow-builder/src/main/resources/class-templates/TaskInputTemplate.java
- jbpm/jbpm-flow-builder/src/main/resources/class-templates/TaskOutputTemplate.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/humantask/HumanTaskTransition.java
- jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/InputModelClassGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/OutputModelClassGenerator.java
- kogito-codegen/src/main/resources/class-templates/ReactiveRestResourceTemplate.java
- kogito-codegen/src/main/resources/class-templates/RestResourceSignalTemplate.java
- kogito-codegen/src/main/resources/class-templates/RestResourceTemplate.java
- kogito-codegen/src/main/resources/class-templates/RestResourceUserTaskTemplate.java
- kogito-codegen/src/main/resources/class-templates/spring/SpringRestResourceSignalTemplate.java
- kogito-codegen/src/main/resources/class-templates/spring/SpringRestResourceTemplate.java
- kogito-codegen/src/main/resources/class-templates/spring/SpringRestResourceUserTaskTemplate.java
- Model interface extends MapOutput and MapInput interfaces
- xxxTaskOutput classes implements MapOutput (generated code does not
longer need to invoke toMap when building HumanTaskTransition)
- New methods toModel on InputModel and toOutput on Model
- Add chechError to ProcessInstance
- Modification on templates to use them (removing mapInput, mapOutput and
getModel)
> [KOGITO-2753] Processes: Remove model transformations from REST endpoint

- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/xml/XmlProcessReader.java
https://issues.redhat.com/browse/KOGITO-3031
Yeah, I know what you're thinking; complain with this commit, I am just an executor https://github.com/kiegroup/kogito-runtimes/commit/9b62b4b66880d19e78382873726031dcc322b770#diff-9a0b59684704d04412ddab34e4b8ac7c
#YOLO 
"proper" solution may be to configure the logger so that it is silent, but I think that would require shipping a default `logback.xml` ? I don't think that's something we usually do
> KOGITO-3031 Error log displayed with bpmn process

- kogito-test-utils/src/test/java/org/kie/kogito/kafka/KafkaClientTest.java
JIRA: https://issues.redhat.com/browse/KOGITO-3036
Description: Remove KafkaClient utility as it's causing issues running the pipelines and does not bring up any particular functionality. 
> KOGITO-3036: Remove KafkaClient randomly failing test from Kogito Runtimes

- Jenkinsfile.promote
https://issues.redhat.com/browse/KOGITO-3035
So that the default branch is moved only for `latest` version (goes in hand as well with `latest` of images)
> KOGITO-3035 add UPDATE_STABLE_BRANCH param

- api/kogito-api/src/main/java/org/kie/api/io/ResourceType.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/io/CollectedResource.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/prediction/PredictionCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegen.java
- kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/AppPaths.java
- kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/GeneratedFileWriter.java
- kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/InMemoryCompiler.java
- kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
I'll be away until end of August, so I invite you to take a look, and if something looks off, I would still encourage you to merge __and then__ amend with further PRs, because I believe this refactor is long overdue -- unless there are larger issues. Alternatively, whoever has right may push on top of this. 
- I have moved and renamed a lot of code into methods and/or their own classes. It is a bit tidier, although it can be further improved. E.g. I have created a Quarkus-specific InMemoryCompiler that delegates to the Drools' Java Compiler wrapper hiding some internal flags.
- I have also removed usages of the `XGenerator#fromJar()` method; instead I have added an utility method to read a <Path, Resource> pair (called CollectedResource for lack of a better name) from Paths. If a Path is …
> KOGITO-3055  Refactor Quarkus Extension

- jenkins-tests/pom.xml
[KOGITO-3173](https://issues.redhat.com/browse/KOGITO-3173)
Many thanks for submitting your Pull Request :heart: :racing_car: ! 
> KOGITO-3173 - kogito-runtimes-jenkins-tests parent has wrong relative path

- kogito-bom/pom.xml
Create new maven modules for data index service artifacts with infinispan and mongodb.
Jira: https://issues.redhat.com/browse/KOGITO-2889
> [KOGITO-2889] add data index service modules for different storage types in bom

- Jenkinsfile.drools
https://issues.redhat.com/browse/KOGITO-3220
`cut` is broken -- probably too brittle:
mvn versions:display-property-updates -DincludeProperties=version.org.kie7 -DallowSnapshots -N  | grep version.org.kie7 | cut -d " " -f8
let's try with `awk`
> KOGITO-3220  Fix Drools snapshot build

- archetypes/kogito-quarkus-archetype/pom.xml
- archetypes/kogito-quarkus-archetype/src/test/resources/projects/it-basic/goal.txt
JIRA: https://issues.redhat.com/browse/KOGITO-3216
Description: Making the examples to use the same quarkus version from the command line, made the above issue be gone.
> KOGITO-3216: Fix mismatch version when building Quarkus archetypes

- Jenkinsfile-sonarcloud-daily
- Jenkinsfile.drools
- Jenkinsfile.quarkus
JIRA: https://issues.redhat.com/browse/KOGITO-3230
Description: The kogito runtime pipeline has a timeout of 360 minutes, nevertheless the drools, quarkus and sonar pipelines remains with 120 minutes leading with the build being aborted by Jenkins when the time exceeded this timeout.
> KOGITO-3230: Increase the timeout of pipelines

- api/kogito-internal/src/main/java/org/kie/internal/process/CorrelationAwareProcessRuntime.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/AbstractProcessInstanceFactory.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/LightProcessRuntime.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessInstanceManager.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessRuntimeImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/DefaultProcessInstanceManager.java
- jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java
- jbpm/jbpm-flow/src/test/java/org/kie/kogito/process/impl/AbstractProcessInstanceTest.java
Follow-up of [KOGITO-2893](https://issues.redhat.com/browse/KOGITO-2893) (as it got merged before I had a chance to review it)
As we discussed with @ruromero business key is now just set and used only when querying using data index. This means that methods removed in this PR are no longer needed.
> [KOGITO-2893] Detach Business Key from ID - follow-up cleaning

- integration-tests/integration-tests-quarkus/src/test/java/org/kie/kogito/integrationtests/quarkus/NativeJavaFNctxIT.java
Temporarily disabling because it breaks in native mode with Quarkus master / graalvm 20.2
> KOGITO-3267  Disable test NativeJavaFNctxIT (breaks with native image)

- integration-tests/integration-tests-quarkus/src/test/java/org/kie/kogito/integrationtests/quarkus/BasicRestTest.java
- integration-tests/integration-tests-quarkus/src/test/java/org/kie/kogito/integrationtests/quarkus/EnumsTest.java
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/BasicRestTest.java
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/EnumsTest.java
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/TestWorkItem.java
- kogito-codegen/src/main/resources/class-templates/ReactiveRestResourceTemplate.java
- kogito-codegen/src/main/resources/class-templates/RestResourceTemplate.java
- kogito-codegen/src/main/resources/class-templates/spring/SpringRestResourceTemplate.java
Changins tasks endpoint to return list of work items rather than a map with id and name
Merge with https://github.com/kiegroup/kogito-examples/pull/347
> [KOGITO-1942] tasks endpoint to return a list work item

- kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionContainerGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/io/CollectedResource.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/prediction/PredictionCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegen.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/AbstractCodegenTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/decision/DecisionCodegenTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/decision/DecisionModelResourcesProviderCodegenTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/io/CollectedResourceTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/prediction/PredictionCodegenTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegenTest.java
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/GenerateModelMojo.java
- kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/DMNCompilationProvider.java
- kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/DecisionTablesCompilationProvider.java
- kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/ProcessCompilationProvider.java
- kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/RulesCompilationProvider.java
https://issues.redhat.com/browse/KOGITO-3110
The method ofCollectedResources is almost exactly the same in DecisionCodegen, PredictionCodegen, ProcessCodegen and IncrementalRuleCodegen.
Remove all other variations of the ofPath, ofFiles etc. and use ofCollectedResources everywhere (where applicable)
> KOGITO-3110 Refactor ofCollectedResources methods in *Codegen

- kogito-codegen/src/main/resources/class-templates/events/CloudEventsMessageProducerTemplate.java
minor follow up to https://github.com/kiegroup/kogito-runtimes/pull/748, just remove a useless import in the fixed template
> KOGITO-3292 KNative eventing is not enabled with Quarkus Extension (fix template)

- kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionContainerGenerator.java
- kogito-codegen/src/main/resources/class-templates/DecisionContainerTemplate.java
https://issues.redhat.com/browse/KOGITO-3330
In GraalVM 20.2 under certain conditions, it is not possible to hold onto an input stream reader that has been generated from a classpath resource -- see https://github.com/quarkusio/quarkus/issues/8694#issuecomment-691828808
The hotfix consists in eagerly reading the entire resource when native mode is detected at build time (detected via special System property).
in other words, instead of:
```
new InputStreamReader(...getResourceAsStream())
```
for native image we do 
```
bytes = getResourceAsStream().readAllBytes()
new InputStreamReader(new ByteArrayInputStream(bytes))
```
We may have to revisit the issue to see if there are "better" ways to fix it (e.g. Quarkus has most probably a "proper" way to handle resources); in the meantime, we need …
> KOGITO-3330 Hotfix: Conditional eager reading of resources on native-image

- drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/util/StronglyTypedUtils.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionRestResourceGenerator.java
- kogito-codegen/src/main/resources/class-templates/DecisionRestResourceTemplate.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/decision/DecisionCodegenTest.java
https://issues.redhat.com/browse/KOGITO-3078
This PR is to have `OutputSet` as a return type of DMN REST endpoint when stronglytyped is enabled. So swagger-ui can provide type information and proper payload example.
- [x ] You have read the [contributors guide](CONTRIBUTING.md)
- [x ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x ] Pull Request contains link to the JIRA issue
- [x ] Pull Request contains link to any dependent or related Pull Request
- [x ] Pull Request contains description of the issue
- [x ] Pull Request does not include fixes for issues other than the main ticket
> [KOGITO-3078] DMN strongly typed: output definition

- api/kogito-api/src/main/java/org/kie/kogito/rules/RuleUnit.java
- drools/kogito-ruleunits/src/main/java/org/kie/kogito/rules/units/InterpretedRuleUnit.java
- drools/kogito-ruleunits/src/main/java/org/kie/kogito/rules/units/impl/AbstractRuleUnit.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/TemplatedGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/RuleUnitContainerGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/RuleUnitGenerator.java
- kogito-codegen/src/main/resources/class-templates/CdiApplicationTemplate.java
- kogito-codegen/src/main/resources/class-templates/SessionRuleUnitTemplate.java
- kogito-codegen/src/main/resources/class-templates/SpringApplicationTemplate.java
- kogito-codegen/src/main/resources/class-templates/rules/CdiRuleUnitContainerTemplate.java
- kogito-codegen/src/main/resources/class-templates/rules/RuleUnitContainerTemplate.java
- kogito-codegen/src/main/resources/class-templates/rules/RuleUnitTemplate.java
- kogito-codegen/src/main/resources/class-templates/rules/SpringRuleUnitContainerTemplate.java
follow up to https://github.com/kiegroup/kogito-runtimes/pull/657 
must merge with: https://github.com/kiegroup/kogito-examples/pull/350
- this mimicks the work done for Application.java and Processes.java but for RuleUnits.java
- RuleUnits is now a factory in non-DI contexts (i.e. kogito-codegen) 
- otherwise it collects and provides all the RuleUnit beans and it can be injected with `@Inject/@Autowire RuleUnits` 
The change is that currently `RuleUnits` is _always_ a factory; i.e. it always returns _new beans_. While in DI contexts, it should delegate generation to the DI container.
This PR also makes less necessary `ProjectModel`/`ProjectRuntime`, which are currently _always_ being used to construct rule units. This PR makes every RuleUnit<T> class self-contained, it no longer requires …
> KOGITO-2911 Refactor Codegen for "RuleUnits" class in Application.java 

- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/events/CloudEventsResourceGenerator.java
- kogito-codegen/src/main/resources/class-templates/events/CloudEventsListenerResource.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/process/events/CloudEventsResourceGeneratorTest.java
See: https://issues.redhat.com/browse/KOGITO-3421
Tested with: https://github.com/kiegroup/kogito-examples/pull/372
In this PR we generate a random name for the `emiiter` variable since in SW engine we are using CE `source` as the name of the trigger, which is an URI. We can't use that as var name.
> KOGITO-3421 Fix variable name generation in CloudEvents resource router

- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/events/CloudEventsMessageProducerGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/events/CloudEventsResourceGenerator.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/process/events/CloudEventsMessageProducerGeneratorTest.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/process/events/CloudEventsResourceGeneratorTest.java
See: https://issues.redhat.com/browse/KOGITO-3447
End up that the random variable strategy wouldn't work with IDE testing nor with `mvn clean install`, since Arc is linked before testing and the files are generated again before building the final jar. Codegen MUST be idempotent.
This is a MUST for Knative demos.
> KOGITO-3447 Sanitizing codegen variable names for Knative Addon

- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/RestTaskDescriptor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ServiceTaskDescriptor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/WorkItemNodeVisitor.java
- jbpm/jbpm-flow-builder/src/main/resources/class-templates/RestWorkItemHandlerTemplate.java
- jbpm/jbpm-serverless-workflow/pom.xml
- jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/parser/ServerlessWorkflowParser.java
- jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/parser/core/ServerlessWorkflowFactory.java
- jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/parser/util/ServerlessWorkflowUtils.java
- kogito-bom/pom.xml
- kogito-build-parent/pom.xml
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java
- kogito-quarkus-extension/runtime/pom.xml
- kogito-quarkus-extension/runtime/src/main/java/org/kie/kogito/quarkus/runtime/graal/graal/JsonSmartSubstitutions.java
- kogito-workitems/kogito-rest-workitem/pom.xml
- kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandler.java
- kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandlerParamResolver.java
- kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandlerResult.java
- kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/jsonpath/functions/JSonPathResultHandler.java
- kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/jsonpath/functions/JsonPathResolver.java
- kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/jsonpath/suppliers/JsonPathExprSupplier.java
- kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/jsonpath/suppliers/JsonPathResultExprSupplier.java
- kogito-workitems/kogito-rest-workitem/src/test/java/org/kogito/workitem/rest/RestTaskHandlerTest.java
- kogito-workitems/pom.xml
- pom.xml
Changes for adding a RestWorkItemHandler
Please check example at [#369](https://github.com/kiegroup/kogito-examples/pull/369)
Summary of changes:
-  Using vert.x both for Quarkus and Springboot (jax-rs client is not working on native mode, check https://github.com/quarkusio/quarkus/issues/6151). It is used in async mode, so do not block the thread while the rest invocation is being performed and handler is completed when the response arrive
- New work item handler for Rest invocations (RestTaskHandler) has been added. Required parameters are endpoint (read from function defintion), method (read from function metadata) and ResultHandler (this one is auto generated by serverless parser). User and password for basic authentication are optional. 
-  Since input/output parameters can be Json …
> [KOGITO-3158] Adding RestTaskHandler

- CONTRIBUTING.md
Added a known issue when in some cases test containers fail to run, and a workaround. BTW let's keep an eye on the issue I have linked: apparently the testcontainer RC fixes the issue (?)
-----
> KOGITO-3594  Add note to CONTRIBUTING.md on how to disable RYUK in case of issues

- integration-tests/integration-tests-quarkus-decisions/pom.xml
- integration-tests/integration-tests-quarkus-decisions/src/test/java/org/kie/kogito/integrationtests/quarkus/BasicAddTest.java
- integration-tests/integration-tests-quarkus-decisions/src/test/java/org/kie/kogito/integrationtests/quarkus/DSCoercionTest.java
- integration-tests/integration-tests-quarkus-decisions/src/test/java/org/kie/kogito/integrationtests/quarkus/ElementAtIndexTest.java
- integration-tests/integration-tests-quarkus-decisions/src/test/java/org/kie/kogito/integrationtests/quarkus/JavaFNctxTest.java
- integration-tests/integration-tests-quarkus-decisions/src/test/java/org/kie/kogito/integrationtests/quarkus/NativeJavaFNctxIT.java
https://issues.redhat.com/browse/KOGITO-3269
I believe since [KOGITO-3370](https://issues.redhat.com/browse/KOGITO-3370) the `integration-tests-quarkus-<vertical>` modules no longer require additional synthetic annotations such like 
```
@QuarkusTestResource(InfinispanQuarkusTestResource.Conditional.class)
```
Since `integration-tests-quarkus-decisions` for instance do NOT deal with Infinispan.
For the reason why that Infinispan synthetic test annotation broke Native Image, you can reference the log here: https://issues.redhat.com/browse/KOGITO-3269?focusedCommentId=15324521&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-15324521
In short
```
[ERROR] org.kie.kogito.integrationtests.quarkus.NativeJavaFNctxIT  Time elapsed: 0.1 s  <<< ERROR! …
```
> KOGITO-3269 Restore native test in integration-tests-quarkus-decisions

- drools/kogito-scenario-simulation/src/test/resources/sampleTest/Violation Scenarios.scesim
https://issues.redhat.com/browse/KOGITO-2773
The real name of "Type" column is "Type" and not "string". The editor will show "string" but, under the cover, "Type" is used because is a "Anonymous" DMNType (a type with allowed values). This change will enable the examples to be both compatible with Kogito channels and Business Central
In addition the DMNPath was wrong. Updated with the correct path.
> KOGITO-2773: Update scesim example enabling compatibility with BC

- Jenkinsfile.deploy
Reverts kiegroup/kogito-runtimes#816
This is causing some issues with `jenkins-ci` libraries from spock testing due to another settings.xml used when using the deploy pipeline in release mode.
Another fix will come later. First reverting.
> Revert "KOGITO-3570 No defaut settings.xml for release build"

- drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/rest/DMNJSONUtils.java
- integration-tests/integration-tests-quarkus-decisions/src/main/resources/OneOfEachType.dmn
- integration-tests/integration-tests-quarkus-decisions/src/main/resources/application.properties
- integration-tests/integration-tests-quarkus-decisions/src/test/java/org/kie/kogito/integrationtests/quarkus/OASTest.java
- integration-tests/integration-tests-quarkus-decisions/src/test/java/org/kie/kogito/integrationtests/quarkus/OneOfEachTypeTest.java
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/pom.xml
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/main/resources/OneOfEachType.dmn
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/main/resources/application.properties
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/OASTest.java
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/OneOfEachTypeTest.java
- kogito-build-parent/pom.xml
- kogito-codegen/pom.xml
- kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionRestResourceGenerator.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/PCLResolverFn.java
- kogito-codegen/src/main/resources/class-templates/DecisionRestResourceTemplate.java
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/GenerateModelMojo.java
- kogito-quarkus-extension/deployment/pom.xml
- kogito-quarkus-extension/integration-test/src/test/java/io/quarkus/it/kogito/dmn/DMNTest.java
- kogito-quarkus-extension/runtime/pom.xml
This is a DRAFT PR for now, to better clarify one of the many usages of https://issues.redhat.com/browse/DROOLS-5714
**referenced Pull Requests**: part of an ensemble of PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1493
* https://github.com/kiegroup/drools/pull/3155
* (DRAFT) this PR
<details>
<summary>
</summary>
* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>
* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b> …
> KOGITO-3601 DMN integrate programmatically generated OAS definitions

- Jenkinsfile.quarkus
- integration-tests/integration-tests-quarkus-decisions/pom.xml
- integration-tests/integration-tests-quarkus-predictions/pom.xml
- integration-tests/integration-tests-quarkus-processes/pom.xml
- integration-tests/integration-tests-quarkus-rules/pom.xml
https://issues.redhat.com/browse/KOGITO-3694
CI build using Quarkus snapshot failed on `org.kie.kogito.integrationtests.quarkus.DecisionTableTest.org.kie.kogito.integrationtests.quarkus.DecisionTableTest` with
```
used by: java.lang.ClassCastException: class java.util.logging.LogManager$RootLogger cannot be cast to class org.jboss.logmanager.Logger (java.util.logging.LogManager$RootLogger is in module java.logging of loader 'bootstrap'; org.jboss.logmanager.Logger is in unnamed module of loader 'app')
at io.quarkus.test.QuarkusUnitTest.<clinit>(QuarkusUnitTest.java:81)
... 46 more
```
So this PR ensure all Quarkus integration tests are using Jboss LogManager
> [KOGITO-3694] Configure Jboss LogManager for Quarkus integration tests

- integration-tests/integration-tests-kogito-plugin/src/it/integration-tests-kogito-plugin-it/invoker.properties
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/invoker.properties
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-kafka-it/invoker.properties
Maven invoker plugin is configured to not hit Central, but just use the local maven repository; yet it simulates the whole downloading routine, producing a lot of useless noise.
It turns out there is an incantation that you can use either in MAVEN_OPTS or at the CLI to disable such output:
```
-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
```
in recent Maven version there is also a CLI option: `--no-transfer-progress` or `-ntp`; we may want to consider adding it to our CI builds, as the output itself may slow down the build (I think the final error should be reported in case of missing dep) 
https://issues.redhat.com/browse/KOGITO-3691
----
Please make sure that your PR meets the following …
> KOGITO-3691 Disable local 'Download' logging in maven invoker plugin

- kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionModelResourcesProviderGenerator.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/decision/DecisionModelResourcesProviderGeneratorTest.java
- kogito-codegen/src/test/resources/decision/models/dmnprocess.bpmn2
- kogito-codegen/src/test/resources/decision/models/vacationDaysAlt/vacationDaysAlt.dmn
https://issues.redhat.com/browse/KOGITO-3690
From
```java
resourcePaths.add(new org.kie.kogito.dmn.DefaultDecisionModelResource(new org.kie.api.management.GAV("dummy", "dummy", "0.0"), "https://github.com/kiegroup/kogito-examples/dmn-quarkus-listener-example", "LoanEligibility", org.kie.kogito.decision.DecisionModelType.DMN, readResource(org.drools.core.util.IoUtils.class.getClassLoader().getResourceAsStream("LoanEligibility.dmn"))), new org.kie.kogito.dmn.DefaultDecisionModelResource(new org.kie.api.management.GAV("dummy", "dummy", "0.0"), "https://github.com/kiegroup/drools/kie-dmn/_A4BCA8B8-CF08-433F-93B2-A2598F19ECFF", "Traffic Violation", org.kie.kogito.decision.DecisionModelType.DMN, readResource(org.drools.core.util.IoUtils.class.getClassLoader().getResourceAsStream("Traffic …
```
> [KOGITO-3690] Fix DecisionModelResourcesProvider codegen in case of multiple DMN models

- kogito-codegen/src/main/resources/class-templates/DecisionModelResourcesProviderTemplate.java
https://issues.redhat.com/browse/KOGITO-3738
My IDE freaks out every time the code is generated in `integration-test` because the root project is set to 8 compatibility, and all children inherits from it. For now I am just inserting a stock "readAllBytes()" impl,
1) but we can move most of this stock logic to an abstract class and inherit from there
2) alternative: we can set the pom.xml of the submodule to 11 -- don't know if this works especially with upstream Quarkus, so I am doing (1)
-----
> KOGITO-3738 Use JDK8-compatible readBytes impl in DecisionModelResourcesProvider

- kogito-build-parent/pom.xml
JIRA: https://issues.redhat.com/browse/KOGITO-3790
Currently only some paths are excluded from the codecov analysis (see below)
Since we have to rename the `kogito-apps` `integration-tests` module (for example to `apps-integration-tests`) so to avoid conficts with the `integration-tests` module already present here in `kogito-runtimes`, we have to exclude the class files generated from that new module as well. 
> KOGITO-3790 - Exclude apps-integration-tests class files from codecov analysis

- kogito-build-parent/pom.xml
JIRA: https://issues.redhat.com/browse/KOGITO-3790
Currently only some paths are excluded from the codecov analysis (see below)
Since we have to rename the `kogito-apps` `integration-tests` module (for example to `apps-integration-tests`) so to avoid conficts with the `integration-tests` module already present here in `kogito-runtimes`, we have to exclude the class files generated from that new module as well. 
> [1.0.x] KOGITO-3790 - Exclude apps-integration-tests class files from codecov analysis

- Jenkinsfile.drools
- Jenkinsfile.native
- Jenkinsfile.quarkus
https://issues.redhat.com/browse/KOGITO-3834
Now we have three jobs scheduled at the same time (10am UTC).
New proposed schedule:
- Jenkinsfile.drools: 2am UTC (~1 hour of execution time)
- Jenkinsfile.quarkus: 4am UTC (~1 hour of execution time)
- Jenkinsfile.native: 6am UTC (~2.5 hours of execution time)
> [KOGITO-3834] Update daily job scheduling to minimize overlapping

- kogito-build-parent/pom.xml
- kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoImageNameSubstitutor.java
- kogito-test-utils/src/main/resources/testcontainers.properties
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/892
- https://github.com/kiegroup/kogito-examples/pull/457
> KOGITO-3862 - Make Docker images used by TestContainers compatible with Docker registry mirror

- addons/persistence/mongodb-persistence-addon/pom.xml
- kogito-build-parent/pom.xml
- kogito-test-utils/pom.xml
Our BOM is published to platform and therefore end-users get our version of test containers. It would be better to NOT publish our test container dependency. 
Final solution: test bom
Workaround: use version property explicitly
related https://github.com/kiegroup/kogito-apps/pull/536
> [1.0.x] KOGITO-3868 TestContainer dependency in BOM causes issues in quarkus-platform

- kogito-codegen/src/main/resources/class-templates/DecisionContainerTemplate.java
https://issues.redhat.com/browse/KOGITO-3897
blocks quarkus-platform build due to JDK8 incompat.
Follow up to  https://github.com/kiegroup/kogito-runtimes/pull/860/
I don't know why we have 2 templates, but that's another issue
---
> [1.0.x] KOGITO-3897 Use JDK8-compatible readBytes impl in DecisionContainerTemplate

- kogito-build-parent/pom.xml
- kogito-cloud-services/kogito-cloud-kubernetes-client/src/test/java/org/kie/kogito/cloud/kubernetes/client/MockKubernetesServerSupport.java
- kogito-cloud-services/kogito-cloud-kubernetes-client/src/test/java/org/kie/kogito/cloud/kubernetes/client/operations/ServiceOperationsStatusCodeHandlingTest.java
- kogito-cloud-services/kogito-cloud-kubernetes-client/src/test/java/org/kie/kogito/cloud/kubernetes/client/operations/ServiceOperationsTest.java
- kogito-cloud-services/kogito-cloud-kubernetes-client/src/test/resources/logback-test.xml
- kogito-cloud-services/kogito-cloud-workitems/src/test/java/org/kie/kogito/cloud/workitems/KubernetesDiscoveredServiceWorkItemHandlerTest.java
- kogito-cloud-services/kogito-cloud-workitems/src/test/java/org/kie/kogito/cloud/workitems/service/discovery/KubernetesServiceDiscoveryTest.java
See: https://issues.redhat.com/browse/KOGITO-3832
The test has been disabled because of https://github.com/fabric8io/kubernetes-client/issues/2631
> [KOGITO-3832] Bump to Kubernetes Client 4.12.0

- kogito-codegen/src/main/java/org/kie/kogito/codegen/GeneratedFile.java
- kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java
See: https://issues.redhat.com/browse/KOGITO-3659
On Serverless Workflows, sometimes we want to reuse a given set of functions on subprocesses. In such scenarios, the codegen was duplicating the `WorkItemHandlers` responsible for handling these functions.
An example of such a case can be viewed in: <PR to be sent>
Instead of using a `List`, we use a `Set` to not have duplicates in the final generated code. This can be re-think in the future. For example: would make sense to generate all the handlers beforehand on a specific package instead? Today each process take care of their handlers, we don't have "global" scope for such thing. Wouldn't that make sense? For a handler to be reused on subprocesses/flows?
Many thanks for submitting your …
> KOGITO-3659 Process codegen won't generate duplicate classes

- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/BoundaryEventNodeInstance.java
- kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/PublishEventTest.java
Fix https://issues.redhat.com/browse/KOGITO-4057
BoundaryEventNodes didn't have a triggerTime initialized. This field is mapped to the graphql.schema as the `NodeInstance:enter` required field.
> [KOGITO-4057] Missing triggerTime in BoundaryEventNodes

- addons/monitoring/monitoring-elastic/monitoring-elastic-common/pom.xml
- addons/monitoring/monitoring-elastic/monitoring-elastic-common/src/main/java/org/kie/kogito/monitoring/elastic/common/ElasticConfigFactory.java
- addons/monitoring/monitoring-elastic/monitoring-elastic-common/src/main/java/org/kie/kogito/monitoring/elastic/common/ElasticRegistry.java
- addons/monitoring/monitoring-elastic/monitoring-elastic-common/src/main/java/org/kie/kogito/monitoring/elastic/common/KogitoElasticConfig.java
- addons/monitoring/monitoring-elastic/monitoring-elastic-common/src/test/java/org/kie/kogito/monitoring/elastic/common/ElasticConfigFactoryTest.java
- addons/monitoring/monitoring-elastic/monitoring-elastic-common/src/test/java/org/kie/kogito/monitoring/elastic/common/ElasticRegistryTest.java
- addons/monitoring/monitoring-elastic/monitoring-elastic-common/src/test/java/org/kie/kogito/monitoring/elastic/common/KogitoElasticConfigTest.java
- addons/monitoring/monitoring-elastic/monitoring-elastic-quarkus-addon/pom.xml
- addons/monitoring/monitoring-elastic/monitoring-elastic-quarkus-addon/src/main/java/org/kie/kogito/monitoring/elastic/quarkus/QuarkusElasticRegistryProvider.java
- addons/monitoring/monitoring-elastic/monitoring-elastic-quarkus-addon/src/main/resources/META-INF/kogito.addon
- addons/monitoring/monitoring-elastic/monitoring-elastic-springboot-addon/pom.xml
- addons/monitoring/monitoring-elastic/monitoring-elastic-springboot-addon/src/main/java/org/kie/kogito/monitoring/elastic/springboot/SpringbootElasticRegistryProvider.java
- addons/monitoring/monitoring-elastic/monitoring-elastic-springboot-addon/src/main/resources/META-INF/kogito.addon
- addons/monitoring/monitoring-elastic/pom.xml
- addons/monitoring/pom.xml
- kogito-bom/pom.xml
- kogito-build-parent/pom.xml
jira: https://issues.redhat.com/browse/KOGITO-3823
Third and last PR for the monitoring refactoring. The user can configure the `quarkus` or the `springboot` elastic addon with the config properties 
`kogito.addon.monitoring.elastic.host`
`kogito.addon.monitoring.elastic.index`
`kogito.addon.monitoring.elastic.userName`
`kogito.addon.monitoring.elastic.password`
and so on..
No additional requirements are requested to the user in order to use the addon. 
This PR aims to add the artifacts to export the metrics to elastic. 
- [ x] You have read the [contributors guide](CONTRIBUTING.md)
- [ x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
> KOGITO-3823 - Elastic monitoring addons 

- addons/tracing/tracing-decision-springboot-addon/src/main/java/org/kie/kogito/tracing/decision/SpringBootModelEventEmitter.java
Jira bug: https://issues.redhat.com/browse/KOGITO-4114
There is a conflict between the decision tracing topic and the dmn tracing topic names. If the user configures the tracing addon with the property `kogito.addon.tracing.model.kafka.topic.name`, the dmn models are pushed to the same topic of the decisions. 
By consequence: 
- the model event causes a deserialization exception and the event is discarded
- no models are registered
> KOGITO-4114 - Solve conflicts of tracing dmn model topic name key

- Jenkinsfile
To allow to select correct target branch on optaplanner.
Cherry-pick: https://github.com/kiegroup/kogito-runtimes/pull/966
> [master][cherry-pick] fix for optaplanner checkout in PR release branch (#966)

- kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegen.java
[KOGITO-4151](https://issues.redhat.com/browse/KOGITO-4151)
`unitsMap` is not used anymore.
> KOGITO-4151 - Remove unused unitsMap from IncrementalRuleCodegen

- archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/README.md
- archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/src/main/resources/application.properties
- integration-tests/integration-tests-quarkus-decisions/src/main/resources/application.properties
As described in JIRA https://issues.redhat.com/browse/KOGITO-4224
Moreover since Quarkus v1.11 I would just embrace the (Quarkus) platform conventions: https://quarkus.io/blog/quarkus-1-11-0-final-released/#non-application-endpoints-moved-to-q
> KOGITO-4224 Kogito Quarkus archetype disaligned static serv. Swagger/OAS

- api/kogito-api/src/build/revapi-config.json
- api/kogito-api/src/main/java/org/kie/api/builder/model/KieBaseModel.java
- api/kogito-api/src/main/java/org/kie/api/conf/BetaRangeIndexOption.java
- api/kogito-api/src/main/resources/org/kie/api/kmodule.xsd
- forward port for kogito-api
https://issues.redhat.com/browse/DROOLS-5910
This PR is a forward port of https://github.com/kiegroup/droolsjbpm-knowledge/commit/5cafa765f32074193dc7d8e8820b641fc50eb677
This PR is required when you update to the drools version which contains https://github.com/kiegroup/drools/commit/d0ecb0a55a454eeec45658f2ebe58a878dd0dc87
(currently drools 7.50.0-SNAPSHOT)
> DROOLS-5910 Enable range index for JoinNode

- .github/pull_request_template.md
This is a proposal to enforce that we have an IDE configuration file that the contributors should use. 
Chatting with people, It turned out that not everybody is using it. 
This is mainly for new joiners/contributors that are not aware of it (even if it's in the contributors guide - first line of the template). 
> Proposal: enforce code-style format check in pull request template

- CONTRIBUTING.md
- kogito-build-parent/pom.xml
- Centralize license header settings in `kogito-build-parent` bom
- Use checkstyle to validate license header based on regex ( no git dependency )
- For now Checkstyle will log errors in console but not break the build, this will allow changes to be pushed later on before we turned it on
- For automatically formatting classes we will still use `license-maven-plugin`. To format code please run:  `mvn com.mycila:license-maven-plugin:format`
Assembly:
- https://github.com/kiegroup/kogito-examples/pull/553
- https://github.com/kiegroup/kogito-runtimes/pull/1046
> KOGITO-4376 Review license header validation during maven build

- kogito-quarkus-extension/integration-test-hot-reload/pom.xml
- kogito-quarkus-extension/integration-test-legacy/pom.xml
- kogito-quarkus-extension/integration-test/pom.xml
This native-image mojo has been removed in current master.
It was deprecated for a while and quarkus.package.type=native should be used instead.
This PR will work with both Quarkus 1.11 and Quarkus master so can be safely merged.
> KOGITO-4430 Remove native-image mojo usage in Quarkus ITs

- integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/BasicRestTest.java
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/BasicRestTest.java
- jbpm/process-serialization-protobuf/src/main/java/org/jbpm/marshalling/impl/AbstractProtobufProcessInstanceMarshaller.java
Setting variable context from marshaller even if there are no properties
> [KOGITO-4411] null pointer exception when process is started

- kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/io/CollectedResource.java
resolve symlinks -- on macOS `/var` is symlinked to `/private/var`
https://issues.redhat.com/browse/KOGITO-4435
> KOGITO-4435 Fix path resolution error on macOS

- Jenkinsfile
- Jenkinsfile.deploy
- Jenkinsfile.drools
- Jenkinsfile.native
- Jenkinsfile.promote
- Jenkinsfile.quarkus
- Jenkinsfile.sonarcloud
https://issues.redhat.com/browse/KOGITO-4501
Use shared library to clean the node used by Jenkins.
This will also allow to improve the shared lib later on without having to modify all pipelines.
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1090
- https://github.com/kiegroup/optaplanner/pull/1172
- https://github.com/kiegroup/kogito-apps/pull/665
- https://github.com/kiegroup/kogito-examples/pull/584
> KOGITO-4501 Clean node in pipelines

- archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/pom.xml
Jira: [KOGITO-4558](https://issues.redhat.com/browse/KOGITO-4558)
Escaping properties in archetype-resources to defer their expansion.
> KOGITO-4558 escape properties to defer expansion

- kogito-codegen-modules/kogito-codegen-predictions/src/main/java/org/kie/kogito/codegen/prediction/PredictionCodegen.java
- kogito-codegen-modules/kogito-codegen-predictions/src/test/java/org/kie/kogito/codegen/prediction/PredictionCodegenTest.java
- kogito-codegen-modules/kogito-codegen-predictions/src/test/resources/prediction/test_scorecard.pmml
- kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/KogitoPackageSources.java
@danielezonca @evacchi  @jiripetrlik
See https://issues.redhat.com/browse/KOGITO-4586
This PR restore the reflect-config.json generation that was wrongly removed by https://issues.redhat.com/browse/DROOLS-5702
> [KOGITO-4586] Fixing reflect-config.json generation

- kogito-quarkus-parent/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-deployment/src/main/java/org/kie/kogito/quarkus/decisions/deployment/DecisionsAssetsProcessor.java
- kogito-quarkus-parent/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java
* [Jira task](https://issues.redhat.com/browse/KOGITO-4637)
Building [the dmn-event-driven-quarkus example from master](https://github.com/kiegroup/kogito-examples/tree/master/dmn-event-driven-quarkus) in native mode returns this error:
```
2021-03-10 09:06:32,599 ERROR [org.kie.kog.clo.CloudEventUtils] (vert.x-eventloop-thread-0) Unable to serialize CloudEvent data: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class org.kie.kogito.dmn.rest.KogitoDMNResult and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1277)
```
According to [Quarkus …
> KOGITO-4637: add dmn classes to DecisionsAssetsProcessor

- kogito-quarkus-parent/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test/src/test/java/org/kie/kogito/quarkus/dmn/NativeDMNIT.java
breaks Quarkus LTS **native** build
https://issues.redhat.com/browse/KOGITO-4663
building locally native image:
all green ☑️
> KOGITO-4663 Disable strongly-typed DMN native build (currently broken)

- .github/quarkus-ecosystem-test
- integration-tests/integration-tests-kogito-plugin/src/it/integration-tests-kogito-plugin-it/invoker.properties
cherry pick #1142 
Do not push versions as system properties as it does not work very well
with the invoker.
Also no need to push the version manually to the invoker, things are
only handled in the pom.
> [1.4.x] KOGITO-4687 Fix Quarkus Ecosystem CI with Quarkus master

- kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceQuarkusTemplate.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceUserTaskQuarkusTemplate.java
cherry pick #1146 
https://issues.redhat.com/browse/KOGITO-4693
a particularly contrived nested lambda case causes Quarkus monitoring feature to break with the following trace during hot reload
```
Caused by: java.lang.IllegalArgumentException: Cannot find method lambda$taskTransition_Task_0$16[class java.lang.String, class java.lang.String, class java.lang.String, class com.example.New_text_process_2_TaskOutput, class java.lang.String, interface java.util.List] on class com.example.New_text_processResource
at io.quarkus.arc.impl.Reflections.findMethodInternal(Reflections.java:110)
at io.quarkus.arc.impl.Reflections.access$100(Reflections.java:24)
at io.quarkus.arc.impl.Reflections$2.apply(Reflections.java:40)
at io.quarkus.arc.impl.Reflections$2.apply(Reflections.java:37)
at …
```
> [1.4.x] KOGITO-4693 Use static method in process codegen (workaround Quarkus)

- kogito-quarkus-parent/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/InMemoryCompiler.java
- kogito-quarkus-parent/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java
- kogito-quarkus-parent/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoQuarkusResourceUtils.java
- kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-deployment/src/main/java/org/kie/kogito/quarkus/deployment/ProcessesAssetsProcessor.java
https://issues.redhat.com/browse/KOGITO-4737
CompilatIonProviders use `-g -parameters` while in the BuildStep (InMemoryCompiler) we do not propagate these flags, not even in dev mode.
This PR propagates such flags when (if) CompilationProvider is used together with the BuildStep (see https://github.com/kiegroup/kogito-runtimes/pull/1123)
(this currently does not really happen because BuildStep-based early quit in DevMode, subsumed by the CompilationProvider, but in another PR we will probably enable this flow)
> KOGITO-4737 Quarkus Extension: Should use same compiler flags in CompilationProvider and BuildStep

- kogito-build-parent/pom.xml
Updates Kogito to a tagged release of Drools, so that https://github.com/kiegroup/optaplanner/pull/1220 can consume the new APIs.
> Bump Drools to 7.52.0.t20210322

- Jenkinsfile
- integration-tests/integration-tests-quarkus-processes/pom.xml
- integration-tests/integration-tests-quarkus-processes/src/main/resources/application.properties
See: https://github.com/quarkusio/quarkus/issues/12486#issuecomment-802169769
<details>
<summary>
</summary>
</details>
> Fixing native compilation on Process Integration Tests

- Jenkinsfile
- Jenkinsfile.native
https://issues.redhat.com/browse/KOGITO-4770
So we don't need to have the latest GraalVM on node for native building. It uses the quarkus provided docker image.
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1173
- https://github.com/kiegroup/optaplanner/pull/1232
- https://github.com/kiegroup/kogito-apps/pull/727
- https://github.com/kiegroup/kogito-examples/pull/626
<details>
<summary>
</summary> …
> KOGITO-4770 Corrected native PR check

- kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/RuleCodegenError.java
https://issues.redhat.com/browse/KOGITO-4845
<details>
<summary>
</summary>
</details>
> [KOGITO-4845] Kogito doesn't show stack trace of executable model generic Runtime Errors

- addons/events/knative-eventing-addon/src/main/java/org/kie/kogito/events/knative/ce/extensions/KogitoProcessExtension.java
- addons/events/knative-eventing-addon/src/test/java/org/kie/kogito/events/knative/ce/CloudEventConverterTest.java
- addons/events/knative-eventing-addon/src/test/java/org/kie/kogito/events/knative/ce/extensions/KogitoProcessExtensionTest.java
- addons/events/knative-eventing-addon/src/test/java/org/kie/kogito/events/knative/ce/http/CloudEventListenerResourceTest.java
- api/kogito-events-api/pom.xml
- api/kogito-events-api/src/main/java/org/kie/kogito/event/AbstractDataEvent.java
- api/kogito-events-api/src/main/java/org/kie/kogito/event/CloudEventExtensionConstants.java
- api/kogito-events-api/src/test/java/org/kie/kogito/event/CloudEventExtensionConstantsTest.java
- api/kogito-services/src/main/java/org/kie/kogito/services/event/AbstractProcessDataEvent.java
- api/kogito-services/src/main/java/org/kie/kogito/services/event/UserTaskInstanceDataEvent.java
- jbpm/jbpm-flow/src/test/java/org/kie/kogito/event/impl/EventImplTest.java
See: https://issues.redhat.com/browse/KOGITO-4456 
In this PR we adjust the extension CloudEvent data to match the required rules from the spec: https://github.com/cloudevents/spec/blob/v1.0.1/spec.md#attribute-naming-convention
I plan to remove the `knative-addon` module in https://issues.redhat.com/browse/KOGITO-4457 (cc @MarianMacik)
@kostola @danielezonca I think you can move the DMN extension properties to the `events-api` as well and verify if the names matches the specification.
> [KOGITO-4456] - Fix CloudEvents Kogito extension naming

- Jenkinsfile
- addons/cloudevents/cloudevents-spring-boot-addon-it/pom.xml
- addons/explainability-addon/explainability-quarkus-addon/pom.xml
- addons/persistence/infinispan-quarkus-health-addon/pom.xml
- addons/task-management/task-management-quarkus-addon/pom.xml
- archetypes/kogito-quarkus-archetype/pom.xml
- archetypes/kogito-quarkus-dm-archetype/pom.xml
- archetypes/kogito-springboot-archetype/pom.xml
- archetypes/kogito-springboot-dm-archetype/pom.xml
- archetypes/pom.xml
- integration-tests/integration-tests-kogito-plugin/pom.xml
- integration-tests/integration-tests-kogito-plugin/src/it/integration-tests-kogito-plugin-it/pom.xml
- integration-tests/integration-tests-quarkus-decisions/pom.xml
- integration-tests/integration-tests-quarkus-predictions/pom.xml
- integration-tests/integration-tests-quarkus-processes/pom.xml
- integration-tests/integration-tests-quarkus-rules/pom.xml
- integration-tests/integration-tests-springboot/pom.xml
- jbpm/jbpm-bpmn2/pom.xml
- kogito-build-parent/pom.xml
- kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-integration-test-hot-reload/pom.xml
- kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-integration-test-maven-devmode/pom.xml
- kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-integration-test-maven-devmode/src/test/java/io/quarkus/it/kogito/devmode/DevMojoIT.java
- kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-integration-test/pom.xml
- kogito-quarkus-parent/kogito-quarkus-predictions-extension/kogito-quarkus-predictions-integration-test/pom.xml
- kogito-quarkus-parent/pom.xml
[KOGITO-4847](https://issues.redhat.com/browse/KOGITO-4847)
* fixing surefire/filesafe systemProperties to systemPropertyVariables (https://maven.apache.org/surefire/maven-surefire-plugin/examples/system-properties.html, https://maven.apache.org/surefire/maven-failsafe-plugin/examples/system-properties.html)
* moving invoker properties to kogito-build-parent pluginManagement for invoker plugin.
* introducing explicit test dependencies in modules that use invoker to run other maven projects - aggregation of the dependencies need by those projects being invoked.
* Making sure all maven invocations respect `-Dmaven.repo.local=<path>` and `-s <path>/settings.xml` configurations
* by setting explicitly in surefire/failsafe (for quarkus plugin)
* by passing directly in code (IT tests for …
> KOGITO-4847 Fix local builds for integration tests

- kogito-build-parent/pom.xml
Jira: [KOGITO-4895](https://issues.redhat.com/browse/KOGITO-4895)
Property sonar.exclusions defined in integration-tests module is affecting sonar reporting for all the modules for some reason. As a short-term solution, trying to replace the exclusions **/* with property sonar.skip, which should be scoped to a module based on the documentation.
Further investigation why is the issue occurring will be a follow-up task.
<details>
<summary>
</summary>
* <b>Full Kogito testing</b> (with cloud images and operator BDD testing) …
> KOGITO-4895 add empty sonar.exclusions into kogito-build-parent

- api/kogito-api/src/main/java/org/kie/kogito/process/workitem/TaskModel.java
- integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/TaskTest.java
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/EnumsTest.java
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/TaskTest.java
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/TestWorkItem.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/UserTaskModelMetaData.java
- jbpm/jbpm-flow-builder/src/main/resources/class-templates/TaskInputTemplate.java
- jbpm/jbpm-flow-builder/src/main/resources/class-templates/TaskModelTemplate.java
- jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java
- jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/BaseWorkItem.java
- jbpm/process-serialization-protobuf/pom.xml
- jbpm/process-serialization-protobuf/src/main/java/org/jbpm/marshalling/impl/AbstractProtobufProcessInstanceMarshaller.java
- jbpm/process-serialization-protobuf/src/main/java/org/jbpm/marshalling/impl/JBPMMessages.java
- jbpm/process-serialization-protobuf/src/main/resources/org/jbpm/marshalling/jbpmmessages.proto
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessResourceGenerator.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceQuarkusTemplate.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceSpringTemplate.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceUserTaskQuarkusTemplate.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceUserTaskSpringTemplate.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/TaskModelFactoryTemplate.java
Changes GET task is and GET tasks API to return same data. 
The new structure contains both input and output parametes, not just input.
Merge with https://github.com/kiegroup/kogito-examples/pull/652
Relevant generated code
```
public class Approvals_TaskModelFactory {
public static TaskModel from(org.kie.kogito.process.WorkItem workItem) {
switch(workItem.getNodeId()) {
case "2":
return Approvals_2_TaskModel.from(workItem);
case "1":
return Approvals_1_TaskModel.from(workItem);
default:
throw new IllegalArgumentException("Invalid task name for work item " + workItem);
}
}
}
```
And
```
public class Approvals_1_TaskModel implements TaskModel<org.acme.travels.Approvals_1_TaskInput, org.acme.travels.Approvals_1_TaskOutput> {
private String id;
private String name;
private int state;
private …
```
> [KOGITO-4502] GET task id API to return task info, not only the input model

- api/kogito-api/src/main/java/org/kie/kogito/rules/RuleUnit.java
- drools/kogito-ruleunits/src/main/java/org/kie/kogito/rules/units/impl/AbstractRuleUnit.java
- drools/kogito-ruleunits/src/main/java/org/kie/kogito/rules/units/impl/AbstractRuleUnits.java
* [KOGITO-4956] avoid registering anonymous rule units
* wip
(cherry picked from commit c6cc0f7514cb592fbebe29d0b502d3dbfc3965fd)
<details>
<summary>
</summary>
<b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can …
> [1.6.x][KOGITO-4956] avoid registering anonymous rule units

- addons/cloudevents/pom.xml
- addons/events/pom.xml
- addons/pom.xml
- archetypes/pom.xml
- kogito-codegen-modules/pom.xml
- pom.xml
This PR is trying to fix [issue](https://youtrack.jetbrains.com/issue/IDEA-266880) in Intellij IDEA where modules in profiles cannot be loaded even the profile is activated by default. The original jira where the profile(s) where created 
<details>
<summary>
</summary>
<b>This check should be used only if a big change is done as it takes time to run, need …
> [1.5.x] [BXMSPROD-1208] added community vs prod modules activation profile

- kogito-build-parent/pom.xml
https://issues.redhat.com/browse/KOGITO-4887
- https://github.com/kiegroup/kogito-runtimes/pull/1200
- https://github.com/kiegroup/kogito-apps/pull/774
- https://github.com/kiegroup/kogito-examples/pull/667
- Upgrades Quarkus 1.13 to latest:
- does not include ISPN 12 yet
- adds a version override for MongoDB on spring boot (otherwise the version upgrade breaks)
- makes our life miserable in the process
🙈 
<details>
```diff
@@ -17,7 +17,7 @@
<bouncycastle.version>1.68</bouncycastle.version>
<bouncycastle.fips.version>1.0.2</bouncycastle.fips.version>
<bouncycastle.tls.fips.version>1.0.11</bouncycastle.tls.fips.version>
-        <jandex.version>2.2.2.Final</jandex.version>
+        <jandex.version>2.2.3.Final</jandex.version>
<resteasy.version>4.5.9.Final</resteasy.version> …
```
> KOGITO-4887 Bump Quarkus 1.13

- .jenkins/dsl/jobs.groovy
- Jenkinsfile.drools
This will allow to run sanity checks on Drools release
<details>
<summary>
</summary>
</details>
> Setup Drools pipeline as configurable

- kogito-build/kogito-build-parent/pom.xml
Jira: https://issues.redhat.com/browse/KOGITO-4895
Property sonar.exclusions need to be in full form to get an empty value explicitly set.
<details>
<summary>
</summary>
</details>
> KOGITO-4895 Keep sonar.exclusions property empty

- archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/pom.xml
- archetypes/kogito-quarkus-dm-archetype/src/main/resources/archetype-resources/pom.xml
Jira: https://issues.redhat.com/browse/KOGITO-5140
Property expansion in archetype resources occur early if the referenced property is part of the maven build that builds the archetype itself. To prevent this, all property references that are supposed to be referencing a property in the generated project (i.e. keep in form `${kogito.version}` instead of expanding with the exact value during archetype project build) need to have the dollar sign escaped as `\${kogito.version}`.
<details>
<summary>
</summary>
* <b>Full Kogito …
> KOGITO-5140 defer expansion of properties with versions in quarkus archetypes

- api/kogito-api/src/main/java/org/kie/kogito/internal/process/runtime/KogitoProcessInstance.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/context/variable/VariableScopeInstance.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/ProcessInstanceImpl.java
- jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java
See: https://issues.redhat.com/browse/KOGITO-5190
Context: https://kie.zulipchat.com/#narrow/stream/232676-kogito/topic/Get.20current.20process.20instance.20Id
After the unfork, we had to deprecate the `long getId()` method from the process instance since on Kogito we use a UUID instead. There were some leftovers in the code that we fixed in this PR. Although there are some usages that might also need to be removed in the future:
https://github.com/kiegroup/kogito-runtimes/blob/1.6.0.Final/jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateBasedNodeInstance.java#L108-L109
<details>
<summary>
How to retest …
> [KOGITO-5190] - Removing usage of deprecated getId from core process

- addons/persistence/postgresql-persistence-addon/src/main/java/org/kie/kogito/persistence/KogitoProcessInstancesFactory.java
- addons/persistence/postgresql-persistence-addon/src/main/java/org/kie/kogito/persistence/postgresql/PostgreProcessInstances.java
- addons/persistence/postgresql-persistence-addon/src/main/resources/sql/create_tables.sql
- addons/persistence/postgresql-persistence-addon/src/test/java/org/kie/persistence/postgresql/PostgreProcessInstancesIT.java
- addons/persistence/postgresql-persistence-addon/src/test/java/org/kie/persistence/postgresql/PostgreProcessInstancesWithLockIT.java
- api/kogito-api/src/main/java/org/kie/kogito/process/MutableProcessInstances.java
- api/kogito-api/src/main/java/org/kie/kogito/process/ProcessInstance.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessInstanceManager.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/DefaultProcessInstanceManager.java
- jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java
- jbpm/jbpm-flow/src/test/java/org/kie/kogito/process/impl/AbstractProcessInstanceTest.java
- jbpm/jbpm-flow/src/test/java/org/kie/kogito/process/impl/DefaultProcessInstanceManagerTest.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/persistence/PersistenceGenerator.java
It includes optional lock for optimistic concurrency using version for PostgreSQL persistence.
<details>
<summary>
</summary>
<b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests …
> [KOGITO-4438] PostgreSQL research about doing optmistic locking

- .github/workflows/quarkus-snapshot.yaml
The ecosystem CI fails due to: "Error: The process '/usr/bin/git' failed with exit code 1" as its `master` branch has been renamed to `main`.
<details>
<summary>
</summary>
<b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests …
> Rename master to main in Quarkus ecosystem CI

- jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/serialization/process/protobuf/ProtostreamProtobufAdapterTypeProvider.java
During dev the context class loader in quarkus has the right class loader for reading resources.
> [KOGITO-5244] Error in process instance marshalling persisting in mongodb.

- kogito-cloud-services/kogito-cloud-kubernetes-client/src/test/java/org/kie/kogito/cloud/kubernetes/client/KubeClientConfigTest.java
- kogito-cloud-services/kogito-cloud-kubernetes-client/src/test/java/org/kie/kogito/cloud/kubernetes/client/operations/ServiceOperationsStatusCodeHandlingTest.java
- kogito-cloud-services/kogito-cloud-kubernetes-client/src/test/java/org/kie/kogito/cloud/kubernetes/client/operations/ServiceOperationsTest.java
- kogito-cloud-services/kogito-cloud-workitems/src/test/java/org/kie/kogito/cloud/workitems/BaseTestKubernetesDiscoveredService.java
- kogito-cloud-services/kogito-cloud-workitems/src/test/java/org/kie/kogito/cloud/workitems/DiscoveredServiceWorkItemHandlerTest.java
- kogito-cloud-services/kogito-cloud-workitems/src/test/java/org/kie/kogito/cloud/workitems/KNativeDiscoveredServiceWorkItemHandlerTest.java
- kogito-cloud-services/kogito-cloud-workitems/src/test/java/org/kie/kogito/cloud/workitems/KubernetesDiscoveredServiceWorkItemHandlerTest.java
- kogito-cloud-services/kogito-cloud-workitems/src/test/java/org/kie/kogito/cloud/workitems/service/discovery/KubernetesServiceDiscoveryTest.java
See origin issue: https://issues.redhat.com/browse/KOGITO-5273
See refactor issue: https://issues.redhat.com/browse/KOGITO-5284
KOGITO-5284 will be part of the Addon API refactoring effort. These "cloud services" needed to be re-engineered to be an addon instead of a loose couple library in the runtimes ecosystem.
<details>
<summary>
</summary>
* <b>Full Kogito …
> [KOGITO-5273] - Disabling Kubernetes API Mock tests until refactoring

- addons/monitoring/monitoring-core/monitoring-core-quarkus-addon/src/main/java/org/kie/kogito/monitoring/core/quarkus/QuarkusMetricsFilterRegister.java
- addons/monitoring/monitoring-core/monitoring-core-quarkus-addon/src/test/java/org/kie/kogito/monitoring/core/quarkus/QuarkusMetricsFilterRegisterTest.java
https://issues.redhat.com/browse/KOGITO-5282
Before: performing `mvn clean package` on `dmn-drools-quarkus-metrics` project
> [INFO] --- quarkus-maven-plugin:1.13.3.Final:build (default) @ dmn-drools-quarkus-metrics ---
> [INFO] [org.jboss.threads] JBoss Threads version 3.2.0.Final
> [INFO] Performed addonsConfig discovery, found: AddonsConfig{usePersistence=false, useTracing=false, useMonitoring=true, usePrometheusMonitoring=true, useCloudEvents=false, useExplainability=false, useProcessSVG=false}
> [INFO] Generator discovery performed, found [openapispecs, rules, decisions]
> ...
> **[WARNING] [io.quarkus.resteasy.common.deployment.ResteasyCommonProcessor] Directly injecting a @ConfigProperty into a JAX-RS provider may lead to unexpected results. To ensure proper results, please change …
> [KOGITO-5282] Fix warning in Quarkus related to ConfigProperty usage with Provider

- kogito-bom/pom.xml
Given that the kogito-bom is imported into the quarkus-universe-bom, it is expected to include the extension deployment artifacts in addition to the runtime ones.
> Add Quarkus extension deployment artifacts to the kogito-bom

- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ServerlessWorkflowParser.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/ServerlessWorkflowParsingTest.java
See: https://issues.redhat.com/browse/KOGITO-3919
Small change in order to use CE `type` on SW Event definitions.
<details>
<summary>
</summary>
* <b>Native checks</b> …
> [KOGITO-3919] - Using CE type instead of Source on SW builders

- integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-infinispan/src/test/java/org/kie/kogito/it/NativeInfinispanPersistenceIT.java
- integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-kafka-persistence/src/test/java/org/kie/kogito/it/NativeKafkaPersistenceIT.java
- integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-mongodb/src/test/java/org/kie/kogito/it/NativeMongoDBPersistenceIT.java
- integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-postgresql/src/test/java/org/kie/kogito/it/NativePostgreSQLPersistenceIT.java
- integration-tests/integration-tests-quarkus-processes-persistence/pom.xml
- This PR fixes native image tests for persistence which weren't running 🚀  
- However when they run, they are all broken 😢 
- PostgreSQL: serialization issue
- Infinispan: serialization issue
- MongoDB: serialization issue
- Kafka: field is being injected (not supported with NativeImageTest)
> KOGITO-5361 Native Image tests are not configured correctly on persistence addons

- kogito-cloud-services/kogito-cloud-kubernetes-client/src/test/java/org/kie/kogito/cloud/kubernetes/client/KubeClientConfigTest.java
- kogito-cloud-services/kogito-cloud-kubernetes-client/src/test/java/org/kie/kogito/cloud/kubernetes/client/operations/ServiceOperationsStatusCodeHandlingTest.java
- kogito-cloud-services/kogito-cloud-kubernetes-client/src/test/java/org/kie/kogito/cloud/kubernetes/client/operations/ServiceOperationsTest.java
- kogito-cloud-services/kogito-cloud-workitems/src/test/java/org/kie/kogito/cloud/workitems/BaseTestKubernetesDiscoveredService.java
- kogito-cloud-services/kogito-cloud-workitems/src/test/java/org/kie/kogito/cloud/workitems/DiscoveredServiceWorkItemHandlerTest.java
- kogito-cloud-services/kogito-cloud-workitems/src/test/java/org/kie/kogito/cloud/workitems/KNativeDiscoveredServiceWorkItemHandlerTest.java
- kogito-cloud-services/kogito-cloud-workitems/src/test/java/org/kie/kogito/cloud/workitems/KubernetesDiscoveredServiceWorkItemHandlerTest.java
- kogito-cloud-services/kogito-cloud-workitems/src/test/java/org/kie/kogito/cloud/workitems/service/discovery/KubernetesServiceDiscoveryTest.java
Cherry Pick for #1354
<details>
<summary>
</summary>
* <b>Run (or rerun) native specific test(s)</b> …
> [1.5.x][KOGITO-5273] - Disabling Kubernetes API Mock tests until refactoring

- jbpm/jbpm-flow/src/main/java/org/kie/kogito/event/impl/CloudEventConsumer.java
As a quick fix to allow process chaining through messages, if
kogitoReferenceId does not point to an existing process instance, create
a new one.
This is a temporary solution till we migrate jBPM conversation approach
implemented with https://issues.redhat.com/browse/JBPM-9735
> [KOGITO-5319] KogitoReferenceId handling

- .github/workflows/apps-pr.yml
- .github/workflows/examples-pr.yml
- .github/workflows/optaplanner-pr.yml
- .github/workflows/runtimes-pr.yml
https://issues.redhat.com/browse/BXMSPROD-1390
related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1384
- https://github.com/kiegroup/kogito-examples/pull/736
<details>
<summary>
</summary>
* <b>Native …
> BXMSPROD-1390 github actions flows concurrency

- kogito-build/kogito-build-parent/pom.xml
- kogito-quarkus-parent/kogito-quarkus-test-list/pom.xml
- kogito-quarkus-parent/pom.xml
Jira: https://issues.redhat.com/browse/KOGITO-5247
This modules produces `kogito-quarkus-test-list` XML file with testArtifact list defined using `fileSet` resources configuration of `rpkgtests-maven-plugin` plugin.
This artifact will be released and available in Maven repository.
<details>
<summary>
</summary>
* <b>Native checks</b> …
> KOGITO-5247 add kogito-quarkus-test-list module

- kogito-build/kogito-build-parent/pom.xml
[KOGITO-5445](https://issues.redhat.com/browse/KOGITO-5445)
Upgrading version of rpkgtests-maven-plugin due to build issue in kogito-quarkus-test-list on OpenJDK 16.
<details>
<summary>
</summary> …
> KOGITO-5445 upgrade rpkgtests-maven-plugin version

- api/kogito-api/src/main/java/org/kie/kogito/MapInput.java
- api/kogito-api/src/main/java/org/kie/kogito/MapInputId.java
- api/kogito-api/src/main/java/org/kie/kogito/Model.java
- api/kogito-api/src/main/java/org/kie/kogito/Models.java
- api/kogito-api/src/main/java/org/kie/kogito/ReflectiveModelAccessException.java
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-kafka-it/src/test/java/org/kie/kogito/integrationtests/springboot/PingPongMessageTest.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ModelMetaData.java
- jbpm/jbpm-flow-builder/src/main/resources/class-templates/ModelNoIDTemplate.java
- jbpm/jbpm-flow-builder/src/main/resources/class-templates/ModelTemplate.java
The idea is to remove useless codegen and align to a single strategy over the whole platform; i.e., replace it with reflection; then use Quarkus' opt-in mechanisms where necessary to allow reflection on our models. 
This will also make it possible for users to use their own models (otherwise user-provided models should explicitly provide toMap/fromMap methods, which is inconvenient).
- In further PRs we are going also to remove generics from `Process<T>` and `ProcessInstance<T>`; making them `Process` and `ProcessInstance`.
- Instead of the `T variables()` method, we will provide a `<T> T variables(Class<T>)` method
- users will be able to supply their choice of a class to such method, and retrieve the subset of fields that match the variables
- this in turn subsumes the requirement for …
> KOGITO-5062 Use reflection in generated models

- kogito-build-parent/pom.xml
- kogito-quarkus-parent/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test-hot-reload/pom.xml
- kogito-quarkus-parent/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test/pom.xml
- kogito-quarkus-parent/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/pom.xml
- kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-deployment/pom.xml
- kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-integration-test-hot-reload/pom.xml
- kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-integration-test-maven-devmode/pom.xml
- kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-integration-test/pom.xml
- kogito-quarkus-parent/kogito-quarkus-predictions-extension/kogito-quarkus-predictions-integration-test/pom.xml
- kogito-quarkus-parent/kogito-quarkus-rules-extension/kogito-quarkus-rules-integration-test-hot-reload/pom.xml
- kogito-quarkus-parent/kogito-quarkus-rules-extension/kogito-quarkus-rules-integration-test/pom.xml
- kogito-quarkus-parent/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/pom.xml
…t5-internal and add new prop for non-bom managed dep.
When aligning internally to a productized version of Quarkus in [RHPAM-3706](https://issues.redhat.com/browse/RHPAM-3706) we realised there are some deps that aren't part of the runtime and therefore aren't productized, we use `quarkus-junit5-internal` which is defined in the quarkus-bom so this change uses the BOM managed version (as is done in other places).
There is also quarkus-test-maven being used that is not BOM managed, as a temporary solution to keep it at the community version I'm introducing a version property to be kept in sync with version.io.quarkus that would not be touched by PME when aligning the version in the productized build.
Please make sure that your PR …
> [RHPAM-3706] Use BOM managed version for non-productized quarkus-juni… [1.5.x]

- .github/quarkus-ecosystem-test
`quarkus-ecosystem-test` is bumping only the Quarkus version, without the 3rd party dependencies, this is a recipe for breakage: add 3rd party dependency bump to the CI.
Note: in our script we also [pin the Maven version](https://github.com/kiegroup/kogito-pipelines/blob/master/tools/update-quarkus-versions.sh#L141-L146) to the one running in our repo -- so that Maven plugins are kept aligned to our Maven executable. This may not be required for this CI.
> Quarkus Ecosystem CI: Update dependencies using Quarkus BOM

- .jenkins/dsl/jobs.groovy
Reverts kiegroup/kogito-runtimes#1423
Revert until https://github.com/kiegroup/optaplanner/pull/1414 and related are merged
> Revert "PLANNER-2467 Jenkinsfiles moved to .ci/jenkins"

- quarkus/extensions/kogito-quarkus-test-list/pom.xml
[KOGITO-5580](https://issues.redhat.com/browse/KOGITO-5580)
Use absolute paths starting at project root in kogito-quarkust-test-list module configuration.
<details>
<summary>
</summary> …
> KOGITO-5580 adapt kogito-quarkus-test-list after refactoring

- kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/Generator.java
- kogito-codegen-modules/kogito-codegen-core/src/main/java/org/kie/kogito/codegen/core/AbstractGenerator.java
- kogito-codegen-modules/kogito-codegen-core/src/test/java/org/kie/kogito/codegen/core/ApplicationGeneratorTest.java
- kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java
- kogito-codegen-modules/kogito-codegen-decisions/src/test/java/org/kie/kogito/codegen/decision/DecisionCodegenTest.java
- kogito-codegen-modules/kogito-codegen-decisions/src/test/java/org/kie/kogito/codegen/decision/DecisionModelResourcesProviderGeneratorTest.java
- kogito-codegen-modules/kogito-codegen-decisions/src/test/java/org/kie/kogito/codegen/decision/DecisionValidationTest.java
- kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/OpenApiClientCodegen.java
- kogito-codegen-modules/kogito-codegen-openapi/src/test/java/org/kie/kogito/codegen/openapi/client/OpenApiClientCodegenTest.java
- kogito-codegen-modules/kogito-codegen-predictions/src/main/java/org/kie/kogito/codegen/prediction/PredictionCodegen.java
- kogito-codegen-modules/kogito-codegen-predictions/src/test/java/org/kie/kogito/codegen/prediction/PredictionCodegenTest.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/persistence/PersistenceGenerator.java
- kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/process/ProcessCodegenTest.java
- kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/process/persistence/FileSystemPersistenceGeneratorTest.java
- kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/process/persistence/InfinispanPersistenceGeneratorTest.java
- kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/process/persistence/JDBCPersistenceGeneratorTest.java
- kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/process/persistence/KafkaPersistenceGeneratorTest.java
- kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/process/persistence/MongoDBPersistenceGeneratorTest.java
- kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/process/persistence/PersistenceGeneratorTest.java
- kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegen.java
- kogito-codegen-modules/kogito-codegen-rules/src/test/java/org/kie/kogito/codegen/rules/BigRuleSetCodegenTest.java
- kogito-codegen-modules/kogito-codegen-rules/src/test/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegenTest.java
- kogito-codegen-modules/kogito-codegen-sample/kogito-codegen-sample-generator/src/main/java/org/kie/kogito/codegen/sample/generator/SampleCodegen.java
- kogito-codegen-modules/kogito-codegen-sample/kogito-codegen-sample-generator/src/test/java/org/kie/kogito/codegen/sample/generator/SampleCodegenTest.java
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/ProcessClassesMojo.java
https://issues.redhat.com/browse/KOGITO-5622
Kogito has a compile time execution (codegen) and a runtime execution (engine execution).
Kogito integration with Quarkus and Springboot is done differently:
- in Quarkus there are multiple extensions that implicitly brings in both the compile time (aka `deployment` using Quarkus naming) and the runtime for the selected engine (DMN, BPMN etc)
- in Springboot we have a single `kogito-maven-plugin` with all compile time code for all the possible engines even if the runtime part is not available
Quarkus behaviour is already correct while with SpringBoot there is a side effect: `kogito-maven-plugin` is performing some generation even for engines that are not available that can lead to compilation errors. This was not really possible until now but …
> [KOGITO-5622] Implement Generator.isEmpty() to skip generation when no resources are available

- grafana-api/src/main/java/org/kie/kogito/grafana/GrafanaConfigurationWriter.java
- grafana-api/src/test/java/org/kie/kogito/grafana/GrafanaConfigurationWriterTest.java
Fixes https://github.com/kiegroup/kogito-examples/issues/835
Jira: https://issues.redhat.com/browse/KOGITO-5660
Examples PR: https://github.com/kiegroup/kogito-examples/pull/837
<details>
<summary>
</summary>
* <b>Native …
> KOGITO-5660 - Fix illegal char in grafana dashboards for Windows OS

- jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/canonical/ActivityGenerationModelTest.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/RuleSetNodeVisitor.java
- kogito-codegen-modules/kogito-codegen-api/src/test/java/org/kie/kogito/codegen/api/utils/KogitoContextTestUtils.java
- kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegen.java
- kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/ProjectRuntimeGenerator.java
- kogito-codegen-modules/kogito-codegen-rules/src/test/java/org/kie/kogito/codegen/rules/BigRuleSetCodegenTest.java
- kogito-codegen-modules/kogito-codegen-rules/src/test/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegenTest.java
https://issues.redhat.com/browse/KOGITO-5674
At the moment, if users try to use a legacy use case (ruleflowgroup in a process or kieSession in DRL) must include kogito-legacy-api as dependency.
This is not enforced at the moment and the compilation might fail with a very cryptic message like compilation failure in one of the generated classes (i.e. [KOGITO-5643](https://issues.redhat.com/browse/KOGITO-5643)).
This PR introduces a similar check both for processes and rules
<details>
<summary>
</summary>
* <b>Run (or rerun) specific test(s)</b> …
> [KOGITO-5674] Improve error reporting related to kogito-legacy-api

- integration-tests/integration-tests-quarkus-gradle/pom.xml
- kogito-build/kogito-build-parent/pom.xml
it now supports both `quickly` and `skipITs` and of course its native `exec.skip`
https://issues.redhat.com/browse/KOGITO-5713
<details>
<summary>
</summary> …
> KOGITO-5713 Gradle integration test build should be skippable

- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/pom.xml
Signed-off-by: Alberto Morales Perez <almorale@redhat.com>
Backport for: https://github.com/kiegroup/kogito-runtimes/pull/1576
> [RHPAM-3890][1.11.x] Use BOM managed version for non-productized Quarkus test artifacts

- jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ProcessFactoryTest.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/ProcessSupplier.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/DummyKnowledgeRuntime.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/LightProcessRuntime.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/LightProcessRuntimeContext.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/WorkItemNodeInstance.java
- jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcess.java
- jbpm/jbpm-flow/src/test/java/org/jbpm/process/instance/LightProcessRuntimeTest.java
This JIRA can be split in two parts
- First one is a carry forward from v7 to support retries in ProcessWorkItemHandlerException, which just involve ```workItemNodeInstance```
- Second one is to change the engine to support createProcessInstance of subprocess for error handling in Kogito (by hacking  ```DummyKnowledgeImplementation```).  This second one is tricky. I just add a Map to be able to access process definition from process id (the InternalProcessRuntime  instance can only start same type of process than the catching one), but I feel we should refactor the engine core in next release. There are too many layers that might be simplified
> [KOGITO-5394] WorkItem retry implementation 

- quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-deployment/src/main/java/org/kie/kogito/quarkus/decisions/deployment/DecisionsAssetsProcessor.java
- quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions/pom.xml
- quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions-deployment/src/main/java/org/kie/kogito/quarkus/predictions/deployment/PredictionsAssetsProcessor.java
- quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions/pom.xml
- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/ProcessesAssetsProcessor.java
- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes/pom.xml
- quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules-deployment/src/main/java/org/kie/kogito/quarkus/rules/deployment/RulesAssetsProcessor.java
- quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules/pom.xml
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/deployment/ServerlessWorkflowAssetsProcessor.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/pom.xml
In Quarkus 2.x capabilities should be configured in the extension descriptors. While creating instances of `CapabilityBuildItem` still works, moving them to descriptors will make the dev tools aware of the provided capabilities and so they will be taken into account when checking compatibility of selected extensions for a Quarkus app.
> Configure Quarkus extension capabilities in extension descriptors

- api/kogito-api-incubation-application/pom.xml
- api/kogito-api-incubation-application/src/main/java/org/kie/kogito/incubation/application/AppRoot.java
- api/kogito-api-incubation-application/src/main/java/org/kie/kogito/incubation/application/ReflectiveAppRoot.java
- api/kogito-api-incubation-common/README.md
- api/kogito-api-incubation-common/pom.xml
- api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/Castable.java
- api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/ComponentRoot.java
- api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/DataContext.java
- api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/DefaultCastable.java
- api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/Id.java
- api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/InternalObjectMapper.java
- api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/LocalId.java
- api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/LocalUri.java
- api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/LocalUriId.java
- api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/MapDataContext.java
- api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/MapLikeDataContext.java
- api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/PathLocalId.java
- api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/RemoteId.java
- api/kogito-api-incubation-common/src/test/java/org/kie/kogito/incubation/common/DataContextTest.java
- api/kogito-api-incubation-common/src/test/java/org/kie/kogito/incubation/common/LocalUriTest.java
- api/kogito-api-incubation-common/src/test/java/org/kie/kogito/incubation/common/PathLocalIdTest.java
- api/pom.xml
- kogito-bom/pom.xml
- quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/pom.xml
- quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/src/main/java/org/kie/kogito/incubation/application/quarkus/QuarkusAppRoot.java
https://issues.redhat.com/browse/KOGITO-5747
Blocks:
- #1547 
- #1549 
- #1550 
- #1551 
These shared modules make available the `common` component and the `application` component. 
Every component should provide one or more service implementations. Each service takes an identifier (a Path from a root) and usually a `DataContext`. The generic form of interaction should follow the pattern:
```java
LocalId id = appRoot.get(MyComponent.class).get("componentName").subs().get("someSubComponent")
DataContext result = svc.evaluationMethod(id, dataContext);
```
for instance, evaluating a DMN may look like this:
```java
LocalDecisionId decisionId = appRoot.get(DecisionIds.class).get(namespaceString, nameString);
DataContext result = svc.evaluate(decisionId, dataContext);
```
When a component …
> KOGITO-5747 Public API: Shared Modules (Incubation)

- kogito-test-utils/src/main/java/org/kie/kogito/test/utils/SocketUtils.java
- kogito-test-utils/src/test/java/org/kie/kogito/test/utils/SocketUtilsTest.java
jira related: https://issues.redhat.com/browse/KOGITO-5553
As part of unification between jobs and data-index integration test we need a common place to avoid duplicate SocketUtils..  moving that to  kogito-test-utils.
<details>
<summary>
</summary>
* <b>Run (or rerun) …
> KOGITO-5553: Move SocketUtils to kogito-test-utils

- api/kogito-api/src/main/java/org/kie/kogito/rules/RuleUnitInstance.java
- drools/kogito-ruleunits/src/main/java/org/kie/kogito/rules/units/AbstractRuleUnitInstance.java
- kogito-codegen-modules/kogito-codegen-rules/src/main/resources/class-templates/rules/RestQueryJavaTemplate.java
- kogito-codegen-modules/kogito-codegen-rules/src/main/resources/class-templates/rules/RestQueryQuarkusTemplate.java
- kogito-codegen-modules/kogito-codegen-rules/src/main/resources/class-templates/rules/RestQuerySpringTemplate.java
Backport of https://github.com/kiegroup/kogito-runtimes/pull/1597
> [1.11.x][KOGITO-5832] dispose a rule unit instance in the generated rest endpoint after it has been used to serve a request

- integration-tests/integration-tests-quarkus-decisions/pom.xml
- integration-tests/integration-tests-quarkus-norest/pom.xml
- integration-tests/integration-tests-quarkus-predictions/pom.xml
- integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-infinispan/pom.xml
- integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-jdbc/pom.xml
- integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-kafka-persistence/pom.xml
- integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-mongodb/pom.xml
- integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-postgresql/pom.xml
- integration-tests/integration-tests-quarkus-processes/pom.xml
- integration-tests/integration-tests-quarkus-rules/pom.xml
- kogito-build/kogito-build-parent/pom.xml
- kogito-codegen-modules/kogito-codegen-integration-tests/pom.xml
- quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test-hot-reload/pom.xml
- quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test/pom.xml
- quarkus/extensions/kogito-quarkus-extension/kogito-quarkus-integration-test-maven-devmode/pom.xml
- quarkus/extensions/kogito-quarkus-extension/kogito-quarkus-integration-test/pom.xml
- quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions-integration-test/pom.xml
- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-integration-test-hot-reload/pom.xml
- quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules-integration-test-hot-reload/pom.xml
- quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules-integration-test-session/pom.xml
- quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules-integration-test/pom.xml
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/pom.xml
- quarkus/extensions/kogito-quarkus-test-list/pom.xml
- quarkus/extensions/pom.xml
https://issues.redhat.com/browse/KOGITO-5789
* Use newly added property in rpkgtests-maven-plugin to include just projects part of current reactor.
* configure kogito-quarkus-test-list as IT module (excluded by `-DexcludeITModules`).
<details>
<summary>
</summary>
* …
> KOGITO-5789 use activating property for kogito-quarkus-test-list

- api/kogito-api/src/main/java/org/kie/kogito/internal/process/runtime/KogitoProcessRuntime.java
- api/kogito-api/src/main/java/org/kie/kogito/process/ProcessInstance.java
- integration-tests/integration-tests-quarkus-processes/src/main/java/org/acme/CustomTaskWorkItemHandler.java
- integration-tests/integration-tests-quarkus-processes/src/main/java/org/acme/WIHRegister.java
- integration-tests/integration-tests-quarkus-processes/src/main/resources/error-handling.bpmn
- integration-tests/integration-tests-quarkus-processes/src/main/resources/exce-proc.bpmn
- integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/BasicRestIT.java
- jbpm/jbpm-bpmn2/pom.xml
- jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/handler/WorkItemHandlerExceptionHandlingTest.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/AbstractProcessRuntime.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/DummyKnowledgeRuntime.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/InternalProcessRuntime.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/KogitoProcessRuntimeImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/LightProcessRuntime.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/LightProcessRuntimeContext.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessRuntimeFactoryServiceImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessRuntimeImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/WorkItemNodeInstance.java
- jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java
- jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/ProcessServiceImpl.java
- jbpm/jbpm-flow/src/test/java/org/jbpm/process/instance/LightProcessRuntimeTest.java
Further changes needed for error handling strategy to work
- Change the approach to start subprocess, using Kogito API to do that
- If a workItem is not a UserTask, REST GET tasks API was failing (not all work items are user tasks and tasks api is intended to return just user tasks, so a new method was added to ProcessInstance interface, allowing filtering of work items) 
- Adding test to integration
> [KOGITO-5394] Workitem error Handling strategy

- jbpm/jbpm-bpmn2/src/test/resources/BPMN2-MultiInstanceLoopCharacteristicsProcessWithOutput.bpmn2
- jbpm/jbpm-bpmn2/src/test/resources/BPMN2-MultiInstanceLoopCharacteristicsProcessWithOutputCmpCond.bpmn2
- jbpm/jbpm-bpmn2/src/test/resources/subprocess/ErrorsBetweenProcess-Process.bpmn2
- jbpm/jbpm-flow-builder/pom.xml
- jbpm/jbpm-flow-builder/src/test/java/org/jbpm/compiler/canonical/ProcessToExecModelGeneratorTest.java
- jbpm/jbpm-flow-builder/src/test/java/org/jbpm/integrationtests/ProcessEventListenerTest.java
- jbpm/jbpm-flow-builder/src/test/java/org/jbpm/integrationtests/ProcessEventTest.java
- jbpm/jbpm-flow-builder/src/test/java/org/jbpm/integrationtests/ProcessExceptionHandlerTest.java
- jbpm/jbpm-flow-builder/src/test/java/org/jbpm/integrationtests/ProcessSplitTest.java
- jbpm/jbpm-flow-builder/src/test/java/org/jbpm/integrationtests/ProcessStartTest.java
- jbpm/jbpm-flow-builder/src/test/resources/org/jbpm/integrationtests/test_ProcessMultithreadEvent.rf
- jbpm/jbpm-flow/pom.xml
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/validation/RuleFlowProcessValidator.java
- kogito-build/kogito-dependencies-bom/pom.xml
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java
With this enhancement users you see a specific error message such as: 
`Node 'Dump order' [2] uses unknown variable(s) in the script: [orders]`
instead of getting a generic fail to validate process class without knowing the reason
> KOGITO-5514 - Validate variables use in script tasks

- api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/MapDataContext.java
- api/kogito-api-incubation-common/src/test/java/org/kie/kogito/incubation/common/DataContextTest.java
The method is present but erroneously stubbed (returned null: discovered this while working on examples)
It should pull the data from the map and then return a value of that type (performing a conversion -- not a cast -- if necessary)
e.g.:
```java
User u = new User();
u.firstName = "Paul";
u.lastName = "McCartney";
u.addr = new Address();
u.addr.street = "Abbey Rd.";
MapDataContext mdc = MapDataContext.of(Map.of("Paul", u));
User paul = (User) mdc.get("Paul"); // returns Object
User user = mdc.get("Paul", User.class); // returns User
```
<details>
<summary>
</summary> …
> KOGITO-5975  Public API: MapDataContext#get(String,Class<T>) returns null

- integration-tests/integration-tests-quarkus-decisions/pom.xml
- integration-tests/integration-tests-quarkus-norest/pom.xml
- integration-tests/integration-tests-quarkus-predictions/pom.xml
- integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-infinispan/pom.xml
- integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-jdbc/pom.xml
- integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-kafka-persistence/pom.xml
- integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-mongodb/pom.xml
- integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-postgresql/pom.xml
- integration-tests/integration-tests-quarkus-processes/pom.xml
- integration-tests/integration-tests-quarkus-rules/pom.xml
- kogito-build/kogito-build-parent/pom.xml
- kogito-codegen-modules/kogito-codegen-integration-tests/pom.xml
- quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test-hot-reload/pom.xml
- quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test/pom.xml
- quarkus/extensions/kogito-quarkus-extension/kogito-quarkus-integration-test-maven-devmode/pom.xml
- quarkus/extensions/kogito-quarkus-extension/kogito-quarkus-integration-test/pom.xml
- quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions-integration-test/pom.xml
- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-integration-test-hot-reload/pom.xml
- quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules-integration-test-hot-reload/pom.xml
- quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules-integration-test-session/pom.xml
- quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules-integration-test/pom.xml
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/pom.xml
- quarkus/extensions/kogito-quarkus-test-list/pom.xml
- quarkus/extensions/pom.xml
Cherry-pick of #1584 .
https://issues.redhat.com/browse/KOGITO-5789
<details>
<summary>
</summary>
* <b>Full Kogito testing</b> (with …
> [1.11.x][KOGITO-5789] use activating property for kogito-quarkus-test-list

- integration-tests/integration-tests-quarkus-gradle/src/main/resources/gradle.properties
this creates a chicken and egg problem when quarkus platform is unreleased, but the core is already available
the solution should be to use io:quarkus:quarkus-bom instead of  io:quarkus.**platform**:quarkus-bom instead of
> KOGITO-6031  Gradle integration test should not use quarkus platform BOM

- .github/pull_request_template.md
- .github/workflows/kogito-apps-pr.yml
- .github/workflows/kogito-examples-pr.yml
- .github/workflows/kogito-runtimes-pr.yml
- .github/workflows/optaplanner-pr.yml
See build-chain update details at https://github.com/kiegroup/github-action-build-chain/pull/190
related PRs:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1798
- https://github.com/kiegroup/kie-soup/pull/235
- https://github.com/kiegroup/droolsjbpm-knowledge/pull/576
- https://github.com/kiegroup/drools/pull/3959
- https://github.com/kiegroup/optaplanner/pull/1640
- https://github.com/kiegroup/lienzo-core/pull/156
- https://github.com/kiegroup/lienzo-tests/pull/130
- https://github.com/kiegroup/appformer/pull/1208
- https://github.com/kiegroup/kie-uberfire-extensions/pull/127
- https://github.com/kiegroup/jbpm/pull/2053
- https://github.com/kiegroup/kie-jpmml-integration/pull/69
- https://github.com/kiegroup/droolsjbpm-integration/pull/2638
- …
> [ISSUE 117] build-chain upgraded to v2.6.13

- addons/common/persistence/jdbc/src/main/java/org/kie/kogito/persistence/jdbc/GenericRepository.java
- addons/common/persistence/jdbc/src/main/resources/sql/create_tables_Oracle.sql
Fix for: https://issues.redhat.com/browse/KOGITO-6113
ORACLE JDBC index name too long
Many thanks for submitting your Pull Request :heart:!
> KOGITO-6113 shorten index name for oracle

- api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/EmptyDataContext.java
- api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/EmptyMetaDataContext.java
- api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/ExtendedDataContext.java
- api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/InternalObjectMapper.java
- api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/MapDataContext.java
- api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/MetaDataContext.java
- api/kogito-api-incubation-common/src/test/java/org/kie/kogito/incubation/common/DataContextTest.java
- api/kogito-api-incubation-common/src/test/java/org/kie/kogito/incubation/common/DataContexts.java
- api/kogito-api-incubation-common/src/test/java/org/kie/kogito/incubation/common/ExtendedDataContextTest.java
- api/kogito-api-incubation-decisions-services/src/main/java/org/kie/kogito/incubation/decisions/services/DecisionService.java
- api/kogito-api-incubation-decisions-services/src/test/java/org/kie/kogito/incubation/decisions/services/TestTypes.java
- api/kogito-api-incubation-predictions-services/src/main/java/org/kie/kogito/incubation/predictions/services/PredictionService.java
- api/kogito-api-incubation-predictions-services/src/test/java/org/kie/kogito/incubation/predictions/services/TestTypes.java
- quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test/src/test/java/org/kie/kogito/quarkus/dmn/CustomEndpointIT.java
- quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions/src/main/java/org/kie/kogito/core/decision/incubation/quarkus/support/QuarkusDecisionService.java
- quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions-integration-test/src/test/java/org/kie/kogito/quarkus/pmml/CustomEndpointIT.java
- quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions/src/main/java/org/kie/kogito/core/prediction/incubation/quarkus/support/QuarkusPredictionService.java
**This is intended also as a RFC**.
related: https://github.com/kiegroup/kogito-examples/pull/941
Introduce the `ExtendedDataContext` that services may opt-in to return. 
An `ExtendedDataContext` contains a `meta()` and a `data()` section. 
```java
public final class ExtendedDataContext implements DataContext {
public DataContext meta();
public DataContext data();
} 
```
`ExtendedDataContext.as(T)` is equivalent to `ExtendedDataContext.data().as(T)` unless `T=ExtendedDataContext`
Thus, to access MetaData users may write:
```
DataContext ctx = svc.evaluate(id, input);
ExtendedDataContext ectx = ctx.as(ExtendedDataContext.class);
DataContext meta = ectx.meta() 
```
`meta` and `data` are both `DataContexts` so they may be converted to another type as any other `DataContext`.
For instance, …
> KOGITO-5841  Public API: Allow extra-metadata in DataContext

- quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/InMemoryCompiler.java
- quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java
- quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoQuarkusResourceUtils.java
- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/ProcessesAssetsProcessor.java
<details>
<summary>
</summary> …
> Remove usage of deprecated curateOutcomeBuildItem.getEffectiveModel() method

- drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/AbstractDecisionModels.java
- kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionContainerGenerator.java
- quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test/src/main/resources/a.dmn
- quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test/src/test/java/org/kie/kogito/quarkus/dmn/CustomEndpointIT.java
- quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test/src/test/java/org/kie/kogito/quarkus/dmn/DMNIT.java
https://issues.redhat.com/browse/KOGITO-6145
<details>
<summary>
</summary> …
> KOGITO-6145 DMN codegen heuristic for DMN Editor encoding

- integration-tests/integration-tests-quarkus-processes/pom.xml
- quarkus/extensions/kogito-quarkus-extension/kogito-quarkus-integration-test-maven-devmode/src/test/resources/projects/classic-inst/src/main/resources/application.properties
- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/pom.xml
- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/KogitoBuildTimeConfig.java
- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/KogitoDevServicesBuildTimeConfig.java
- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/KogitoDevServicesProcessor.java
- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/ProcessesAssetsProcessor.java
- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/devservices/DataIndexInMemoryContainer.java
- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/resources/dev-templates/dataindex.html
- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/resources/dev-templates/embedded.html
- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-integration-test-hot-reload/src/test/resources/application.properties
- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes/pom.xml
- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes/src/main/java/org/kie/kogito/quarkus/processes/devservices/DataIndexEventPublisher.java
- quarkus/test/src/main/java/org/kie/kogito/testcontainers/quarkus/KafkaQuarkusTestResource.java
To test this, start a Kogito project that contains the `kogito-quarkus-processes` extension.
That should start Data Index in the background. To access the data index UI, jump to Quarkus Dev mode UI:
Clicking on Data Index GraphQL UI bring the UI allowing to query for process instances and tasks.
Start a new process instance and check if results show up in the UI once querying.
> KOGITO-5508 Data Index Dev Service

- api/kogito-api/src/main/java/org/kie/kogito/ProcessInput.java
- integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/ProcessIT.java
- integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/TaskIT.java
- integration-tests/integration-tests-quarkus-processes/src/test/resources/testJsonSchema/test_approvals.json
- integration-tests/integration-tests-quarkus-processes/src/test/resources/testJsonSchema/test_approvals_firstLineApproval.json
- integration-tests/integration-tests-quarkus-processes/src/test/resources/testJsonSchema/test_approvals_firstLineApproval_instance.json
- integration-tests/integration-tests-quarkus-processes/src/test/resources/testJsonSchema/test_cinema.json
- integration-tests/integration-tests-quarkus-processes/src/test/resources/testJsonSchema/test_greetings.json
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/main/java/org/acme/travels/Traveller.java
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/ProcessTest.java
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/TaskTest.java
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/resources/testJsonSchema/test_approvals.json
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/resources/testJsonSchema/test_approvals_firstLineApproval.json
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/resources/testJsonSchema/test_approvals_firstLineApproval_instance.json
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/resources/testJsonSchema/test_cinema.json
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/resources/testJsonSchema/test_greetings.json
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessToExecModelGenerator.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/util/JsonSchemaUtil.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/json/JsonSchemaGenerator.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/json/JsonUtils.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceQuarkusTemplate.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceSpringTemplate.java
- kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/json/JsonSchemaGeneratorTest.java
- kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/json/JsonUtilsTest.java
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/ProcessClassesMojo.java
- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/ProcessesAssetsProcessor.java
- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-integration-test-hot-reload/src/test/java/io/quarkus/it/kogito/jbpm/HotReloadIT.java
Adding JSON schema generation for ProcessModelnput, so we can use it in our quarkus runtime tools extension to start processes via form.
It also fixes a recursivity issue generating schemas when there are cross-dependencies between models in a variable, by using schema refs.
This is part of an ensemble, please merge with:
https://github.com/kiegroup/kogito-runtimes/pull/1697
https://github.com/kiegroup/kogito-apps/pull/1121
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class …
> KOGITO-5891: JSON Schema generation for ProcessModelInput

- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/GatewayFEELIT.java
https://issues.redhat.com/browse/KOGITO-6422
followup on https://github.com/kiegroup/kogito-runtimes/pull/1582
the order of the test executed on Jenkins for 1.15.x is not the same as: the order of test executed on Jenkins+main, or 1.15.x and the local machine.
This PR targets the 1.15.x branch which is currently exhibiting this failure per https://kie.zulipchat.com/#narrow/stream/236603-kogito-ci/topic/.5B1.2E15.2Ex.5D.20Kogito.20Runtimes/near/264852294
If passing, I will fwd-port to `main` just to be sure also there.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect …
> KOGITO-6422 GatewayFEELIT ConnectException: Connection refused

- .ci/jenkins/Jenkinsfile.deploy
- .ci/jenkins/Jenkinsfile.quarkus
- .ci/jenkins/Jenkinsfile.sonarcloud
<details>
<summary>
</summary> …
> [1.11.x] Corrected notifications

- .ci/jenkins/Jenkinsfile.deploy
- .ci/jenkins/Jenkinsfile.quarkus
- .ci/jenkins/Jenkinsfile.sonarcloud
<details>
<summary>
</summary> …
> Corrected notifications

- .ci/jenkins/Jenkinsfile.deploy
- .ci/jenkins/Jenkinsfile.quarkus
- .ci/jenkins/Jenkinsfile.sonarcloud
<details>
<summary>
</summary> …
> [1.15.x] Corrected notifications

- integration-tests/integration-tests-quarkus-processes/src/main/resources/application.properties
Adding the increase of quarkus.native.native-image-xmx to avoid OutOfMemoryError: GC overhead limit exceeded
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you …
> [1.11.x] Update native memory to avoid GC overhead

- api/kogito-services/src/main/java/org/kie/kogito/services/event/EventConsumerFactory.java
- api/kogito-services/src/main/java/org/kie/kogito/services/event/impl/AbstractMessageConsumer.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/AbstractNodeVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/BoundaryEventNodeVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/EventNodeVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/StartNodeVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/TriggerMetaData.java
- jbpm/jbpm-flow/src/main/java/org/kie/kogito/event/impl/CloudEventConsumer.java
- jbpm/jbpm-flow/src/main/java/org/kie/kogito/event/impl/DataEventConsumer.java
- jbpm/jbpm-flow/src/main/java/org/kie/kogito/event/impl/DefaultEventConsumerFactory.java
- jbpm/jbpm-flow/src/test/java/org/kie/kogito/event/impl/EventImplTest.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/MessageConsumerGenerator.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/MessageConsumerJavaTemplate.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/MessageConsumerQuarkusTemplate.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/MessageConsumerSpringTemplate.java
- kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqExpression.java
- kogito-serverless-workflow/kogito-jsonpath-expression/src/main/java/org/kie/kogito/expr/jsonpath/JsonPathExpression.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CallbackHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/EventHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/SwitchHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/ServerlessWorkflowParsingTest.java
- kogito-serverless-workflow/kogito-serverless-workflow-utils/src/main/java/org/kie/kogito/serverless/workflow/utils/ExpressionHandlerUtils.java
- kogito-workitems/kogito-jackson-utils/src/main/java/org/kie/kogito/jackson/utils/MergeUtils.java
- quarkus/addons/knative/eventing/deployment/src/test/java/org/kie/kogito/addons/quarkus/knative/eventing/deployment/KogitoProcessKnativeEventingProcessorTest.java
This add filter and merge support for SWF event states. 
In order to achieve that, code generator was slightly changed, so `eventToModel` method is only generated is the target node is a start one. This step is required to not force events to carry the whole model, as was kind of assumed before this change. 
The presence of that optional method has an additional benefit.  It allow us to identify at runtime if the target of the event is start node, so an attempt to start a process should be done or the targer is an intermediate event and a signal method should be called. This allow us to prevent what was happning with https://issues.redhat.com/browse/KOGITO-6356 
To round up this set of changes, name of classes generated for events in a subprocess are now guaranteed to be unique (which was …
> [KOGITO-6418] Event states filter and merging

- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/transformation/JsonResolver.java
- jbpm/jbpm-flow/src/test/java/org/jbpm/process/core/transformation/JsonResolverTest.java
cherry-pick:
- KOGITO-6319 LocalDates are supported in the ObjectMapper (processes) (#1762)
> KOGITO-6319 LocalDates are supported in the ObjectMapper (processes) 

- jbpm/jbpm-flow/src/main/java/org/kie/kogito/event/impl/CloudEventConsumer.java
- jbpm/jbpm-flow/src/test/java/org/kie/kogito/event/impl/EventImplTest.java
Async findById in ProcessInstances used by CloudEventConsumero avoid Thread Blocked Exception.
This issue was noticed using the latest PostgreSQL 14+ with the reactive client.
https://issues.redhat.com/browse/KOGITO-6448
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always …
> KOGITO-6448 async findById processInstance used by CloudEventConsumer

- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/EventFlowIT.java
JIRA: https://issues.redhat.com/browse/KOGITO-6489
Quarkus 2.6.x uses Kafka 3, which is incompatible with vertx-kafka-client:4.2.2.
That makes necessary stop using vertx-kafka-client classes directly and use MicroProfile Reactive Messaging if possible.
> KOGITO-6489 Removed from EventFlowIT the dependency on KafkaTestClient

- kogito-bom/pom.xml
- quarkus/addons/tracing-decision/deployment/pom.xml
- quarkus/addons/tracing-decision/deployment/src/main/java/org/kie/kogito/tracing/decision/quarkus/deployment/DevServicesConfig.java
- quarkus/addons/tracing-decision/deployment/src/main/java/org/kie/kogito/tracing/decision/quarkus/deployment/DevServicesConfigProcessor.java
- quarkus/addons/tracing-decision/deployment/src/main/java/org/kie/kogito/tracing/decision/quarkus/deployment/DevServicesSetupEnvironmentProcessor.java
- quarkus/addons/tracing-decision/deployment/src/main/java/org/kie/kogito/tracing/decision/quarkus/deployment/KogitoAddOnTracingDecisionProcessor.java
- quarkus/addons/tracing-decision/deployment/src/main/java/org/kie/kogito/tracing/decision/quarkus/deployment/KogitoBuildTimeConfig.java
- quarkus/addons/tracing-decision/deployment/src/main/java/org/kie/kogito/tracing/decision/quarkus/deployment/KogitoDevServicesBuildTimeConfig.java
- quarkus/addons/tracing-decision/deployment/src/main/java/org/kie/kogito/tracing/decision/quarkus/deployment/KogitoDevServicesProcessor.java
- quarkus/addons/tracing-decision/deployment/src/main/java/org/kie/kogito/tracing/decision/quarkus/devservices/TrustyServiceInMemoryContainer.java
- quarkus/addons/tracing-decision/deployment/src/main/resources/application.properties
- quarkus/addons/tracing-decision/integration-tests/pom.xml
- quarkus/addons/tracing-decision/integration-tests/src/test/java/org/kie/kogito/tracing/QuarkusTracingAddonDevServicesIT.java
- quarkus/addons/tracing-decision/integration-tests/src/test/resources/LoanEligibility.dmn
- quarkus/addons/tracing-decision/integration-tests/src/test/resources/application.properties
- quarkus/addons/tracing-decision/pom.xml
- quarkus/addons/tracing-decision/runtime/pom.xml
- quarkus/addons/tracing-decision/runtime/src/main/java/org/kie/kogito/tracing/decision/TrustyConstants.java
See https://issues.redhat.com/browse/FAI-681
Part of an ensemble:
- https://github.com/kiegroup/kogito-runtimes/pull/1759
- https://github.com/kiegroup/kogito-apps/pull/1157
- https://github.com/kiegroup/kogito-examples/pull/1032
These PRs contain the changes I've had to implement to have the following running:-
- A `kogito` application running on `localhost:8080`
- This `kogito` application starting a Docker container for a service it needs `TrustyService`.
- This `kogito` application connecting with and using Quarkus' DevServices Redpanda (Kafka) instance.
- `TrustyService` connecting with and using Quarkus' DevServices Redpanda (Kafka) instance.
- `TrustyService` connecting with and using Quarkus' DevServices PostgreSQL instance.
You can run …
> FAI-681: Integrate TrustyService with Quarkus DevServices services

- integration-tests/integration-tests-quarkus-decisions/src/test/java/org/kie/kogito/integrationtests/quarkus/OASIT.java
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/OASTest.java
- kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionRestResourceGenerator.java
1.16.x backport of https://github.com/kiegroup/kogito-runtimes/pull/1857
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories …
> [1.16.x] KOGITO-6531 Broken Swagger-UI Quarkus for DMN OpenAPI references

- jbpm/jbpm-flow-builder/src/test/java/org/jbpm/compiler/PackageBuilderTest.java
- jbpm/jbpm-flow-builder/src/test/java/org/jbpm/process/builder/JavaActionBuilderTest.java
- jbpm/jbpm-flow-builder/src/test/java/org/jbpm/process/builder/JavaReturnValueConstraintEvaluatorBuilderTest.java
- jbpm/jbpm-flow-builder/src/test/java/org/jbpm/process/builder/MVELActionBuilderTest.java
- jbpm/jbpm-flow-builder/src/test/java/org/jbpm/process/builder/MVELDecisionBuilderTest.java
- jbpm/jbpm-flow-builder/src/test/java/org/jbpm/process/builder/MVELReturnValueConstraintEvaluatorBuilderTest.java
**JIRA**: https://issues.redhat.com/browse/DROOLS-6646
Related PRs
https://github.com/kiegroup/drools/pull/4116
https://github.com/kiegroup/kogito-runtimes/pull/1862
> [DROOLS-6646] move ClassFieldAccessorStore out of drools-core

- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/AbstractNodeVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ActionNodeVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/EndNodeVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ExpressionSupplier.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ForEachNodeVisitor.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/actions/ProduceEventAction.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/ActionNodeFactory.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/EndNodeFactory.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/SupportsAction.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/MessageProducerJavaTemplate.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ServerlessWorkflowParser.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/SwitchHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/suppliers/CollectorActionSupplier.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/suppliers/CompensationActionSupplier.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/suppliers/ExpressionActionSupplier.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/suppliers/InjectActionSupplier.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/suppliers/MergeActionSupplier.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/suppliers/ProduceEventActionSupplier.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/suppliers/SysoutActionSupplier.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/ServerlessWorkflowUtils.java
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/SWFProduceEventAction.java
This PR add support for this part of the spec  https://github.com/serverlessworkflow/specification/blob/0.6.x/specification.md#eventref-definition. This will allow sending events from an action
Note that we are not implementing resultEventRef, fire&wait scenarios can be implemented using an action that publish an event inside a callback state. 
To implement this, ActionNodeVisitor has been heavily refactor, so we can reuse already generated code that publish events. 
New inteface ExpressionSupplier has been created inside flow-builder. This allow passing node information to SWF action supplier (which is needed to get the proper id for the event producer) 
See examples at https://github.com/kiegroup/kogito-examples/pull/1082
> [KOGITO-6331] Implementing eventRef for actions

- integration-tests/integration-tests-quarkus-decisions/src/test/java/org/kie/kogito/integrationtests/quarkus/OASIT.java
- integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/OASTest.java
- kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionRestResourceGenerator.java
https://issues.redhat.com/browse/KOGITO-6531
<details>
<summary>
</summary> …
> KOGITO-6531 Broken Swagger-UI Quarkus for DMN OpenAPI references

- jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ErrorEventTest.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/context/exception/ExceptionHandlerPolicy.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/context/exception/ExceptionHandlerPolicyFactory.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/context/exception/ExceptionScope.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/context/exception/RootCauseExceptionPolicy.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/context/exception/SubclassExceptionPolicy.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/context/exception/ExceptionScopeInstance.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/NodeInstanceImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/RuleSetNodeInstance.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateBasedNodeInstance.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/WorkItemNodeInstance.java
- kogito-codegen-modules/kogito-codegen-integration-tests/src/test/java/org/kie/kogito/codegen/data/HelloService.java
- kogito-codegen-modules/kogito-codegen-integration-tests/src/test/resources/error/BoundaryError.bpmn2
This will allow to use more generic exception in this example 
https://github.com/kiegroup/kogito-examples/blob/stable/serverless-workflow-error-quarkus/src/main/resources/error.sw.json#L43
After this change, it will also work with java.lang.RuntimeException
> [KOGITO-6456] Implementing recognition of children exceptions

- quarkus/addons/tracing-decision/deployment/src/main/java/org/kie/kogito/tracing/decision/quarkus/devservices/TrustyServiceInMemoryContainer.java
See https://issues.redhat.com/browse/KOGITO-6535
This change _minimises_ the potential for the addon using a stale version of Trusty Service whilst also removing the need to maintain a specific version number. It follows the change made by @cristianonicolai on for the Process extension [here](https://github.com/kiegroup/kogito-runtimes/pull/1856).
IMO, consistency within our own codebase is important.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect …
> KOGITO-6535: Kogito Dev Service not pulling latest version of TrustyServicePostgres image

- kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java
- kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionContainerGenerator.java
- kogito-codegen-modules/kogito-codegen-decisions/src/test/java/org/kie/kogito/codegen/decision/DecisionCodegenTest.java
- quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-deployment/src/main/java/org/kie/kogito/quarkus/decisions/deployment/DecisionsAssetsProcessor.java
1.16.x backport of https://github.com/kiegroup/kogito-runtimes/pull/1895
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories …
> [1.16.x] KOGITO-6574 DMN nativeimage NoSuchMethodException: <stronglytype>.init()

- quarkus/addons/tracing-decision/deployment/src/main/java/org/kie/kogito/tracing/decision/quarkus/deployment/KogitoDevServicesProcessor.java
- quarkus/addons/tracing-decision/integration-tests/src/test/resources/application.properties
See https://issues.redhat.com/browse/FAI-698
This allows use of a locally built `trusty-service-postgresql` to be used for the DevUI extension, if needed.
Part of an ensemble:
- https://github.com/kiegroup/kogito-runtimes/pull/1883
- https://github.com/kiegroup/kogito-apps/pull/1198
<details>
<summary>
</summary> …
> FAI-698: trusty-service-postgresql: Create docker images locally

- quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoInternalObjectMapperProvider.java
<details>
<summary>
</summary>
Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] tests</b>
Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] LTS</b> …
> KOGITO-6553 MissingInternalObjectMapper exception in Native Mode 

- quarkus/addons/common/deployment/src/main/java/org/kie/kogito/quarkus/addons/common/deployment/TrustyServiceAvailableBuildItem.java
- quarkus/addons/tracing-decision/deployment/src/main/java/org/kie/kogito/tracing/decision/quarkus/deployment/KogitoDevServicesProcessor.java
- quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoDataIndexServiceAvailableBuildItem.java
- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/KogitoDevServicesProcessor.java
See https://issues.redhat.com/browse/FAI-694
This PR adds two new `BuildItem`'s signalling when a back-end service is available.
They determine what UI components are visible in the DevUI console. 
This is part of an ensemble:
- https://github.com/kiegroup/kogito-runtimes/pull/1818
- https://github.com/kiegroup/kogito-apps/pull/1176
<details>
<summary>
</summary> …
> FAI-694: Quarkus: runtime-tools-quarkus-extension: Make UI features pluggable

- kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/OpenApiSpecDescriptor.java
- kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/di/ServicesConfigurationHandler.java
- kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/io/ClasspathResolver.java
<details>
<summary>
</summary> …
> KOGITO-6522: OpenAPI on Windows generates wrong path during executiontime

- kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/context/impl/AbstractKogitoBuildContext.java
- kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/utils/AppPaths.java
- kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/OpenApiClientCodegen.java
- kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/OpenApiClientException.java
- kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/OpenApiUtils.java
- kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/io/AbstractPathResolver.java
- kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/io/HTTPResolver.java
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/AbstractKieMojo.java
- quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java
- quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoQuarkusResourceUtils.java
We don't need the output Maven target dir to generate these files since it's an intermediary process handled by the inner openapi library.
cc @aloubyansky 
see: https://issues.redhat.com/browse/KOGITO-6581
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository …
> [KOGITO-6581] Use a temporary location to generate intermediate openapi files

- quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java
if @evacchi has a better idea for the Kogito "incubation" API feel free to apply!
This is my current best proposal, as the fix can be equivalently demonstrated by annotating:
```
RegisterForReflection(targets = {<all concrete classes used in JSON for Kogito "incubation" API here>})
```
on the "custom endpoint" showing Kogito-incubation-api-style REST.
Tested locally, this fixes with GraalVM:
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to …
> KOGITO-6656 Kogito "incubation" API DMN test failing in native mode

- README.md
- kogito-build/kogito-dependencies-bom/pom.xml
https://issues.redhat.com/browse/KOGITO-6682
Related PRs:
- https://github.com/kiegroup/drools/pull/4174
- https://github.com/kiegroup/kogito-runtimes/pull/1962
- https://github.com/kiegroup/optaplanner/pull/1820
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/647
- https://github.com/kiegroup/optaplanner-quickstarts/pull/277
- https://github.com/kiegroup/kogito-apps/pull/1227
- https://github.com/kiegroup/kogito-examples/pull/1109
> KOGITO-6682 Force maven version to 3.8.1+

- quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test/pom.xml
https://issues.redhat.com/browse/KOGITO-6170
follow-up of:
- https://github.com/kiegroup/kogito-runtimes/pull/1668#issuecomment-948478908
- https://github.com/quarkusio/quarkus/pull/20933
with
- https://github.com/kiegroup/kogito-runtimes/pull/1446
now available,
these versions can be removed; showing local test:
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the …
> KOGITO-6170 Remove forced maven dependencies for Codestart

- quarkus/extensions/kogito-quarkus-extension/kogito-quarkus-integration-test-maven-devmode/src/test/resources/projects/classic-inst/pom.xml
- quarkus/extensions/kogito-quarkus-extension/kogito-quarkus-integration-test-maven-devmode/src/test/resources/projects/simple-dmn/pom.xml
https://issues.redhat.com/browse/KOGITO-6718
<details>
<summary>
</summary> …
> KOGITO-6718 Avoid fixed maven-compiler-plugin version in it tests

- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/eventMultiple.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/expression.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/ExpressionRestIT.java
<details>
<summary>
</summary> …
> [KOGITO-6661] Implementing useData and useResult

- addons/common/rest-exception-handler/src/main/java/org/kie/kogito/resource/exceptions/BaseExceptionsHandler.java
- api/kogito-api/src/main/java/org/kie/kogito/internal/process/runtime/KogitoWorkflowProcessInstance.java
- api/kogito-api/src/main/java/org/kie/kogito/process/ProcessError.java
- api/kogito-api/src/main/java/org/kie/kogito/process/ProcessInstance.java
- api/kogito-api/src/main/java/org/kie/kogito/process/ProcessInstanceExecutionException.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
- jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/DataInputSchemaAction.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/ExpressionRestIT.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/pom.xml
Target of the changes performed with this PR was to obtain the output shown in the attaching image of a REST request to start a workflow with invalid parameters
In order to achieve that, basically following steps were done:
- Rest Exception handler addon was added to Serveless workflow dependencies
- Root cause of ProcessIntanceExecutionException is now properly set, which implies slightly modifying WorkFlowProcessInstanceImpl
- `BaseExceptionHandler`in the addon was modified to properly deal with ProcessInstanceExecutionException root cause.
> [KOGITO-6706] Polishing exception handling

- api/kogito-events-api/src/main/java/org/kie/kogito/event/KogitoEventStreams.java
- quarkus/addons/messaging/common/src/main/java/org/kie/kogito/addon/quarkus/messaging/common/QuarkusTopicDiscovery.java
- quarkus/addons/messaging/deployment/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/deployment/ChannelInfo.java
- quarkus/addons/messaging/deployment/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/deployment/ChannelMappingStrategy.java
- quarkus/addons/messaging/deployment/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/deployment/EventGenerator.java
- quarkus/addons/messaging/deployment/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/deployment/KogitoAddOnMessagingProcessor.java
The properties to rename channel are 
`kogito.addon.messaging.incoming.defaultName` and` kogito.addon.messaging.outgoing.defaultName`
See example at https://github.com/kiegroup/kogito-examples/pull/1126
> [KOGITO-6768] Be able to rename default channel

- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ServerlessWorkflowParser.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CallbackHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/TimeoutsConfigResolver.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/AbstractServerlessWorkflowParsingTest.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/CallbackStateServerlessWorkflowParsingTest.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/ServerlessWorkflowParsingTest.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/WorkflowTestUtils.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/utils/TimeoutsConfigResolverTest.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/resources/exec/callback-state-timeouts.sw.json
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/resources/exec/callback-state-timeouts.sw.yml
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/resources/exec/callback-state.sw.json
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/resources/exec/callback-state.sw.yml
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/pom.xml
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/specs/external-service.yaml
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/AbstractCallbackStateIT.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/CallbackStateIT.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/CallbackStateTimeoutsIT.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/ExternalServiceMock.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/WorkflowTestUtils.java
<details>
<summary>
</summary> …
> KOGITO-6744: [SW] Implement Callback state eventTimeout

- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/ForEachNodeFactory.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/ForEachStateHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/ServerlessWorkflowUtils.java
Declaring temporary variables as internal prevents them to be visible outside the process (they are not longer included in the model)
> [KOGITO-6763] User internal tag for temporary variables

- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/SwitchHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/ServerlessWorkflowParsingTest.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/resources/exec/switch-state-produce-events-default.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/greetUnknown.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/GreetRestIT.java
Default condition transitions should be handled as any other transition. 
The callback should add the default metadata base on the right input node. 
Added integration test with default condition not present in existing conditions based on previous existing one.
> [KOGITO-6853] Data conditions based switch state fails when the defaultCondition points to a state not present in the dataConditions

- api/kogito-events-api/src/main/java/org/kie/kogito/event/AbstractDataEvent.java
- quarkus/addons/messaging/common/src/main/java/org/kie/kogito/addon/quarkus/messaging/common/message/CloudEventHttpOutgoingDecorator.java
- quarkus/addons/messaging/common/src/test/java/org/kie/kogito/addon/quarkus/messaging/common/message/CloudEventHttpOutgoingDecoratorTest.java
- quarkus/addons/messaging/common/src/test/resources/application.properties
JIRA: https://issues.redhat.com/browse/KOGITO-6849
https://github.com/kiegroup/kogito-examples/pull/1165 depends on this PR.
* Fixes the lack of "Content-Type" header and "source" attribute.
* Improves the test for CloudEventHttpOutgoingDecorator.
-------
<details>
<summary>
</summary>
[build-chain …
> KOGITO-6849 Fixed CloudEvent lacking of "Content-Type" header

- .ci/jenkins/Jenkinsfile.quarkus
<details>
<summary>
</summary> …
> [1.13.x] Remove runtimes with persistence integration-tests

- kogito-build/kogito-build-no-bom-parent/pom.xml
- springboot/archetype/pom.xml
[KOGITO-6885](https://issues.redhat.com/browse/KOGITO-6885)
<details>
<summary>
</summary> …
> KOGITO-6885 - Upgrade maven-archetype-plugin to 3.2.1

- .ci/jenkins/Jenkinsfile.quarkus
- .github/quarkus-ecosystem-test
- Ecosystem CI script is updating the wrong BOM
- Ecosystem CI script is missing a version property
- Add version property to Jenkins CI too
> Ecosystem CI + Jenkins: maven plugin version should be updated

- quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test/src/test/filtered-resources/project.properties
- quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test/src/test/java/org/kie/kogito/quarkus/dmn/KogitoDMNCodeCodestartIT.java
use of old assertJ API. I think we are erroneously depending on the AssertJ version that is shipping with Quarkus somehow
```
2022-03-18T06:00:41.7516065Z [ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 29.376 s <<< FAILURE! - in org.kie.kogito.quarkus.dmn.KogitoDMNCodeCodestartIT
2022-03-18T06:00:41.7519047Z [ERROR] org.kie.kogito.quarkus.dmn.KogitoDMNCodeCodestartIT.testContent  Time elapsed: 0.104 s  <<< ERROR!
2022-03-18T06:00:41.7520044Z java.lang.NoSuchMethodError: 'org.assertj.core.api.AbstractAssert org.assertj.core.api.AbstractPathAssert.satisfies(java.util.function.Consumer[])'
2022-03-18T06:00:41.7521037Z 	at org.kie.kogito.quarkus.dmn.KogitoDMNCodeCodestartIT.testContent(KogitoDMNCodeCodestartIT.java:53)
Failing test is in …
```
> KOGITO-6890 Code Start test is picking up AssertJ version from the environment

- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/descriptors/SupplierUtils.java
- kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqExpression.java
- kogito-serverless-workflow/kogito-jq-expression/src/test/java/org/kie/kogito/expr/jq/JqExpressionHandlerTest.java
- kogito-serverless-workflow/kogito-jsonpath-expression/src/test/java/org/kie/kogito/expr/jsonpath/JsonPathExpressionHandlerTest.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/OpenAPIDescriptor.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/suppliers/CollectionParamsDecoratorSupplier.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/suppliers/ConfigWorkItemSupplier.java
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/test/java/org/kie/kogito/serverless/workflow/JsonNodeJqResolverTest.java
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/test/java/org/kie/kogito/serverless/workflow/JsonNodeJsonPathResolverTest.java
- kogito-workitems/kogito-jackson-utils/src/test/java/org/kie/kogito/jackson/utils/JsonNodeVisitorTest.java
- kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandler.java
- kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandlerUtils.java
- kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/decorators/AbstractParamsDecorator.java
- kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/decorators/CollectionParamsDecorator.java
- kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/decorators/ParamsDecorator.java
- kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/decorators/PrefixParamsDecorator.java
- kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/pathresolvers/DefaultPathParamResolver.java
- kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/pathresolvers/PathParamResolver.java
- kogito-workitems/kogito-rest-workitem/src/test/java/org/kogito/workitem/rest/RestWorkItemHandlerTest.java
- kogito-workitems/kogito-rest-workitem/src/test/java/org/kogito/workitem/rest/decorators/ParamsDecoratorTest.java
- kogito-workitems/kogito-rest-workitem/src/test/java/org/kogito/workitem/rest/pathresolvers/DefaultPathParamResolverTest.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/fahrenheit-to-celsius.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/specs/multiplication.yaml
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/OperationsMockService.java
This adds support for query and header parameter. 
And fixed an issue that ocurrs when the argument string contains a constant and JQ was considering it to be a valid expression (false positive). It turns out that we need to evaluate againts an empty context for the jq parser to realize the string literal is not a valid function.
> [KOGITO-6895] Add support for query and header params

- kogito-build/kogito-build-no-bom-parent/pom.xml
- kogito-build/kogito-dependencies-bom/pom.xml
- kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoKeycloakContainer.java
- springboot/bom/pom.xml
https://issues.redhat.com/browse/KOGITO-6929
<details>
<summary>
</summary> …
> KOGITO-6929 spring-boot to 2.6.6

- addons/common/process-svg/src/main/java/org/kie/kogito/svg/AbstractProcessSvgService.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java
Two problems fixed:
1) SVG being added even if resource is not a file (before it only worked if the bpmn resourece was a file) 
2) Windows classpath issue (not a good idea to use Path for accessing classpath resources, classpath resources are based on / for all OS, Paths are converted in windows to \)
And just take the opportunity to avoid an uneeded byte[]->string->byte[] conversion and reuse the byte[] as taken from the svg.
> [KOGITO-6931] Fixing svg resource loading and windows path

- jbpm/jbpm-bpmn2/pom.xml
- jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/objects/Person.java
- jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/structureref/StructureRefTest.java
- jbpm/jbpm-flow-builder/pom.xml
- kogito-build/kogito-dependencies-bom/pom.xml
Cherry-pick https://github.com/kiegroup/kogito-runtimes/pull/2126
Removing only the process use of Xstream and upgrading to latest available as drools-core make use of it.
> [1.13.x] KOGITO-6936 - Drop Xstream from process modules

- kogito-build/kogito-build-no-bom-parent/pom.xml
- kogito-build/kogito-dependencies-bom/pom.xml
- kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoKeycloakContainer.java
https://issues.redhat.com/browse/KOGITO-6929
Related PRs:
* https://github.com/kiegroup/kogito-runtimes/pull/2135
* https://github.com/kiegroup/kogito-examples/pull/1217
* https://github.com/kiegroup/kogito-runtimes/pull/2120
<details>
<summary>
</summary>
[build-chain …
> [1.13.x] KOGITO-6929 spring-boot to 2.6.6 (#2120)

- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/pom.xml
- the shared test SW must always be included
<details>
<summary>
</summary> …
> SW Integration tests quick fix

- grafana-api/README.md
- integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/TaskIT.java
- quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoQuarkusResourceUtils.java
Dumping kogito generated files to disk (target/classes) is not really required for quarkus image to work. 
So, in production enviroment dumping kogito generated files to disk has been disabled.
This way we achieve the goal of kogito not requiring (by itself) an underlying file system with write permission (implicitly it will still write through quarkus, but we are delegating that issue to Quarkus and removing from kogito)
We also allow reading a file from file system at build time and adding it to the runtime classpath without writing it back to the file system (the scenario that trigger the issue) 
Dumping can be enable by setting  property `kogito.quarkus.codegen.dumpFiles` to true. 
This should be done only in corner cases (like the grafana unit test in metrics example) where the files …
> [KOGITO-6989] Error dumping files to disk should not break build

- jbpm/jbpm-flow-builder/pom.xml
- kogito-build/kogito-kie-bom/pom.xml
**JIRA**: https://issues.redhat.com/browse/DROOLS-6914
Related PRs:
https://github.com/kiegroup/drools/pull/4329
https://github.com/kiegroup/kogito-runtimes/pull/2161
> [DROOLS-6914] remove possibility of using serialized packages as kie resources

- kogito-build/kogito-dependencies-bom/pom.xml
cherry-pick: https://github.com/kiegroup/kogito-runtimes/pull/2156
Related PRs:
- https://github.com/kiegroup/drools/pull/4342
- https://github.com/kiegroup/optaplanner/pull/1958
- https://github.com/kiegroup/optaplanner-quickstarts/pull/327
- https://github.com/kiegroup/kogito-runtimes/pull/2174
- https://github.com/kiegroup/kogito-apps/pull/1315
- https://github.com/kiegroup/kogito-examples/pull/1238
> [1.21.x] Bump Quarkus version to 2.8.2.Final (#2156)

- kogito-serverless-workflow/kogito-jsonpath-expression/src/test/java/org/kie/kogito/expr/jsonpath/JsonPathExpressionHandlerTest.java
Jira: [KOGITO-7087](https://issues.redhat.com/browse/KOGITO-7087)
Increasing test coverage for kogito-jsonpath-expression module.
Resulting coverage report (compiled locally):
<details>
<summary>
</summary> …
> KOGITO-7087 increase unit test coverage in kogito-jsonpath-expression

- kogito-codegen-modules/kogito-codegen-rules/src/test/resources/org/kie/kogito/codegen/rules/myunit/MyUnit.drl
**JIRA**: https://issues.redhat.com/browse/DROOLS-6937
Related PRs:
https://github.com/kiegroup/drools/pull/4353
https://github.com/kiegroup/kogito-runtimes/pull/2183
> [DROOLS-6937] remove naming convention to infer rule unit name from drl file

- .ci/jenkins/Jenkinsfile.quarkus
<details>
<summary>
</summary> …
> Correct Quarkus check for classloader issues in nightly

- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/.gitignore
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/pom.xml
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/META-INF/services/io.quarkus.test.common.QuarkusTestResourceLifecycleManager
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/resources/application.properties
For now all tests will run using PostgreSQL persistence, I created a follow up jira https://issues.redhat.com/browse/KOGITO-7128 where we can then have the same tests to be executed with and without persistence.
> KOGITO-6897 Enable IT tests to use postgresql persistence

- .ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-7177
This PR will add the nightly check against Quarkus LTS version
as well as the optional PR check which can be started with `jenkins run quarkus-lts`
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/434
- https://github.com/kiegroup/kogito-runtimes/pull/2210
> KOGITO-7177 Setup Quarkus LTS nightly/pr checks

- springboot/archetype/pom.xml
- springboot/archetype/src/main/resources/META-INF/archetype-post-generate.groovy
Creating a project without including a starter will generate the following error:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (default-cli) on project standalone-pom: Invalid Kogito starter, please use one of the following: rules, decisions, predictions -> [Help 1]`
> [1.13.x] KOGITO-7201 - Filter starters and addons based on profile

- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/context/variable/Variable.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/DataType.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/coverter/CloneHelper.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/coverter/TypeConverterRegistry.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/type/ObjectDataType.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/context/variable/VariableScopeInstance.java
- jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java
- jbpm/jbpm-flow/src/test/java/org/jbpm/process/core/datatype/impl/coverter/CloneHelperTest.java
- jbpm/jbpm-flow/src/test/java/org/kie/kogito/process/impl/AbstractProcessInstanceTest.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/helloworld.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/HelloWorldIT.java
When the default value of a process variable is not constant, it should be cloned per process instance, or different process instances will see changes performed by other process instances. 
This adds an specific cloner for JsonNode and a default generic one for POJOS implementing cloneable or providing a copy constructor
> [KOGITO-7174] Default values should be cloned per process instance

- integration-tests/integration-tests-quarkus-gradle/integration-tests-quarkus-gradle-project/gradle/wrapper/gradle-wrapper.properties
- kogito-build/kogito-build-no-bom-parent/pom.xml
Fix for issues with CI running with Quarkus main
<details>
<summary>
</summary> …
> Fix for issues with CI running with Quarkus main

- jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/expr/ExpressionHandler.java
- jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/expr/ExpressionHandlerFactory.java
- kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqExpressionHandler.java
- kogito-serverless-workflow/kogito-jsonpath-expression/src/main/java/org/kie/kogito/expr/jsonpath/JsonPathExpression.java
- kogito-serverless-workflow/kogito-jsonpath-expression/src/main/java/org/kie/kogito/expr/jsonpath/JsonPathExpressionHandler.java
- kogito-serverless-workflow/kogito-jsonpath-expression/src/main/java/org/kie/kogito/expr/jsonpath/WorkflowJacksonJsonNodeJsonProvider.java
- kogito-serverless-workflow/kogito-jsonpath-expression/src/test/java/org/kie/kogito/expr/jsonpath/JsonPathExpressionHandlerTest.java
It turns out we can keep the $ if prefixing by @
> [KOGITO-7318] Improving jsonpath handling of secret, workflow, constant

- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/pom.xml
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/java/org/kie/kogito/workflows/services/GreeterService.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/greeting.proto
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/rpcgreet.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/RPCGreetIT.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/src/main/resources/application.properties
Adding integrationt test for kogito-runtimes based on existing kogito-examples
> [KOGITO-7218] Adding integration test for gRPC

- .ci/jenkins/Jenkinsfile.deploy
- .ci/jenkins/Jenkinsfile.drools
- .ci/jenkins/Jenkinsfile.native
- .ci/jenkins/Jenkinsfile.promote
- .ci/jenkins/Jenkinsfile.quarkus
- .ci/jenkins/Jenkinsfile.sonarcloud
- .ci/jenkins/dsl/Jenkinsfile.seed
https://issues.redhat.com/browse/KOGITO-7356
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/484
- https://github.com/kiegroup/drools/pull/4446
- https://github.com/kiegroup/kogito-runtimes/pull/2252
- https://github.com/kiegroup/kogito-apps/pull/1375
- https://github.com/kiegroup/kogito-examples/pull/1285
- https://github.com/kiegroup/kogito-images/pull/1275
- https://github.com/kiegroup/kogito-operator/pull/1204
- https://github.com/kiegroup/optaplanner/pull/2023
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/708
- https://github.com/kiegroup/optaweb-employee-rostering/pull/826
- https://github.com/kiegroup/optaplanner-quickstarts/pull/352
> [1.13.x] KOGITO-7356 Do not use master node in pipelines

- addons/common/source-files/pom.xml
- addons/common/source-files/src/main/java/org/kie/kogito/addon/source/files/SourceFilesException.java
- addons/common/source-files/src/main/java/org/kie/kogito/addon/source/files/SourceFilesProvider.java
- addons/common/source-files/src/main/java/org/kie/kogito/addon/source/files/SourceFilesProviderImpl.java
- addons/common/source-files/src/test/java/org/kie/kogito/addon/source/files/SourceFilesProviderImplTest.java
- addons/common/source-files/src/test/resources/META-INF/resources/sources/hiring.bpmn
- addons/common/source-files/src/test/resources/META-INF/resources/sources/petstore.json
- addons/common/source-files/src/test/resources/META-INF/resources/sources/petstore.sw.json
- addons/common/source-files/src/test/resources/META-INF/resources/sources/ymlgreet.sw.yml
- integration-tests/integration-tests-quarkus-source-files/pom.xml
- integration-tests/integration-tests-quarkus-source-files/src/main/resources/application.properties
- integration-tests/integration-tests-quarkus-source-files/src/test/java/org/kie/kogito/integrationtests/quarkus/source/files/SourceFilesAddOnIT.java
- integration-tests/integration-tests-quarkus-source-files/src/test/resources/ymlgreet-expected.sw.yml
- quarkus/addons/source-files/runtime/pom.xml
- quarkus/addons/source-files/runtime/src/main/java/org/kie/kogito/addon/source/files/SourceFilesResource.java
- quarkus/addons/source-files/runtime/src/test/java/org/kie/kogito/addon/source/files/SourceFilesResourceTest.java
- quarkus/addons/source-files/runtime/src/test/resources/application.properties
Jira: https://issues.redhat.com/browse/KOGITO-7235
Renamed getSourcesFiles endpoint path to "/sources/processes/{processId}"
Removed hard-coded @rolesAllowed, leaving the control to quarkus security framework on /sources/ path like it was done before:
quarkus.http.auth.policy.source-files-addon-policy.roles-allowed=source-files-client
quarkus.http.auth.permission.source-files-addon.paths=/sources/*
quarkus.http.auth.permission.source-files-addon.policy=source-files-addon-policy
Added new endpoint with path "/sources/processes/{processId}/definition" to get the process definition file content.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and …
> KOGITO-7235: Add endpoint to get source definition file content

- kogito-build/kogito-dependencies-bom/pom.xml
JIRA: https://issues.redhat.com/browse/DROOLS-7016
> [DROOLS-7016] align JavaParser version with the one used in Quarkus

- api/kogito-api/src/main/java/org/kie/kogito/internal/utils/ConversionUtils.java
Once the null pointer exception is prevented, the proper error message is displayed
> [KOGITO-7414] Avoid null pointer exception if operationid is null

- kogito-build/kogito-dependencies-bom/pom.xml
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/operationid/WorkflowOperationIdFactoryProvider.java
Also removing quarkus prefix from property, which was uneeded, so final property name will be 
`kogito.sw.operationIdStrategy`
See examples at https://github.com/kiegroup/kogito-examples/pull/1314
> [KOGITO-6687] Update openapi extension version

- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/LightWorkItemManager.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/humantask/HumanTaskWorkItemHandler.java
See [Zulip](https://kie.zulipchat.com/#narrow/stream/232676-kogito/topic/LifeCycle.20in.20custom.20KogitoWorkItemHandler/near/288549942) link for an explanation of the issue 
After this change, users will be able to override transitionToPhase to customize the handler
> [KOGITO-7506] Fixing transitionToPhase inheritance

- jbpm/jbpm-bpmn2/pom.xml
- jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ProcessFactoryTest.java
- jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/objects/ExceptionOnPurposeHandler.java
- jbpm/jbpm-flow/pom.xml
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/context/exception/AbstractHierarchyExceptionPolicy.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/context/exception/ExceptionHandlerPolicyFactory.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/context/exception/MessageContentExceptionPolicy.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/context/exception/RootCauseExceptionPolicy.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/context/exception/WebApplicationExceptionPolicy.java
- jbpm/jbpm-flow/src/test/java/org/jbpm/process/core/context/exception/ExceptionHandlerPolicyTest.java
JIRA: https://issues.redhat.com/browse/KOGITO-7453
This PR extends the current logic to map error codes in a workflow definition to exceptions handled by the engine at runtime. In addition to use the FQCN of an exception in the error code, it allows to map errors using a (partial) match of the error message, or in case of a WebApplicationException, using the http status code.
The PR adds two new ExceptionHandlerPolicy implementation classes:
- `MessageContentExceptionPolicy`: Compares the defined error code against the error message caught by the engine. Uses lowercase/partial comparison and supports usage of regex
- `WebApplicationExceptionPolicy`: For exceptions of type `javax.ws.rs.WebApplicationException`, this policy evaluates the defined error code against the HTTP code from the …
> KOGITO-7453: Add ExceptionHandlerPolicy implementation classes to extend error code evaluation

- .github/workflows/kogito-apps-pr.yml
- .github/workflows/kogito-examples-pr.yml
- .github/workflows/kogito-runtimes-pr.yml
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/543
- https://github.com/kiegroup/kogito-runtimes/pull/2317
- https://github.com/kiegroup/kogito-apps/pull/1407
- https://github.com/kiegroup/kogito-examples/pull/1324
- https://github.com/kiegroup/drools/pull/4525
- https://github.com/kiegroup/optaplanner/pull/2063
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/728
- https://github.com/kiegroup/optaweb-employee-rostering/pull/841
> [KOGITO-7504] Update Maven to 3.8.6

- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/DataInputSchemaAction.java
This will include the list of exceptions, if more than one, in the exception being thrown when validation is active. 
This message will be later used to build the error object returned by the rest call. 
This also align the message being logged with the exception being launched, which in some cases were not the same
> [KOGITO-7617] Changing error handling to print list of exceptions

- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/rpc/ProtobufUtilRPCConverter.java
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/rpc/RPCConverter.java
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/rpc/RPCWorkItemHandler.java
JIRA: [KOGITO-7612](https://issues.redhat.com/browse/KOGITO-7612)
PR set:
* https://github.com/kiegroup/kogito-runtimes/pull/2342
* https://github.com/kiegroup/kogito-examples/pull/1332
Info:
1. Method type is now properly set (Unary, Client/Server streaming, Bidirectional).
1. Unary scenario remains unchanged.
1. Server streaming (one message sent, multiple messages received from the server) is similar to the unary scenario, just more messages are received. They are merged as an array to the workflow data under the `response` tag by default. This behaviour was in place from the beginning unless a specific `actionDataFilter` is used.
1. In fact, when I looked at the implementation of unary and server streaming calls, they are async internally but they wait until the response comes from …
> KOGITO-7612 - Implement gRPC streaming scenarios

- kogito-build/kogito-dependencies-bom/pom.xml
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/pom.xml
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/AbstractCallbackStateIT.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/CallbackStateIT.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/CallbackStateTimeoutsIT.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/CorrelationIT.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/GrpcServerPortResource.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/RPCGreetIT.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/SwitchStateEventConditionBasedIT.java
Fixes failing tests on main.
@fjtirado Moved the newly added gPRC test to use `QuarkusTest` temporarily as it seems to be an issue with DevServices to restart the app when using a TestProfile. More details https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/DevServices.20properties.20on.20profile.20restart
> KOGITO-7716 - Remove quarkus-test-kafka-companion dependency

- .ci/jenkins/Jenkinsfile.quarkus
- .ci/jenkins/dsl/jobs.groovy
- kogito-build/kogito-dependencies-bom/pom.xml
- quarkus/bom/pom.xml
- quarkus/extensions/kogito-quarkus-extension/kogito-quarkus-integration-test-maven-devmode/pom.xml
The kogito-runtimes prod nightly build is failing due to `io.quarkus:quarkus-devtools-testing` is not productized by throwing
```
[ERROR] Failed to execute goal on project kogito-quarkus-serverless-workflow-integration-test: Could not resolve dependencies for project org.kie.kogito:kogito-quarkus-serverless-workflow-integration-test:jar:2.0.0.redhat-2022080923: Failure to find io.quarkus:quarkus-devtools-testing:jar:2.7.5.Final-redhat-00011 in REPO_URL was cached in the local repository, resolution will not be reattempted until the update interval of qe-repository has elapsed or updates are forced -> [Help 1]
```
I suggest to use `version.io.quarkus.quarkus-test-maven` property for `io.quarkus:quarkus-devtools-testing` dependency, this way community libraries for this particular …
> quarkus-devtools-testing to version.io.quarkus.quarkus-test-maven

- kogito-workitems/kogito-jackson-utils/src/main/java/org/kie/kogito/jackson/utils/MergeUtils.java
- kogito-workitems/kogito-jackson-utils/src/test/java/org/kie/kogito/jackson/utils/MergeUtilsTest.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/rpcgreet.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/EmitEnumRPCGreetIT.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/RPCGreetIT.java
Before this JIRA, the code always try to merge the two arrays (an union), and the boolean just indicates if duplicates should be skipped. Now the boolean indicates whether the array should be merged (true) or replaced (false). Therefore true is equivalent to previous behaviour when skipDuplicate was true (this is the expected behaviour for JsonSchema generation), And by default (false), the array will be replaced, which is the desired behaviour for Serverless Workflow action
Why should be the default for Serveless Workflow?
Considers this case, where we have an array called minority in our workflow model with following content
```
[ {
"message" : "Marc",
"innerMessage" : {
"number" : 23,
"state" : "UNKNOWN"
},
"state" : "UNKNOWN"
}, {
"message" : "Boungiorno Marco",
"innerMessage" : { …
```
> [KOGITO-7752] Merge arrays should replace by default

- jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessConfig.java
- jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/MultiWorkItemHandlerConfig.java
- jbpm/jbpm-flow/src/test/java/org/kie/kogito/process/impl/AbstractProcessConfigTest.java
There were two options to support this, either change the interface from single instance to iterable or consolidate the iterable information into one instance. The second is less intrusive, in my opinion, because existing code is already using forName directly over the object returned by ProcessConfig in a couple of places and we will need an utility method that does that in order to avoid duplication. 
This second approach can be implemented using two different approaches,either the consolidated instance is just a wrapper (new class)  that invoke the different underlying implementation (similar that the utility method that would have been added if we took he discarded approach) or we can use existing CachedWorkItemHandler class and register all instance into it. I chose the second one …
> [KOGITO-7557]  Supporting multiple workitemhandlers

- jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ErrorEventTest.java
- jbpm/jbpm-bpmn2/src/test/resources/error/ErrorVariable.bpmn2
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/actions/SignalProcessInstanceAction.java
If inputName variable is null, rather than taking variable name, take variable value.
This partially fixes issue reported in the JIRA https://github.com/comlinegmbh/kogito-error-boundary-poc
Partially because there is still two variable change event rather than one, but at least the "theException" has the expected value. 
@elguardian Maybe there is a better solution, please take a look.
> [KOGITO-7777] Signal action takes variableName if inputName is null

- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/functions/WorkItemFunctionNamespace.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/types/ServiceTypeHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/WorkItemBuilder.java
This class is useful for generating custom work item handlers for function namespaces and will be used in examples.
In the previous PR I added only the one that is helpful for generating custom actions for namespaces and miss that one
> [KOGITO-7845] Adding FunctionNamespace work item abstract class

- quarkus/addons/common/deployment/src/main/java/org/kie/kogito/quarkus/addons/common/deployment/AnyEngineKogitoAddOnProcessor.java
- quarkus/addons/common/deployment/src/main/java/org/kie/kogito/quarkus/addons/common/deployment/RequireCapabilityKogitoAddOnProcessor.java
- quarkus/addons/messaging/deployment/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/deployment/KogitoProcessMessagingProcessor.java
- quarkus/addons/process-svg/deployment/src/main/java/org/kie/kogito/svg/deployment/KogitoAddOnProcessSVGProcessor.java
In next versions of Quarkus, it won't allow using `@Produce(EmptyBuildItem.class)` (an exception will be thrown). 
More information about this change can be found here: https://github.com/quarkusio/quarkus/pull/27427
Moreover, for the use case you were using `@Produce(EmptyBuildItem.class)`, validations, we should use `ValidationErrorBuildItem`. I didn't do it because it would require adding the dependency `quarkus-arc-deployment`, so I replaced it with `@Produce(ArtifactResultBuildItem.class)` which is guaranteed that the build step will be executed.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), …
> Replace EmptyBuildItem with ArtifactResultBuildItem

- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/pom.xml
- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/KogitoDevServicesProcessor.java
Unless `placeholder` string is used, DevServices will now use the full string that is defined in the pom.xml, including the version part of it.
> KOGITO-7911 - Allow to override Data Index image version

- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java
Rather than throwing NPE when user has provided an error reference but there is not any error definition is present, a clear message stating that should be printed
The building will continue failing, as expected
<details>
<summary>
</summary> …
> [KOGITO-7933] Avoiding NPE for error definition

- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/Metadata.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/node/ForEachNode.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/ForEachNodeInstance.java
- kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqExpression.java
- kogito-serverless-workflow/kogito-jsonpath-expression/src/main/java/org/kie/kogito/expr/jsonpath/JsonPathExpression.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/VariableInfo.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/ForEachStateHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/types/ExpressionTypeHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/types/SysOutTypeHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/suppliers/ExpressionActionSupplier.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/suppliers/SysoutActionSupplier.java
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/BaseExpressionAction.java
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/ExpressionAction.java
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/SysoutAction.java
- kogito-serverless-workflow/kogito-serverless-workflow-utils/src/main/java/org/kie/kogito/serverless/workflow/utils/ExpressionHandlerUtils.java
- kogito-serverless-workflow/kogito-serverless-workflow-utils/src/main/java/org/kie/kogito/serverless/workflow/utils/JsonNodeContext.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/java/org/kie/kogito/workflows/services/DummyRPCCustomType.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/java/org/kie/kogito/workflows/services/RPCCustomWorkItemHandler.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/java/org/kie/kogito/workflows/services/RPCCustomWorkItemHandlerConfig.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/META-INF/services/org.kie.kogito.serverless.workflow.parser.FunctionTypeHandler
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/forEachCustomType.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/ForEachRestIT.java
ForEach was only working with ActionNodes. This change will allow it to work with any NodeInstance (in theory), In practise, we have either WorkItemNode or ActionNode and this is the scenario a test was added for.
> [KOGITO-7924] ForEach working with WorkItemHandler

- quarkus/addons/knative/eventing/deployment/src/main/java/org/kie/kogito/addons/quarkus/knative/eventing/deployment/KogitoProcessKnativeEventingProcessor.java
Jira- https://issues.redhat.com/browse/KOGITO-7792
When there is no SW file in the resources folder KogitoProcessContainerGeneratorBuildItem shouldn't be called.  Added a guard check to return if processContainerBuildItem is null , in order to avoid  KogitoProcessContainerGeneratorBuildItem getting executed.
> [KOGITO-7792]-Project fails to build if no SW file is defined and Knative Eventing and Kubernetes add-on is presented in classpath

- api/kogito-api/src/main/java/org/kie/kogito/Models.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/LambdaSubProcessNodeVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessMetaData.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessToExecModelGenerator.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/MessageConsumerGenerator.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ModelClassGenerator.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessInstanceGenerator.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessResourceGenerator.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/ServerlessWorkflowUtils.java
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/models/JsonNodeModel.java
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/models/JsonNodeModelInput.java
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/models/JsonNodeModelOutput.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/RPCGreetIT.java
The purpose of this JIRA is to be able to start a process using REST  by passing as body 
`{"input":[2,4,6,8,10], "divisor": 2}`
rather than 
`{"workflowdata":{"input":[2,4,6,8,10], "divisor": 2}}`
Backward compatibility is maintained, process can still be started passing workflowdata
In order to do that the overall idea is to skip model generation for serverless workflow and use hardcoded models that follow the same structure than the generated ones. 
I made some improvements (from my point of view) to model class reflection handling 
@hbelmiro  is going to work on  https://issues.redhat.com/browse/KOGITO-7956 to update swagger doscs
> [KOGITO-7852] Remove workflowdata from POST start request

- kogito-build/kogito-dependencies-bom/pom.xml
Cherry pick for https://github.com/kiegroup/kogito-runtimes/pull/2484
> [1.28.x][KOGITO-7971] Align smallrye openapi components to Quarkus 2.7 LTS

- kogito-codegen-modules/kogito-codegen-predictions/src/main/java/org/kie/kogito/codegen/prediction/PredictionCodegen.java
- kogito-codegen-modules/kogito-codegen-predictions/src/main/java/org/kie/kogito/codegen/prediction/PredictionCodegenUtils.java
- kogito-codegen-modules/kogito-codegen-predictions/src/test/java/org/kie/kogito/codegen/prediction/PredictionCodegenGenerateTest.java
- kogito-codegen-modules/kogito-codegen-predictions/src/test/java/org/kie/kogito/codegen/prediction/PredictionCodegenInternalGenerateTest.java
- quarkus/addons/tracing-decision/deployment/src/main/java/org/kie/kogito/tracing/decision/quarkus/deployment/KogitoDevServicesBuildTimeConfig.java
- quarkus/addons/tracing-decision/deployment/src/main/java/org/kie/kogito/tracing/decision/quarkus/deployment/KogitoDevServicesProcessor.java
- quarkus/addons/tracing-decision/deployment/src/main/java/org/kie/kogito/tracing/decision/quarkus/devservices/TrustyServiceInMemoryContainer.java
- quarkus/addons/tracing-decision/integration-tests/pom.xml
- quarkus/addons/tracing-decision/integration-tests/src/test/java/org/kie/kogito/tracing/QuarkusTracingAddonDevServicesIT.java
- quarkus/addons/tracing-decision/integration-tests/src/test/resources/application.properties
@ricardozanini @evacchi @danielezonca 
See https://issues.redhat.com/browse/KOGITO-8083
Requirements/issues for this PR:
1) I want to reduce the impact as much as possible
2) I want to reuse `SocketUtils.findAvailablePort()` (from `kogito-test-utils`)
3)  `TrustyServiceInMemoryContainer` and `KogitoDevServicesProcessor` are defined in the `deployment` module, that does not depends (of course) on `integration-tests`)
4) I tried to define an optional "BuildItem", add it to `KogitoDevServicesProcessor.startTrustyServiceDevService(...)` and create the "builder" in the `integration-tests` moduile, but that builder is not invoked
5) following the above, I couldnot find a way to "programmatically" add a configuration (the randomly chosen port) to one of the parameters of the above method
6) the …
> [KOGITO-8083] Set random port for tracing tests - Additional fix on Prediction Codegen

- jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/AbstractNodeHandler.java
- jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/EndEventHandler.java
- jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/EndNodeHandler.java
- jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/ProcessHandler.java
- jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/SubProcessHandler.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/xml/XmlWorkflowProcessDumper.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/xml/processes/ConnectionHandler.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/xml/processes/ConstraintHandler.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/xml/processes/ExceptionHandlerHandler.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/ProcessInstanceImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/validation/RuleFlowProcessValidator.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/node/AsyncEventNodeInstance.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/NodeInstanceImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/DynamicUtils.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/EventNodeInstance.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/EventSubProcessNodeInstance.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/FaultNodeInstance.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/LambdaSubProcessNodeInstance.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/SplitInstance.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateNodeInstance.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/SubProcessNodeInstance.java
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/AbstractKieMojo.java
- quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java
- quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoQuarkusResourceUtils.java
- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes/src/main/java/org/kie/kogito/core/process/incubation/quarkus/support/HumanTaskServiceImpl.java
https://issues.redhat.com/browse/KOGITO-7952
Goal here is to reduce the number of code smells in Kogito-runtimes.
Addressed in this PR is the code smell, (Java) "Static" base class members should not be accessed via derived types (78)
https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS3252&id=org.kie.kogito%3Akogito-runtimes
I have remedied this by always addressing the static member directly, rather than a derived type's name.
<details>
<summary>
</summary> …
> Kogito-7952 Sonarcloud - (Java) "Static" base class members should not be accessed via derived types (78)

- jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/EndEventTest.java
- jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
- jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/StandaloneBPMNProcessTest.java
- kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/process/persistence/marshaller/AbstractMarshallerGeneratorTest.java
- kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/process/persistence/proto/AbstractProtoGeneratorTest.java
- quarkus/integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/ManagementAddOnIT.java
- quarkus/integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/MonitoringIT.java
https://issues.redhat.com/browse/KOGITO-8085
Goal here is to reduce the number of code smells in Kogito-runtimes.
Addressed in this PR are the following code smells:
1) (Java) Consecutive AssertJ "assertThat" statements should be chained (11): https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS5853&id=org.kie.kogito%3Akogito-runtimes
I have addressed this by chaining AssertJ statements that are targeting the same object.
2) (Java) AssertJ methods setting the assertion context should come before an assertion (6):  https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS5833&id=org.kie.kogito%3Akogito-runtimes 
I have addressed this by modifying AssertJ statements that called .withFailMessage after the assertion instead of before.
3) (Java) Assertions comparing …
> Kogito-8085 Sonarcloud - Addressing code smells related to unchained, incorrectly structured, and incompatible type assertThat statements 

- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ServerlessWorkflowParser.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/schema/OpenApiModelSchemaGenerator.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/schema/OpenApiModelSchemaUtil.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/ServerlessWorkflowParsingTest.java
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/SWFConstants.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/deployment/ServerlessWorkflowAssetsProcessor.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/src/main/java/org/kie/kogito/serverless/workflow/openapi/ServerlessWorkflowOASFilter.java
JIRA: https://issues.redhat.com/browse/KOGITO-7647
Example of OpenAPI document for a project that has three workflows:
| Workflow ID | Input Schema |
|--------|---------|
| expression | expression.json |
| expression_alt | expression_alt.json |
| jsongreet | - |
Open API document:
```yaml
...
paths:
/expression:
...
post:
tags:
- expression
summary: expression
description: ""
operationId: createResource_expression
parameters:
- name: businessKey
in: query
schema:
default: ""
type: string
requestBody:
content:
application/json:
schema:
$ref: '#/components/schemas/expression_workflowdata'
responses:
"200":
description: OK
...
/expression_alt:
...
post:
tags:
- expression_alt
summary: expression_alt
description: ""
operationId: createResource_expression_alt
parameters:
- name: businessKey …
```
> [KOGITO-7647] Added workflow ID as a prefix for OpenAPI input schemas

- kogito-test-utils/pom.xml
- kogito-test-utils/src/test/java/org/kie/kogito/test/resources/ConditionHolderTest.java
- kogito-test-utils/src/test/java/org/kie/kogito/test/utils/SocketUtilsTest.java
- kogito-test-utils/src/test/java/org/kie/kogito/testcontainers/InfinispanContainerTest.java
- kogito-test-utils/src/test/java/org/kie/kogito/testcontainers/KeycloakContainerTest.java
- kogito-test-utils/src/test/java/org/kie/kogito/testcontainers/KogitoKafkaContainerTest.java
- kogito-test-utils/src/test/java/org/kie/kogito/testcontainers/KogitoMongoDBContainerTest.java
- kogito-test-utils/src/test/java/org/kie/kogito/testcontainers/KogitoRedisSearchContainerTest.java
issue: https://issues.redhat.com/browse/KOGITO-8133
This patch migrates kogito-runtime tests inside the kogito-test-utils module to assertj assertions.
It removes use of junit assertions.
Where possible it simplifies the assertion using assertj features.
This patch is part of the ongoing effort to standardize kogito-runtime tests to assertj.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we …
> Kogito-8133 Migrate test assertions in kogito-test-utils module to AssertJ assertions

- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/AbstractNodeVisitor.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowProcessFactory.java
The idea is that the classes that cannot be loaded are not loaded but directly reference by generated code
This is a good change regardless the native issue that triggered it (which is after all fixed in later releases)
> [KOGITO-8158] Changing fromType to fromClass

- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/process/builder/ProcessBuildContext.java
- jbpm/jbpm-flow-builder/src/test/java/org/jbpm/process/builder/JavaActionBuilderTest.java
- jbpm/jbpm-flow-builder/src/test/java/org/jbpm/process/builder/MVELActionBuilderTest.java
- jbpm/jbpm-flow-builder/src/test/java/org/jbpm/process/builder/MVELDecisionBuilderTest.java
- jbpm/jbpm-flow-builder/src/test/java/org/jbpm/process/builder/MVELReturnValueConstraintEvaluatorBuilderTest.java
`PackageBuildContext#init` is an internal method that has been deprecated for a while. Remove all references and use the new `initContext`.
- https://github.com/kiegroup/drools/pull/4739
- https://github.com/kiegroup/kogito-runtimes/pull/2549
> DROOLS-6946 Remove deprecated method PackageBuildContext#init

- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/rpc/RPCWorkItemHandler.java
- kogito-workitems/kogito-jackson-utils/pom.xml
- kogito-workitems/kogito-jackson-utils/src/main/java/org/kie/kogito/jackson/utils/JsonObjectUtils.java
- kogito-workitems/kogito-jackson-utils/src/main/java/org/kie/kogito/jackson/utils/ObjectMapperFactory.java
Since mandrel is failing in old version and this is pretty specific scenario (dataOnly = true in the flow), it is better to implement a custom method to generate the json node from a DataEvent holding a json node for that specific scenarion.
That will work for both mandrel versions and actually be faster
<details>
<summary>
</summary> …
> [KOGITO-8161] Fixing CloudEvent conversion to json node in native

- kogito-workitems/kogito-jackson-utils/src/test/java/org/kie/kogito/jackson/utils/JsonNodeConverterTest.java
- kogito-workitems/kogito-jackson-utils/src/test/java/org/kie/kogito/jackson/utils/JsonNodeVisitorTest.java
- kogito-workitems/kogito-jackson-utils/src/test/java/org/kie/kogito/jackson/utils/JsonObjectUtilsTest.java
- kogito-workitems/kogito-jackson-utils/src/test/java/org/kie/kogito/jackson/utils/ListenerAwareTest.java
- kogito-workitems/kogito-jackson-utils/src/test/java/org/kie/kogito/jackson/utils/MergeUtilsTest.java
- kogito-workitems/kogito-rest-workitem/src/test/java/org/kogito/workitem/rest/RestWorkItemHandlerTest.java
- kogito-workitems/kogito-rest-workitem/src/test/java/org/kogito/workitem/rest/pathresolvers/DefaultPathParamResolverTest.java
- kogito-workitems/pom.xml
issue: https://issues.redhat.com/browse/KOGITO-8134
This patch migrates kogito-runtime tests inside the kogito-workitems module to assertj assertions.
It removes use of junit assertions.
Where possible it simplifies the assertion using assertj features.
This patch is part of the ongoing effort to standardize kogito-runtime tests to assertj.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we …
> Kogito-8134 Migrate test assertions in kogito-workitems module to AssertJ assertions	

- api/kogito-api-incubation-processes/src/main/java/org/kie/kogito/incubation/processes/ProcessIdParser.java
- api/kogito-timer/src/main/java/org/kie/kogito/timer/impl/CronExpression.java
- jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/ActionNodeHandler.java
- jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/ProcessHandler.java
- jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xpath/XPATHActionBuilder.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/assembler/DuplicateProcess.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/descriptors/ExpressionUtils.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/xml/compiler/XmlDumper.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/xml/core/ExtensibleXmlParser.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/xml/processes/GlobalHandler.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/process/builder/dialect/java/ProcessKnowledgeHelperFixer.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/process/builder/dialect/mvel/MVELReturnValueEvaluatorBuilder.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/LightProcessRuntime.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/MVELAction.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/XPATHReturnValueEvaluator.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/node/Split.java
- kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionValidation.java
- kogito-codegen-modules/kogito-codegen-sample/kogito-codegen-sample-generator/src/main/java/org/kie/kogito/codegen/sample/generator/SampleCodegen.java
- quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions/src/main/java/org/kie/kogito/core/decision/incubation/quarkus/support/DecisionServiceImpl.java
- quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoQuarkusResourceUtils.java
- quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions/src/main/java/org/kie/kogito/core/prediction/incubation/quarkus/support/PredictionServiceImpl.java
- quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules/src/main/java/org/kie/kogito/core/rules/incubation/quarkus/support/RuleUnitServiceImpl.java
- quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules/src/main/java/org/kie/kogito/core/rules/incubation/quarkus/support/StatefulRuleUnitServiceImpl.java
https://issues.redhat.com/browse/KOGITO-7942
Goal here is to reduce the number of code smells in Kogito-runtimes.
Addressed in this PR is the code smell, (Java) Sections of code should not be commented out (38).
https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS125&id=org.kie.kogito%3Akogito-runtimes
I have remedied this by deleting commented out code; in cases where Sonarcloud was flagging a comment as code, I removed the punctuation so it will be treated as a comment.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there …
> Kogito-7942 Sonarcloud - (Java) Sections of code should not be commented out (38)

- CONTRIBUTING.md
- Develop_on_Mac.md
@danielezonca @yesamer @baldimir 
Add instructions for native image build on MAC
<details>
<summary>
</summary> …
> [mac_contributing_info] Add instructions for Native Image build on MAC

- .github/pull_request_template.md
- .github/workflows/pr-backporting.yml
**JIRA**: 
https://issues.redhat.com/browse/BXMSPROD-1892
**referenced Pull Requests**:
* https://github.com/kiegroup/kogito-pipelines/pull/743
Added GitHub workflow to automate pull request backporting:
* create backporting pull requests whenever a pull request (having one or more labels `backport-<branch>`) is successfully merged.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle …
> Automated pull request backporting workflow

- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/functions/WorkItemFunctionNamespace.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/types/WorkItemTypeHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/WorkItemBuilder.java
This method will allow implementations interested on validation to isolate this validation in a proper place (before the workitemhandler is created)
> [KOGITO-8351] Adding validate argument

- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/functions/WorkItemFunctionNamespace.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/types/WorkItemTypeHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/WorkItemBuilder.java
As @ricardozanini points out validate method needs the function name to be able to throw a meaningful exception. 
Also, it is interesting if in future we add more things to function ref in the spec.
> [KOGITO-8351] Refining validate args

- api/kogito-api/src/main/java/org/kie/kogito/internal/process/event/KogitoObjectListenerAware.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/LambdaSubProcessNodeVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ModelMetaData.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/descriptors/ExpressionUtils.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/coverter/DataTypeDeserializer.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/coverter/DataTypeSerializer.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/coverter/JacksonConverter.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/coverter/JacksonUnconverter.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/coverter/TypeConverterRegistry.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/context/variable/VariableScopeListener.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/ForEachStateHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/models/JsonNodeModel.java
- kogito-serverless-workflow/kogito-serverless-workflow-utils/src/main/java/org/kie/kogito/serverless/workflow/utils/JsonNodeContext.java
- kogito-workitems/kogito-jackson-utils/src/main/java/org/kie/kogito/jackson/utils/ArrayNodeListenerAware.java
- kogito-workitems/kogito-jackson-utils/src/main/java/org/kie/kogito/jackson/utils/ObjectNodeListenerAware.java
- kogito-workitems/kogito-jackson-utils/src/test/java/org/kie/kogito/jackson/utils/ListenerAwareTest.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/foreach_child.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/foreach_parent.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/ForEachRestIT.java
This PR is:
- Cloning workflow data when passing it to the subprocess (and avoid recursivity in listener when assigning an object to itself)
- Making the iterationParameter accessible to the subprocess (the subprocess will still have access to the parent flow)
- Adding  @dmarrazzo use case that originates the JIRA to the set on integration
In order to achieve the second goal, after trying different approaches, I chose to map the variable name and do a small trick on JsonNodeContext to decide its inclusion in the jq scope (see https://github.com/eiiches/jackson-jq/issues/221, once this is available in JQ library, we can refactor this class and clean it up)
> [KOGITO-8330] ForEach and subprocess

- kogito-build/kogito-dependencies-bom/pom.xml
- springboot/bom/pom.xml
See: https://issues.redhat.com/browse/KOGITO-8432
Small update on our SB libraries to fix the affected components. See: https://github.com/spring-projects/spring-boot/issues/32221 for more info.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and …
> [KOGITO-8432] - CVE-2022-25857 - Upgrade SnakeYAML on Spring Boot related components

- api/kogito-api/pom.xml
- kogito-bom/pom.xml
@ricardozanini @danielezonca @mariofusco 
See https://issues.redhat.com/browse/KOGITO-8425
I tested it locally with pmml-quarkus-example (where the same issue is present).
But this PR does not fix eveything.
`kogito-pmml-api-dependencies` was wrongly declared as "pom", and fixing that resolved its issue.
But the problem (empty paths) is still present for `kogito-pmml-dependencies` and `kogito-efesto-drl`.
Those are actually "pom" artifacts, but quarkus resolve them as "jar" and try to look for them as jar artifact, that of course can't be found (see [here](https://github.com/kiegroup/kogito-runtimes/blob/6f6b6ad58254d414956dd4bb36b8af7a29cdd1fa/quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main …
> [KOGITO-8425] Fix kogito-pmml-api-dependencies

- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/ParallelHandler.java
Despite the description of this JIRA, branch name is already available on 0.8, so using it (with an if in case is null, since it wont be mandatory till 0.9)
Note that user explicitly has to use the branch name to the flow, if not, there will duplicated node names as if now.
> [KOGITO-8446] Adding branch name to node name on parallel state

- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/operationid/AbstractWorkflowOperationIdFactory.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/operationid/FileNameWorkflowOperationIdTest.java
Now the message when using file:// (which is not a valid file path) is 
`Empty file name for function named 'sayHello', please review uri 'file://greeting.proto' or consider using a different strategy defined in the kogito.sw.operationIdStrategy property `
> [KOGITO-8464] Improve error message when using an invalid uri

- kogito-build/kogito-dependencies-bom/pom.xml
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/types/AsyncAPITypeHandler.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/asyncapi/WorkflowAsyncApiSpecInputProvider.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/asyncPublisher.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/specs/asyncAPI.yaml
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/AsyncAPIIT.java
Adding the publish test, and fixing a couple of minor issues:
1.  Using no arguments caused a null pointer
2.  Cannot resuse the same spec file in multiple flows within the same project. 
3. Both flows (publising and consume) use the same channel for publish/sbuscribe intentionally
This requires async extension version 0.0.3 (being releases right now), because before same channel name was not supported
> [KOGITO-8489] Adding publishing test using the same channel

- quarkus/addons/kubernetes/deployment/src/test/java/org/kie/kogito/addons/quarkus/kubernetes/KubernetesAddOnTest.java
For some reason, the Kubernetes deployment test still starts the k8s containers. The property must be set in the unit test Shrink archive.
See: https://issues.redhat.com/browse/KOGITO-8537
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be …
> [KOGITO-8537] Move devservices disabled property to unit test from properties

- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/CompositeContextNodeVisitor.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/actions/AbstractNodeInstanceAction.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/actions/CompleteCompositeNodeInstanceAction.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/actions/CompleteStateBasedNodeInstanceAction.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/AbstractCompositeNodeFactory.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/impl/ExtendedNodeImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/impl/NodeImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/node/StateBasedNode.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/SplitInstance.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CallbackHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/EventHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/ServerlessWorkflowParsingTest.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/eventMultiple.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/eventMultipleExclusive.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/eventMultipleTimeout.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/eventMultipleTimeoutExclusive.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/EventFlowIT.java
For exclusive rather than and-split and xor-join, we should have xand-split and xor-join.
Not exclusive remain the same, and-split and and-join. 
In order nested xand to work, split are embedded into composite nodes
For timers, there are two approaches. If the node is composite, a timer is added to it node (which internally use a DroolsAction, a slightly modification of existing CancelTimer). If the node is not a composite one (for example, in callback, when there is only one event node or in an event state with only one event type), then the former approach based on X_AND gateway is still used.
> [KOGITO-7982] Changing splitType to XAND for exclusive

- .github/workflows/surefire.yml
Looks like for the now the check run is being checked for main and not the PR. See - https://github.com/kiegroup/kogito-runtimes/actions/runs/4076623144/jobs/7024603659#step:5:19
Merge after:
* https://github.com/kiegroup/kogito-pipelines/pull/803
> [BXMSPROD-728] set commit for check_run

- .github/workflows/kogito-runtimes-pr.yml
Hi we will need to revert this due to an issue that github itself hasn't fixed. 
The way [action-surefire-report](https://github.com/ScaCap/action-surefire-report) or [action-junit-report](https://github.com/mikepenz/action-junit-report) publish/annotate test failures is using github's check api. Whenever a workflow is run it creates something called a check suite which contains check runs. These check runs are responsible for letting us update github action status. Now these actions give us 2 options to update github action status using check runs - use existing "in_progress" check runs or create a new one.
1. Using existing check runs: We can't use existing check runs since by the time surefire gets to analyse and publish results the workflow which triggered the surefire analysis would …
> Revert distinguish PR status for kogito-runtimes

- kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/context/KogitoBuildContext.java
- kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/utils/KogitoCodeGenConstants.java
- kogito-codegen-modules/kogito-codegen-core/src/main/java/org/kie/kogito/codegen/core/CustomDashboardGeneratedUtils.java
- kogito-codegen-modules/kogito-codegen-core/src/main/java/org/kie/kogito/codegen/core/io/CollectedResourceProducer.java
- kogito-codegen-modules/kogito-codegen-core/src/main/java/org/kie/kogito/codegen/core/utils/ApplicationGeneratorDiscovery.java
- kogito-codegen-modules/kogito-codegen-core/src/test/java/org/kie/kogito/codegen/core/io/CollectedResourceProducerTest.java
- kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java
- quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/src/main/java/org/kie/kogito/quarkus/config/KogitoBuildTimeConfig.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/deployment/ServerlessWorkflowAssetsProcessor.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/pom.xml
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/.greet-hidden.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/GreetRestIT.java
See: https://issues.redhat.com/browse/KOGITO-8634
@danielezonca we need to figure out:
<details>
<summary>
</summary>
[build-chain …
> [KOGITO-8634] Remove hidden files from CollectedResource in codegen

- springboot/bom/pom.xml
Jira - https://issues.redhat.com/browse/KOGITO-8485
Swagger is generated with example: null after upgrading jackson dependencies to 2.14.1 version in 1.31.1.Final version.
Upgraded swagger-annotations & springdoc-openapi-ui versions to be compatible with the 2.1.4.1 version of   jackson dependencies.
> [KOGITO-8485]- Swagger is generated with example: null on 1.32

- kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandler.java
- kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/pathresolvers/DefaultPathParamResolver.java
- kogito-workitems/kogito-rest-workitem/src/test/java/org/kogito/workitem/rest/RestWorkItemHandlerTest.java
As per JIRA description. 
More traces were added to be able to follow handler execution in failing cases (given the variabality of the possible inputs, this is desirable in this case) 
Merged with https://github.com/kiegroup/kogito-examples/pull/1595. I do not think the handler should support that case, that was a plain invalid URI, so I changed the example.  Code is properly encoding URI template parameters (both for path and query parameters), which might containe whitepaces, trails and so on. They are escaped properly, but a hardcoded URI with white spaces is a not valid one, so I do not think is kogito repsonsibility to transform it into a valid one, it is writer of the bpmn responsbilibty to encode the hardcoded URI (the important thing is the fact that it is hardcoded, not using …
> [KOGITO-8779] Restworkitemhandler query segment

- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/LightProcessRuntime.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessRuntimeImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/event/DefaultSignalManager.java
JIRA: https://issues.redhat.com/browse/DROOLS-7351
First implementation of a reliable session with a simplified strategy only using persisted object stores and reflushing all the objects contained in the stores when a new session is created out of an existing one.
> [DROOLS-7351] first implementation of reliable session

- .ci/jenkins/Jenkinsfile.setup-branch
This will run only on release branches now. I didn't know `setup-branch` is also called on main.
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to …
> Update data-index-ephemeral image tag only on a release branch

- .ci/jenkins/Jenkinsfile.deploy
```
14:32:05  + mvn -B -s /tmp/tmp.v1OJYZfQJb-settings.xml -fae -ntp -q help:evaluate -Dfull -Dexpression=data-index-ephemeral.image -DforceStdout
14:32:08  [ERROR] [ERROR] Some problems were encountered while processing the POMs:
14:32:08  [ERROR] Non-resolvable import POM: Could not find artifact org.kie.kogito:kogito-quarkus-bom:pom:1.36.0.Final in mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/) @ org.kie.kogito:quarkus-extensions:1.36.0.Final, /home/jenkins/workspace/KIE/kogito/1.36.x/release/kogito-runtimes-deploy/kogito-runtimes/quarkus/extensions/pom.xml, line 20, column 19
14:32:08  [ERROR] Non-resolvable import POM: Could not find artifact org.kie.kogito:kogito-bom:pom:1.36.0.Final in mirror-central …
```
> Release: Fix setup data-index image tag

- springboot/addons/messaging/implementation/src/main/java/org/kie/kogito/addon/cloudevents/spring/SpringKafkaConsumerConfig.java
Changed SpringKafkaConsumerConfig to read the properties:
```ini
spring.kafka.security.protocol = ...
spring.kafka.ssl.trust-store-location = ...
spring.kafka.ssl.trust-store-password = ...
spring.kafka.ssl.key-store-location = ...
spring.kafka.ssl.key-store-password = ...
```
> #2745 spring configure consumer for SSL with Kafka

- quarkus/addons/process-svg/deployment/pom.xml
- quarkus/addons/process-svg/runtime/pom.xml
- quarkus/integration-tests/integration-tests-quarkus-source-files/pom.xml
https://issues.redhat.com/browse/KOGITO-9055
SVG does not really need resteasy-common, but just the standard jaxrs annotations. 
Note that for quarkus3.x the dependency should be the jakarta one, not the jboss one
Added dependency change on source files integration tests
> [KOGITO-9055] resteasy-reactive should not be together with resteasy-classic

- .ci/environments/quarkus-3/after.sh
- .ci/environments/quarkus-3/before.sh
- .ci/environments/quarkus-3/patches/0001_before_sh.patch
- .ci/environments/quarkus-3/quarkus3.yml
https://issues.redhat.com/browse/KOGITO-9072
With this PR the `0001_before_sh` patch will be much smaller and won't contain the version change.
The version is set after all patches are applied, in the `after.sh` script
Here are the pros:
- Better reading of the patch if needed. and only the migration part will be displayed when reviewing
- Adding new module if needed without those being much impacted by the Q3
- `versions:set` is taking ~20s and we remove one quick install which is taking minutes
**Related:**
- https://github.com/kiegroup/drools/pull/5202
- https://github.com/kiegroup/kogito-runtimes/pull/2954
> KOGITO-9072 Setup version after the patches are applied

- api/kogito-events-core/pom.xml
- api/kogito-events-core/src/main/java/org/kie/kogito/event/cloudevents/utils/BaseCloudEventValidator.java
- api/kogito-events-core/src/main/java/org/kie/kogito/event/cloudevents/utils/CloudEventUtils.java
- api/kogito-events-core/src/main/java/org/kie/kogito/event/cloudevents/utils/CloudEventValidatorV03.java
- api/kogito-events-core/src/main/java/org/kie/kogito/event/cloudevents/utils/CloudEventValidatorV1.java
- api/kogito-events-core/src/main/java/org/kie/kogito/event/cloudevents/utils/InvalidCloudEventException.java
- api/kogito-events-core/src/test/java/org/kie/kogito/event/cloudevents/utils/BaseCloudEventValidatorTest.java
- api/kogito-events-core/src/test/java/org/kie/kogito/event/cloudevents/utils/CloudEventValidatorV03Test.java
- api/kogito-events-core/src/test/java/org/kie/kogito/event/cloudevents/utils/CloudEventValidatorV1Test.java
- quarkus/addons/knative/serving/runtime/src/main/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/CloudEventKnativeServiceRequestClient.java
- quarkus/addons/knative/serving/runtime/src/test/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/CloudEventKnativeServiceRequestClientTest.java
- quarkus/addons/knative/serving/runtime/src/test/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/KnativeServerlessWorkflowCustomFunctionTest.java
Jira: https://issues.redhat.com/browse/KOGITO-8848
PR to update docs:
- https://github.com/kiegroup/kogito-docs/pull/337
-----------
<details>
<summary>
</summary> …
> KOGITO-8848 Added flexibility for users to send a custom CloudEvent ID in Knative custom functions

- .ci/jenkins/Jenkinsfile.promote
JIRA: [KOGITO-8455](https://issues.redhat.com/browse/KOGITO-8455)
Dep PRs: 
- [kogito-runtimes](https://github.com/kiegroup/kogito-runtimes/pull/3017)
- [kogito-apps](https://github.com/kiegroup/kogito-apps/pull/1740)
- [kogito-examples](https://github.com/kiegroup/kogito-examples/pull/1678)
- [jenkins-pipeline-shared-libraries](https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/275)
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect …
> KOGITO-8455: CI ReleaseNotes Creation

- .ci/environments/quarkus-3/before.sh
<details>
<summary>
</summary> …
> Quarkus 3: Fix before.sh rebase

- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java
- quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/src/main/java/org/kie/kogito/quarkus/config/KogitoBuildTimeConfig.java
To be consistent with alrady existing naming convention. Also adding the property to KogitoBuildTimeConfig bean to avoid quarkus warning
> [KOGITO-9217] Set property name to "kogito.codegen.process.failOnError"

- api/kogito-api/src/main/java/org/kie/kogito/process/ProcessInstance.java
- api/kogito-api/src/main/java/org/kie/kogito/process/ProcessService.java
- api/kogito-events-core/src/main/java/org/kie/kogito/event/AbstractDataEvent.java
- api/kogito-events-core/src/main/java/org/kie/kogito/event/impl/ProcessEventDispatcher.java
- api/kogito-events-core/src/test/java/org/kie/kogito/event/impl/ProcessEventDispatcherTest.java
- jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java
- jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/ProcessServiceImpl.java
As requested on comunity, this add CE attributes/extensions as headers available in KogitoProcessContext. 
I reused the exist Map<String,List<String>> interface.
> [KOGITO-9281] Setting CE attributes as process instance headers

- .ci/environments/quarkus-3/patches/0022_spring_boot_it_fix.patch
**DON'T MERGE YET! this is a WIP PR.**
Closes https://github.com/kiegroup/kie-issues/issues/352
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) …
> [WIP] kie-issues#352: [Spring-Boot 3.0.5 Migration] Fix IT Tests

- .ci/environments/quarkus-3/patches/0014_remove_jdk17_test_warnings.patch
<details>
<summary>
</summary> …
> Quarkus 3: Fix patches

- kogito-build/kogito-dependencies-bom/pom.xml
- kogito-serverless-workflow/kogito-serverless-workflow-builder/pom.xml
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/pom.xml
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/JsonSchemaValidator.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/serverless/workflow/parser/schema/OpenApiModelSchemaGenerator.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/ExpressionRestIT.java
- quarkus/integration-tests/integration-tests-quarkus-processes/pom.xml
Using jackson validator rather than gson one. 
In order gson one to dissapear completely, we need PR to remove it from [Java SDK.](https://github.com/serverlessworkflow/sdk-java/blob/main/pom.xml#L130-L140) 
There is also another subttle change in behaviour (for good). This jackson API allows us to distinghish between a validation failure of the schema against the data (that might or not be ignored as per spec) and a failure parsing the schema itself (which in my opinion should be propagated always because there is a fatal configuration error that requires user intervention, for example, a bad formatted schema file or an unavailable one) .
> [KOGITO-9501] Changing Everit to json-schema-validator

- .ci/environments/quarkus-3/patches/0001_before_sh.patch
- .ci/environments/quarkus-3/patches/0004_javax.enterprise_to_jakarta.enterprise.patch
- .ci/environments/quarkus-3/patches/0016_update_dependencies_version.patch
- .ci/environments/quarkus-3/project-recipe.yml
- .ci/environments/quarkus-3/quarkus3.yml
fix patch
<details>
<summary>
</summary> …
> Quarkus 3: corrected patch

- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/ServerlessWorkflowUtils.java
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/JsonSchemaValidator.java
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/io/URIContentLoaderFactory.java
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/io/URIContentLoaderType.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/serverless/workflow/parser/schema/JsonSchemaImpl.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/serverless/workflow/parser/schema/OpenApiModelSchemaGenerator.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/serverless/workflow/parser/schema/RefSchemas.java
Fix problem generating swagger
See example at https://github.com/kiegroup/kogito-examples/pull/1741
> [KOGITO-9584] Ensure nested schemas are resolved for swagger doc

- addons/common/source-files/pom.xml
- addons/common/source-files/src/main/java/org/kie/kogito/addon/source/files/SourceFilesProviderImpl.java
- api/kogito-api/src/main/java/org/kie/kogito/internal/SupportedExtensions.java
- jbpm/jbpm-flow-builder/pom.xml
- jbpm/jbpm-flow/pom.xml
- kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/java/org/kie/kogito/codegen/process/ProcessGenerationIT.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java
- kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/process/ProcessGenerationUtils.java
- quarkus/addons/source-files/deployment/src/main/java/org/kie/kogito/addon/source/files/deployment/KogitoAddOnSourceFilesProcessor.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/WorkflowCodeGenUtils.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/deployment/ServerlessWorkflowCompilationProvider.java
Besides declaring DMN as optional in jbpm-flow and jbpm-flow-builder, this refactors the extension identification code to avoid an undesired dependency between source addon and codegen, which carry forward dmn (because codegen correctly depends on bpmn2, which needs dmn)
To be merged with https://github.com/kiegroup/kogito-apps/pull/1808
> [KOGITO-9568] Declaring dmn as optional

- kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/main/java/org/kie/kogito/serverless/workflow/executor/StaticWorkflowApplication.java
- kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/main/java/org/kie/kogito/serverless/workflow/executor/StaticWorkflowProcess.java
- kogito-serverless-workflow/kogito-serverless-workflow-executor-kafka/pom.xml
- kogito-serverless-workflow/kogito-serverless-workflow-executor-kafka/src/test/java/org/kie/kogito/serverless/workflow/executor/WorkflowEventSubscriberTest.java
- quarkus/addons/process-definitions/runtime/pom.xml
- quarkus/addons/process-definitions/runtime/src/main/java/org/kie/kogito/process/definitions/ProcessDefinitionsResource.java
New method added to StaticWorkfApplication. This method accepts the ProcessInstancesFactory object of the persistence addon
Usage example  
```
try (StaticWorkflowApplication application =
StaticWorkflowApplication.create().processInstancesFactory(new RocksDBProcessInstancesFactory(new Options().setCreateIfMissing(true), tempDir.toString())))
```
Also added persistence addon support to definitions addon
> [KOGITO-9613] Adding persistence support to executor

- addons/common/kubernetes-service-catalog/pom.xml
- addons/common/kubernetes-service-catalog/src/test/java/org/kie/kogito/addons/k8s/resource/catalog/KubernetesServiceCatalogTest.java
- quarkus/addons/fabric8-kubernetes-service-catalog/runtime/pom.xml
- quarkus/addons/fabric8-kubernetes-service-catalog/runtime/src/test/java/org/kie/kogito/addons/quarkus/fabric8/k8s/service/catalog/Fabric8KubernetesServiceCatalogTest.java
- quarkus/addons/fabric8-kubernetes-service-catalog/runtime/src/test/java/org/kie/kogito/addons/quarkus/fabric8/k8s/service/catalog/KnativeServiceDiscoveryTest.java
- quarkus/addons/fabric8-kubernetes-service-catalog/runtime/src/test/resources/knative/quarkus-greeting-kubernetes.yaml
- quarkus/addons/fabric8-kubernetes-service-catalog/runtime/src/test/resources/knative/quarkus-greeting-openshift.yaml
- quarkus/addons/fabric8-kubernetes-service-catalog/test-utils/src/main/java/org/kie/kogito/addons/quarkus/k8s/test/utils/KnativeResourceDiscoveryTestUtil.java
- quarkus/addons/knative/serving/runtime/src/test/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/KnativeServerlessWorkflowCustomFunctionTest.java
- quarkus/addons/kubernetes/runtime/src/test/java/org/kie/kogito/addons/quarkus/k8s/config/KubeDiscoveryConfigCacheUpdaterTest.java
Jira: https://issues.redhat.com/browse/KOGITO-9605
This PR refactors tests related to `KubernetesServiceCatalog` so they can be reused by the implementation created in https://issues.redhat.com/browse/KOGITO-9145
--------
<details>
<summary>
</summary>
[build-chain …
> KOGITO-9605 Created abstract test class that implementations of `KubernetesServiceCatalog` must cover

- kogito-build/kogito-dependencies-bom/pom.xml
- quarkus/integration-tests/integration-tests-quarkus-openapi-client/src/main/resources/application.properties
- quarkus/integration-tests/integration-tests-quarkus-openapi-client/src/main/resources/openapi2-sec-no-auth.sw.json
- quarkus/integration-tests/integration-tests-quarkus-openapi-client/src/main/resources/openapi3-sec-no-auth.sw.json
- quarkus/integration-tests/integration-tests-quarkus-openapi-client/src/main/resources/specs/openapi3.0-security-no-auth.yaml
- quarkus/integration-tests/integration-tests-quarkus-openapi-client/src/main/resources/specs/swagger2.0-security-no-auth.yaml
- quarkus/integration-tests/integration-tests-quarkus-openapi-client/src/test/java/org/kie/kogito/quarkus/it/openapi/client/ApiWithSecurityContextIT.java
- quarkus/integration-tests/integration-tests-quarkus-openapi-client/src/test/java/org/kie/kogito/quarkus/it/openapi/client/mocks/AuthSecurityMockService.java
- quarkus/integration-tests/integration-tests-quarkus-openapi-client/src/test/java/org/kie/kogito/quarkus/it/openapi/client/mocks/MockServiceConfigurer.java
See https://issues.redhat.com/browse/KOGITO-9625
<details>
<summary>
</summary> …
> KOGITO-9625: Upgrade quarkus-openapi-generator to 1.3.8

- .ci/jenkins/dsl/jobs.groovy
- .github/pull_request_template.md
- .github/workflows/pr-jenkins.yml
Never used/maintained
https://issues.redhat.com/browse/KOGITO-9725
- https://github.com/kiegroup/kogito-pipelines/pull/1044
- https://github.com/kiegroup/kogito-runtimes/pull/3180
- https://github.com/kiegroup/kogito-apps/pull/1839
- https://github.com/kiegroup/kogito-examples/pull/1769
- https://github.com/kiegroup/kogito-images/pull/1672
- https://github.com/kiegroup/kogito-operator/pull/1514
> KOGITO-9725 DSL cleanup: Remove 'kogito-bdd' check

- quarkus/addons/kubernetes/runtime/src/main/java/org/kie/kogito/addons/quarkus/k8s/config/KubernetesAddonConfigSource.java
- quarkus/addons/kubernetes/runtime/src/main/resources/META-INF/services/org.eclipse.microprofile.config.spi.ConfigSource
Jira: https://issues.redhat.com/browse/KOGITO-8749
--------
<details>
<summary>
</summary> …
> KOGITO-8749 Disabled Kubernetes Dev Services by default

- .ci/environments/quarkus-3/patches/0001_before_sh.patch
- .ci/environments/quarkus-3/project-recipe.yml
- .ci/environments/quarkus-3/quarkus3.yml
<details>
<summary>
</summary> …
> Quarkus 3: Update openapi version

- addons/common/process-management/src/main/java/org/kie/kogito/process/management/BaseProcessInstanceManagementResource.java
- quarkus/integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/ManagementAddOnIT.java
- springboot/integration-tests/src/it/integration-tests-springboot-processes-it/src/test/java/org/kie/kogito/integrationtests/springboot/ManagementAddOnTest.java
NodeDefinitionId is used by runtime tools
> [KOGITO-9763] Restoring nodeDefinitionId

- addons/common/process-management/src/main/java/org/kie/kogito/process/management/BaseProcessInstanceManagementResource.java
- addons/common/process-management/src/test/java/org/kie/kogito/process/management/BaseProcessInstanceManagementResourceTest.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/Metadata.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ServerlessWorkflowParser.java
- quarkus/addons/process-management/integration-tests/src/main/resources/parallel.sw.json
- quarkus/addons/process-management/integration-tests/src/test/java/org/kie/kogito/quarkus/workflows/ManagementFlowIT.java
This way annotations can be retrieved by process management interface
> [KOGITO-9673] Adding SWF annotations to process metadata

- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/expression.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/ExpressionRestIT.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/src/main/java/org/kie/kogito/serverless/workflow/QuarkusKogitoProcessContextResolver.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/src/main/resources/META-INF/services/org.kie.kogito.serverless.workflow.utils.KogitoProcessContextResolverExtension
> [KOGITO-9650] Adding identity to SWF workflow

- api/kogito-api/pom.xml
- api/kogito-api/src/main/java/org/kie/kogito/MapInput.java
- api/kogito-api/src/main/java/org/kie/kogito/Models.java
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/models/JsonNodeModel.java
BeanInstrospector does not work with uppercase (both Message and message fields are mapped to message property, hence the issue). Lets take benefit that the generated code is annotated with JsonProperty annotation with the right case and use jackson for serialization/deserialization of Map into Model and Model into Map. 
@tarilabs Im including you because as core Java developer your feedback is appreciated
I commented some of the decissions inline in the code.
> [KOGITO-5823] Supporting uppercase properties

- kogito-serverless-workflow/kogito-serverless-workflow-rest-parser/src/main/java/org/kie/kogito/serverless/workflow/parser/types/RestTypeHandler.java
This can be forced by setting value to null in RestTypeHandler
> [KOGITO-9786] Default port should be calculated by RestWorkItemHandler

- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/io/CachedContentLoader.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/io/ClassPathContentLoader.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/io/FileContentLoader.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/io/URIContentLoader.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/io/URIContentLoaderFactory.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/io/ClassPathContentLoaderTest.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/rpc/WorkflowRPCCodeGenProvider.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-extension-live-reload-test/src/test/resources/asyncPublisher.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-extension-live-reload-test/src/test/resources/openAPIEnumParameter.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-extension-live-reload-test/src/test/resources/rpcgreet.sw.json
In case the file cannot be retrieved from file system or relative classpath use absolute classpath to try to retrieve it.
> [KOGITO-9775] Classpath loading as fallback

- .ci/jenkins/Jenkinsfile
kiegroup/kie-issues#587
Aborting previous builds when new one is triggered (PR branch push or target branch push).
Full ensemble:
apache/incubator-kie-drools#5535
apache/incubator-kie-kogito-runtimes#3237
apache/incubator-kie-kogito-apps#1887
apache/incubator-kie-kogito-examples#1812
apache/incubator-kie-optaplanner#2988
apache/incubator-kie-optaplanner-quickstarts#608
> kie-issues#587 abort stale builds

- kogito-build/kogito-build-no-bom-parent/pom.xml
- pom.xml
- quarkus/addons/pom.xml
- springboot/integration-tests/src/it/integration-tests-springboot-processes-persistence-it/pom.xml
This is part of an effort from issue https://github.com/kiegroup/kie-issues/issues/511. 
- Changes root parent pom from jboss-parent to apache parent pom.xml. 
- Aligns version property names with apache parent pom. 
- Adds missing version properties.
> [kie-issues#511] Migrate from jboss-parent to apache parent pom.

- .ci/jenkins/Jenkinsfile
First task in regards to apache/incubator-kie-issues#599
Disabling sonar checks, as it currently breaks the build due to bug and misconfiguration.
> kie-issues#599: disable sonar in PR checks

- addons/common/rest-exception-handler/src/main/java/org/kie/kogito/resource/exceptions/BaseExceptionsHandler.java
- addons/common/rest-exception-handler/src/test/java/org/kie/kogito/resource/exceptions/BaseExceptionHandlerTest.java
- quarkus/addons/rest-exception-handler/src/main/java/org/kie/kogito/resource/exceptions/WorkItemExecutionExceptionMapper.java
- springboot/addons/rest-exception-handler/src/main/java/org/kie/kogito/resource/exceptions/springboot/ExceptionsHandler.java
Adding handler for WorkItemExecutionException
> [KOGITO-9838] Improving error message for WorkItemExecutionException

- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/WorkflowWorkItemHandler.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/ClassAnnotatedWorkflowHandlerGenerator.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/openapi/WorkflowOpenApiHandlerGenerator.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/openapiarray.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/specs/array.yaml
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/OpenAPIArrayFlowIT.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/OpenAPIArrayMockService.java
Fix a problem that prevents using arrays as open api body request (top level, inner ones were already supported)
Also fixes compilation issues when open api extension generate pojos as inner classes
> [KOGITO-9861] Fixing compilation issues with nested classes and arrays

- kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqExpression.java
- kogito-serverless-workflow/kogito-jq-expression/src/test/java/org/kie/kogito/expr/jq/JqExpressionHandlerTest.java
See added test for a better understanding of the issue. Before this JIRA, isValid method was returning true for that expression, because of jq library internals. 
This PR uses reflection to try to invoke functions calls (but only function calls) as part of validation procedure.
> [KOGITO-9844] Enhace jq validation to detect invalid functions

- quarkus/addons/common/reactive-messaging/pom.xml
- quarkus/addons/common/reactive-messaging/src/main/java/org/kie/kogito/addon/quarkus/common/reactive/messaging/http/CloudEventHttpOutgoingDecorator.java
- quarkus/addons/common/reactive-messaging/src/test/java/org/kie/kogito/addon/quarkus/messaging/common/message/http/CloudEventHttpOutgoingDecoratorTest.java
- quarkus/addons/events/process/deployment/pom.xml
- quarkus/addons/events/process/deployment/src/main/java/org/kie/kogito/events/process/deployment/KogitoAddOnEventProcessProcessor.java
- quarkus/addons/events/process/runtime/pom.xml
- quarkus/addons/jobs/knative-eventing/runtime/src/main/java/org/kie/kogito/jobs/knative/eventing/quarkus/KnativeEventingJobsService.java
- quarkus/addons/jobs/knative-eventing/runtime/src/test/java/org/kie/kogito/jobs/knative/eventing/quarkus/KnativeEventingJobsServiceTest.java
- quarkus/addons/messaging/deployment/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/deployment/KogitoAddOnMessagingProcessor.java
- quarkus/extensions/kogito-quarkus-workflow-extension-common/kogito-quarkus-workflow-common/src/main/java/org/kie/kogito/quarkus/workflow/devservices/DataIndexEventPublisher.java
- Ensures that the kogito-addons-quarkus-events-process addon produces the proper content type header when http cloud events are used.
- Ensure the data index dev services produce the proper content type header.
<details>
<summary>
</summary> …
> KOGITO-9849 DataIndex is not processing well the http cloud events

- .ci/jenkins/tests/pom.xml
- pom.xml
This PR changes the JBoss Nexus configuration to Apache Nexus.
> [kie-issues#628] Change JBoss Nexus to Apache Nexus.

- .ci/jenkins/Jenkinsfile.pr.1.40.x
- kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoKafkaContainer.java
- kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoKeycloakContainer.java
- kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoRedisSearchContainer.java
- quarkus/extensions/kogito-quarkus-workflow-extension-common/kogito-quarkus-workflow-common-deployment/src/main/java/org/kie/kogito/quarkus/workflow/deployment/devservices/DataIndexInMemoryContainer.java
Cherry-pick of apache/incubator-kie-issues#622 to improve stability of CI builds.
> kie-issues#622: explicitly provide startupTimeout in waitingFor call

- kogito-build/kogito-build-no-bom-parent/pom.xml
apache/incubator-kie-issues#647
Given that CI builds set `maven.test.failure.ignore` to true, any build failure would be silently ignored, unless invoker plugin writes the build fail as a junit report with failure outcome.
This is achieved by property writeJunitReport which is false by default and needs to be overriden.
To be validated by presence of test case `maven.invoker.it.integration-tests-springboot-kafka-it.integration-tests-springboot-kafka-it` in the test results.
> kie-issues#647: add writeJunitReport to invoker configuration

- quarkus/addons/python/integration-tests/pom.xml
Fixing native image generation issue when using python. The Jep library was not included if LD_LIBRARY_PATH is not set.
> [KOGITO-9914] Setting LD_LIBRARY_PATH to include Jep

- kogito-build/kogito-dependencies-bom/pom.xml
cherry-pick Quarkus 2.16.12 upgrade #3253
> bump to Quarkus 2.16.12 (#3253)

- api/kogito-events-core/src/test/java/org/kie/kogito/event/cloudevents/utils/CloudEventUtilsTest.java
- api/kogito-events-core/src/test/java/org/kie/kogito/event/impl/DataEventFactoryTest.java
- kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoGenericContainer.java
- quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-integration-test/src/main/java/org/acme/GreetingResource.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/CallbackStateWithTimeoutsErrorHandlerIT.java
This sets the level for container and kafka to warn (this generates a log of trace that does not really tell us anything unless debugging kafka or container issue, which is not the point of the test runt)
There is still an annoying system.out that is printing all kafka events, but I do not think that can be fixed in this repo
> Try to reduce the log file size of SWF IT

- kogito-build/kogito-dependencies-bom/pom.xml
This PR upgrades the version of `commons-compress` to fix the `CVE-2023-42503` included in the `v1.22`.
More Info: CVE-2023-42503: Apache Commons Compress denial of service vulnerability. More info: 
https://nvd.nist.gov/vuln/detail/CVE-2023-42503
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds …
> NO_ISSUE: Overriding `commons-compress` version to fix `CVE-2023-42503` present in `1.22`

- kogito-build/kogito-dependencies-bom/pom.xml
This PR upgrades the version of `commons-compress` to fix the `CVE-2023-42503` included in the `v1.22`.
More Info: CVE-2023-42503: Apache Commons Compress denial of service vulnerability. More info: 
https://nvd.nist.gov/vuln/detail/CVE-2023-42503
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds …
> [1.40.x] NO_ISSUE: Overriding `commons-compress` version to fix `CVE-2023-42503` present in `1.22`

- .ci/jenkins/Jenkinsfile.deploy
- .ci/jenkins/Jenkinsfile.promote
- .ci/jenkins/Jenkinsfile.quarkus-3.rewrite.pr
- .ci/jenkins/Jenkinsfile.quarkus-3.rewrite.standalone
- .ci/jenkins/Jenkinsfile.setup-branch
apache/incubator-kie-issues#667
Fixing cleanup and settings.xml pipeline configuration to work correctly in ASF Jenkins.
* Deferred wipeout was causing issues when invoked in early stages
* Docker cleanup can't be done since the overall build is in docker container that uses the docker.sock from the host - it would attempt to erase itself.
* withSettingsXmlId shared library method does imply usage of a prohibited groovy method, thus replacing with explicit configFileProvider and passing as withSettingsXmlFile goes around that part of code. 
Complete list:
apache/incubator-kie-kogito-pipelines#1113
apache/incubator-kie-kogito-runtimes#3272
apache/incubator-kie-kogito-apps#1909
apache/incubator-kie-kogito-examples#1820
apache/incubator-kie-drools#5572
apache/incubator-kie-optaplanner#3010 …
> kie-issues#667: fix cleanup and settingsXml handling

- .ci/jenkins/Jenkinsfile
- .ci/jenkins/dsl/jobs.groovy
apache/incubator-kie-issues#599
Explicitly setting sonar.projectKey in PR checks and buildchain nightly.
apache/incubator-kie-drools#5573
apache/incubator-kie-kogito-apps#1910
apache/incubator-kie-kogito-pipelines#1116
apache/incubator-kie-kogito-runtimes#3274
apache/incubator-kie-optaplanner#3011
> kie-issues#599: set projectKey for sonarcloud

- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/PojoServiceIT.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/WorkflowTestUtils.java
Pretty print was being called and concatenated regardless the logger is enable or not. Due to the massive amount of events that we might potentially received there, this might well explain why some test were timing out. In any case, it is a mistake that should be fixed. 
Update: 
Since the failure was still there, I tried invoking the operation after event registration, to rule out process publishing event too soon
> Properly trace cloud events

- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ForEachNodeVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessVisitor.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowProcessFactory.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/ForEachNodeFactory.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/validation/RuleFlowProcessValidator.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/WorkflowProcess.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/impl/NodeImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/impl/WorkflowProcessImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/node/ForEachNode.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateBasedNodeInstance.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ServerlessWorkflowParser.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/ForEachStateHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/TimeoutsConfigResolver.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/utils/TimeoutsConfigResolverTest.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/callback-state-with-timeouts-error-handler.sw.json
Allow expressions in timeout durations for SWF. 
This requires changes at engine side.
> [KOGITO-9811] Evaluating timeout duration as expression

- quarkus/addons/pom.xml
This carry backward change from main to 1.40.x
> Remove python from default profile

- kogito-build/kogito-build-no-bom-parent/pom.xml
Fixes:
* apache/incubator-kie-issues#742
Upgrading jacoco maven plugin version due to JDK 17 issues we've seen in CI after JDK upgrade.
> kie-issues#742: upgrade jacoco maven plugin to 0.8.11

- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/CallbackStateTimeoutsIT.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/CallbackStateWithTimeoutsErrorHandlerIT.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/EventTimedoutIT.java
- Disabled until they get fixed/stable
https://github.com/apache/incubator-kie-kogito-runtimes/issues/3320
These tests are flaky. Even if I set a longer timeout value (e.g. from 10 sec to 60 sec), the tests may still fail.
Disabling tests is a temporal workaround to make CI healthy. Those tests should be re-enabled after getting stabilized.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we …
> issues#3320 Flaky timeout tests

- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/callback-state-with-timeouts-error-handler.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/eventWithError.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/specs/callbackResults.yaml
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/CallbackStateTimeoutsIT.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/CallbackStateWithTimeoutsErrorHandlerIT.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/EventTimedoutIT.java
Seems that either the test are executed on parallel or the same container is being reused for the same test. In both cases, the tests might fail randomly because they share the same topic. Therefore, the best approach is to  use different ones so they are fully independent.
> Using different topics

- kogito-codegen-modules/kogito-codegen-core/src/main/java/org/kie/kogito/codegen/core/io/CollectedResourceProducer.java
Fixes https://github.com/apache/incubator-kie-issues/issues/754
[Dependant Drools PR](https://github.com/apache/incubator-kie-drools/pull/5620)
Uses UTF-8 on important places during the Quarkus build. I suggest we should do a broader encoding review during next year. There are more places, like e.g. calling String.getBytes() without encoding and similar on many places. Unfortunately this is very hard to test, as the behaviour I was fixing only happens on an environment that doesn't use UTF-8, so there are no new test cases added. If you know about some option how to add such tests, please let me know and I will add them.
> [kie-issues#754] Use UTF-8 on important places during Quarkus build

- kogito-serverless-workflow/kogito-serverless-workflow-executor-python/src/test/java/org/kie/kogito/serverless/workflow/executor/PythonFluentWorkflowApplicationTest.java
Disabling test that is hanging on CI, therefore blocking the nightly builds.
> [NO ISSUE] Disable hanging test on CI.

- kogito-build/kogito-build-no-bom-parent/pom.xml
- quarkus/addons/python/integration-tests/src/test/java/org/kie/kogito/quarkus/workflows/PythonFlowIT.java
The version of maven-plugin-plugin was not compatible with Java 17. After the upgrade, the compilaton works.
> [NO ISSUE] Update maven-plugin-plugin version to fix Java 17 compilation

- api/kogito-api/src/main/java/org/kie/kogito/internal/process/runtime/KogitoNodeInstance.java
- api/kogito-api/src/main/java/org/kie/kogito/internal/process/runtime/KogitoWorkflowProcessInstance.java
- api/kogito-events-api/src/main/java/org/kie/kogito/event/process/ProcessInstanceNodeEventBody.java
- api/kogito-events-api/src/main/java/org/kie/kogito/event/process/ProcessInstanceSLAEventBody.java
- api/kogito-events-api/src/main/java/org/kie/kogito/event/process/ProcessInstanceStateEventBody.java
- api/kogito-events-api/src/main/java/org/kie/kogito/event/usertask/UserTaskInstanceStateEventBody.java
- api/kogito-events-core/src/main/java/org/kie/kogito/event/impl/ProcessInstanceEventBatch.java
- api/kogito-events-core/src/main/java/org/kie/kogito/event/job/JobInstanceDataEvent.java
- api/kogito-events-core/src/main/java/org/kie/kogito/event/process/ProcessInstanceNodeDataEvent.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessInstance.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/event/UserTaskEventImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/event/UserTaskStateEventImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/humantask/HumanTaskWorkItemDecoratorImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/NodeInstance.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/NodeInstanceImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
- kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/java/org/kie/kogito/codegen/tests/PublishEventIT.java
issue https://github.com/apache/incubator-kie-issues/issues/576
depends on https://github.com/apache/incubator-kie-drools/pull/5571
> [incubator-kie-issues-576] Data Audit apps for kogito

- quarkus/addons/python/integration-tests/src/test/java/org/kie/kogito/quarkus/workflows/PythonFlowIT.java
Closes https://github.com/apache/incubator-kie-issues/issues/806
Disabling `PythonFlowIT` it tests until we have a proper fix for the python integration in native images
<details>
<summary>
</summary> …
> incubator-kie-issues#806: Disable `PythonFlowIT` it tests.

- quarkus/addons/python/integration-tests/pom.xml
- quarkus/addons/python/integration-tests/src/test/java/org/kie/kogito/quarkus/workflows/PythonFlowIT.java
- quarkus/addons/python/runtime/src/main/resources/META-INF/native-image/jni-config.json
Fixes https://github.com/apache/incubator-kie-issues/issues/818
LD_LIBRARY_PATH should point either to graalvm_home|java_home/server/lib and some extra classes (mainly jdk ones) are needed in the jni set.
> [Fix_@818] Fixing native python test on Java 17

- .ci/jenkins/Jenkinsfile.weekly.deploy
- .ci/jenkins/dsl/jobs.groovy
- .ci/jenkins/tests/setup_pipeline_env.sh
- .github/workflows/pr-jenkins.yml
ISSUE: https://github.com/apache/incubator-kie-issues/issues/821
This PR introduces a new weekly Jenkins job for Kogito Runtimes that updates the project version to 999-YYYYMMDD-SNAPSHOT locally, build it and deploy the artifacts to Apache snapshot repository.
The weekly job also creates a new tag in the repo with this format: 999-YYYYMMDD.
> kie-issues#821: Kogito-runtimes weekly job

- api/kogito-events-core/src/main/java/org/kie/kogito/event/impl/ProcessInstanceEventBatch.java
Fixes https://github.com/apache/incubator-kie-kogito-runtimes/issues/3384
> [Fix_#3384] Including business key on process instance state event

- quarkus/addons/events/process/runtime/src/main/java/org/kie/kogito/events/config/EventsRuntimeConfig.java
- quarkus/addons/events/process/runtime/src/main/java/org/kie/kogito/events/process/ReactiveMessagingEventPublisher.java
The new configurable properties are 
```
kogito.events.processinstances.errors.propagate
kogito.events.processdefinitions.errors.propagate
kogito.events.usertasks.errors.propagate
```
Default value is false, so exception wont be propaged unless explicitly indicated
I manually tested that when 
`kogito.events.processdefinitions.errors.propagate=true`
and 
`mp.messaging.outgoing.kogito-processdefinitions-events.connector=quarkus-http`
if there is not data-index, quarkus wont start. 
```
2024-01-30 19:11:39,813 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile [dev]): java.lang.RuntimeException: Failed to start quarkus
at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
at io.quarkus.runtime.Application.start(Application.java:101)
at …
```
> [Fix_#3366] Configuring exception propagation for event publishing

- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/assembler/DuplicateProcess.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/ProcessLoadError.java
- kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/QueryGenerator.java
Backport of #3346
@gitgabrio @baldimir 
**referenced Pull Requests**:  https://github.com/apache/incubator-kie-kogito-runtimes/pull/3379
<details>
<summary>
</summary> …
> [1.40.x] [incubator-kie-issues#814] Fix NPE on BaseKnowledgeBuilderResultImpl hashCode()

- kogito-codegen-modules/kogito-codegen-core/src/main/resources/class-templates/config/GlobalObjectMapperQuarkusTemplate.java
- quarkus/addons/messaging/common/src/main/java/org/kie/kogito/addon/quarkus/messaging/common/AbstractQuarkusCloudEventEmitter.java
- quarkus/addons/messaging/deployment/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/deployment/ChannelInfo.java
- quarkus/addons/messaging/deployment/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/deployment/ChannelMappingStrategy.java
- quarkus/addons/messaging/deployment/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/deployment/CloudEventMode.java
Knative has issues with structure event, so we are switching to binary, by defaullt, for quarkus-http connector. 
This behaviour can be modified through configuration. 
Users can specifiy
`kogito.addon.messaging.outgoing.cloudEventMode.<channelName>=BINARY|STRUCTURED`
to configure cloud event mode per outgoing channel 
or just 
`kogito.addon.messaging.outgoing.cloudEventMode=BINARY|STRUCTURED`
to set it overrall. 
If nothing specified, binary is used for quarkus-http connector and structured for the others, to keep backward compatibility with existing examples using Kafka. 
This requires changes on kogito-apps tests https://github.com/apache/incubator-kie-kogito-apps/pull/1974 and examples https://github.com/apache/incubator-kie-kogito-examples/pull/1862
Fixes …
> [Fix_3383] Adding binary cloud event support for outgoing messages

- quarkus/addons/common/reactive-messaging/src/main/java/org/kie/kogito/addon/quarkus/common/reactive/messaging/http/CloudEventHttpOutgoingDecorator.java
CloudEvent+json content type should be used only in structured mode
Merge with https://github.com/apache/incubator-kie-kogito-examples/pull/1864
> Fixing ce content type when using binary

- jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/AbstractNodeHandler.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/WorkItemNodeVisitor.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/DefaultProcessInstanceManager.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/actions/HandleMessageAction.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/actions/SignalProcessInstanceAction.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/humantask/HumanTaskHelper.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/util/UUIDGenerator.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/impl/DataDefinition.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/CompositeNodeInstance.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/DynamicUtils.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/TimerNodeInstance.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/WorkItemNodeInstance.java
- jbpm/jbpm-flow/src/test/java/org/kie/kogito/process/impl/DefaultProcessInstanceManagerTest.java
- jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/serialization/process/impl/ProtobufProcessInstanceReader.java
- kogito-build/kogito-build-no-bom-parent/pom.xml
This PR replaces occurences of UUID.randomUUID with a generated UUID with a deterministic seed. That means, each sequence of generated random UUIDs are reproducible.
> [kie-issues#843] Replace random UUID generator with a deterministic random one.

- api/kogito-api/src/main/java/org/kie/kogito/internal/utils/KogitoTags.java
- api/kogito-events-core/src/main/java/org/kie/kogito/event/impl/ProcessInstanceEventBatch.java
- jbpm/jbpm-bpmn2/src/main/java/org/kie/kogito/process/bpmn2/BpmnVariables.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/AbstractVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ModelMetaData.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/VariableDeclarations.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/context/variable/Variable.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/context/variable/VariableScope.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/ForEachNodeFactory.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java
Fixes https://github.com/apache/incubator-kie-kogito-runtimes/issues/3406
> [Fix #3406] Avoid publishing internal variables

- kogito-build/kogito-dependencies-bom/pom.xml
Tracker: https://github.com/apache/incubator-kie-issues/issues/913
Aligns with Quarkus 3.2.10.Final and the dependency upgrades in the new release.
> [kie-issues#913] Upgrade to and align with 3.2.10.Final Quarkus LTS release.

- jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/canonical/ActivityGenerationModelTest.java
- jbpm/jbpm-bpmn2/src/test/resources/BPMN2-UserTask.bpmn2
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/UserTaskModelMetaData.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/context/variable/Variable.java
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3415
The older regular expression check does not longer makes sense, It prevents variables in user task model generated classes to be assigned to constant values.
> [Fix #3415] Allow constant values in user task assignments

- api/kogito-api/src/main/java/org/kie/kogito/internal/process/event/KogitoProcessEventSupport.java
- api/kogito-api/src/main/java/org/kie/kogito/uow/events/UnitOfWorkProcessEventListener.java
- api/kogito-events-core/src/main/java/org/kie/kogito/event/impl/ProcessInstanceEventBatch.java
- api/kogito-events-core/src/test/java/org/kie/kogito/event/impl/ProcessInstanceEventBatchTest.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/event/AbstractProcessNodeEvent.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/event/ErrorEventImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/event/KogitoProcessEventSupportImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/event/KogitoProcessNodeLeftEventImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/event/KogitoProcessNodeTriggeredEventImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/event/MessageEventImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
Fixes https://github.com/apache/incubator-kie-issues/issues/987
Ensure that starting event is the first one and complete process events is the last one
Unlink error event from state event so, if there is an error is published always and not only if it happens in the sync part of the process. 
Merge with https://github.com/apache/incubator-kie-drools/pull/5766 and https://github.com/apache/incubator-kie-kogito-apps/pull/2011
> [Fix apache/incubator-kie-issues#987] New onError event

- api/kogito-api/src/main/java/org/kie/kogito/uow/events/UnitOfWorkProcessEventListener.java
- kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/java/org/kie/kogito/codegen/tests/PublishEventIT.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/WorkflowEventIT.java
- quarkus/integration-tests/integration-tests-quarkus-decisions/src/test/java/org/kie/kogito/integrationtests/quarkus/OASIT.java
Fixing IT tests that fails after change
> [Fix apache/incubator-kie-issues#987] Fix nightly

- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/TimeoutsConfigResolver.java
- quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java
- quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/test/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessorTest.java
Closes: #3388 
<details>
<summary>
</summary> …
> kie-kogito-runtimes-3388: Improve serverless workflows timeouts duration validation message

- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/NodeInstanceContainer.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/RetriggerIT.java
Calling getNodeInstance over containernode creates another instance, hence the previous node container instance is there when the engine checks if the process can be completed (so it does not complete it) 
Therefore, as an alternative, a existing instance with that node id is searched, if found, that is the parent container instance where to recreate the node instance to be retriggered. If not found, we call getNodeInstance over the container node.
> [Fix #3390] Process is not completed when node is retriggered (but end node is executed)

- quarkus/addons/source-files/deployment/src/main/java/org/kie/kogito/addon/source/files/deployment/KogitoAddOnSourceFilesProcessor.java
Fixes
*  apache/incubator-kie-kogito-runtimes#3438
Check if the resources folder exists before trying to walk it in source files addon.
This has started failing native builds after 
* apache/incubator-kie-issues#847
> incubator-kie-kogito-runtimes#3438: check if resources folder path exists

- addons/common/marshallers/avro/pom.xml
- addons/common/marshallers/avro/src/main/java/org/kie/kogito/event/avro/AvroIO.java
- addons/common/marshallers/avro/src/test/avro/pojo.avsc
- addons/common/marshallers/avro/src/test/java/org/kie/kogito/event/avro/AvroMarshallUnmarshallTest.java
- kogito-build/kogito-dependencies-bom/pom.xml
The issue is caused because quarkus-avro uses 1.11.1 version (for quarkus2) or 1.11.3 (for quarkus 3) of apache avro and jackson-avro uses version 1.8.4. 
When using avro generator Version > 1.9, it adds an additional field which makes jackson serializer fails. 
Configuring mapper to ignore unknown properties do the trick. 
Fixes https://github.com/apache/incubator-kie-kogito-runtimes/issues/3436
> [Fix #3436] Ignoring unknown properties

- addons/common/persistence/jdbc/src/main/java/org/kie/kogito/persistence/jdbc/GenericRepository.java
- addons/common/persistence/jdbc/src/main/java/org/kie/kogito/persistence/jdbc/JDBCProcessInstances.java
- addons/common/persistence/jdbc/src/main/java/org/kie/kogito/persistence/jdbc/Repository.java
- addons/common/persistence/jdbc/src/main/resources/db/ansi/V10.0.0__add_business_key_ansi.sql
- addons/common/persistence/jdbc/src/main/resources/db/postgresql/V10.0.0__add_business_key_PostgreSQL.sql
- addons/common/persistence/jdbc/src/test/java/org/kie/persistence/jdbc/AbstractProcessInstancesIT.java
- api/kogito-api/src/main/java/org/kie/kogito/process/ProcessInstances.java
A new mapping table has been added. 
Test already existed for business key in serverless workflow extension.
Fixes https://github.com/apache/incubator-kie-kogito-runtimes/issues/3413
> [Fix_#3413] Speed up businesskey query performance

- quarkus/addons/events/process/runtime/src/main/java/org/kie/kogito/events/process/ReactiveMessagingEventPublisher.java
Fixes https://github.com/apache/incubator-kie-kogito-runtimes/issues/3453
Unfortunately OnOverflow annotation requires contant value, so this cannot be make configurable without code generation. Therefore I just changed overflow strategy to unbounded.
> [Fix #3453] Setting overflow strategy to unbounded for process events

- jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/feel/FeelProcessValidator.java
- jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/SplitHandler.java
- jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/XmlBPMNProcessDumper.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/ProcessBuilderImpl.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/SplitNodeVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/StateNodeVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/process/builder/MultiConditionalSequenceFlowNodeBuilder.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/process/builder/SplitNodeBuilder.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/validation/RuleFlowProcessValidator.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/impl/NodeImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/node/Split.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/node/StateNode.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/NodeInstanceImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/SplitInstance.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateNodeInstance.java
- kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/java/org/kie/kogito/codegen/process/ProcessGenerationIT.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/ServerlessWorkflowParsingTest.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/WorkflowTestUtils.java
- kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/test/java/org/kie/kogito/serverless/workflow/executor/StaticWorkflowApplicationTest.java
- kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/test/resources/switch.yaml
Fixes https://github.com/apache/incubator-kie-kogito-runtimes/issues/3456
The engine was not ready to support multiple constraints over the same connection. That makes sense for BPMN, but it is not necesarily true for SWF, as shown by the example in the issue.
Therefore, it has been changed to support both  (BPMN constraint will be size one)
> [Fix #3456]Support multiple constraint over same connection

- addons/common/rest-exception-handler/src/main/java/org/kie/kogito/resource/exceptions/BaseExceptionsHandler.java
- quarkus/addons/knative/serving/integration-tests/src/test/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/it/KnativeServingAddonIT.java
Fixes https://github.com/apache/incubator-kie-kogito-runtimes/issues/3460
> [Fix #3460] Fix ClassCastException on Exception mapping

- kogito-build/kogito-dependencies-bom/pom.xml
- springboot/bom/pom.xml
- springboot/integration-tests/src/it/integration-tests-springboot-processes-it/src/test/java/org/kie/kogito/integrationtests/springboot/LinkTest.java
- springboot/integration-tests/src/it/integration-tests-springboot-processes-it/src/test/java/org/kie/kogito/integrationtests/springboot/ManagementAddOnTest.java
- springboot/integration-tests/src/it/integration-tests-springboot-processes-it/src/test/java/org/kie/kogito/integrationtests/springboot/MonitoringTest.java
- springboot/integration-tests/src/it/integration-tests-springboot-processes-it/src/test/java/org/kie/kogito/integrationtests/springboot/ProcessSvgAddonTest.java
- springboot/integration-tests/src/it/integration-tests-springboot-processes-it/src/test/java/org/kie/kogito/integrationtests/springboot/SignalProcessTest.java
- springboot/starters/pom.xml
This is a PR to upgrade Spring Boot to version 3.2.4.
kie-issue: https://github.com/apache/incubator-kie-issues/issues/995
Related kogito-examples PR: https://github.com/apache/incubator-kie-kogito-examples/pull/1903
Related optaplanner PR: https://github.com/apache/incubator-kie-optaplanner/pull/3074
Related optaplanner-quickstarts PR: https://github.com/apache/incubator-kie-optaplanner-quickstarts/pull/628
> [kie-issues#995] Upgrade Spring Boot to 3.2.4

- NOTICE
This is a non-code related commit to clarify the copyright information. The content of the file comes from https://github.com/apache/incubator-kie-kogito-apps/blob/main/NOTIC
> chor: add copyright information, the same one used in incubator-kie-kogito-apps

- addons/common/monitoring/core/src/main/java/org/kie/kogito/monitoring/core/common/process/MetricsProcessEventListener.java
- api/kogito-api/src/main/java/org/kie/kogito/internal/utils/KogitoTags.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java
Fixes https://github.com/apache/incubator-kie-kogito-runtimes/issues/3483
Add "kogito_node_instance_duration_milliseconds" distribution summary. 
Different to the other two summaries, times are collected in milliseconds rather than seconds
> [Fix #3483] Adding state duration summary

- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/CodegenNodeInstanceFactoryRegistry.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/NodeInstanceFactoryProvider.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/NodeInstanceFactoryRegistry.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/factory/AbstractNodeInstanceFactory.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/factory/DefaultNodeInstanceFactory.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/factory/DefaultNodeInstanceFactoryProvider.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/factory/SingletonNodeInstanceFactory.java
- jbpm/jbpm-flow/src/main/resources/META-INF/services/org.jbpm.workflow.instance.impl.NodeInstanceFactoryProvider
Closes: https://github.com/apache/incubator-kie-issues/issues/1108
> [incubator-kie-issues-1108] Add capability to create node instances (node states) from the nodes

- addons/common/persistence/jdbc/src/main/java/org/kie/kogito/persistence/jdbc/correlation/JDBCCorrelationRepository.java
- addons/common/persistence/jdbc/src/main/java/org/kie/kogito/persistence/jdbc/correlation/JDBCCorrelationService.java
- addons/common/persistence/jdbc/src/main/resources/db/ansi/V1.35.0__create_runtime_ansi.sql
- addons/common/persistence/jdbc/src/main/resources/db/ansi/V10.0.1__create_correlation_ansi.sql
- addons/common/persistence/jdbc/src/main/resources/db/postgresql/V10.0.1__alter_correlation_PostgreSQL.sql
- addons/common/persistence/jdbc/src/test/java/org/kie/persistence/jdbc/correlation/JDBCCorrelationServiceIT.java
- quarkus/addons/persistence/jdbc/runtime/src/main/java/org/kie/kogito/persistence/quarkus/JDBCorrelationServiceProducer.java
Fixes https://github.com/apache/incubator-kie-kogito-runtimes/issues/3480
> [Fix #3480] Changing jsonb to varchar

- kogito-bom/pom.xml
- kogito-serverless-workflow/kogito-serverless-workflow-monitoring/pom.xml
- kogito-serverless-workflow/kogito-serverless-workflow-monitoring/src/main/java/org/kie/kogito/serverless/workflow/monitoring/SonataFlowMetricProcessEventListener.java
- kogito-serverless-workflow/kogito-serverless-workflow-monitoring/src/test/java/org/kie/kogito/serverless/workflow/monitoring/SonataFlowMetricProcessEventListenerTest.java
- kogito-serverless-workflow/pom.xml
- quarkus/addons/monitoring/sonataflow/pom.xml
- quarkus/addons/monitoring/sonataflow/src/main/java/org/kie/sonataflow/monitoring/SonataFlowMetricEventListenerFactory.java
- quarkus/addons/monitoring/sonataflow/src/main/resources/META-INF/beans.xml
- quarkus/addons/monitoring/sonataflow/src/main/resources/application.properties
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3486
Name of the new counters is` sonataflow_input_parameters_counter`
Array input parameters will be stored by default as json strings 
This can be changed by setting `kie.monitoring.sonataflow.arrays.store` property value to `MULTI_PARAM`, in which case arrays will be stored individually with keys of the forms `arrray_key_name[array_item_number]`
Lets illustrate that with an example
If input is
```
{
"numbers": [
{
"x": 12321,
"y": 3
},
{
"x": 18,
"y": 3232323
}
]
}
```
by default it will be stored as
`"param_name":"numbers","param_value":"[{\"x\":12321,\"y\":3},{\"x\":18,\"y\":3232323}]"`
But if application.properties contains 
`kie.monitoring.sonataflow.arrays.store=MULTI_PARAM`
There will be four entries added to the …
> [Fix #3486] Add input param counter

- jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/GlobalHandler.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/AbstractNodeVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/AbstractVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/process/builder/action/ActionCompiler.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/process/builder/action/ActionCompilerRegistry.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/process/builder/action/JavaActionCompiler.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/process/builder/action/MVELActionCompiler.java
- jbpm/jbpm-flow-builder/src/main/resources/META-INF/services/org.jbpm.process.builder.action.ActionCompiler
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/AbstractCompositeNodeFactory.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/ExtendedNodeFactory.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/NodeFactory.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/validation/RuleFlowProcessValidator.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/impl/ExtendedNodeImpl.java
- jbpm/jbpm-flow/src/test/java/org/jbpm/ruleflow/core/validation/RuleFlowProcessValidatorTest.java
- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/ActivityTest.java
- jbpm/jbpm-tests/src/test/java/org/jbpm/test/utils/EventTrackerProcessListener.java
- jbpm/jbpm-tests/src/test/java/org/jbpm/test/utils/ProcessTestHelper.java
- jbpm/jbpm-tools/jbpm-tools-maven-plugin/src/test/resources/unit/project/src/main/bpmn/BPMN2-SubProcessWithEntryExitScripts.bpmn2
Closes: https://github.com/apache/incubator-kie-issues/issues/1136
> [incubator-kie-issues-1136] Add script onEntry, on Exit for java

- .ci/jenkins/Jenkinsfile.promote
Part of:
* apache/incubator-kie-issues#776
Other related PRs:
* apache/incubator-kie-kogito-pipelines#1194
* apache/incubator-kie-benchmarks#286
* apache/incubator-kie-docs#4536
* apache/incubator-kie-kogito-runtimes#3501
* apache/incubator-kie-kogito-apps#2047
* apache/incubator-kie-kogito-examples#1914
* apache/incubator-kie-kogito-docs#626
* apache/incubator-kie-drools#5927
* apache/incubator-kie-optaplanner#3083
* apache/incubator-kie-kogito-serverless-operator#462
Replacing old approach to merge PRs:  merge locally + push into remote
New behavior relies on gh cli directly to approve and merge PR.
> kie-issues#776: automate PR merge into protected branches

- kogito-build/kogito-dependencies-bom/pom.xml
Related https://github.com/apache/incubator-kie-issues/issues/1199
> CVE-2024-30171, CVE-2024-30172, CVE-2024-29857: bc*-jdk18on upgrade.

- kogito-build/kogito-dependencies-bom/pom.xml
Related https://github.com/apache/incubator-kie-issues/issues/1202
> Upgrading SpringBoot 3.2.5 to address CVE-2024-22262 found on spring-web.

- .ci/jenkins/Jenkinsfile.setup-branch
Part of
* apache/incubator-kie-issues#1237
Adjusts the snapshot version changes to happen only in new branch when branching, not in main.
Ensemble:
* apache/incubator-kie-kogito-pipelines#1201
* apache/incubator-kie-drools#5967
* apache/incubator-kie-optaplanner#3089
* apache/incubator-kie-kogito-runtimes#3527
* apache/incubator-kie-kogito-apps#2059
* apache/incubator-kie-kogito-examples#1925
* apache/incubator-kie-optaplanner-quickstarts#630
> kie-issues#1237: stay on x.y.999-SNAPSHOT in release branches

- .ci/jenkins/Jenkinsfile.deploy
- kogito-build/kogito-build-no-bom-parent/pom.xml
- pom.xml
- Adds gpg setup and apache-release Maven profile to the release build.
- Fixes javadoc build on JDK 17.
> [NO-ISSUE] Use apache-release profile when doing a release build

- kogito-bom/pom.xml
- quarkus/addons/pom.xml
This is a follow-up on https://github.com/apache/incubator-kie-kogito-runtimes/pull/3531. In the current state, the build fails on: 
```
[ERROR] Deployment artifact org.kie:kie-addons-quarkus-tracing-decision-deployment::jar was found to be missing dependencies on the Quarkus extension artifacts marked with '-' below:
[ERROR] -     org.kie:kie-addons-quarkus-tracing-decision::jar
[ERROR] -     io.quarkus:quarkus-resteasy-jackson-deployment::jar
[ERROR] -         io.quarkus:quarkus-resteasy-deployment::jar
[ERROR] -             io.quarkus:quarkus-vertx-http-deployment::jar
[ERROR] -             io.quarkus:quarkus-resteasy-server-common-deployment::jar
[ERROR] -                 io.quarkus:quarkus-resteasy-common-deployment::jar
[ERROR] -         io.quarkus:quarkus-jackson-deployment::jar …
```
> [disabling_tracing-decision_module] Removing tracing-decision module from maven reactor

- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/AbstractVisitor.java
- jbpm/jbpm-flow-builder/src/test/java/org/jbpm/compiler/canonical/ProcessToExecModelGeneratorTest.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowNodeContainerFactory.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowProcessFactory.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/AbstractCompositeNodeFactory.java
- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/VariableTagsTest.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/ServerlessWorkflowCodestartTest.java
Closes: https://github.com/apache/incubator-kie-issues/issues/1195
> [incubator-kie-issues-1195] Process Variable support multiple metadata fields

- quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java
- quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/resources/application.properties
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3546. This is an issue in native build consequence of the refactor done by https://github.com/apache/incubator-kie-kogito-runtimes/pull/3482
I think including the service loader classes should be enough for native compiler to realize it should include all node classes, but @domhanak please let us know if the issue is fixed by this change
> [Fix_#3546] NodeInstanceFactoryProvided not included in native build

- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/ActivityTest.java
In addition to previous changes associated with PR's #3516
& #3519
Migrated some BPMN processes which are being compiled using legacy v7 to code generation approach, using new branch incubator-kie-issues-1131-2
Issue: https://github.com/apache/incubator-kie-issues/issues/1131
> [incubator-kie-issues-1131] Process test migration from v7 legacy runtime to code generation - 2

- jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/AdHocSubProcessHandler.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/DynamicNodeVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/builtin/JavaConstraintEvaluatorBuilder.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/node/DynamicNodeVisitorBuilder.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/DynamicNodeFactory.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/node/DynamicNode.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/NodeInstanceContainer.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/DynamicNodeInstance.java
- jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java
- jbpm/jbpm-flow/src/test/java/org/kie/kogito/process/impl/AbstractProcessInstanceTest.java
- jbpm/jbpm-tests/src/test/bpmn/org/jbpm/bpmn2/adhoc/BPMN2-AdHocSubProcessAutoComplete.bpmn2
- jbpm/jbpm-tests/src/test/bpmn/org/jbpm/bpmn2/adhoc/BPMN2-AdHocSubProcessAutoCompleteExpression.bpmn2
- jbpm/jbpm-tests/src/test/bpmn/org/jbpm/bpmn2/adhoc/BPMN2-AdHocSubProcessEmptyCompleteExpression.bpmn2
- jbpm/jbpm-tests/src/test/bpmn/org/jbpm/bpmn2/adhoc/BPMN2-AdHocTerminateEndEvent.bpmn2
- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/ActivityTest.java
- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/StandaloneBPMNProcessTest.java
- kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/resources/cases/CaseWithTwoStages.bpmn2
- kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/resources/cases/CaseWithTwoStagesConditions.bpmn2
- kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/resources/cases/EmptyCaseStage.bpmn2
- kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/resources/cases/NoStartNodeCaseWithBoundaryTimerStage.bpmn2
- kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/resources/cases/stage/activation/NoStartNodeAdhocCaseWithActivationCondition.bpmn2
- kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/resources/cases/stage/activation/NoStartNodeAdhocCaseWithActivationConditionNoTerminate.bpmn2
- kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/resources/cases/stage/completion/StageWithTaskCaseDataBoolean.bpmn2
- kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/resources/cases/stage/completion/StageWithTaskCaseDataInteger.bpmn2
- kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/resources/cases/stage/completion/StageWithTaskCaseDataString.bpmn2
Closes: https://github.com/apache/incubator-kie-issues/issues/1286
> [incubator-kie-issues-1286] Adhoc functionality missing in kogito jBPM engine

- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/ActivityTest.java
In addition to previous changes associated with PRhttps://github.com/apache/incubator-kie-kogito-runtimes/pull/3520
Migrated some BPMN processes which are being compiled using legacy v7 to code generation approach, using new branch incubator-kie-issues-1131-4
Closes: https://github.com/apache/incubator-kie-issues/issues/1131
> [incubator-kie-issues-1131] test migration from V7 to code generation-4

- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/ActivityTest.java
In local env this takes more that 2s. It is possible that in CI, it takes more than 10 (several PRs are failing in this test consistently)
For some reason I cannot include @Abhitocode in the list of reviewers
> Increase timeout in flaky test

- .ci/jenkins/Jenkinsfile.deploy
Part of: https://github.com/apache/incubator-kie-issues/issues/1387
> kie-issues#1387: Adjust pipelines to use the gpg key provided by Apache to sign the artifacts

- kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/context/KogitoApplicationPropertyProvider.java
- kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/context/impl/AbstractKogitoBuildContext.java
- kogito-codegen-modules/kogito-codegen-core/src/main/java/org/kie/kogito/codegen/core/ApplicationGenerator.java
- kogito-codegen-modules/kogito-codegen-core/src/test/java/org/kie/kogito/codegen/core/ApplicationGeneratorTest.java
- quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoQuarkusApplicationPropertiesProvider.java
Fixes https://github.com/apache/incubator-kie-issues/issues/1373
Depends on https://github.com/apache/incubator-kie-drools/pull/6008
@bncriju
<details>
<summary>
</summary> …
> [incubator-kie-issues#1373] Fixing rest generation config.

- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/ActivityTest.java
migrated some BPMN processes which are being compiled using legacy v7 to code generation approach, using new branch incubator-kie-issues-1131-5
> [incubator-kie-issues-1131] test migration from V7 to code generation-5

- kogito-serverless-workflow/kogito-serverless-workflow-openapi-common/src/main/java/org/kie/kogito/serverless/workflow/operationid/SpecWorkflowOperationIdFactory.java
- springboot/integration-tests/pom.xml
If common-openapi jar is modified, reproducilbe will always fail no matter the nature of the change.
The PR makes a dummy modification on common-openapi, which makes reprodubile to fail on CI, and change the pom for  springboot integration test in order to avoid that failure.
> Fix Springboot IT test reproducible failing when code is modified for build time only modules

- .ci/jenkins/Jenkinsfile.deploy
Part of: https://github.com/apache/incubator-kie-issues/issues/1397
> kie-issues#1397 - Adjust git tag creation for Apache 10 release 

- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/EscalationEventTest.java
Migrated tests within EscalationEventTest.Java
The test can be identified by referring to EscalationEventTest.java:
https://github.com/apache/incubator-kie-kogito-runtimes/blob/main/jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/EscalationEventTest.java
> [incubator-kie-issues-1131] test migration from V7 to code generation-13

- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/StandaloneBPMNProcessTest.java
Migrated tests within StandaloneBPMNProcessTest.java
The test can be identified by referring to StandaloneBPMNProcessTest.java:
https://github.com/apache/incubator-kie-kogito-runtimes/blob/main/jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/StandaloneBPMNProcessTest.java
**Note**: will resolve conflicts once reviewed for any changes.
> [incubator-kie-issues-1131] test migration from V7 to code generation-11

- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/DataTest.java
Migrated tests within DataTest.Java
The test can be identified by referring to DataTest.java:
https://github.com/apache/incubator-kie-kogito-runtimes/blob/main/jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/DataTest.java
**Note**: will resolve conflicts once reviewed for any changes.
> [incubator-kie-issues-1131] test migration from V7 to code generation-10

- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/EndEventTest.java
Migrated tests within EndEventTest.Java
The test can be identified by referring to EndEventTest.java:
https://github.com/apache/incubator-kie-kogito-runtimes/blob/main/jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/EndEventTest.java
> [incubator-kie-issues-1131] test migration from V7 to code generation-9

- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/CompensationTest.java
Migrated tests within  CompensationTest.Java
The test can be identified by referring to CompensationTest.java:
https://github.com/apache/incubator-kie-kogito-runtimes/blob/main/jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/CompensationTest.java
> [incubator-kie-issues-1131] test migration from V7 to code generation-8

- .ci/jenkins/Jenkinsfile.deploy
The release.grovvy file has been renamed to releaseUtils.groovy on [ jenkins-pipeline-shared-libraries](https://github.com/apache/incubator-kie-kogito-pipelines/tree/10.0.x/jenkins-pipeline-shared-libraries/vars). 
This PR updates the deploy job to use the new name.
> [10.0.x] NO-ISSUE: Update release utils file

- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/VariableTagsTest.java
Migrated tests within VariableTagsTest.java
The test can be identified by referring to VariableTagsTest.java:
https://github.com/apache/incubator-kie-kogito-runtimes/blob/main/jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/VariableTagsTest.java
> [incubator-kie-issues-1131] test migration from V7 to code generation-17

- drools/kogito-pmml-dependencies/pom.xml
Fixes https://github.com/apache/incubator-kie-issues/issues/1441
pmml-drools implementations should be excluded from pmml dependencies.
This is a first step, but further analysis/refactoring is required
This is needed by 
<details>
<summary>
</summary>
[build-chain …
> [incubator-kie-issues#1441] Clean kogito-pmml-dependencies

- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/json/JsonSchemaGenerator.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/json/JsonUtils.java
- kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/json/JsonUtilsTest.java
- kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/test/java/org/kie/kogito/serverless/workflow/executor/StaticFluentWorkflowApplicationTest.java
- kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/test/java/org/kie/kogito/serverless/workflow/executor/StaticWorkflowApplicationTest.java
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/MergeAction.java
- kogito-workitems/kogito-jackson-utils/src/main/java/org/kie/kogito/jackson/utils/MergeUtils.java
- kogito-workitems/kogito-jackson-utils/src/test/java/org/kie/kogito/jackson/utils/MergeUtilsTest.java
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3629
> [Fix_#3629] Set merge result to array or non object

- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/ActivityTest.java
Migrated two tests within ActivityTest.java
testMinimalProcessMetaData
testSubProcess
Issue: https://github.com/apache/incubator-kie-issues/issues/1131
> [incubator-kie-issues-1131] v7 migration to code generation-32

- jbpm/jbpm-tests/src/test/bpmn/org/jbpm/bpmn2/feel/BPMN2-GatewayFEEL.bpmn2
- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/FEELTest.java
Migrated tests within FeelTest.java
The test can be identified by referring to FeelTest.java:
https://github.com/apache/incubator-kie-kogito-runtimes/blob/main/jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/FeelTest.java
**NOTE**: This PR still contains issues, will update and push once resolved.
> [incubator-kie-issues-1131] test migration from V7 to code generation-19

- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/FlowTest.java
Migrated tests within FlowTest.java
The test can be identified by referring to FlowTest.java:
https://github.com/apache/incubator-kie-kogito-runtimes/blob/main/jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/FlowTest.java
> [incubator-kie-issues-1131] test migration from V7 to code generation-20

- springboot/integration-tests/integration-tests-springboot-decisions-it/pom.xml
- springboot/integration-tests/integration-tests-springboot-kafka-it/pom.xml
- springboot/integration-tests/integration-tests-springboot-norest-it/pom.xml
- springboot/integration-tests/integration-tests-springboot-processes-it/pom.xml
- springboot/integration-tests/integration-tests-springboot-processes-persistence-it/integration-tests-springboot-processes-filesystem/pom.xml
- springboot/integration-tests/integration-tests-springboot-processes-persistence-it/integration-tests-springboot-processes-infinispan/pom.xml
- springboot/integration-tests/integration-tests-springboot-processes-persistence-it/integration-tests-springboot-processes-jdbc/pom.xml
- springboot/integration-tests/integration-tests-springboot-processes-persistence-it/integration-tests-springboot-processes-mongodb/pom.xml
- springboot/integration-tests/integration-tests-springboot-processes-persistence-it/integration-tests-springboot-processes-postgresql/pom.xml
- springboot/integration-tests/integration-tests-springboot-processes-persistence-it/pom.xml
Fixes https://github.com/apache/incubator-kie-issues/issues/1462
This PR refactor the spring boot integration tests poms to avoid usage of extensions flag, redefining the lifecicle in the poms themselves.
To exactly recreate the same steps, some hack has been used
1. multiple declaration of same plugins (maven-compile-plugin and kogito-maven-plugin)
2. mapping of plugin to "wrong" phases (process-resources)
The execution order can be viewed/compared using
`mvn fr.jcgay.maven.plugins:buildplan-maven-plugin:list`
Thanks to @elguardian for pom modification suggestion
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any …
> [incubator-kie-issues#1462] Refactoring springboot integration tests configuration to avoid usage of extensions flag

- kogito-codegen-modules/kogito-codegen-predictions/src/test/java/org/kie/kogito/codegen/prediction/PredictionCodegenGenerateTest.java
- kogito-codegen-modules/kogito-codegen-predictions/src/test/java/org/kie/kogito/codegen/prediction/PredictionCodegenInternalGenerateTest.java
Fixes https://github.com/apache/incubator-kie-kogito-runtimes/issues/3640
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories …
> [incubator-kie-kogito-runtimes#3640] Fix and restore PredictionCodegen-related tests

- api/kogito-api/src/main/java/org/kie/kogito/source/files/SourceFile.java
- api/kogito-api/src/test/java/org/kie/kogito/source/files/SourceFileTest.java
Closes/Fixes/Resolves https://github.com/apache/incubator-kie-issues/issues/1468
In a Windows machine, a nested resource will have a Windows path with backslash (`\`). The `getResourceAsStream` only supports Posix paths (`/`). This PR adds a `toPosixPath` method which transform Windows paths to Posix paths, and it keeps Posix paths unchanged.
Manually tested in Windows, WSL and macOS.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect …
> [incubator-kie-issues-1468] Starting a project in development mode in Windows will fail if it has nested resources

- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/SLAComplianceTest.java
Migrated tests within SLAComplianceTest.java
The test can be identified by referring to SLAComplianceTest.java:
https://github.com/apache/incubator-kie-kogito-runtimes/blob/main/jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/SLAComplianceTest.java
> [incubator-kie-issues-1131] test migration from V7 to code generation-18

- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/DataTest.java
All testdataOutput tests within DataTest.java misses assert statement that actually evaluates the functionality. Add the assert statements and verify.
Tests can be identified by referring to:
https://github.com/apache/incubator-kie-kogito-runtimes/blob/main/jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/DataTest.java#L389
> [incubator-kie-issues-1131] Improve DataOutput tests within DataTest.Java adding assert statement

- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
Migrated tests within IntermediateEventTest.java
The test can be identified by referring to IntermediateEventTest.java:
https://github.com/apache/incubator-kie-kogito-runtimes/blob/main/jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
> [incubator-kie-issues-1131] test migration from V7 to code generation-14

- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/StandaloneBPMNProcessTest.java
Migrated tests within StandaloneBPMNProcessTest.java- 2
The test can be identified by referring to StandaloneBPMNProcessTest.java:
https://github.com/apache/incubator-kie-kogito-runtimes/blob/main/jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/StandaloneBPMNProcessTest.java
> [incubator-kie-issues-1131] test migration from V7 to code generation-30

- kogito-build/kogito-dependencies-bom/pom.xml
**Description:** Bump quarkus-embedded-postgresql to 3.8.6 (latest Quarkus LTS)
> Bump version.io.quarkiverse.embedded.postgresql to 0.2.3

- jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/rule/RuleFlowGroupRuleTypeEngineImpl.java
- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/ActivityTest.java
Closes https://github.com/apache/incubator-kie-issues/issues/1491
> Dispose KieSession after rules execution when using ruleFlowGroup

- addons/common/rest-exception-handler/src/main/java/org/kie/kogito/resource/exceptions/BaseExceptionsHandler.java
- api/kogito-api/src/main/java/org/kie/kogito/internal/process/runtime/MessageException.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/MessageException.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/ErrorExpressionAction.java
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3677
Merge with https://github.com/apache/incubator-kie-kogito-examples/pull/2015
> [Fix #3677] Removing exception type from error message

- kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/Generator.java
- kogito-codegen-modules/kogito-codegen-core/src/main/java/org/kie/kogito/codegen/core/GeneratorConfig.java
- kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/persistence/PersistenceGenerator.java
- kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/config/NamedRuleUnitConfig.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/operationid/WorkflowOperationIdFactoryProvider.java
- quarkus/addons/dynamic/integration-tests/pom.xml
- quarkus/extensions/kogito-quarkus-workflow-extension-common/kogito-quarkus-workflow-common/src/main/java/org/kie/kogito/quarkus/workflow/KogitoBeanProducer.java
Fixes https://github.com/apache/incubator-kie-issues/issues/1500
Related PR:
https://github.com/apache/incubator-kie-drools/pull/6107
<details>
<summary>
</summary> …
> [incubator-kie-issues#1500] Add javadoc to kogito properties

- .ci/jenkins/Jenkinsfile.deploy
- jbpm/pom.xml
- springboot/pom.xml
Fixes https://github.com/apache/incubator-kie-issues/issues/1504
<details>
<summary>
</summary> …
> [incubator-kie-issues#1504] Conditionally build all or only reproducible modules based on only.reproducible flag

- api/kogito-events-core/src/main/java/org/kie/kogito/event/AbstractDataEvent.java
- api/kogito-events-core/src/main/java/org/kie/kogito/event/process/MultipleProcessInstanceDataEvent.java
- api/kogito-events-core/src/main/java/org/kie/kogito/event/process/ProcessInstanceDataEvent.java
- api/kogito-events-core/src/main/java/org/kie/kogito/event/usertask/MultipleUserTaskInstanceDataEvent.java
- api/kogito-events-core/src/main/java/org/kie/kogito/event/usertask/UserTaskInstanceDataEvent.java
- kogito-build/kogito-dependencies-bom/pom.xml
- quarkus/addons/events/process/runtime/pom.xml
- quarkus/addons/events/process/runtime/src/main/java/org/kie/kogito/events/process/AbstractMessagingEventPublisher.java
- quarkus/addons/events/process/runtime/src/main/java/org/kie/kogito/events/process/GroupingMessagingEventPublisher.java
- quarkus/addons/events/process/runtime/src/test/java/org/kie/kogito/events/process/GroupingMessagingEventPublisherTest.java
Fix https://github.com/apache/incubator-kie-issues/issues/1457
Merge with https://github.com/apache/incubator-kie-kogito-examples/pull/2017 and https://github.com/apache/incubator-kie-kogito-apps/pull/2093
> [incubator-kie-issues#1457] Allow grouping of events

- kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqExpression.java
- kogito-serverless-workflow/kogito-jsonpath-expression/src/main/java/org/kie/kogito/expr/jsonpath/JsonPathExpression.java
- kogito-serverless-workflow/kogito-jsonpath-expression/src/main/java/org/kie/kogito/expr/jsonpath/WorkflowJacksonJsonNodeJsonProvider.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/test/java/org/kie/kogito/serverless/workflow/executor/StaticFluentWorkflowApplicationTest.java
- kogito-serverless-workflow/kogito-serverless-workflow-utils/src/main/java/org/kie/kogito/serverless/workflow/utils/VariablesHelper.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/forEachCustomType.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/forEachRest.sw.json
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/foreach_child.sw.json
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3694
Access to loop variable in for each state is now performed as variable (using "$") rather than as property (using ".") 
To be merged with https://github.com/apache/incubator-kie-kogito-examples/pull/2019
> [Fix #3694] Avoid generation of fake ProcessInstanceVariableDataEvent

- kogito-serverless-workflow/kogito-jsonpath-expression/src/main/java/org/kie/kogito/expr/jsonpath/JsonPathExpression.java
- kogito-serverless-workflow/kogito-jsonpath-expression/src/test/java/org/kie/kogito/expr/jsonpath/JsonPathExpressionHandlerTest.java
Fix  https://github.com/apache/incubator-kie-kogito-runtimes/issues/3712
> [Fix #3712] Allow concatenation of secrets and const

- api/kogito-api/src/main/java/org/kie/kogito/usertask/model/Attachment.java
- api/kogito-api/src/main/java/org/kie/kogito/usertask/model/Comment.java
- api/kogito-api/src/main/java/org/kie/kogito/usertask/model/UserTaskEntity.java
Closes: https://github.com/apache/incubator-kie-issues/issues/1519
> [incubator-kie-issues-1519] Clean Up Task Model

- addons/common/rest-exception-handler/src/main/java/org/kie/kogito/resource/exceptions/BaseExceptionsHandler.java
- api/kogito-api/src/main/java/org/kie/kogito/usertask/UserTaskInstanceNotAuthorizedException.java
- api/kogito-api/src/main/java/org/kie/kogito/usertask/UserTaskInstanceNotFoundException.java
- jbpm/jbpm-usertask/src/main/java/org/kie/kogito/usertask/impl/lifecycle/DefaultUserTaskLifeCycle.java
- kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/java/org/kie/kogito/codegen/tests/UserTaskIT.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/usertask/RestResourceUserTaskQuarkusTemplate.java
- quarkus/addons/rest-exception-handler/src/main/java/org/kie/kogito/resource/exceptions/UserTaskInstanceNotAuthorizedExceptionMapper.java
- quarkus/addons/rest-exception-handler/src/main/java/org/kie/kogito/resource/exceptions/UserTaskInstanceNotFoundExceptionMapper.java
- quarkus/addons/rest-exception-handler/src/main/java/org/kie/kogito/resource/exceptions/UserTaskTransitionExceptionMapper.java
Closes: https://github.com/apache/incubator-kie-issues/issues/1520
> [incubator-kie-issues-1520] Proper user task exception handling

- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessResourceGenerator.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/util/CodegenUtil.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/usertask/UserTaskCodegen.java
- kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/process/ProcessResourceGeneratorTest.java
Closes: https://github.com/apache/incubator-kie-issues/issues/1517
> [incubator-kie-issues-1517] Add Transactional Rest endpoints to UserTasks

- quarkus/addons/events/process/runtime/src/main/java/org/kie/kogito/events/process/GroupingMessagingEventPublisher.java
- quarkus/addons/events/process/runtime/src/main/java/org/kie/kogito/events/process/ReactiveMessagingEventPublisher.java
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3717
> [Fix #3717] Switching kogito.events.grouping from buildtime to runtime

- .ci/jenkins/dsl/jobs.groovy
Adjusting branch.yaml configuration to split maven related configurations for nightly and release.
Part of ensemble:
- apache/incubator-kie-kogito-pipelines#1254
- apache/incubator-kie-drools#6130
- apache/incubator-kie-optaplanner#3133
- apache/incubator-kie-optaplanner-quickstarts#634
- apache/incubator-kie-kogito-runtimes#3737
- apache/incubator-kie-kogito-apps#2119
- apache/incubator-kie-kogito-examples#2025
The scope of changes:
- maven settings.xml reference (config file id pointing at pre-defined config file in jenkins)
- artifacts upload repository
- url - mostly informational, should not be needed for deploy itself (inheriting that configuration from apache parent)
- credentials-id - the important part, allowing to configure different credentials for nightly and release.
Notes:
- …
> [10.0.x] CI duplicate maven configuration entries

- .ci/jenkins/dsl/jobs.groovy
Adjusting branch.yaml configuration to split maven related configurations for nightly and release.
Part of ensemble:
- apache/incubator-kie-kogito-pipelines#1259
- apache/incubator-kie-drools#6132
- apache/incubator-kie-optaplanner#3135
- apache/incubator-kie-optaplanner-quickstarts#635
- apache/incubator-kie-kogito-runtimes#3738
- apache/incubator-kie-kogito-apps#2121
- apache/incubator-kie-kogito-examples#2026
The scope of changes:
- maven settings.xml reference (config file id pointing at pre-defined config file in jenkins)
- artifacts upload repository
- url - mostly informational, should not be needed for deploy itself (inheriting that configuration from apache parent)
- credentials-id - the important part, allowing to configure different credentials for nightly and release.
Notes:
- …
> CI duplicate maven configuration entries

- addons/common/task-management/src/main/java/org/kie/kogito/task/management/service/TaskInfo.java
- addons/common/task-management/src/main/java/org/kie/kogito/task/management/service/TaskManagementOperations.java
- addons/common/task-management/src/main/java/org/kie/kogito/task/management/service/TaskManagementService.java
- api/kogito-api/src/main/java/org/kie/kogito/usertask/UserTask.java
- api/kogito-api/src/main/java/org/kie/kogito/usertask/UserTaskInstance.java
- api/kogito-api/src/main/java/org/kie/kogito/usertask/model/AttachmentInfo.java
- api/kogito-api/src/main/java/org/kie/kogito/usertask/view/UserTaskView.java
- api/kogito-events-core/src/main/java/org/kie/kogito/event/impl/adapter/AdapterHelper.java
- api/kogito-events-core/src/main/java/org/kie/kogito/event/impl/adapter/UserTaskStateEventDataEventAdapter.java
- jbpm/jbpm-usertask-workitem/src/main/java/org/kie/kogito/jbpm/usertask/handler/UserTaskKogitoWorkItemHandler.java
- jbpm/jbpm-usertask/src/main/java/org/kie/kogito/usertask/impl/AbstractUserTask.java
- jbpm/jbpm-usertask/src/main/java/org/kie/kogito/usertask/impl/DefaultUserTaskInstance.java
- jbpm/jbpm-usertask/src/main/java/org/kie/kogito/usertask/impl/UserTaskServiceImpl.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/util/CodegenUtil.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/usertask/UserTaskCodegen.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/usertask/RestResourceUserTaskSpringTemplate.java
- quarkus/addons/task-management/runtime/src/main/java/org/kie/kogito/task/management/TaskManagementResource.java
- quarkus/integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/TaskIT.java
- springboot/addons/task-management/src/main/java/org/kie/kogito/task/management/TaskManagementRestController.java
- springboot/integration-tests/integration-tests-springboot-processes-it/src/test/java/org/kie/kogito/integrationtests/springboot/TaskTest.java
Closes: https://github.com/apache/incubator-kie-issues/issues/1485
> [incubator-kie-issues-1485] Reenable event test in ProcessTestEvents in kogito-apps

- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/StandaloneBPMNProcessTest.java
This  is appearing consistently in multiple PRs after merging issue [1522](https://github.com/apache/incubator-kie-issues/issues/1522)
Executing work item WorkItem 5ee6fb6f-a098-44db-b345-645d9ceb3671 [name=Human Task, state=1, processInstanceId=4239d505-5136-431a-85bb-e69ee7f4d2c7, parameters{UNIQUE_TASK_ID=_5, NodeName=Two}]
2024-10-22T15:29:09.0028304Z [ERROR] Tests run: 49, Failures: 1, Errors: 0, Skipped: 5, Time elapsed: 5.791 s <<< FAILURE! -- in org.jbpm.bpmn2.StandaloneBPMNProcessTest
2024-10-22T15:29:09.0033454Z [ERROR] org.jbpm.bpmn2.StandaloneBPMNProcessTest.testEventBasedSplit2 -- Time elapsed: 0.532 s <<< FAILURE!
2024-10-22T15:29:09.0034881Z org.opentest4j.AssertionFailedError: 
2024-10-22T15:29:09.0035522Z 
2024-10-22T15:29:09.0035868Z expected: 2 …
> Fixing flaky test failing in multiple PRs

- jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/UserTaskHandler.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/WorkItemModelMetaData.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/node/HumanTaskNode.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/HumanTaskNodeInstance.java
- jbpm/jbpm-usertask-workitem/pom.xml
- jbpm/jbpm-usertask-workitem/src/main/java/org/kie/kogito/jbpm/usertask/handler/UserTaskKogitoWorkItemHandler.java
Closes: https://github.com/apache/incubator-kie-issues/issues/1556
> [incubator-kie-issues-1556] Unify task parameters in jbpm-flow

- kogito-build/kogito-dependencies-bom/pom.xml
- kogito-serverless-workflow/kogito-serverless-workflow-dmn-parser/src/test/java/org/kie/kogito/serverless/workflow/dmn/SWFDMNTest.java
- kogito-serverless-workflow/kogito-serverless-workflow-dmn/src/main/java/org/kie/kogito/serverless/workflow/dmn/SWFDecisionEngine.java
Fixes https://github.com/apache/incubator-kie-issues/issues/1574
<details>
<summary>
</summary> …
> [incubator-kie-issues#1574] Fix CVE-2024-47561

- addons/common/jbpm-usertask-storage-jpa/src/main/java/org/jbpm/usertask/jpa/model/AttachmentEntity.java
- addons/common/jbpm-usertask-storage-jpa/src/main/java/org/jbpm/usertask/jpa/model/CommentEntity.java
- addons/common/jbpm-usertask-storage-jpa/src/main/resources/kie-flyway/db/user-tasks/h2/V1.0.0__jBPM_user_task_create.sql
- addons/common/jbpm-usertask-storage-jpa/src/main/resources/kie-flyway/db/user-tasks/postgresql/V1.0.0__jBPM_user_task_create.sql
Just fixing two constraints names for consistency with other tables.
<details>
<summary>
</summary>
[build-chain …
> [NO_ISSUE] fix constraints names

- kogito-build/kogito-build-no-bom-parent/pom.xml
- springboot/integration-tests/integration-tests-springboot-decisions-it/pom.xml
- springboot/integration-tests/integration-tests-springboot-kafka-it/pom.xml
- springboot/integration-tests/integration-tests-springboot-norest-it/pom.xml
- springboot/integration-tests/integration-tests-springboot-processes-it/pom.xml
- springboot/integration-tests/integration-tests-springboot-processes-persistence-it/pom.xml
Resolves https://github.com/apache/incubator-kie-issues/issues/1564
- Adds a classifier to Spring Boot executable jars in integration-tests. 
- Moves the unpack profile to an earlier Maven phase to make the unpacked classes available for code generation happening during compile phase.
> [kie-issues#1564] Do not overwrite original jar with Spring Boot executable jar in integration tests

- jbpm/jbpm-usertask/src/main/java/org/kie/kogito/usertask/impl/DefaultUserTaskInstance.java
Data-Index was storing the UserTaskInstance inputs as null even if the runtime had a non-null value. The problem was due to a wrong argument order when building the `UserTaskVariableEvent`.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and …
> [NO_ISSUE] Fix User Task variable events.

- jbpm/jbpm-usertask/src/main/java/org/kie/kogito/usertask/impl/json/SimpleDeserializationProblemHandler.java
- jbpm/jbpm-usertask/src/main/java/org/kie/kogito/usertask/impl/json/SimplePolymorphicTypeValidator.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/usertask/UserTaskCodegen.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/usertask/RestResourceUserTaskQuarkusTemplate.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/usertask/RestResourceUserTaskSpringTemplate.java
- quarkus/integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/TaskIT.java
- springboot/integration-tests/integration-tests-springboot-processes-it/src/test/java/org/kie/kogito/integrationtests/springboot/TaskTest.java
Closes: https://github.com/apache/incubator-kie-issues/issues/1557
> [incubator-kie-issues-1557] Marshalling POJO Input/output in user task

- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/validation/RuleFlowProcessValidator.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/operationid/AbstractWorkflowOperationIdFactory.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ParserContext.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ServerlessWorkflowParser.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/ActionNodeUtils.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/ActionResourceFactory.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/SwitchHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/validation/SwitchValidator.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/validation/WorkflowValidator.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/types/ScriptTypeHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/types/SysOutTypeHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/parser/handlers/validation/SwitchValidatorTest.java
- kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/test/java/org/kie/kogito/serverless/workflow/executor/StaticFluentWorkflowApplicationTest.java
- kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/test/java/org/kie/kogito/serverless/workflow/executor/StaticWorkflowApplicationTest.java
- kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/test/resources/wrong.sw.json
- kogito-serverless-workflow/kogito-serverless-workflow-executor-grpc/src/main/java/org/kie/kogito/serverless/workflow/executor/StaticRPCRegister.java
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3733
> [Fix #3733] Collecting more than one error message

- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/test/util/DefaultCountDownProcessEventListener.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/event/EventTypeFilter.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/actions/AbstractNodeInstanceAction.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowProcessFactory.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/BoundaryEventNodeInstance.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/CompositeNodeInstance.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateBasedNodeInstance.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/TimerNodeInstance.java
- jbpm/jbpm-tests/src/test/bpmn/org/jbpm/bpmn2/loop/BPMN2-MultiInstanceLoopSubprocessBoundaryTimer.bpmn2
- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
- jbpm/jbpm-usertask/src/main/java/org/kie/kogito/usertask/impl/DefaultUserTaskInstance.java
Closes: https://github.com/apache/incubator-kie-issues/issues/1555
> [incubator-kie-issues-1555] Multiple sub process instances cancelled by the same timer.

- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/validation/WorkflowValidator.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/ServerlessWorkflowUtils.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/utils/WorkflowUtilsTest.java
- kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/test/java/org/kie/kogito/serverless/workflow/executor/StaticWorkflowApplicationTest.java
- kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/test/resources/wrong.sw.json
- kogito-serverless-workflow/kogito-serverless-workflow-fluent/src/main/java/org/kie/kogito/serverless/workflow/fluent/StateBuilder.java
- kogito-serverless-workflow/kogito-serverless-workflow-fluent/src/main/java/org/kie/kogito/serverless/workflow/fluent/TransitionBuilder.java
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3772
> [Fix #3772] Duplicate function error

- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/usertask/UserTaskCodegen.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/usertask/UserTaskCodegenHelper.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/usertask/UserTaskConfigGenerator.java
- kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/usertask/UserTaskCodegenHelperTest.java
Closes https://github.com/apache/incubator-kie-issues/issues/1614
<details>
<summary>
</summary>
[build-chain …
> incubator-kie-issues#1614: Fix UserTasks Codegen issue in windows

- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/NodeInstanceImpl.java
A nitpick, but calling three consecutives times logger.error looks pretty bad
> Node instance Mvel evaluation error message

- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
- jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java
- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/StandaloneBPMNProcessTest.java
AbstracPRocessInstance.getStatus does not inmediately match WorfklowProcessIntance.getState after KogitoProcessEventListener.afterProcessCompleted is invoked (eventually they are sync). There is a chance that tests that relies on afterProcessCompleted to handle CountdownLatch receive a wrong status is they check the status just after the countdownlatch reach zero (thats why those test are flaky)
> Fixing status flaky test

- kogito-codegen-modules/kogito-codegen-core/src/main/resources/class-templates/config/GlobalObjectMapperQuarkusTemplate.java
- kogito-codegen-modules/kogito-codegen-core/src/main/resources/class-templates/config/GlobalObjectMapperSpringTemplate.java
- kogito-workitems/kogito-jackson-utils/src/main/java/org/kie/kogito/jackson/utils/ObjectMapperFactory.java
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3778
> [Fix #3778] Serializing dates as strings

- api/kogito-api/src/main/java/org/kie/kogito/usertask/UserTaskAssignmentStrategy.java
- api/kogito-api/src/main/java/org/kie/kogito/usertask/model/Reassignment.java
- jbpm/jbpm-usertask/src/main/java/org/kie/kogito/usertask/impl/AbstractUserTask.java
- jbpm/jbpm-usertask/src/main/java/org/kie/kogito/usertask/impl/BasicUserTaskAssignmentStrategy.java
- jbpm/jbpm-usertask/src/main/java/org/kie/kogito/usertask/impl/DefaultUserTaskInstance.java
- jbpm/jbpm-usertask/src/main/java/org/kie/kogito/usertask/impl/lifecycle/DefaultUserTaskLifeCycle.java
- jbpm/jbpm-usertask/src/main/java/org/kie/kogito/usertask/impl/model/DeadlineHelper.java
- jbpm/jbpm-usertask/src/test/java/org/kie/kogito/usertask/impl/model/DeadlineHelperTest.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/usertask/UserTaskCodegen.java
Closes https://github.com/apache/incubator-kie-issues/issues/1626
Fixes Typos in public API method for custom User Task assignment strategy
- Included reassignments typos.
Ensemble:
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3786
https://github.com/apache/incubator-kie-kogito-examples/pull/2039
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a …
> incubator-kie-issues#1626: Fix Typo in public API method for custom User Task assignment strategy

- kogito-build/kogito-build-no-bom-parent/pom.xml
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-image-integration-test/pom.xml
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3782
Merge with https://github.com/apache/incubator-kie-kogito-apps/pull/2144
> [Fix #3782] Properly resolving root dir in all CI environments

- kogito-build/kogito-dependencies-bom/pom.xml
Temporary declaring xstream dependency, a version (1.4.20) is transitively imported by Quarkus 3.8 affected by CVE
> Explicitly declaring xstream to override a transitively imported version affected by CVE 

- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/timer/BusinessCalendarImpl.java
- jbpm/jbpm-flow/src/test/java/org/jbpm/process/core/timer/BusinessCalendarImplTest.java
Closes: https://github.com/apache/incubator-kie-issues/issues/1648
> [incubator-kie-issues#1648] Fix BusinessCalendarImpl time calculation when currentCalHour < startHour

- .rat-excludes
- LICENSE
- drools/kogito-pmml/src/test/resources/org/kie/kogito/pmml/test_regression.pmml
- drools/kogito-pmml/src/test/resources/org/kie/kogito/pmml/test_tree.pmml
- drools/kogito-scenario-simulation/src/test/resources/dmnPmml/test_regression.pmml
- drools/kogito-scenario-simulation/src/test/resources/dmnPmml/test_tree.pmml
- kogito-codegen-modules/kogito-codegen-predictions/src/test/resources/prediction/test_miningmodel.pmml
- kogito-codegen-modules/kogito-codegen-predictions/src/test/resources/prediction/test_regression.pmml
- kogito-codegen-modules/kogito-codegen-predictions/src/test/resources/prediction/test_scorecard.pmml
- quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions-integration-test/src/main/resources/PMMLRegression.pmml
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/src/main/resources/META-INF/beans.xml
- quarkus/integration-tests/integration-tests-quarkus-norest/src/main/resources/PMMLRegression.pmml
- quarkus/integration-tests/integration-tests-quarkus-predictions/src/main/resources/PMMLRegression.pmml
- quarkus/integration-tests/integration-tests-quarkus-predictions/src/main/resources/PMMLTree.pmml
- springboot/integration-tests/src/it/integration-tests-springboot-decisions-it/src/main/resources/PMMLRegression.pmml
- springboot/integration-tests/src/it/integration-tests-springboot-decisions-it/src/main/resources/PMMLTree.pmml
- springboot/integration-tests/src/it/integration-tests-springboot-norest-it/src/main/resources/PMMLRegression.pmml
This is backport of https://github.com/apache/incubator-kie-kogito-runtimes/pull/3798
Address copyright issue from the apache/incubator-kie-issues/issues/1634:
- https://github.com/apache/incubator-kie-issues/issues/1634#issuecomment-2505506658
This PR is not for adding license headers into files as no such file was marked as blocker from Apache KIE 10 release.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could …
> [10.0.x] kie-issues#1634: Fix pmml files licensing (#3798)

- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/EventNodeInstance.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateBasedNodeInstance.java
Closes https://github.com/apache/incubator-kie-issues/issues/1650
> [incubator-kie-issues#1650] Add nodeInstanceId reference to node SLA timers

- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/ErrorEventTest.java
- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/FlowTest.java
Migrated below tests
1. ErrorEventTest
- testErrorBoundaryEvent
2. Flow Test
- testMultiInstanceLoopCharacteristicsProcessWithORGateway
The test can be identified by referring to EscalationEventTest.java and FlowTest,java
https://github.com/apache/incubator-kie-kogito-runtimes/blob/main/jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/EscalationEventTest.java
> [incubator-kie-issues-1131] test migration from V7 to code generation-25

- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/models/JsonNodeModel.java
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/models/JsonNodeModelInput.java
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/ExpressionRestIT.java
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3809
> [Fix #3809] Allowing additional properties on user input

- kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoKafkaContainer.java
Missing to add "kafka" as network alias for some tests at kogito-apps
Related to https://github.com/apache/incubator-kie-issues/issues/1682
> [incubator-kie-issues-1682] Add kafka network alias

- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/ActivityTest.java
Migrated testErrorBetweenProcessesProcess within ActivityTest.java based on the changes suggested as below,
```
Application app = ProcessTestHelper.newApplication();
ProcessTestHelper.registerProcessEventListener(app, new DefaultKogitoProcessEventListener() {
@Override
public void afterProcessCompleted(ProcessCompletedEvent event) {
if ("ErrorsBetweenSubProcess".equals(event.getProcessInstance().getProcessId())) {
assertThat(event.getProcessInstance().getState()).isEqualTo(ProcessInstance.STATE_ABORTED);
}
}
});
ErrorsBetweenSubProcessProcess.newProcess(app);
org.kie.kogito.process.Process<ErrorsBetweenProcessModel> process = ErrorsBetweenProcessProcess.newProcess(app);
ErrorsBetweenProcessModel model = process.createModel();
model.setTipoEvento("error");
model.setPasoVariable(3); …
```
> [incubator-kie-issues-1131] test migration from V7 to code generation-35

- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
Migrated tests within IntermediateEventTest.java-2
The test can be identified by referring to IntermediateEventTest.java:
https://github.com/apache/incubator-kie-kogito-runtimes/blob/main/jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
> [incubator-kie-issues-1131] test migration from V7 to code generation-22

- jbpm/jbpm-tests/src/test/bpmn/org/jbpm/bpmn2/activity/BPMN2-ScriptTaskFEEL.bpmn2
- jbpm/jbpm-tests/src/test/bpmn/org/jbpm/bpmn2/subprocess/BPMN2-DynamicSignalParent.bpmn2
- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/ActivityTest.java
- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/ErrorEventTest.java
- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/FlowTest.java
- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
Few tests within jbpm-tests are disabled as on-exit is not supported. Check if they can be enabled and converted.
Reference issue link: https://issues.redhat.com/browse/KOGITO-2067
Below are the tests: 
(https://github.com/apache/incubator-kie-kogito-runtimes/tree/main/jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2)
Below tests within **IntermediateEventTest** cannot be migrated as due to kie session not working in kogito
testDynamicCatchEventSignalWithVariableUpdated
testDynamicCatchEventSignalWithVariableUpdatedBroadcastSignal
Below tests within FlowTest fail when tried to enable and run in original v7 format,
**testInclusiveSplitWithLoopInsideSubprocess** - process goes to an error state, rather than maintaining the active state, when completing the work item for handler2. In …
> [incubator-kie-issues-1131] test migration from V7 to code generation-36

- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/AbstractCompositeNodeVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/AbstractNodeVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessVisitor.java
- jbpm/jbpm-tests/src/test/bpmn/org/jbpm/bpmn2/loop/BPMN2-MultiInstanceLoopCharacteristicsTaskWithOutputCmpCondSequential.bpmn2
- jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/FlowTest.java
Closes https://github.com/apache/incubator-kie-issues/issues/1719
> [incubator-kie-issues#1719] Enable onEntry/onExit scripts in embedded nodes

- jbpm/jbpm-flow/src/test/java/org/jbpm/process/core/timer/BusinessCalendarImplTest.java
Closes/Fixes/Resolves #3818
**Description:** Wrong calculation in test rollCalendarAfterHolidays if day is near to end-of-year
<details>
<summary>
</summary> …
> [Fix_3818] Wrong calculation in test rollCalendarAfterHolidays if day is near to end-of-year

- addons/common/jbpm-usertask-storage-jpa/src/main/resources/kie-flyway/db/user-tasks/h2/V1.0.2__jBPM_user_tasks_comments_increase_comment_size.sql
- addons/common/jbpm-usertask-storage-jpa/src/main/resources/kie-flyway/db/user-tasks/postgresql/V1.0.2__jBPM_user_tasks_comments_increase_comment_size.sql
Part of https://github.com/apache/incubator-kie-issues/issues/1737
Needed by https://github.com/apache/incubator-kie-kogito-apps/pull/2173
Increased the size of columns that store comments from 255 to 1000
> [incubator-kie-issues#1737] jBPMN Comment columns are too short (part 1) 

- .ci/jenkins/tests/pom.xml
Part of https://github.com/apache/incubator-kie-issues/issues/1750
We have noticed some builds causing many 404 errors on `repository.apache.org`, causing GitHub Actions runners to be banned (https://infra.apache.org/infra-ban.html).
Looking at various logs, it looks like this workflow may be one of the jobs triggering this problem. Including Maven Central explicitly in the repositories section will make Maven check that repository first, which should help a lot.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class …
> kie-issues#1750: Try Maven Central before hitting `repository.apache.org`

- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/AbstractKieMojo.java
- kogito-maven-plugin/src/test/java/org/kie/kogito/maven/plugin/AbstractKieMojoTest.java
Fixes https://github.com/apache/incubator-kie-issues/issues/1775
This PR:
1. overwrite the code-gen context properties only if related system properties are not null/empty
2. unit test newly added methods/checks
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is …
> [incubator-kie-issues#1775] Springboot apps - Conditionally overwrite code-related context properties only if twin system properties are not null

- kogito-build/kogito-build-no-bom-parent/pom.xml
- kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoPostgreSqlContainer.java
- kogito-test-utils/src/test/java/org/kie/kogito/testcontainers/KogitoMongoDBContainerTest.java
- quarkus/addons/events/mongodb/runtime/src/test/resources/application.properties
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties
- quarkus/integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/test/java/org/kie/kogito/it/PersistenceTest.java
- quarkus/integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-jdbc/src/main/resources/application.properties
- quarkus/integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-postgresql/src/main/resources/application.properties
- quarkus/integration-tests/integration-tests-quarkus-usertasks/src/main/resources/application.properties
- quarkus/test/src/test/java/org/kie/kogito/testcontainers/quarkus/MongoDBQuarkusTestResourceTest.java
- springboot/test/src/test/java/org/kie/kogito/testcontainers/springboot/MongoDBSpringBootTestResourceTest.java
Closes/Fixes/Resolves [kie-issues#1749](https://github.com/apache/incubator-kie-issues/issues/1749)
<details>
<summary>
</summary>
[build-chain …
> [Fixes_kie_issues_1749] Switch dockerhub to a mirrored registry

- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/AbstractKieMojo.java
- kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/util/CompilerHelper.java
Fixes https://github.com/apache/incubator-kie-issues/issues/1812
<details>
<summary>
</summary> …
> [incubator-kie-issues#1812] Restore source dumping from kogito-maven-plugin

- springboot/integration-tests/integration-tests-springboot-kafka-it/src/main/resources/application.properties
As part of resolution of  https://github.com/apache/incubator-kie-kogito-runtimes/issues/3813, a misleading application.properties should be changed
> [Fix #3813] Removing Quarkus Configuration From Springboot file

- addons/common/flyway/pom.xml
- addons/common/flyway/src/main/java/org/kie/flyway/initializer/KieFlywayInitializer.java
- addons/common/flyway/src/main/java/org/kie/flyway/initializer/db/DataBaseInfo.java
- addons/common/flyway/src/main/java/org/kie/flyway/initializer/db/KieFlywayDataBaseHelper.java
- addons/common/flyway/src/test/java/org/kie/flyway/initializer/db/KieFlywayDataBaseHelperTest.java
Fixes: https://github.com/apache/incubator-kie-issues/issues/1816
<details>
<summary>
</summary>
[build-chain …
> kie-issues#1816: Make `kie-flyway` sanitize DataSource product name before loading migrations.

- kogito-build/kogito-dependencies-bom/pom.xml
Fixes https://github.com/apache/incubator-kie-issues/issues/1788.
Dashbuilder Appformer also uses keycloak, but I think this takes care of it as well. We'll need to do a full build to make sure everything is good.
> [kie-issues 1788] Updating to Keycloak 26.1.0

- kogito-build/kogito-dependencies-bom/pom.xml
Unify netty-handler and netty-common versions to 4.1.115-Final - the one used by quarkus
Requires https://github.com/apache/incubator-kie-drools/pull/6263
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally …
> [NO_ISSUE] Fix netty-related CVE. Unify versions

- kogito-build/kogito-dependencies-bom/pom.xml
The current version of the netty-codec-http dependency (4.1.107.Final) used in the kogito-runtimes repository contains a CVE vulnerability. This vulnerability is being introduced transitively via the io.smallrye.reactive.mutiny-vertx-web-client dependency. To mitigate this issue, update the version of smallrye-mutiny-vertx-web-client to 3.17.1.
Closes: https://github.com/apache/incubator-kie-issues/issues/1850
> [kie-issues#1850] update the version of smallrye-mutiny-vertx-web-client to 3.17.1.

- addons/common/tracing/decision-common/src/main/java/org/kie/kogito/tracing/decision/event/EventUtils.java
Added the fix for this problem in incubator-kie-drools
Fixes: https://github.com/apache/incubator-kie-issues/issues/1752
Related PR: https://github.com/apache/incubator-kie-drools/pull/6261
This required the changes to be done in runtimes repo also.
>  [incubator-kie-issues#1752] Lambda function returns null - changes in runtimes

- api/kogito-api/src/main/java/org/kie/kogito/jobs/descriptors/UserTaskInstanceJobDescription.java
- api/kogito-api/src/main/java/org/kie/kogito/jobs/descriptors/UserTaskInstanceJobDescriptionBuilder.java
- api/kogito-services/src/main/java/org/kie/kogito/services/jobs/impl/InMemoryUserTaskJobExecutorFactory.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
- jbpm/jbpm-usertask-workitem/src/main/java/org/kie/kogito/jbpm/usertask/handler/UserTaskKogitoWorkItemHandler.java
- jbpm/jbpm-usertask/src/main/java/org/kie/kogito/usertask/impl/DefaultUserTaskInstance.java
Part of https://github.com/apache/incubator-kie-issues/issues/1858
The Jobs scheduled by the UserTask Subsystem when registering the Deadlines/Reassignments are lacking of some fields processId, processInsanceId and nodeInstanceId when indexed in data-index. 
Ensemble:
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3857
https://github.com/apache/incubator-kie-kogito-apps/pull/2203
> [incubator-kie-issues#1858] Fixed missing data in jobs associated with User Tasks Part 1

- quarkus/addons/pom.xml
- quarkus/addons/python/integration-tests/pom.xml
- quarkus/addons/python/pom.xml
This includes python serverless workflow addon in regular modules, but keep Python IT module just for full build. 
This way community users will be able to test python examples at their own risk, without compromising release because of the inherent flaky nature of pip/jep relationship
> Including Python modules in regular build (but not IT)

- jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/timer/DateTimeUtils.java
- jbpm/jbpm-flow/src/test/java/org/jbpm/process/core/timer/DateTimeUtilsTest.java
https://github.com/apache/incubator-kie-kogito-runtimes/issues/3871
Using timer node with timer expression R/PT5M, the job gets executed immediately, then in the configured 5min intervals.
> Incubator-kie-issues-3871] Repeating timer gets executed immediately

- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/AbstractVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/CatchLinkNodeVisitor.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ThrowLinkNodeVisitor.java
- kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/java/org/kie/kogito/codegen/process/ProcessGenerationIT.java
Closes https://github.com/apache/incubator-kie-issues/issues/1932
Added default name for ThrowLink and CatchLink nodes
> [Incubator-kie-issues-1932] Fix for node name being null for throw and catch link

- api/kogito-events-core/src/main/java/org/kie/kogito/event/impl/adapter/AbstractDataEventAdapter.java
- kogito-bom/pom.xml
- kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/java/org/kie/kogito/codegen/rules/PublishEventBusinessRuleIT.java
- kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/java/org/kie/kogito/codegen/tests/PublishEventIT.java
Issue: https://github.com/apache/incubator-kie-issues/issues/1937
> [incubator-kie-issues-1924] Data Audit stores subprocess events always in completed state

- api/kogito-events-api/src/main/java/org/kie/kogito/event/process/KogitoMarshallEventFlag.java
- api/kogito-events-api/src/main/java/org/kie/kogito/event/process/ProcessInstanceStateEventBody.java
- api/kogito-events-core/src/main/java/org/kie/kogito/event/impl/adapter/AbstractDataEventAdapter.java
Fix https://github.com/apache/incubator-kie-issues/issues/1952
To be merged with https://github.com/apache/incubator-kie-kogito-apps/pull/2218
A cloud event is univocally identified by the combination of id and source
> [Fix apache/incubator-kie-issues#1952]  Adding cloud event id and source

- kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/transaction/ExceptionHandlerTransactionQuarkusTemplate.java
Closes https://github.com/apache/incubator-kie-issues/issues/1966
Closes/Fixes/Resolves incubator-kie-issues-1966
With transactions enabled, if there's an error during the execution of a node instance the process isn't set into error state. This is because ExceptionHandlerTransaction is doing a wrong verification on the processContainer to see if it is resolvable via CDI:
@Override
@Transactional(value = TxType.REQUIRES_NEW)
public void handle(Exception th) {
if (processesContainer.isResolvable()) { <- here is the problem
return;
}
...
}
With this check if the container is resolvable (which should always be), it will return and not setting the process instance in error state, and in the case it is NOT resolvable it …
> [incubator-kie-issues-1966] `ExceptionHandlerTransaction` not setting process Instances in Error state

- kogito-build/kogito-dependencies-bom/pom.xml
Issue: https://github.com/apache/incubator-kie-issues/issues/1915
This PR upgrades javaparser to the latest version and uses the same version as in Drools, as part of the [related PR](https://github.com/apache/incubator-kie-drools/pull/6365). 
Related PR: https://github.com/apache/incubator-kie-drools/pull/6365
> [kie-issues#1915] Upgrade javaparser to 3.26.4.

- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-extension-live-reload-test/src/main/resources/application.properties
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties
This disables keycloak dev services in sonataflow integration tests.
> [NO-ISSUE] Disable keycloak dev services in Sonataflow integration tests.

- api/kogito-events-core/src/main/java/org/kie/kogito/event/DataEventFactory.java
- api/kogito-events-core/src/main/java/org/kie/kogito/event/impl/AbstractMessageProducer.java
- api/kogito-events-core/src/main/java/org/kie/kogito/event/impl/MessageProducerWithContext.java
- jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/descriptors/ExpressionUtils.java
- jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/actions/ProduceEventAction.java
- kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/MessageProducerJavaTemplate.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java
- kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/suppliers/ProduceEventActionSupplier.java
- kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/main/java/org/kie/kogito/serverless/workflow/executor/events/CloudEventReceiver.java
- kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/main/java/org/kie/kogito/serverless/workflow/executor/events/InMemoryEventEmitter.java
- kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/main/java/org/kie/kogito/serverless/workflow/executor/events/InMemoryEventEmitterFactory.java
- kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/main/java/org/kie/kogito/serverless/workflow/executor/events/InMemoryEventReceiverFactory.java
- kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/main/java/org/kie/kogito/serverless/workflow/executor/events/InMemoryEventShared.java
- kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/main/resources/META-INF/services/org.kie.kogito.event.EventEmitterFactory
- kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/main/resources/META-INF/services/org.kie.kogito.event.EventReceiverFactory
- kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/test/java/org/kie/kogito/serverless/workflow/executor/StaticFluentWorkflowApplicationTest.java
- kogito-serverless-workflow/kogito-serverless-workflow-executor-kafka/src/main/java/org/kie/kogito/serverless/workflow/executor/KafkaEventReceiverFactory.java
- kogito-serverless-workflow/kogito-serverless-workflow-fluent/src/main/java/org/kie/kogito/serverless/workflow/fluent/ActionBuilder.java
- kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/SWFProduceEventAction.java
- kogito-workitems/kogito-jackson-utils/src/main/java/org/kie/kogito/jackson/utils/StringConverter.java
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3971
This adds also support for [EventRef.contextAttributes](https://github.com/serverlessworkflow/specification/blob/0.8.x/specification.md#eventref-definition), which is needed to be able to include the target process intances id to be notified by an event.  
However, this support has not been added to the codegen, that will be done with https://github.com/apache/incubator-kie-kogito-runtimes/issues/3973
> [Fix #3971] Adding default event broker and support for context attrs

- kogito-build/kogito-dependencies-bom/pom.xml
- quarkus/addons/mail/runtime/pom.xml
- quarkus/addons/messaging/integration-tests/pom.xml
- quarkus/addons/tracing-decision/runtime/pom.xml
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-extension-live-reload-test/pom.xml
- quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/pom.xml
- quarkus/integration-tests/integration-tests-quarkus-processes/pom.xml
This PR upgrades kafka-clients to 3.9.1 due to vulnerabilities.
Related PRs:
drools: https://github.com/apache/incubator-kie-drools/pull/6404
kogito-apps: https://github.com/apache/incubator-kie-kogito-apps/pull/2243
> [NO-ISSUE] Upgrade kafka-clients to 3.9.1. 

- jbpm/jbpm-usertask/src/main/java/org/kie/kogito/usertask/impl/lifecycle/DefaultUserTaskLifeCycle.java
- kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/java/org/kie/kogito/codegen/tests/UserTaskIT.java
Workflow Engine- User in a task Excluded users can still claim and complete the task
Closes https://github.com/apache/incubator-kie-issues/issues/2059
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest …
> [incubator-kie-issues : 2059] Workflow Engine- User in a task Excluded users can still claim and complete the task

- jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/NodeInstanceFactoryRegistry.java
- jbpm/jbpm-usertask/src/main/java/org/kie/kogito/usertask/impl/DefaultUserTaskInstance.java
- jbpm/jbpm-usertask/src/main/resources/META-INF/native-image/reflect-config.json
Fixes https://github.com/apache/incubator-kie-issues/issues/2056
Issue 1: To fix 
`java.lang.ClassNotFoundException: org.jbpm.workflow.instance.impl.CodegenNodeInstanceFactoryRegistry`
when running process examples in native mode, initialize map `LOADED_NODE_INSTANCE_FACTORY_REGISTRIES` with the object of `CodegenNodeInstanceFactoryRegistry` class using new keyword
Issue 2: to fix serialization and reflection issue on `DefaultUserTaskInstance`, added `reflect-config.json`
> Fixes for supporting native mode
