apache/incubator-kie-kogito-runtimes

Jenkinsfile
@mswiderski @mariofusco please review. 
This is a PoC PR automation pipeline script for Jenkins. I tested it locally with Jenkins on Docker, now we need to test it on KIE Jenkins.
=> DROOLS-3816 Add Jenkinsfile for PR automation

drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/CanonicalModelCodeGenerationKieProject.java, drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/ModelWriter.java, drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/ProjectSourceClass.java, drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/generator/ModuleSourceClass.java, kie-maven-plugin/src/main/java/org/kie/maven/plugin/GenerateModelMojo.java
examples are now building as expected
=> DROOLS-3920: Fix missing DI annotations on Drools Submarine Maven codegen

addons/monitoring-prometheus-addon/src/main/java/ork/kie/addons/monitoring/process/PrometheusProcessEventListener.java, api/kie-api/src/main/java/org/kie/api/runtime/process/WorkItemNotFoundException.java, api/kie-api/src/main/java/org/kie/submarine/process/ProcessInstance.java, api/kie-api/src/main/java/org/kie/submarine/process/WorkItem.java, jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/canonical/ActivityGenerationModelTest.java, jbpm/jbpm-bpmn2/src/test/resources/handler/onboarding.bpmn, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ModelMetaData.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessToExecModelGenerator.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/UserTaskModelMetaData.java, jbpm/jbpm-flow-builder/src/main/resources/class-templates/ModelTemplate.java, jbpm/jbpm-flow-builder/src/main/resources/class-templates/TaskInputTemplate.java, jbpm/jbpm-flow-builder/src/main/resources/class-templates/TaskOutputTemplate.java, jbpm/jbpm-flow-builder/src/test/java/org/jbpm/compiler/canonical/ProcessToExecModelGeneratorTest.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/LightWorkItemManager.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/LambdaSubProcessNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/kie/submarine/process/impl/AbstractProcessInstance.java, jbpm/jbpm-flow/src/main/java/org/kie/submarine/process/impl/BaseWorkItem.java, kie-maven-plugin/pom.xml, submarine-codegen/pom.xml, submarine-codegen/src/main/java/org/kie/submarine/codegen/process/ProcessCodegen.java, submarine-codegen/src/main/java/org/kie/submarine/codegen/process/ResourceGenerator.java, submarine-codegen/src/main/java/org/kie/submarine/codegen/process/UserTasksModelClassGenerator.java, submarine-codegen/src/main/resources/class-templates/RestResourceTemplate.java, submarine-codegen/src/main/resources/class-templates/RestResourceUserTaskTemplate.java
depends on https://github.com/kiegroup/submarine-bom/pull/11
=> JBPM-8448 - Basic support for human task

api/kie-api/src/main/java/org/kie/submarine/rules/impl/AbstractRuleUnitInstance.java, submarine-codegen/src/main/java/org/kie/submarine/codegen/rules/RuleUnitSourceClass.java
should fix runtime NPE on native-image
=> Fix Drools codegen to avoid refleciton in class bind

submarine-codegen/src/main/java/org/kie/submarine/codegen/rules/RuleUnitInstanceSourceClass.java, submarine-codegen/src/main/java/org/kie/submarine/codegen/rules/RuleUnitSourceClass.java
@mariofusco I have fixed yesterday's commit. Codegen for Rule Unit now works properly even with native-image generation.
=> DROOLS-3973: Codegen'd rule unit should override reflective bind

jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/AbstractNodeHandler.java, jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/BusinessRuleTaskHandler.java, jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/CallActivityHandler.java, jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/ProcessHandler.java, jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/SubProcessHandler.java, jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/TaskHandler.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/LambdaSubProcessNodeVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ModelMetaData.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessMetaData.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessToExecModelGenerator.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/VariableDeclarations.java, submarine-codegen/src/main/java/org/kie/submarine/codegen/process/ProcessCodegen.java
=> JBPM-8458: Code generation in subprocess node may use local data type info

api/kie-api/pom.xml, api/kie-internal/pom.xml, drools/drools-compiler/pom.xml, drools/drools-core-dynamic/pom.xml, drools/drools-core/pom.xml, drools/drools-model/drools-canonical-model/pom.xml, drools/drools-model/drools-constraint-parser/pom.xml, drools/drools-model/drools-model-compiler/pom.xml, drools/drools-model/drools-model-compiler/src/test/java/org/drools/modelcompiler/ComplexRulesTest.java, jbpm/jbpm-bpmn2/pom.xml, jbpm/jbpm-flow-builder/pom.xml, jbpm/jbpm-flow/pom.xml
Only merge after https://github.com/kiegroup/submarine-bom/pull/16.
=> [DROOLS-3968] Move off JUnit 4 and onto JUnit Vintage

api/kie-api/pom.xml, api/kie-api/src/test/java/org/kie/api/KModuleXSDTest.java, api/kie-api/src/test/java/org/kie/api/internal/utils/ServiceDiscoveryImplTest.java, api/kie-internal/pom.xml, api/kie-internal/src/test/java/org/kie/internal/utils/KieMetaTest.java
Merge after https://github.com/kiegroup/submarine-bom/pull/19
=> DROOLS-4038: Migrate Runtimes > API modules to JUnit 5

Jenkinsfile
https://github.com/kiegroup/kogito-bom/pull/22
https://github.com/kiegroup/kogito-runtimes/pull/55
https://github.com/kiegroup/kogito-cloud/pull/16
https://github.com/kiegroup/kogito-examples/pull/26
=> updated jenkinsfile after repository rename

kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/BuildMojo.java, kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/BytecodeInjectReactive.java, kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/CompilerHelper.java, kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/DiskResourceStore.java, kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/GenerateDMNModelMojo.java, kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/GenerateModelMojo.java, kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/IncludeProjectDependenciesComponentConfigurator.java, kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/InjectReactiveMojo.java, kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/ResourceFileWriter.java, kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/SerializeMojo.java, kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/TouchResourcesMojo.java, kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/util/BytecodeInjectException.java, kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/util/MojoUtil.java
This fixes majority of issues reported by SonarCloud in kogito-maven-plugin (originally there were 102 issues, now there are 5).
=> DROOLS-4197 Fix Sonarcloud problems in kogito-maven-plugin

drools/drools-model/drools-mvel-compiler/pom.xml, drools/drools-model/drools-mvel-parser/src/test/java/org/drools/mvel/parser/DroolsMvelParserTest.java
fix minor issues with maven/java build
=> KOGITO-48: Fix minor build errors in MVEL compiler

api/kogito-api/src/main/java/org/kie/kogito/rules/DataObserver.java, api/kogito-api/src/main/java/org/kie/kogito/rules/DataProcessor.java, api/kogito-api/src/main/java/org/kie/kogito/rules/DataSource.java, api/kogito-api/src/main/java/org/kie/kogito/rules/DataStream.java, api/kogito-services/src/main/java/org/kie/kogito/Executor.java, drools/drools-core/src/main/java/org/drools/core/ruleunit/impl/ListDataStream.java, drools/drools-core/src/test/java/org/drools/core/ruleunit/impl/ListDataStreamTest.java, drools/drools-model/drools-model-compiler/src/test/java/org/drools/modelcompiler/RuleUnitExecModelTest.java, drools/drools-model/drools-model-compiler/src/test/java/org/drools/modelcompiler/RuleUnitTest.java
introduces an Executor where users can submit() long-running units. This is a prototype that needs further work. An example is provided in https://github.com/kiegroup/kogito-examples/pull/59
=> KOGITO-93: Prototype concurrent rule units

drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/AccumulateClassWriter.java, drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/DeclaredTypeWriter.java, drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/ModelWriter.java, drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/PackageModel.java, drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/PackageModelWriter.java, drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/RuleWriter.java
forward port: https://github.com/kiegroup/drools/commit/105879a52f7ed93d3682b0bdcd537968f5c4a0cb
=> [DROOLS-4291] ModelWriter: refactor to smaller classes

addons/persistence/infinispan-persistence-addon/src/main/java/org/kie/kogito/infinispan/CacheProcessInstances.java, api/kogito-api/src/main/java/org/kie/api/runtime/process/ProcessInstance.java, api/kogito-services/src/main/java/org/kie/kogito/services/event/ProcessInstanceDataEvent.java, api/kogito-services/src/main/java/org/kie/kogito/services/event/impl/ProcessInstanceEventBatch.java, api/kogito-services/src/main/java/org/kie/kogito/services/event/impl/ProcessInstanceEventBody.java, drools/drools-compiler/src/test/java/org/drools/compiler/integrationtests/WorkingMemoryLoggerTest.java, jbpm/jbpm-flow/src/main/java/org/jbpm/marshalling/impl/AbstractProtobufProcessInstanceMarshaller.java, jbpm/jbpm-flow/src/main/java/org/jbpm/marshalling/impl/JBPMMessages.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/ProcessInstanceImpl.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/NodeInstanceImpl.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/LambdaSubProcessNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/SubProcessNodeInstance.java, jbpm/jbpm-flow/src/main/resources/org/jbpm/marshalling/jbpmmessages.proto, kogito-codegen/src/main/java/org/kie/kogito/codegen/process/persistence/proto/ProtoField.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/process/persistence/proto/ProtoGenerator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/process/persistence/proto/ProtoMessage.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/process/persistence/proto/ReflectionProtoGenerator.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/process/persistence/proto/ReflectionProtoGeneratorTest.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/PublishEventTest.java, kogito-codegen/src/test/resources/gateway/ExclusiveSplit.bpmn2
@cristianonicolai here are the fixes and improvements to allow to better integration with data index service
=> KOGITO-140, KOGITO-139, KOGITO-141, KOGITO-142

kogito-codegen/README.md
not sure whether we should actually put this in the wiki
=> KOGITO-110: README.md for codegen

archetypes/kogito-springboot-archetype/src/main/resources/archetype-resources/pom.xml, archetypes/kogito-springboot-archetype/src/main/resources/archetype-resources/src/main/java/KogitoApplication.java, archetypes/kogito-springboot-archetype/src/main/resources/archetype-resources/src/main/resources/application.properties, archetypes/kogito-springboot-archetype/src/main/resources/archetype-resources/src/main/resources/test-process.bpmn2
@krisv could you please have a look?
=> KOGITO-166 - SpringBoot archetype does not work with custom groupId

api/kogito-api/pom.xml, api/kogito-api/src/main/java/org/kie/kogito/Application.java, api/kogito-api/src/main/java/org/kie/kogito/decision/DecisionModel.java, api/kogito-api/src/main/java/org/kie/kogito/decision/DecisionModels.java, kogito-codegen/pom.xml, kogito-codegen/src/main/java/org/kie/kogito/codegen/ApplicationGenerator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DMNRestResourceGenerator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionContainerGenerator.java, kogito-codegen/src/main/resources/class-templates/DMNApplicationClassDeclTemplate.java, kogito-codegen/src/main/resources/class-templates/DMNRestResourceTemplate.java, kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/GenerateModelMojo.java
This supersedes https://github.com/kiegroup/kogito-runtimes/pull/121
I will continue working with this branch on my fork/repo. ref: https://github.com/kiegroup/kogito-runtimes/pull/121#issuecomment-523171984
=>  DROOLS-3903 DMN Submarine endpoint codegen

addons/events/kogito-events-reactive-messaging-addon/pom.xml, data-index/data-index-service/pom.xml
depends on https://github.com/kiegroup/kogito-bom/pull/52
=> KOGITO-243 - Align dependencies with Quarkus to avoid enforcer issues

addons/persistence/infinispan-persistence-addon/src/test/java/org/kie/kogito/infinispan/MockCacheProcessInstancesTest.java, data-index/data-index-service/pom.xml, data-index/data-index-service/src/main/java/org/kie/kogito/index/messaging/ReactiveMessagingEventConsumer.java, data-index/data-index-service/src/main/resources/application.properties, data-index/data-index-service/src/test/java/org/kie/kogito/index/IndexingServiceTest.java, data-index/data-index-service/src/test/java/org/kie/kogito/index/messaging/ReactiveMessagingEventConsumerTest.java, drools/drools-compiler/pom.xml, drools/drools-core/pom.xml
Depends on https://github.com/kiegroup/kogito-bom/pull/53
=> KOGITO-238 - Separate consumer for model and process instance

drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/FlowDSL.java, drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/PatternDSL.java, drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/Query0Def.java, drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/Query10Def.java, drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/Query1Def.java, drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/Query2Def.java, drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/Query3Def.java, drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/Query5Def.java, drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/Query6Def.java, drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/Query7Def.java, drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/Query8Def.java, drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/Query9Def.java, drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/QueryDef.java, drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/impl/Query0DefImpl.java, drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/impl/Query10DefImpl.java, drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/impl/Query1DefImpl.java, drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/impl/Query2DefImpl.java, drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/impl/Query3DefImpl.java, drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/impl/Query5DefImpl.java, drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/impl/Query6DefImpl.java, drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/impl/Query7DefImpl.java, drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/impl/Query8DefImpl.java, drools/drools-model/drools-canonical-model/src/main/java/org/drools/model/impl/Query9DefImpl.java, drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/generator/query/FlowDSLQueryGenerator.java, drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/generator/query/Generator.java, drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/generator/query/PatternDSLQueryGenerator.java, drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/generator/query/QueryDefGenerator.java, drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/generator/query/QueryDefImplGenerator.java, drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/builder/generator/query/QueryGenerator.java, drools/drools-model/drools-model-compiler/src/test/java/org/drools/modelcompiler/QueryTest.java
Forward port 
@mariofusco @baldimir
=> [DROOLS-4292] executable-model fails with more than 5 arguments query

drools/drools-model/drools-model-compiler/src/main/java/org/drools/modelcompiler/CanonicalKieModule.java
This is a port of kiegroup/drools#2539.
=> KOGITO-298 Read BPMN files correctly in CanonicalKieModule

addons/pom.xml, archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/pom.xml, drools/pom.xml, jbpm/pom.xml, kogito-codegen/pom.xml, kogito-maven-plugin/pom.xml
Assembly:
- https://github.com/kiegroup/kogito-examples/pull/86
- https://github.com/kiegroup/kogito-bom/pull/55
- https://github.com/kiegroup/kogito-runtimes/pull/151
- https://github.com/kiegroup/kogito-cloud/pull/39
=> KOGITO-253 Consolidate drools-bom and jbpm-bom into kogito-bom

drools/drools-compiler/src/main/java/org/drools/compiler/kproject/models/KieModuleMarshaller.java
this should address https://github.com/quarkusio/quarkus/pull/4092#issuecomment-533005395
before 
```
[INFO] --- quarkus-maven-plugin:0.21.2:dev (default-cli) @ kogito-travel-agency ---
Listening for transport dt_socket at address: 5005
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/home/evacchi/.m2/repository/com/thoughtworks/xstream/xstream/1.4.11.1/xstream-1.4.11.1.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release …
```
=> KOGITO-308: Avoid XStream "Illegal reflective access operation"

api/kogito-api/pom.xml, drools/kogito-dmn/pom.xml, jbpm/jbpm-flow/pom.xml, kogito-maven-plugin/pom.xml, pom.xml
Assembly:
- https://github.com/kiegroup/kogito-bom/pull/57
- https://github.com/kiegroup/kogito-runtimes/pull/168
- https://github.com/kiegroup/kogito-examples/pull/89
- https://github.com/kiegroup/kogito-cloud/pull/44
=> KOGITO-333 - Separate external dependencies into its on BOM

kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegen.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/QueryEndpointGenerator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/RuleCodegenProject.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/RuleUnitContainerGenerator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/RuleUnitGenerator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/RuleUnitInstanceGenerator.java, kogito-codegen/src/main/resources/class-templates/rules/RestQueryTemplate.java
see Jira.
Also, in this PR I am renaming classes ${name}SourceClass to ${name}Generator to follow the convention of all the other generators
=> KOGITO-356: Kogito Query rest endpoint name should be normalized

drools/kogito-dmn/pom.xml, drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/DMNKogito.java, drools/kogito-dmn/src/test/java/org/kie/kogito/dmn/DMNKogitoTest.java, drools/kogito-dmn/src/test/resources/org/kie/kogito/dmn/TrafficViolation.dmn, kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionContainerGenerator.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/decision/DecisionCodegenTest.java, kogito-codegen/src/test/resources/decision/TrafficViolation.dmn
The scope of this PR is to fix OCP resolution errors.
=> KOGITO-366 DMN fix OCP asset resolution errors

data-index/data-index-service/src/test/java/org/kie/kogito/index/graphql/WebSocketSubscriptionTest.java
=> KOGITO-396: WebSocketSubscriptionTest: close http client gracefully 

data-index/data-index-service/src/test/java/org/kie/kogito/index/graphql/WebSocketSubscriptionTest.java
=> KOGITO-400: Temporarily disable flaky websocket test

data-index/data-index-service/pom.xml, data-index/data-index-service/src/main/java/org/kie/kogito/index/vertx/VertxRouterSetup.java, data-index/data-index-storage/data-index-storage-infinispan/pom.xml, drools/drools-core/src/test/java/org/drools/core/common/ClassAwareObjectStoreTest.java, pom.xml
Assembly: 
- https://github.com/kiegroup/kogito-runtimes/pull/209
- https://github.com/kiegroup/kogito-bom/pull/65
- https://github.com/kiegroup/kogito-examples/pull/100
=> KOGITO-480 - Upgrade to Quarkus 0.27.0

addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/resource/JobResource.java
Returns 404 when a job is not found when canceling or getting a job.
=> [Job Service] Returns 404 when a job is not found

kogito-codegen/src/main/java/org/kie/kogito/codegen/process/persistence/MarshallerGenerator.java
Protostream classes from Infinispan are using readInt and writeInt for Integer (and not readInteger and writeInteger).
This was causing some conflicts on our side when generating code for Integer and List of Integer.
Solution is to separate both retrieval: method name and class name for code generation
=> Corrected small bug on MarshallerGenerator class for readInt and writeInt

archetypes/kogito-springboot-archetype/src/main/resources/archetype-resources/pom.xml, archetypes/kogito-springboot-archetype/src/main/resources/archetype-resources/src/main/resources/application.properties, archetypes/kogito-springboot-starter/.gitignore, archetypes/kogito-springboot-starter/pom.xml, archetypes/pom.xml, kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ResourceGenerator.java
depends on https://github.com/kiegroup/kogito-bom/pull/71
=> KOGITO-644 - Kogito SpringBoot starter, KOGITO-643 - Move spring boot based service to RESTEasy spring boot instead of Apache CXF

addons/jobs/jobs-service/pom.xml, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/repository/infinispan/InfinispanConfiguration.java, addons/jobs/jobs-service/src/test/java/org/kie/kogito/jobs/service/resource/InfinispanServerTestResource.java, addons/jobs/jobs-service/src/test/java/org/kie/kogito/jobs/service/resource/JobResourceTest.java, addons/jobs/jobs-service/src/test/resources/application.properties, data-index/data-index-service/pom.xml, data-index/data-index-service/src/test/java/org/kie/kogito/index/InfinispanServerTestResource.java, data-index/data-index-service/src/test/java/org/kie/kogito/index/KeycloakServerTestResource.java, data-index/data-index-service/src/test/java/org/kie/kogito/index/service/KeycloakIntegrationIndexingServiceTest.java, data-index/data-index-service/src/test/resources/application.properties, data-index/data-index-storage/data-index-storage-infinispan/src/main/java/org/kie/kogito/index/infinispan/cache/InfinispanCacheManager.java
Depends on:
- https://github.com/kiegroup/kogito-bom/pull/72
=> KOGITO-681 - Upgrade Quarkus to version 1.0.1

kogito-codegen/src/main/java/org/kie/kogito/codegen/KogitoPackageSources.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegen.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/QueryEndpointGenerator.java
=> KOGITO-707: Codegen: use RuleUnitDescription for Queries

kogito-codegen/src/main/java/org/kie/kogito/codegen/ApplicationGenerator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/GeneratorConfig.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/GeneratorContext.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/context/KogitoBuildContext.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/context/QuarkusKogitoBuildContext.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/context/SpringBootKogitoBuildContext.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/process/AbstractResourceGenerator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/process/CodegenUtils.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ReactiveResourceGenerator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/RuleUnitContainerGenerator.java, kogito-codegen/src/main/resources/class-templates/ReactiveRestResourceTemplate.java, kogito-codegen/src/main/resources/class-templates/RestResourceTemplate.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/AbstractCodegenTest.java, kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/AbstractKieMojo.java, kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/GenerateModelMojo.java
Introduces Reactive REST resources when running on Quarkus.
=> KOGITO-648 - Generate reactive REST endpoint instead of the default one

data-index/README.md
=> docs: Simple readme file for data index service

kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/ProcessClassesMojo.java, kogito-maven-plugin/src/main/resources/META-INF/plexus/components.xml
@evacchi these two where removed by https://github.com/kiegroup/kogito-runtimes/pull/260 which breaks persistence completely for kogito maven plugin.
=> bring back removed persistence generator for kogito maven plugin

addons/jobs/jobs-service/pom.xml, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/executor/HttpJobExecutor.java, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/model/ScheduledJob.java, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/scheduler/BaseTimerJobScheduler.java, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/scheduler/impl/VertxJobScheduler.java, addons/jobs/jobs-service/src/test/java/org/kie/kogito/jobs/service/executor/HttpJobExecutorTest.java, addons/jobs/jobs-service/src/test/java/org/kie/kogito/jobs/service/scheduler/BaseTimerJobSchedulerTest.java, addons/jobs/jobs-service/src/test/java/org/kie/kogito/jobs/service/scheduler/impl/VertxJobSchedulerTest.java
Adding more unit tests on Jobs Service.
@mswiderski 
@cristianonicolai
=> KOGITO-672 - [Job Service] increase test coverage

data-index/data-index-service/pom.xml, data-index/data-index-service/src/main/resources/application.properties, data-index/data-index-service/src/test/java/org/kie/kogito/index/InfinispanServerTestResource.java, data-index/data-index-service/src/test/java/org/kie/kogito/index/KeycloakServerTestResource.java, data-index/data-index-service/src/test/java/org/kie/kogito/index/service/KeycloakIntegrationIndexingServiceTest.java, data-index/data-index-service/src/test/resources/application.properties
Assembly:
- https://github.com/kiegroup/kogito-bom/pull/78
- https://github.com/kiegroup/kogito-runtimes/pull/266
=> KOGITO-772 - Upgrade Quarkus to version 1.1.0

addons/jobs/jobs-service/docker-compose.yaml, addons/jobs/jobs-service/pom.xml, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/converters/HttpConverters.java, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/events/JobDataEvent.java, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/executor/HttpJobExecutor.java, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/json/JacksonConfiguration.java, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/model/ScheduledJob.java, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/qualifier/Repository.java, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/repository/ReactiveJobRepository.java, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/repository/impl/BaseReactiveJobRepository.java, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/repository/impl/InMemoryJobRepository.java, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/repository/impl/JobRepositoryDelegate.java, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/repository/infinispan/InfinispanConfiguration.java, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/repository/infinispan/InfinispanJobRepository.java, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/repository/infinispan/marshaller/BaseMarshaller.java, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/resource/JobResource.java, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/scheduler/BaseTimerJobScheduler.java, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/scheduler/JobSchedulerManager.java, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/scheduler/impl/VertxJobScheduler.java, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/stream/AvailableStreams.java, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/stream/JobStreams.java, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/stream/KafkaJobStreams.java, addons/jobs/jobs-service/src/main/java/org/kie/kogito/jobs/service/utils/FunctionsUtil.java, addons/jobs/jobs-service/src/main/resources/application.properties, addons/jobs/jobs-service/src/test/java/org/kie/kogito/jobs/service/executor/HttpJobExecutorTest.java, addons/jobs/jobs-service/src/test/java/org/kie/kogito/jobs/service/resource/JobResourceTest.java, addons/jobs/jobs-service/src/test/java/org/kie/kogito/jobs/service/scheduler/BaseTimerJobSchedulerTest.java, addons/jobs/jobs-service/src/test/resources/application.properties
This is the initial version, it is publishing events on a Kafka topic.
@mswiderski @cristianonicolai can you take a look and we can see if it will be necessary any adjustments for the proper consumption on the data-index service and any other comments are welcomed.
**It depends on https://github.com/kiegroup/kogito-runtimes/pull/266 to be merged before.**
=> KOGITO-577 - [Job Service] Integration with Data Index

addons/pom.xml, addons/predictions/.gitignore, addons/predictions/kogito-predictions-api/.gitignore, addons/predictions/kogito-predictions-api/pom.xml, addons/predictions/kogito-predictions-api/src/main/java/org/kie/kogito/prediction/api/PredictionAwareHumanTaskLifeCycle.java, addons/predictions/kogito-predictions-api/src/main/java/org/kie/kogito/prediction/api/PredictionOutcome.java, addons/predictions/kogito-predictions-api/src/main/java/org/kie/kogito/prediction/api/PredictionService.java, addons/predictions/kogito-predictions-api/src/test/java/org/kie/kogito/prediction/api/PredictionAwareHumanTaskLifeCycleTest.java, addons/predictions/kogito-predictions-api/src/test/resources/BPMN2-UserTask.bpmn2, addons/predictions/kogito-predictions-api/src/test/resources/logback-test.xml, addons/predictions/kogito-predictions-smile-addon/.gitignore, addons/predictions/kogito-predictions-smile-addon/pom.xml, addons/predictions/kogito-predictions-smile-addon/src/main/java/org/kie/kogito/predictions/smile/AbstractPredictionEngine.java, addons/predictions/kogito-predictions-smile-addon/src/main/java/org/kie/kogito/predictions/smile/AttributeType.java, addons/predictions/kogito-predictions-smile-addon/src/main/java/org/kie/kogito/predictions/smile/RandomForestConfiguration.java, addons/predictions/kogito-predictions-smile-addon/src/main/java/org/kie/kogito/predictions/smile/SmileRandomForest.java, addons/predictions/kogito-predictions-smile-addon/src/test/java/org/kie/kogito/predictions/smile/SmileRandomForestPredictionTest.java, addons/predictions/kogito-predictions-smile-addon/src/test/resources/BPMN2-UserTask.bpmn2, addons/predictions/kogito-predictions-smile-addon/src/test/resources/logback-test.xml, addons/predictions/pom.xml, api/kogito-api/src/main/java/org/kie/api/runtime/process/WorkItemHandler.java, jbpm/jbpm-bpmn2/src/main/java/org/kie/kogito/process/bpmn2/BpmnProcess.java, jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/objects/TestWorkItemHandler.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/LightWorkItemManager.java
depends on https://github.com/kiegroup/kogito-bom/pull/75
examples can be found in kogito quick starts 
https://github.com/mswiderski/kogito-quickstarts/tree/master/kogito-usertasks-with-predictions-quarkus
https://github.com/mswiderski/kogito-quickstarts/tree/master/kogito-usertasks-with-predictions-springboot
best to use spring boot as it does not depend on master of quarkus so does not require additional work.
@ruivieira @DuncanDoyle you might be interested in this....
=> KOGITO-807 - Prediction service as add on for user tasks

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/AbstractCompositeNodeVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/CompositeContextNodeVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessToExecModelGenerator.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/UserTaskModelMetaData.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/EmbeddedSubProcessTest.java, kogito-codegen/src/test/resources/subprocess/EmbeddedSubProcessWithUserTask.bpmn2
=> KOGITO-887 - User tasks from embedded subprocess should be exposed as REST endpoints

addons/persistence/infinispan-persistence-addon/src/test/java/org/kie/kogito/infinispan/MockCacheProcessInstancesTest.java, addons/persistence/infinispan-persistence-addon/src/test/resources/BPMN2-UserTask-NoActors.bpmn2, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/humantask/HumanTaskWorkItemImpl.java
=> KOGITO-1150 - no tasks are returned when work item owner == ''

pom.xml
There is an issue in IntelliJ Idea which prevents running tests
in a project with such a configuration.
=> Move jacoco argline lazy evaluation to a profile

pom.xml
https://issues.redhat.com/browse/KOGITO-1259
=> [KOGITO-1259] Added missing distributionmanagement tag

pom.xml
Assembly:
- https://github.com/kiegroup/kogito-apps/pull/69
- https://github.com/kiegroup/kogito-runtimes/pull/321
=> KOGITO-1211 - Move sonar-maven-plugin into default plugin management

jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/StartEventHandler.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/CompositeContextNodeVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/EventSubprocessNodeVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessToExecModelGenerator.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/StartNodeVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/TriggerMetaData.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowNodeContainerFactory.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowProcessFactory.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/CompositeNodeFactory.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/EventSubProcessNodeFactory.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/StartNodeFactory.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/process/AbstractResourceGenerator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/EventSubProcessTest.java, kogito-codegen/src/test/resources/event-subprocess/EventSubprocessSignal.bpmn2, kogito-codegen/src/test/resources/event-subprocess/EventSubprocessSignalWithData.bpmn2
@ge0ffrey @Christopher-Chianelli here is the support for signal event subprocess, please give it a go
=> KOGITO-1217 - Event Based Subprocess Support - signal start event

archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/pom.xml
to test:
```
mvn archetype:generate -DarchetypeCatalog=local -DarchetypeGroupId=org.kie.kogito -DarchetypeArtifactId=kogito-quarkus-archetype -DarchetypeVersion=8.0.0-SNAPSHOT -DgroupId=com.company -DartifactId=sample-kogito
```
=> KOGITO-1298: Update quarkus archetype to use our new bom

archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/pom.xml
missing maven plugin in previous PR
@jomarko please verify all it's working now
=> KOGITO-1298: Update quarkus archetype to use our new bom (fix maven plugin)

addons/jobs/jobs-api/pom.xml, addons/jobs/jobs-api/src/main/java/org/kie/kogito/jobs/api/Job.java, addons/jobs/jobs-api/src/main/java/org/kie/kogito/jobs/api/URIBuilder.java, addons/jobs/jobs-api/src/test/java/org/kie/kogito/jobs/api/URIBuilderTest.java, addons/jobs/jobs-management-common/pom.xml, addons/jobs/jobs-management-common/src/main/java/org/kie/kogito/jobs/management/RestJobsService.java, addons/jobs/jobs-management-common/src/test/java/org/kie/kogito/jobs/management/RestJobsServiceTest.java, addons/jobs/jobs-management-quarkus-addon/pom.xml, addons/jobs/jobs-management-quarkus-addon/src/main/java/org/kie/kogito/jobs/management/quarkus/VertxJobsService.java, addons/jobs/jobs-management-quarkus-addon/src/test/java/org/kie/kogito/jobs/management/quarkus/VertxJobsServiceTest.java, addons/jobs/jobs-management-springboot-addon/pom.xml, addons/jobs/jobs-management-springboot-addon/src/main/java/org/kie/kogito/jobs/management/springboot/SpringRestJobsService.java, addons/jobs/jobs-management-springboot-addon/src/test/java/org/kie/kogito/jobs/management/springboot/SpringRestJobsServiceTest.java, addons/jobs/pom.xml, bom/pom.xml
Fix URL without port on service configuration.
https://github.com/kiegroup/kogito-apps/pull/94
=> KOGITO-1163 Call to Jobs service fails on OpenShift 

archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/kmodule.xml, archetypes/kogito-springboot-archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/kmodule.xml
=> KOGITO-1420: Remove kmodule.xml from archetypes

Jenkinsfile, Jenkinsfile-sonarcloud-daily, Jenkinsfile.deploy
Relates to https://github.com/kiegroup/kie-jenkins-scripts/pull/711
=> KOGITO-1486 - Update Jenkins Maven to version 3.6.2

Jenkinsfile, Jenkinsfile-sonarcloud-daily, Jenkinsfile.deploy, archetypes/kogito-quarkus-archetype/pom.xml, archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/pom.xml, archetypes/kogito-springboot-archetype/pom.xml, archetypes/kogito-springboot-archetype/src/main/resources/archetype-resources/pom.xml, drools/drools-compiler/src/test/java/org/drools/compiler/integrationtests/Misc2Test.java, drools/drools-core/src/test/java/org/drools/core/meta/org/test/AnotherKlassImpl.java, drools/drools-core/src/test/java/org/drools/core/meta/org/test/KlassImpl.java, drools/drools-core/src/test/java/org/drools/core/meta/org/test/SubKlassImpl.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/AbstractCodegenTest.java, pom.xml
Assembly:
- https://github.com/kiegroup/kogito-examples/pull/159
- https://github.com/kiegroup/kogito-apps/pull/117
- https://github.com/kiegroup/kogito-runtimes/pull/386
=> KOGITO-1545 - Upgrade to Java 11

drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/DMNKogito.java, drools/kogito-dmn/src/test/java/org/kie/kogito/dmn/DMNKogitoTest.java, drools/kogito-scenario-simulation/src/main/java/org/kogito/scenariosimulation/runner/KogitoDMNScenarioRunnerHelper.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DMNRestResourceGenerator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionContainerGenerator.java, pom.xml
Requires https://github.com/kiegroup/drools/pull/2831
=> KOGITO-1575 DMN assembler-free ikb-free DMNRuntime

jbpm/jbpm-serverless-workflow/pom.xml, jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/api/deserializers/DefaultChoiceOperatorDeserializer.java, jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/api/deserializers/DefaultStateTypeDeserializer.java, jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/api/deserializers/EventsActionsActionModeDeserializer.java, jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/api/deserializers/OperationStateActionModeDeserializer.java, jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/api/deserializers/StateDeserializer.java, jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/api/deserializers/StringValueDeserializer.java, jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/api/mapper/WorkflowModule.java, jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/spi/WorkflowManagerProvider.java, jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/spi/WorkflowPropertySourceProvider.java, jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/spi/WorkflowValidatorProvider.java
@cristianonicolai this fixes the sonar reported issues and the two you found in https://github.com/kiegroup/kogito-runtimes/pull/397
=> serverless workflow - fix sonar reported issues

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/AbstractVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ModelMetaData.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/context/variable/Variable.java, jbpm/jbpm-flow/src/test/java/org/jbpm/process/core/context/variable/VariableTest.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/VariableTest.java, kogito-codegen/src/test/resources/servicetask/ServiceTaskWithReservedNameVariable.bpmn2
- Allow using reserved words as variable names
- Jackson annotation used to keep the variable name
- Sanitized name on variables
=> KOGITO-1306 Error during code generation when using java reserved word on variable

.gitignore, Jenkinsfile.deploy, Jenkinsfile.quarkus
https://issues.redhat.com/browse/KOGITO-1666
=> [master] [KOGITO-1666] Updated pipelines to checkout from env.BRANCH_NAME

.gitignore, Jenkinsfile.deploy, Jenkinsfile.quarkus
cherry-pick: https://github.com/kiegroup/kogito-runtimes/pull/409
=> [0.9.x] [KOGITO-1666] [cherry-pick] Updated pipelines to checkout from env.BRANCH_NAME

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ModelMetaData.java
It's just a typo fix so don't have a Jira. Will create one if needed tho.
=> Fix typo in ModelMetaData

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/AbstractVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ModelMetaData.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/context/variable/Variable.java, jbpm/jbpm-flow/src/test/java/org/jbpm/process/core/context/variable/VariableTest.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/VariableTest.java, kogito-codegen/src/test/resources/servicetask/ServiceTaskWithReservedNameVariable.bpmn2
Cherry-pick e7850962916d0c2ae3c356e04d672a6b27a49f8a for issue  KOGITO-1306, allow variables with java reserved names.
=> [0.9.x] KOGITO-1306 Error during code generation when using java reserved word on variable

kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
Cherry-pick commit 915bc8cea27cdea73cf9e48a6f0c981b170ae2f0
=> KOGITO-1564 - 0.9.x - Cherry pick kogito-runtimes: cloud events are empty in native mode

jbpm/jbpm-serverless-workflow/pom.xml, jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/parser/ServerlessWorkflowParser.java, jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/parser/core/ServerlessWorkflowFactory.java, jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/parser/util/ServerlessWorkflowUtils.java, jbpm/jbpm-serverless-workflow/src/main/resources/schema/workflow-01/choices/singlechoice.json, jbpm/jbpm-serverless-workflow/src/main/resources/schema/workflow-01/states/relaystate.json, jbpm/jbpm-serverless-workflow/src/test/java/org/jbpm/serverless/workflow/BaseServerlessTest.java, jbpm/jbpm-serverless-workflow/src/test/java/org/jbpm/serverless/workflow/ServlerlessWorkflowParsingTest.java, jbpm/jbpm-serverless-workflow/src/test/java/org/jbpm/serverless/workflow/TestNodeContainer.java, jbpm/jbpm-serverless-workflow/src/test/java/org/jbpm/serverless/workflow/WorkflowFactoryTest.java, jbpm/jbpm-serverless-workflow/src/test/java/org/jbpm/serverless/workflow/WorkflowUtilsTest.java, jbpm/jbpm-serverless-workflow/src/test/resources/exec/single-relay-state.sw.json, jbpm/jbpm-serverless-workflow/src/test/resources/exec/single-relay-state.sw.yml, jbpm/jbpm-serverless-workflow/src/test/resources/exec/switch-state.sw.json, jbpm/jbpm-serverless-workflow/src/test/resources/exec/switch-state.sw.yml, jbpm/jbpm-serverless-workflow/src/test/resources/specexamples/helloworld.sw.json, jbpm/jbpm-serverless-workflow/src/test/resources/specexamples/helloworld.sw.yml, jbpm/jbpm-serverless-workflow/src/test/resources/specexamples/jobmonitoring.sw.json, jbpm/jbpm-serverless-workflow/src/test/resources/specexamples/jobmonitoring.sw.yml, kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/ServerlessWorkflowTest.java, kogito-codegen/src/test/resources/serverless/single-relay-state.sw.json, kogito-codegen/src/test/resources/serverless/single-relay-state.sw.yml, kogito-codegen/src/test/resources/serverless/switch-state-deny.sw.json, kogito-codegen/src/test/resources/serverless/switch-state-deny.sw.yml, kogito-codegen/src/test/resources/serverless/switch-state.sw.json, kogito-codegen/src/test/resources/serverless/switch-state.sw.yml, pom.xml
* Add support for Relay state
* Add support for Switch state
* Update support for script function
* Add missing tests
=> KOGITO-1704 + KOGITO-1124 - Serverless Workflow - Support for Relay and Switch States

pom.xml
Assembly:
- https://github.com/kiegroup/kogito-apps/pull/154
- https://github.com/kiegroup/kogito-runtimes/pull/420
=> KOGITO-1405 - Add testcontainer Kafka version

kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java, kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/GenerateModelMojo.java
Just adds support for .sw.json and .sw.yml extensions for serverless workflow
Need this so serverless workflow runs on spring boot
=> KOGITO-1821 - Support for Serverless Workflow in Kogito Maven Plugin

api/kogito-services/src/main/java/org/kie/kogito/services/event/impl/ProcessInstanceEventBatch.java, api/kogito-services/src/test/java/org/kie/kogito/services/event/impl/ProcessInstanceEventBatchTest.java
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/425
- https://github.com/kiegroup/kogito-apps/pull/162
=> KOGITO-1732 - Ensure service url is always present in endpoint

pom.xml
Cherry pick of https://github.com/kiegroup/kogito-runtimes/pull/420
Assembly:
- https://github.com/kiegroup/kogito-apps/pull/164
- https://github.com/kiegroup/kogito-runtimes/pull/432
=> KOGITO-1405 - Add testcontainer Kafka version (#420)

.gitignore, README.md
See: https://issues.redhat.com/browse/KOGITO-1770
Small fix for the examples renaming
=> [master][KOGITO-1770] - Renaming examples and README links

api/kogito-services/src/main/java/org/kie/kogito/services/event/impl/ProcessInstanceEventBatch.java, api/kogito-services/src/test/java/org/kie/kogito/services/event/impl/ProcessInstanceEventBatchTest.java
Cherry pick of https://github.com/kiegroup/kogito-runtimes/pull/425
Assembly:
- https://github.com/kiegroup/kogito-apps/pull/175
- https://github.com/kiegroup/kogito-runtimes/pull/441
=> KOGITO-1732 - Ensure service url is always present in endpoint (#425)

.gitignore, README.md
Cherry-pick for: https://github.com/kiegroup/kogito-images/pull/132
=> [0.9.x][KOGITO-1770] - Renaming examples and README links (#431)

drools/drools-compiler/src/main/java/org/drools/compiler/rule/builder/PatternBuilder.java, drools/drools-compiler/src/main/java/org/drools/compiler/rule/builder/RuleBuildContext.java, drools/drools-core-reflective/src/main/java/org/drools/reflective/util/ClassUtils.java, drools/drools-core/src/main/java/org/drools/core/QueryResultsRowImpl.java, drools/drools-core/src/main/java/org/drools/core/base/mvel/MVELCompilationUnit.java, drools/drools-core/src/main/java/org/drools/core/event/rule/impl/SerializableActivation.java, drools/drools-core/src/main/java/org/drools/core/factmodel/AccessibleFact.java, drools/drools-core/src/main/java/org/drools/core/factmodel/ClassDefinition.java, drools/drools-core/src/main/java/org/drools/core/reteoo/BaseTuple.java, drools/drools-core/src/main/java/org/drools/core/rule/Declaration.java, drools/drools-core/src/main/java/org/drools/core/rule/EvalCondition.java, drools/drools-core/src/main/java/org/drools/core/rule/PredicateConstraint.java, drools/drools-core/src/main/java/org/drools/core/rule/builder/dialect/asm/GeneratorHelper.java, drools/drools-core/src/main/java/org/drools/core/rule/constraint/MvelConstraint.java, drools/drools-core/src/main/java/org/drools/core/rule/constraint/XpathConstraint.java, drools/drools-core/src/main/java/org/drools/core/runtime/rule/impl/RowAdapter.java, drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/DMNKogito.java, drools/kogito-dmn/src/test/java/org/kie/kogito/dmn/DMNKogitoTest.java, drools/kogito-scenario-simulation/src/main/java/org/kogito/scenariosimulation/runner/KogitoDMNScenarioRunnerHelper.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DMNRestResourceGenerator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionContainerGenerator.java, kogito-codegen/src/test/resources/org/kie/kogito/codegen/unit/RuleUnitDelete.drl, kogito-codegen/src/test/resources/org/kie/kogito/codegen/unit/RuleUnitModify.drl, kogito-codegen/src/test/resources/org/kie/kogito/codegen/unit/RuleUnitQuery.drl, kogito-quarkus-extension/integration-test/src/test/resources/adult.txt, pom.xml
To be merged, as soon as 7.36.0.Final is finalized
Needed backport of https://github.com/kiegroup/kogito-runtimes/pull/395
@mariofusco aligned a few required fixes from Drools 7
=> KOGITO-1853: Bump to KIE 7.36.0.Final + Backport KOGITO-1575 (0.9.x)

archetypes/kogito-springboot-archetype/src/main/resources/archetype-resources/pom.xml
cherry pick https://github.com/kiegroup/kogito-runtimes/pull/453
=> KOGITO-1892: Spring Boot Archetype: use version property (master)

scripts/release/05-tag-and-push-local-release-branches.sh
Reverts kiegroup/kogito-runtimes#458
=> Revert "Release script - Force tag update"

README.md
=> Add zulip badge to README

.github/pull_request_template.md
- Remove need for using []
- Update link to contributors guide
=> KOGITO-1887 - Git PR template updates

api/kogito-api/src/main/java/org/kie/kogito/jobs/ProcessInstanceJobDescription.java, api/kogito-api/src/main/java/org/kie/kogito/jobs/ProcessJobDescription.java, api/kogito-services/src/main/java/org/kie/services/jobs/impl/InMemoryJobService.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/AbstractProcessRuntimeServiceProvider.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessRuntimeImpl.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcess.java
=> Code formatting and debug logs

Jenkinsfile.deploy, Jenkinsfile.quarkus
=> KOGITO-1868 - Add Zulip notification to daily builds

pom.xml
=> KOGITO-2082 - Upgrade kogito-apps to use Quarkus version 1.4.1

kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/decision/DecisionCodegenTest.java, kogito-codegen/src/test/resources/decision-empty-name/vacationDays.dmn
See https://issues.redhat.com/browse/KOGITO-2016 for the issue description.
=> [KOGITO-2016] Better error message when a DMN model doesn't have a name

Jenkinsfile.quarkus, archetypes/kogito-quarkus-archetype/pom.xml, kogito-quarkus-extension/pom.xml
=> KOGITO-2107 - Remove Quarkus version override for kogito-apps

pom.xml
=> KOGITO-1644 - Add testcontainers junit to managed version

archetypes/kogito-quarkus-archetype/pom.xml, archetypes/kogito-quarkus-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/src/test/java/GreetingsTest.java, archetypes/kogito-quarkus-archetype/src/test/resources/projects/it-basic/archetype.properties, archetypes/kogito-springboot-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, archetypes/kogito-springboot-archetype/src/main/resources/archetype-resources/pom.xml, archetypes/kogito-springboot-archetype/src/main/resources/archetype-resources/src/test/java/GreetingsTest.java, archetypes/kogito-springboot-archetype/src/test/resources/projects/it-basic/archetype.properties
archetypes are currently tested manually. Add integration tests so that we can make sure that the code that is generated works as expected.
https://issues.redhat.com/browse/KOGITO-2136
---
=> KOGITO-2136 Add integration tests to archetypes

Jenkinsfile.drools
https://issues.redhat.com/browse/KOGITO-1895
Add a Jenkinsfile to set-up a periodic build for Drools snapshot
=> KOGITO-1895 Setup CI Build against Drools SNAPSHOT

pom.xml
Before we were (I guess mistakenly) taken that dependency from quarkus bom, see https://github.com/quarkusio/quarkus/issues/8694#issuecomment-627772609
=> add org.testcontainers:junit-jupiter to pom

scripts/release/05-tag-and-push-local-release-branches.sh
=> KOGITO-2058 - Override tag if already exists

Jenkinsfile.quarkus
=> KOGITO-2206 - Extend timeout for Kogito Quarkus daily build

Jenkinsfile.release
=> KOGITO-2036 - Migrate Kogito runtime release pipeline to Jenkins file

Jenkinsfile, Jenkinsfile-sonarcloud-daily, Jenkinsfile.deploy, Jenkinsfile.drools, Jenkinsfile.quarkus, Jenkinsfile.release, pom.xml
=> KOGITO-2233 - Increase build timeout and extend Maven memory

Jenkinsfile-sonarcloud-daily
=> KOGITO-2239 - Add Zulip notification to Sonar daily build

pom.xml
=> KOGITO-2238 - Fix Java parsing error for Sonar analysis

kogito-codegen/src/test/java/org/kie/kogito/codegen/RuleUnitCompilerTest.java, kogito-quarkus-extension/integration-test-hot-reload/pom.xml
https://issues.redhat.com/browse/KOGITO-2272
=> [KOGITO-2272] Hot reload test stuck if deployment is not available

Jenkinsfile.deploy
https://issues.redhat.com/browse/KOGITO-2342
Needed by S2I builds
=> KOGITO-2342 Add back deployment of examples in nightly pipeline

Jenkinsfile
https://issues.redhat.com/browse/KOGITO-2378
PR list:
- https://github.com/kiegroup/kogito-runtimes/pull/542
- https://github.com/kiegroup/kogito-examples/pull/269
- https://github.com/kiegroup/kogito-apps/pull/248
=> [KOGITO-2378] Make Jenkins pull from master before the build

addons/persistence/filesystem-persistence-addon/src/test/java/org/kie/persistence/filesystem/FileSystemProcessInstancesTest.java, api/kogito-api/src/main/java/org/kie/kogito/process/ProcessInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/marshalling/impl/AbstractProtobufProcessInstanceMarshaller.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/ServiceTaskTest.java
Start date is now fixed in startFrom method, which means
internalSetStartDate is not longer internal.
https://issues.redhat.com/browse/KOGITO-1787
=> KOGITO-1787 NullPointerException X-KOGITO-StartFromNode header

Jenkinsfile.release
=> KOGITO-2443 - Build parameters failed to be replaced

integration-tests/integration-tests-kogito-plugin/pom.xml
=> KOGITO-2397 - Add name to maven plugin integration test module

bom/pom.xml
Jira: https://issues.redhat.com/browse/KOGITO-2474
This PR adds the test-jar module of the persistence-commons-infinispan module to the BOM. 
=> KOGITO 2474 - update bom with test-jar for persistence-commons-infinispan

jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/parser/ServerlessWorkflowParser.java, jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/parser/core/ServerlessWorkflowFactory.java, jbpm/jbpm-serverless-workflow/src/test/java/org/jbpm/serverless/workflow/ServlerlessWorkflowParsingTest.java, jbpm/jbpm-serverless-workflow/src/test/java/org/jbpm/serverless/workflow/WorkflowFactoryTest.java, jbpm/jbpm-serverless-workflow/src/test/resources/exec/integration-operation.sw.json, jbpm/jbpm-serverless-workflow/src/test/resources/exec/integration-operation.sw.yml
allows to define and call any present camel route and get results from it
=> KOGITO-2480 - Serverless Workflow Specification - Add support for integration type functions

pom.xml
=> KOGITO-2503 - Upgrade testcontainers dependency

archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/pom.xml
=> KOGITO-2479 - Use quarkus.version property for quarkus-maven-plugin

integration-tests/integration-tests-kogito-plugin/src/it/integration-tests-kogito-plugin-it/pom.xml, integration-tests/integration-tests-springboot/pom.xml, pom.xml
=> KOGITO-2476 - Skip Maven invoker plugin tests when using -DskipTests

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/WorkItemNodeVisitor.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/data/WorkItemParamsService.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/WorkItemParamsTest.java, kogito-codegen/src/test/resources/servicetask/WorkItemParams.bpmn
Fix https://issues.redhat.com/browse/KOGITO-2484
=> [KOGITO-2484] Add support for Int,Bool,Float workItem params

integration-tests/integration-tests-kogito-plugin/src/it/integration-tests-kogito-plugin-it/pom.xml, integration-tests/integration-tests-kogito-plugin/src/it/integration-tests-kogito-plugin-it/src/main/resources/org/acme/travels/singaltest.bpmn2, integration-tests/integration-tests-kogito-plugin/src/it/integration-tests-kogito-plugin-it/src/test/java/org/acme/travels/SignalProcessTest.java, integration-tests/integration-tests-quarkus/pom.xml, integration-tests/integration-tests-quarkus/src/main/resources/singaltest.bpmn2, integration-tests/integration-tests-quarkus/src/test/java/org/kie/kogito/integrationtests/quarkus/SignalProcessTest.java, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/pom.xml, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/main/java/org/kie/kogito/integrationtests/springboot/KogitoSpringbootApplication.java, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/main/resources/singaltest.bpmn2, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/SignalProcessTest.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/process/AbstractResourceGenerator.java, kogito-codegen/src/main/resources/class-templates/RestResourceSignalTemplate.java, kogito-codegen/src/main/resources/class-templates/spring/SpringRestResourceSignalTemplate.java, pom.xml
=> KOGITO-2387 - Generate signal REST endpoint even without data output

kogito-codegen/src/main/java/org/kie/kogito/codegen/JsonSchemaGenerator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/json/JsonUtils.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/JsonSchemaGeneratorTest.java, kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/ProcessClassesMojo.java, kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
Adding "kogito.jsonSchema.version" property for maven and quarkus
Adding "date-time" format for Date types.
=> [KOGITO-2511] Changes in Schema generation

Jenkinsfile.deploy, Jenkinsfile.deploy.new
https://issues.redhat.com/browse/KOGITO-2570
as `mvn clean deploy` will remove test reports.
=> KOGITO-2570 Save reports after test execution

drools/drools-core/src/main/java/org/drools/core/process/instance/WorkItem.java, drools/drools-core/src/main/java/org/drools/core/process/instance/impl/WorkItemImpl.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/LightProcessRuntime.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/WorkItemNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java, jbpm/jbpm-flow/src/test/java/org/kie/kogito/process/impl/AbstractProcessInstanceTest.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/UserTaskTest.java
=> KOGITO-2207 - Create process without adding to ProcessInstanceManager

api/kogito-api/src/main/java/org/kie/api/definition/process/WorkflowProcess.java, api/kogito-api/src/main/java/org/kie/api/runtime/process/WorkflowProcessInstance.java, api/kogito-api/src/main/java/org/kie/kogito/process/flexible/Milestone.java, api/kogito-services/pom.xml, api/kogito-services/src/main/java/org/kie/kogito/services/event/impl/MilestoneEventBody.java, api/kogito-services/src/main/java/org/kie/kogito/services/event/impl/ProcessInstanceEventBatch.java, api/kogito-services/src/main/java/org/kie/kogito/services/event/impl/ProcessInstanceEventBody.java, api/kogito-services/src/test/java/org/kie/kogito/services/event/impl/ProcessInstanceEventBatchTest.java, drools/drools-compiler/src/test/java/org/drools/compiler/integrationtests/WorkingMemoryLoggerTest.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/WorkflowProcess.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/impl/WorkflowProcessImpl.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/PublishEventTest.java, kogito-codegen/src/test/java/org/kie/kogito/process/impl/MilestoneTest.java, kogito-codegen/src/test/java/org/kie/kogito/process/impl/ProcessTestUtils.java
https://issues.redhat.com/browse/KOGITO-2421
Include information about milestones, in cloud events produced by the core engine.
=> KOGITO-2421 Add Milestones to runtime events

addons/persistence/infinispan-persistence-addon/src/test/java/org/kie/kogito/infinispan/MockCacheProcessInstancesTest.java, jbpm/jbpm-bpmn2/src/main/java/org/kie/kogito/process/bpmn2/BpmnProcess.java, jbpm/jbpm-bpmn2/src/main/java/org/kie/kogito/process/bpmn2/BpmnProcessCompiler.java, jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/canonical/ActivityGenerationModelTest.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcess.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/marshalling/ProcessInstanceMarshaller.java, jbpm/jbpm-flow/src/test/java/org/kie/kogito/process/impl/AbstractProcessInstanceTest.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/process/ProcessGenerationTest.java
Follow up changes to https://github.com/kiegroup/kogito-runtimes/pull/586
=> KOGITO-2421 Remove remaining references to legacy process

Jenkinsfile, Jenkinsfile.deploy, Jenkinsfile.deploy.new
JIRA: https://issues.redhat.com/browse/KOGITO-2592
Description: Include persistence and events profiles in the Jenkinsfile.
=> KOGITO-2592: Include persistence and events profiles in Jenkinsfile

addons/tracing/tracing-decision-common/src/main/java/org/kie/kogito/tracing/decision/event/trace/TraceHeader.java
jira: https://issues.redhat.com/browse/KOGITO-2519
This PR cleans up the TraceHeader constructor. 
=> KOGITO-2519 - Update TraceHeader wrong timestamp handling

addons/persistence/infinispan-persistence-addon/src/main/java/org/kie/kogito/infinispan/CacheProcessInstances.java, api/kogito-api/src/main/java/org/kie/kogito/process/ProcessInstances.java, jbpm/jbpm-bpmn2/src/main/java/org/kie/kogito/process/bpmn2/BpmnProcess.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/AbstractProcessInstanceFactory.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/InternalProcessRuntime.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/LightProcessRuntimeContext.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessRuntimeContext.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/ContextInstanceFactoryRegistry.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/ProcessInstanceImpl.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/instance/RuleFlowProcessInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/LambdaSubProcessNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcess.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/marshalling/ProcessInstanceMarshaller.java
- Removed unnecessary casts
- Removed references to legacy process
- Code formatting
=> Code style changes

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/RuleSetNodeVisitor.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/RuleSetNodeFactory.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/RuleSetNodeInstance.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/process/ProcessGenerationTest.java, kogito-codegen/src/test/resources/ruletask/BusinessRuleTaskWithInputExpression.bpmn, kogito-codegen/src/test/resources/ruletask/BusinessRuleTaskWithInputExpression.dmn
Fix https://issues.redhat.com/browse/KOGITO-2656
=> [KOGITO-2656] Generate code for ruleSet mappings and params

bom/pom.xml
Adding the mvn module for the Task Console Quarkus App.
This is part of an ensemble, please merge with:
https://github.com/kiegroup/kogito-runtimes/pull/603
https://github.com/kiegroup/kogito-apps/pull/303
=> KOGITO-2097: Task Console Quarkus App

Jenkinsfile.drools
https://issues.redhat.com/browse/KOGITO-2710
=> KOGITO-2710 Correct Jenkinsfile drools

drools/kogito-dmn/pom.xml, pom.xml
=> KOGITO-2705 - Add kie-dmn-jpmml and kie-dmn-validation to parent pom

pom.xml
JIRA: https://issues.redhat.com/browse/KOGITO-2704
Description: Upgrade surefire version to use the same than in Kogito Examples repository.
=> KOGITO-2704: Upgrade surefire plugin version

pom.xml
https://issues.redhat.com/browse/KOGITO-2782
=> [KOGITO-2782] Upgrade kie7 to 7.40.0.Final

addons/process-management/process-management-addon/src/main/java/org/kie/kogito/process/management/ProcessInstanceManagementResource.java, addons/process-management/process-management-common/src/main/java/org/kie/kogito/process/management/BaseProcessInstanceManagementResource.java, addons/process-management/process-management-common/src/main/java/org/kie/kogito/process/management/ProcessInstanceManagement.java, addons/process-management/process-management-common/src/test/java/org/kie/kogito/process/management/BaseProcessInstanceManagementResourceTest.java, addons/process-management/process-management-springboot-addon/src/main/java/org/kie/kogito/process/management/ProcessInstanceManagementRestController.java, integration-tests/integration-tests-kogito-plugin/src/it/integration-tests-kogito-plugin-it/pom.xml, integration-tests/integration-tests-kogito-plugin/src/it/integration-tests-kogito-plugin-it/src/test/java/org/acme/travels/ManagementAddOnTest.java, integration-tests/integration-tests-quarkus/pom.xml, integration-tests/integration-tests-quarkus/src/test/java/org/kie/kogito/integrationtests/quarkus/ManagementAddOnTest.java, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/pom.xml, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/AdHocFragmentsTest.java, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/DSCoercionTest.java, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/ElementAtIndexTest.java, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/JsonSchemaTest.java, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/ManagementAddOnTest.java, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/SignalProcessTest.java
Documentation PR: https://github.com/kiegroup/kie-docs/pull/2617
=> KOGITO-1133 Add support for listing process nodes via management add on

jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/HumanTaskNodeInstance.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/PublishEventTest.java
https://issues.redhat.com/browse/KOGITO-2796
=> KOGITO-2796 Adjust task name and reference name in task work item

bom/pom.xml
Jira: https://issues.redhat.com/browse/KOGITO-2121
https://issues.redhat.com/browse/KOGITO-2122
https://issues.redhat.com/browse/KOGITO-2146
Description:
Support mongodb as persistence solution for data index. 
=> [KOGITO-2121] add kogito apps mongodb storage modules in bom

api/kogito-api/src/main/java/org/kie/api/runtime/process/WorkItemHandler.java, api/kogito-api/src/main/java/org/kie/api/runtime/process/WorkItemManager.java, api/kogito-api/src/main/java/org/kie/kogito/process/ProcessInstance.java, api/kogito-api/src/main/java/org/kie/kogito/process/workitem/LifeCycle.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/LightWorkItemManager.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/humantask/HumanTaskWorkItemHandler.java, jbpm/jbpm-flow/src/main/java/org/jbpm/util/JsonSchemaUtil.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java, jbpm/jbpm-flow/src/test/java/org/jbpm/util/JsonSchemaUtilTest.java, kogito-codegen/src/main/resources/class-templates/RestResourceUserTaskTemplate.java, kogito-codegen/src/main/resources/class-templates/spring/SpringRestResourceUserTaskTemplate.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/UserTaskTest.java
Creating as Draft since this requires user and group to be passed in the API (so we should not commit till this information is available at client side
=> [KOGITO-2736] Removing allowedPhases from ProcessInstance

Jenkinsfile
https://issues.redhat.com/browse/KOGITO-2837
=> KOGITO-2837 PR check: checkout all repos at once

pom.xml
=> [DROOLS-5533] Update kie7 to 7.41.0.t20200723

drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/DMNKogito.java, drools/kogito-scenario-simulation/src/main/java/org/kogito/scenariosimulation/runner/KogitoDMNScenarioRunnerHelper.java, integration-tests/integration-tests-quarkus/src/main/java/org/kie/kogito/integrationtests/MyMathUtils.java, integration-tests/integration-tests-quarkus/src/main/resources/java_function_context.dmn, integration-tests/integration-tests-quarkus/src/test/java/org/kie/kogito/integrationtests/quarkus/JavaFNctxTest.java, integration-tests/integration-tests-quarkus/src/test/java/org/kie/kogito/integrationtests/quarkus/NativeJavaFNctxIT.java, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/main/java/org/kie/kogito/integrationtests/MyMathUtils.java, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/main/resources/java_function_context.dmn, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/JavaFNctxTest.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java
REQUIRES https://github.com/kiegroup/drools/pull/2985
(so it will require a version bump of dmn kie7)
=> KOGITO-2567 Restore Root classloader in DMNKogito

pom.xml
There is also https://github.com/kiegroup/kogito-examples/pull/261
=> Update developers section with KIE group reference

pom.xml
=> [KOGITO-2925] Update kie7 to 7.41.0

addons/tracing/tracing-decision-api/pom.xml, addons/tracing/tracing-decision-common/pom.xml, addons/tracing/tracing-decision-quarkus-addon/pom.xml, addons/tracing/tracing-decision-springboot-addon/pom.xml, bom/pom.xml
jira: https://issues.redhat.com/browse/KOGITO-2915
The artifact ids of the tracing modules have a different name respect to their folders. 
=> KOGITO-2915 - rename tracing artifacts

kogito-codegen/GUIDELINES.adoc
Add guidelines for usages of DI in the code that we generate, and the _way_ we generate it (tl;dr: favor templates, use "real" classes whenever possible, minimize the code that you _do_ generate)
=> KOGITO-1766 Add guidelines for DI in codegen

addons/persistence/infinispan-persistence-addon/pom.xml
https://issues.redhat.com/browse/KOGITO-2927
Replace infinispan query used in tests with remote client + query DSL
=> KOGITO-2927 Fix incorrect Infinispan dependency in test cases

addons/persistence/infinispan-persistence-addon/pom.xml
=> [0.13.x] KOGITO-2927 Fix incorrect Infinispan dependency in test cases

archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/src/test/resources/application.properties, integration-tests/integration-tests-quarkus/src/test/resources/application.properties
JIRA: https://issues.redhat.com/browse/KOGITO-2717
Description: Use random ports for Quarkus and Spring Boot apps in Tests
=> KOGITO-2717: Use random ports for Quarkus and Spring Boot apps in Tests

pom.xml
cherry pick https://github.com/kiegroup/kogito-runtimes/pull/665
=> [0.13.x] KOGITO-2923  Remove unnecessary Infinispan dependencies from bom

addons/persistence/infinispan-persistence-addon/src/test/java/org/kie/kogito/infinispan/InfinispanServerContainer.java, addons/persistence/infinispan-quarkus-health-addon/src/test/java/org/kie/kogito/infinispan/InfinispanServerTestResource.java, pom.xml
- https://github.com/kiegroup/kogito-runtimes/pull/671
- https://github.com/kiegroup/kogito-apps/pull/367
- https://github.com/kiegroup/kogito-examples/pull/318
=> [0.13.x] KOGITO-2921  Bump to Quarkus 1.7.0.CR1

Jenkinsfile
https://issues.redhat.com/browse/KOGITO-2976
=> KOGITO-2976 Set timeout to 6 hours

pom.xml
https://issues.redhat.com/browse/KOGITO-2921
https://github.com/kiegroup/kogito-runtimes/pull/685
https://github.com/kiegroup/kogito-examples/pull/324
=> [0.13.x] KOGITO-2921 Bump to Quarkus 1.7.0.Final

pom.xml
- https://github.com/kiegroup/kogito-runtimes/pull/682
- https://github.com/kiegroup/kogito-apps/pull/375
- https://github.com/kiegroup/kogito-examples/pull/322
=> KOGITO-2921 Bump to Quarkus 1.7.0.Final

pom.xml
https://issues.redhat.com/browse/KOGITO-3028
It is a temporary fix until JBoss team handles correctly the load balancing and artifacts deployment
=> KOGITO-3028 Update distribution management

kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
Adding event generated class to native image
=> [KOGITO-1893] service fails to receive message in native mode

kogito-test-utils/src/test/java/org/kie/kogito/kafka/KafkaClientTest.java
see https://github.com/quarkusio/quarkus/issues/8694#issuecomment-672580893
=> KOGITO-3051 Disable KafkaClientTest as it causes issues on Quarkus Ecosystem CI

Jenkinsfile.deploy.new, Jenkinsfile.promote, jenkins-tests/pom.xml, jenkins-tests/src/test/vars/JenkinsfilePromote.groovy, pom.xml
This is a PR for the following issues:
- [KOGITO-2286](https://issues.redhat.com/browse/KOGITO-2286) Kogito Runtimes deploy pipeline: Add release parameter and staging repository information
- [KOGITO-2414](https://issues.redhat.com/browse/KOGITO-2414) Kogito Runtimes deploy pipeline: Add "Set mvn version" step
- [KOGITO-2415](https://issues.redhat.com/browse/KOGITO-2415) Kogito Runtimes deploy pipeline: Add "Create PR" step
- [KOGITO-2287](https://issues.redhat.com/browse/KOGITO-2287) Kogito Runtimes promote pipeline: Create Jenkinsfile for promoting runtimes
- [KOGITO-2375](https://issues.redhat.com/browse/KOGITO-2375) Kogito Runtimes promote pipeline: Handling of Merge PR
- [KOGITO-2376](https://issues.redhat.com/browse/KOGITO-2376) Kogito Runtimes promote pipeline: Handling of Git …
=> KOGITO-2286 Pipeline modifications for release process

kogito-build-parent/pom.xml, kogito-codegen/src/main/java/org/kie/kogito/codegen/JsonSchemaGenerator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/JsonSchemaGeneratorTest.java, kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/ProcessClassesMojo.java, kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
https://issues.redhat.com/browse/KOGITO-2979
hot fix for an issue when processing serverless workflow causing classes not to be generated when issuing maven package with quarkus
=> KOGITO-2979 Use jar processing in quarkus extension

Jenkinsfile.drools
https://issues.redhat.com/browse/KOGITO-3125
=> KOGITO-3125 kie7 version in kogito-build-parent

kogito-build-parent/pom.xml, pom.xml
Follow up to https://github.com/kiegroup/kogito-runtimes/pull/707
=> KOGITO-3122 Move Sonar PR profile and properties to build parent module

Jenkinsfile-sonarcloud-daily, Jenkinsfile.deploy, Jenkinsfile.drools, Jenkinsfile.promote, Jenkinsfile.quarkus
https://issues.redhat.com/browse/KOGITO-3144
=> KOGITO-3144 Zulip topic naming convention

pom.xml
https://issues.redhat.com/browse/KOGITO-3147
Reverts kiegroup/kogito-runtimes#687
=> KOGITO-3147 Set back original distribution management

pom.xml
Wait merge of https://github.com/kiegroup/kogito-runtimes/pull/715 before merge this
=> [0.14.x] KOGITO-3147 Set back original distribution management #715

api/kogito-api/src/main/java/org/kie/kogito/auth/IdentityProvider.java, api/kogito-api/src/main/java/org/kie/kogito/auth/IdentityProviders.java, api/kogito-api/src/main/java/org/kie/kogito/process/workitem/Policies.java, api/kogito-api/src/test/java/org/kie/kogito/process/workitem/PoliciesTest.java, api/kogito-services/src/main/java/org/kie/kogito/services/identity/StaticIdentityProvider.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/humantask/HumanTaskWorkItemImpl.java, jbpm/jbpm-flow/src/main/java/org/jbpm/util/JsonSchemaUtil.java, kogito-codegen/src/main/resources/class-templates/ReactiveRestResourceTemplate.java, kogito-codegen/src/main/resources/class-templates/RestResourceTemplate.java, kogito-codegen/src/main/resources/class-templates/RestResourceUserTaskTemplate.java, kogito-codegen/src/main/resources/class-templates/spring/SpringRestResourceTemplate.java, kogito-codegen/src/main/resources/class-templates/spring/SpringRestResourceUserTaskTemplate.java
New Policies and IdentitiyProviders utility classes has been provided.
Template classes changed accordingly.
New eclipse formatter used (hope you like it)
=> [KOGITO-2754] Move policy handling out of Rest endpoint

kogito-codegen/src/main/java/org/kie/kogito/codegen/ApplicationGenerator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/process/persistence/PersistenceGenerator.java, kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
From https://github.com/kiegroup/kogito-runtimes/pull/726
=> KOGITO-3185 Use file system from InMemoryCompiler

kogito-codegen/src/main/java/org/kie/kogito/codegen/process/persistence/PersistenceGenerator.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/process/persistence/MongoDBPersistenceGeneratorTest.java, kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/ProcessClassesMojo.java, kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
=> [KOGITO-1920] - Example for persistence in Mongo DB with Quarkus(native image )

kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/decision/DecisionCodegenTest.java, kogito-codegen/src/test/resources/decision-NSEW/NSEW.dmn, kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/GenerateModelMojo.java, kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/DMNCompilationProvider.java, kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
https://issues.redhat.com/browse/KOGITO-3015
=> KOGITO-3015 DMN Eclipse MP annotation during codegen

kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionContainerGenerator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionValidation.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/AbstractCodegenTest.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/decision/DecisionValidationTest.java, kogito-codegen/src/test/resources/decision-validation-duplicateName/duplicateName.dmn
https://issues.redhat.com/browse/KOGITO-3236
@evacchi could you please comment especially changes in commit e9aa570 which deals only with refactor to use CollectedResource; I seized the chance of this task to refactor to use your newly introduced class.
/cc @danielezonca
=> KOGITO-3236 DMN validation as part of Kogito CodeGen

kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DMNResource.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java
https://issues.redhat.com/browse/KOGITO-3276
=> KOGITO-3276 DMN refactor DMN resource to use CollectedResource

api/kogito-api/src/main/java/org/kie/kogito/event/AbstractDataEvent.java, api/kogito-services/src/main/java/org/kie/kogito/services/event/AbstractProcessDataEvent.java, api/kogito-services/src/main/java/org/kie/kogito/services/event/EventConsumer.java, api/kogito-services/src/main/java/org/kie/kogito/services/event/EventConsumerFactory.java, api/kogito-services/src/main/java/org/kie/kogito/services/event/EventMarshaller.java, integration-tests/integration-tests-quarkus/pom.xml, integration-tests/integration-tests-quarkus/src/main/java/org/acme/travels/Traveller.java, integration-tests/integration-tests-quarkus/src/main/java/org/acme/travels/TravellerValidationService.java, integration-tests/integration-tests-quarkus/src/main/resources/application.properties, integration-tests/integration-tests-quarkus/src/main/resources/handle-travellers.bpmn, integration-tests/integration-tests-quarkus/src/main/resources/travellers.drl, jbpm/jbpm-flow/src/main/java/org/kie/kogito/event/impl/CloudEventConsumer.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/event/impl/DataEventConsumer.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/event/impl/DefaultEventConsumerFactory.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/event/impl/DefaultEventMarshaller.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/event/impl/EventUtils.java, jbpm/jbpm-flow/src/test/java/org/kie/kogito/event/impl/EventImplTest.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/process/MessageConsumerGenerator.java, kogito-codegen/src/main/resources/class-templates/MessageConsumerTemplate.java, kogito-codegen/src/main/resources/class-templates/MessageDataEventTemplate.java, kogito-codegen/src/main/resources/class-templates/MessageProducerTemplate.java, kogito-codegen/src/main/resources/class-templates/events/CloudEventsMessageProducerTemplate.java
Moving most of the code to constant classes. Since we cannot use reflection at runtime, Im relying on Function to execute conditional object creation. 
Result of code generation is:
For consumer
@javax.enterprise.context.ApplicationScoped()
public class TravelersMessageConsumer_3 {
@javax.inject.Inject()
@javax.inject.Named("Travelers")
Process<TravelersModel> process;
@javax.inject.Inject()
Application application;
@org.eclipse.microprofile.config.inject.ConfigProperty(name = "kogito.messaging.as-cloudevents")
Optional<Boolean> useCloudEvents = Optional.of(true);
EventConsumerFactory eventConsumerFactory = new DefaultEventConsumerFactory();
@javax.annotation.PostConstruct()
public void configure() {
}
@org.eclipse.microprofile.reactive.messaging.Incoming("travellers")
public void …
=> [KOGITO-2758] Refactor publisher-consumer code

drools/drools-core-static/src/main/java/org/drools/statics/StaticServiceRegistry.java
@danielezonca @rsynek  @jiripetrlik
See https://issues.redhat.com/browse/KOGITO-3290
=> [KOGITO-3290] Manage PMML dependency as "optional"

kogito-codegen/src/main/resources/class-templates/events/CloudEventsMessageProducerTemplate.java, kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
https://issues.redhat.com/browse/KOGITO-3292
KNative eventing was erroneously disabled when
KOGITO-3055 Refactor Quarkus Extension (#688)
was merged
=> KOGITO-3292 KNative eventing is not enabled with Quarkus Extension

kogito-build-parent/pom.xml, kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoInfinispanContainer.java
https://github.com/kiegroup/kogito-apps/pull/447
https://github.com/kiegroup/kogito-examples/pull/353
=> KOGITO-3260  Bump Extension to Quarkus 1.8.0

archetypes/kogito-quarkus-archetype/README.md, archetypes/kogito-springboot-archetype/README.md
Fix README with the current version on archetypes.
=> KOGITO-3301 Fix README on archetypes

kogito-build-parent/pom.xml
follow up to CR1 bump. Final released today.
merge together with https://github.com/kiegroup/kogito-examples/pull/357
=> KOGITO-3260 Bump Extension to Quarkus 1.8.0.Final

addons/persistence/mongodb-persistence-addon/src/test/resources/logback-test.xml, api/kogito-internal/src/test/resources/logback-test.xml, drools/kogito-pmml/src/test/java/org/kie/kogito/pmml/PmmlPredictionModelTest.java, kogito-build-parent/pom.xml
https://issues.redhat.com/browse/KOGITO-3265
Needed for 0.15.0 release
=> KOGITO-3308 Bump to KIE 7.43.0.Final

jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/transformation/MVELDataTransformer.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/MVELAction.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/MVELReturnValueEvaluator.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/util/VariableUtil.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/validation/RuleFlowProcessValidator.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/impl/WorkflowProcessImpl.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/MVELProcessHelper.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/DynamicUtils.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/ForEachNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/LambdaSubProcessNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/RuleSetNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateBasedNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/SubProcessNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/WorkItemNodeInstance.java, kogito-quarkus-extension/runtime/pom.xml, kogito-quarkus-extension/runtime/src/main/java/org/kie/kogito/quarkus/runtime/graal/graal/MvelSubstitutions.java
=> [0.14.x] KOGITO-3231 GraalVM 20.2 breaks native image

kogito-codegen/src/test/resources/decision-empty-name/vacationDays.dmn, kogito-codegen/src/test/resources/decision/models/vacationDays/vacationDays.dmn
https://issues.redhat.com/browse/KOGITO-3334
=> KOGITO-3334 DMN fix semantically invalid models in kogito-runtimes

jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcess.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/di/CDIDependencyInjectionAnnotator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/di/DependencyInjectionAnnotator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/di/SpringDependencyInjectionAnnotator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java, kogito-codegen/src/main/resources/class-templates/MessageProducerTemplate.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/prediction/PMMLRestResourceGeneratorTest.java
Summary of changes (please read JIRA initial description for more information):
Generated handlers are now passed to constructor explicitly (handlers
field has been removed), which registers them, both for injection and non injection
paths 
Additionally,  when there is any handler present, additional non injected constructor that only accepts Application reference is provided, Itautomatically creates and registers the handlers (user can still pass handler instances using the other constructor in non injection)
Configure and registerListeners methods are only generated if they have
content (which happen when there are listeners)
Activate method will be invoked from generated constructors.
Generated code example 
```
public TravellersProcess(org.kie.kogito.app.Application app) {
this(
app, …
```
=> [KOGITO-2766] Refactoring Process<T> initialization code

kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionRestResourceGenerator.java, kogito-quarkus-extension/integration-test/src/test/java/io/quarkus/it/kogito/dmn/DMNTest.java, kogito-quarkus-extension/integration-test/src/test/java/io/quarkus/it/kogito/dmn/DMNTestIT.java
https://issues.redhat.com/browse/KOGITO-3432
=> KOGITO-3432 DMN fix GraalVM NI introsp. for /dmnresult REST endpoint

integration-tests/integration-tests-quarkus-rules/pom.xml
Fix native build for integration-tests-quarkus-rules project
=> Removed unused dependencies

integration-tests/integration-tests-quarkus-processes/pom.xml, integration-tests/integration-tests-quarkus-processes/src/main/resources/process-parent.bpmn, integration-tests/integration-tests-quarkus-processes/src/main/resources/process-subprocess.bpmn, integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/ParentSubProcessTest.java, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/main/resources/process-parent.bpmn, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/main/resources/process-subprocess.bpmn, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/ParentSubProcessTest.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/SubProcessNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/780
- https://github.com/kiegroup/kogito-examples/pull/370
=> KOGITO-3397 - Set KogitoMetadataProcess when starting a new instance

kogito-bom/pom.xml
Adds security-commons to kogito-bom
Related jira: https://issues.redhat.com/browse/KOGITO-3291
=> KOGITO-3291: Adding security-commons to kogito-bom

addons/events/knative-eventing-addon/src/test/resources/application.properties, kogito-build-parent/pom.xml
Fix https://issues.redhat.com/browse/KOGITO-3478
=> [KOGITO-3478] Upgrade to ce-2.0.0-milestone3

kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/InMemoryCompiler.java
While I was surfing on the code I found this small typo. 
=> KOGITO-3496 - Fix logger class

Jenkinsfile.native
Job that clone and compiles all the repos in native mode
@radtriste @cristianonicolai
=> [KOGITO-3460] Create native daily build

kogito-build-parent/pom.xml
Upgrades Drools used to latest available 7.44.0.Final.
=> KOGITO-3554 Bump KIE7 to 7.44.0.Final

Jenkinsfile.native
=> Move from podman to docker for native builds

kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java
part of an ensemble of PRs
https://issues.redhat.com/browse/KOGITO-2277
Requires PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1458
* https://github.com/kiegroup/drools/pull/3097
=> KOGITO-2277 fix OpenAPI schema for temporals

kogito-build-parent/pom.xml
https://issues.redhat.com/browse/KOGITO-3554
=> [0.16.x] KOGITO-3554 Bump KIE7 to 7.44.0.Final (#808)

Jenkinsfile.deploy, Jenkinsfile.promote
https://issues.redhat.com/browse/KOGITO-3510
=> [KOGITO-3510] Deploy/Promote pipelines: set credentials as params

kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandler.java, kogito-workitems/kogito-rest-workitem/src/test/java/org/kogito/workitem/rest/RestTaskHandlerTest.java
If rest invocation failed, workitem will be aborted.
=> [KOGITO-3495] Error handling on RestworkItemhandler

addons/jobs/jobs-api/src/main/java/org/kie/kogito/jobs/api/Job.java, addons/jobs/jobs-api/src/main/java/org/kie/kogito/jobs/api/JobBuilder.java, addons/jobs/jobs-management-common/src/main/java/org/kie/kogito/jobs/management/RestJobsService.java, addons/jobs/jobs-management-quarkus-addon/src/main/java/org/kie/kogito/jobs/management/quarkus/VertxJobsService.java, addons/jobs/jobs-management-springboot-addon/src/main/java/org/kie/kogito/jobs/management/springboot/SpringRestJobsService.java, api/kogito-api/src/main/java/org/kie/kogito/jobs/ProcessInstanceJobDescription.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateBasedNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/TimerNodeInstance.java
=> KOGITO-3131 Add node instance id to Job related details

Jenkinsfile.deploy
https://issues.redhat.com/browse/KOGITO-3570
Depends on: https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/105
=> KOGITO-3570 No defaut settings.xml for release build

api/kogito-api/src/main/java/org/kie/kogito/event/Topic.java, api/kogito-api/src/main/java/org/kie/kogito/event/TopicType.java, integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/TopicInformationResourceTest.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/process/events/AbstractEventResourceGenerator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/process/events/CloudEventsResourceGenerator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/process/events/TopicsInformationResourceGenerator.java, kogito-codegen/src/main/resources/class-templates/events/TopicsInformationResourceTemplate.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/process/events/TopicsInformationResourceGeneratorTest.java
See: https://issues.redhat.com/browse/KOGITO-3549
TODO:
=> KOGITO-3549 - Introducing TopicsResource Endpoint

addons/tracing/tracing-decision-api/pom.xml, addons/tracing/tracing-decision-api/src/main/java/org/kie/kogito/tracing/decision/event/CloudEventUtils.java, addons/tracing/tracing-decision-api/src/test/java/org/kie/kogito/tracing/decision/event/CloudEventUtilsTest.java, addons/tracing/tracing-decision-common/src/main/java/org/kie/kogito/tracing/decision/BaseModelEventEmitter.java, addons/tracing/tracing-decision-common/src/main/java/org/kie/kogito/tracing/decision/DecisionTracingCollector.java, addons/tracing/tracing-decision-common/src/main/java/org/kie/kogito/tracing/decision/aggregator/Aggregator.java, addons/tracing/tracing-decision-common/src/main/java/org/kie/kogito/tracing/decision/aggregator/DefaultAggregator.java, addons/tracing/tracing-decision-common/src/test/java/org/kie/kogito/tracing/decision/DecisionTracingCollectorTest.java, addons/tracing/tracing-decision-common/src/test/java/org/kie/kogito/tracing/decision/aggregator/DefaultAggregatorTest.java, addons/tracing/tracing-decision-common/src/test/java/org/kie/kogito/tracing/decision/mock/MockDefaultAggregator.java, addons/tracing/tracing-decision-quarkus-addon/src/test/java/org/kie/kogito/tracing/decision/QuarkusModelEventEmitterTest.java
- [JIRA task](https://issues.redhat.com/browse/KOGITO-3452)
=> KOGITO-3452: uniform error handling of build/encode/decode in CloudEventUtils

kogito-bom/pom.xml
* [Jira Task](https://issues.redhat.com/browse/KOGITO-3545)
=> KOGITO-3545: complete DMN tracing examples

Jenkinsfile.deploy
https://issues.redhat.com/browse/KOGITO-3570
=> [KOGITO-3570] Setting correct settings.xml file for release

archetypes/kogito-quarkus-archetype/pom.xml, archetypes/kogito-springboot-archetype/pom.xml, integration-tests/integration-tests-quarkus-decisions/pom.xml, integration-tests/integration-tests-quarkus-predictions/pom.xml, integration-tests/integration-tests-quarkus-processes/pom.xml, integration-tests/integration-tests-quarkus-rules/pom.xml, kogito-codegen/src/test/java/org/kie/kogito/codegen/AddonsConfigTest.java, kogito-quarkus-extension/integration-test-legacy/pom.xml, kogito-quarkus-extension/integration-test/pom.xml
https://issues.redhat.com/browse/KOGITO-3611
When there is a failure in one of the core modules of Kogito, for example `kogito-codegen`, all dependent modules should be skipped by maven but this is not happening because a module that contains a `@QuarkusTest` only depends on `kogito-quarkus` and not the compile time component `kogito-quarkus-deployment` that is automatically loaded by Quarkus.
This is a waste of build time and even more important it makes output logs quite noisy because of a lot failed test that was not supposed to run
```
[INFO] Reactor Summary for Kogito Runtimes 1.0.0-SNAPSHOT:
[INFO] 
[INFO] Kogito Runtimes .................................... SUCCESS [  3.902 s]
[INFO] Kogito Runtimes Build BOM .......................... SUCCESS [  1.591 s]
...
[INFO] Kogito :: …
```
=> [KOGITO-3611] Fix "implicit" module dependencies

kogito-build-parent/pom.xml
@evacchi I believe we missed this during the BUMP.
=> [KOGITO-3623] - Align Smallrye Messaging version with Quarkus

Jenkinsfile.deploy, Jenkinsfile.promote
https://issues.redhat.com/browse/KOGITO-3641
=> KOGITO-3641 Deploy after set next snapshot

integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/pom.xml, kogito-springboot/pom.xml
https://issues.redhat.com/browse/KOGITO-3671
This should fix Springboot integration tests too
=> [KOGITO-3671] Make kogito-springboot depends on swagger-annotations

Jenkinsfile.deploy, Jenkinsfile.promote
https://issues.redhat.com/browse/KOGITO-3641
Cherry-pick: https://github.com/kiegroup/kogito-runtimes/pull/835
=> [0.17.x] KOGITO-3641 Deploy after set next snapshot (#835)

kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
https://issues.redhat.com/browse/KOGITO-1179
=> KOGITO-1179 Unable to execute a job with native application

integration-tests/integration-tests-springboot/pom.xml, kogito-build-parent/pom.xml
let's run CI and see if something breaks.
Notice, I don't think we should merge for 0.17.0. Let's merge for 1.0.
related: https://github.com/kiegroup/kogito-examples/pull/396
----
=> KOGITO-3596 Bump to Quarkus 1.9

jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/ProcessHandler.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ActionNodeVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/BoundaryEventNodeVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/EndNodeVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/StartNodeVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/TriggerMetaData.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/context/exception/CompensationScope.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/context/exception/CompensationScopeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/actions/ProcessInstanceCompensationAction.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/Metadata.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowNodeContainerFactory.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowProcessFactory.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/BoundaryEventNodeFactory.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/ExtendedNodeInstanceImpl.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/BoundaryEventNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/EventNodeInstance.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/process/ProcessGenerationTest.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/CompensationTest.java, kogito-codegen/src/test/java/org/kie/kogito/process/impl/ProcessTestUtils.java, kogito-codegen/src/test/resources/compensation/BPMN2-Compensation-ThrowSpecificForSubProcess.bpmn2, kogito-codegen/src/test/resources/compensation/compensateAll.bpmn2, kogito-codegen/src/test/resources/compensation/compensateFirst.bpmn2, kogito-codegen/src/test/resources/compensation/compensateSecond.bpmn2
Fix https://issues.redhat.com/browse/KOGITO-2849
Cases covered:
- Intermediate compensation
- End Compensation
- Specifying the node to compensate
- Compensate all completed nodes
=> [KOGITO-2849] Support for Compensations

kogito-codegen/src/main/java/org/kie/kogito/codegen/process/persistence/proto/ProtoGenerator.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/process/persistence/proto/ReflectionProtoGeneratorTest.java, kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoInfinispanContainer.java, kogito-test-utils/src/main/resources/testcontainers/infinispan/groups.properties, kogito-test-utils/src/main/resources/testcontainers/infinispan/infinispan-local.xml, kogito-test-utils/src/main/resources/testcontainers/infinispan/users.properties, kogito-test-utils/src/test/java/org/kie/kogito/testcontainers/InfinispanContainerTest.java
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/791
- https://github.com/kiegroup/kogito-apps/pull/495
- https://github.com/kiegroup/kogito-examples/pull/407
- https://github.com/kiegroup/kie-docs/pull/2952
=> KOGITO-3118 Infinispan 11 upgrade

addons/cloudevents/cloudevents-quarkus-addon/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/QuarkusCloudEventEmitter.java, addons/cloudevents/cloudevents-quarkus-addon/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/QuarkusCloudEventPublisher.java, addons/cloudevents/cloudevents-spring-boot-addon/pom.xml, addons/cloudevents/cloudevents-spring-boot-addon/src/main/java/org/kie/kogito/addon/cloudevents/spring/SpringKafkaCloudEventEmitter.java, addons/cloudevents/cloudevents-spring-boot-addon/src/main/java/org/kie/kogito/addon/cloudevents/spring/SpringKafkaCloudEventPublisher.java, api/kogito-api/src/main/java/org/kie/kogito/event/KogitoEventStreams.java, api/kogito-services/src/main/java/org/kie/kogito/services/event/impl/AbstractMessageConsumer.java, api/kogito-services/src/main/java/org/kie/kogito/services/event/impl/AbstractMessageProducer.java, integration-tests/integration-tests-springboot/pom.xml, kogito-build-parent/pom.xml, kogito-codegen/src/main/resources/class-templates/CdiMessageConsumerTemplate.java, kogito-codegen/src/main/resources/class-templates/SpringMessageConsumerTemplate.java, kogito-codegen/src/main/resources/class-templates/SpringMessageProducerTemplate.java, kogito-codegen/src/main/resources/class-templates/events/CloudEventsListenerResource.java
Same as #807 except this is Spring-specific.
Caveats: there is no 'abstraction' for channels/topics in Spring so I had to come up with my own config keys -- we should probably revisit this
related https://github.com/kiegroup/kogito-examples/pull/421
https://issues.redhat.com/browse/KOGITO-3407
----
=> KOGITO-3407 CloudEvent Kafka Publisher+Emitter (Spring Boot)

kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionRestResourceGenerator.java, kogito-codegen/src/main/resources/class-templates/DecisionRestResourceTemplate.java
https://issues.redhat.com/browse/KOGITO-3741
=> KOGITO-3741 DMN relativize OAS to JSONSchema $ref

addons/tracing/tracing-decision-quarkus-addon/src/main/java/org/kie/kogito/tracing/decision/QuarkusModelEventEmitter.java, addons/tracing/tracing-decision-quarkus-addon/src/main/java/org/kie/kogito/tracing/decision/QuarkusStartupModelPublisher.java
JIRA: https://issues.redhat.com/browse/FAI-280
The aim of this PR is to fix the bug https://issues.redhat.com/browse/FAI-280 with a workaround as suggested by the quarkus team https://github.com/quarkusio/quarkus/issues/12820 .
=> FAI-280 - fix dmn model model publisher

drools/drools-core-static/src/main/java/org/drools/statics/StaticKieAssemblers.java, drools/drools-core-static/src/main/java/org/drools/statics/StaticServiceRegistry.java
https://issues.redhat.com/browse/KOGITO-3783
=> [KOGITO-3783] Make more components optional in StaticServiceRegistry

jbpm/jbpm-flow/src/main/java/org/kie/kogito/event/impl/CloudEventConsumer.java
See: https://issues.redhat.com/browse/KOGITO-3798
=> [KOGITO-3798] - Fixing condition check of KogitoReferenceId

jbpm/jbpm-flow/src/main/java/org/kie/kogito/event/impl/CloudEventConsumer.java
=> [KOGITO-3798] - Fixing condition check of KogitoReferenceId (#879)

archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/pom.xml, integration-tests/integration-tests-springboot/pom.xml, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/pom.xml, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-kafka-it/pom.xml, kogito-build-parent/pom.xml
[KOGITO-3827](https://issues.redhat.com/browse/KOGITO-3827)
- https://github.com/kiegroup/kogito-runtimes/pull/884
- https://github.com/kiegroup/kogito-examples/pull/450
----
=> [1.0.x] KOGITO-3827  Bump to Quarkus 1.10.0.CR1

kogito-build-parent/pom.xml
=> [1.0.x] KOGITO-3859  Bump to KIE 7.46.0.Final

jbpm/jbpm-flow/src/main/java/org/jbpm/util/JsonSchemaUtil.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/JsonSchemaGeneratorTest.java
=> [KOGITO-3833] Json Schema generation whitespaces

kogito-quarkus-extension/runtime/src/main/resources/META-INF/quarkus-extension.yaml
https://issues.redhat.com/browse/KOGITO-3870
Set Quarkus Extension to "stable" instead of "preview"; otherwise it will show up with a "preview" label in code.quarkus.io UI
---
=> [1.0.x] KOGITO-3870 Mark Quarkus Extension as "stable"

kogito-build-parent/pom.xml
https://issues.redhat.com/browse/KOGITO-3876
related: https://github.com/kiegroup/kogito-examples/pull/462
----
=> [1.0.x] KOGITO-3876 Bump to Quarkus 1.10.0.Final

Jenkinsfile
https://issues.redhat.com/browse/KOGITO-3615
=> KOGITO-3615 Build OptaPlanner to catch regressions early

addons/persistence/mongodb-persistence-addon/pom.xml, kogito-build-parent/pom.xml, kogito-test-utils/pom.xml
cherry pick #889
related: https://github.com/kiegroup/kogito-apps/pull/545
=> KOGITO-3868 TestContainer dependency in BOM causes issues in quarkus-platform 

archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/pom.xml, integration-tests/integration-tests-springboot/pom.xml, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/pom.xml, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-kafka-it/pom.xml, kogito-build-parent/pom.xml
cherry-pick #884 
related https://github.com/kiegroup/kogito-examples/pull/459
=> KOGITO-3876  Bump to Quarkus 1.10.0.Final

kogito-build-parent/pom.xml
=> KOGITO-3859  Bump to KIE 7.46.0.Final

kogito-codegen/src/main/resources/class-templates/DecisionContainerTemplate.java
=> KOGITO-3897 Use JDK8-compatible readBytes impl in DecisionContainerTemplate

integration-tests/integration-tests-quarkus-processes/src/main/resources/process-subprocess.bpmn, integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/ParentSubProcessTest.java, jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/CallActivityHandler.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/LambdaSubProcessNodeVisitor.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/node/SubProcessNode.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/tests/SubProcessTest.java, kogito-codegen/src/test/resources/org/kie/kogito/codegen/process/process-generation-test.skip.txt, kogito-codegen/src/test/resources/subprocess/ParentProcess.bpmn, kogito-codegen/src/test/resources/subprocess/SubProcess.bpmn
Depends on https://github.com/kiegroup/kogito-runtimes/pull/880
=> KOGITO-3604 - Assign constant value to sub process model

addons/cloudevents/cloudevents-quarkus-addon/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/QuarkusCloudEventPublisher.java
=> [KOGITO-3911] [1.0.x] Fix to ack received kafka messages on QuarkusCloudEventPublisher

integration-tests/integration-tests-quarkus-processes/src/main/resources/MultipleThrowLinkProcess.bpmn2, integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/LinkTest.java, jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/ProcessHandler.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/process/ProcessGenerationTest.java, kogito-codegen/src/test/resources/links/DifferentLinkProcess.bpmn2, kogito-codegen/src/test/resources/links/EmptyLinkProcess.bpmn2, kogito-codegen/src/test/resources/links/MultipleCatchLinkProcess.bpmn2, kogito-codegen/src/test/resources/links/UnconnectedLinkProcess.bpmn2, kogito-codegen/src/test/resources/org/kie/kogito/codegen/process/process-generation-test.skip.txt
Carry forward of changes from JBPM to Kogito regarding links
=> [KOGITO-3896] Link events has reverted multiple source/target behavior

kogito-build-parent/pom.xml
Assembly:
- https://github.com/kiegroup/kogito-examples/pull/479
- https://github.com/kiegroup/kogito-runtimes/pull/918
=> KOGITO-3957 Upgrade Quarkus to latest stable

kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
https://issues.redhat.com/browse/KOGITO-3985
Quarkus produces this warning during the execution
```
Dec 09, 2020 11:06:26 AM io.quarkus.deployment.ExtensionLoader deprecatedProducer
WARN: Producing values from constructors and fields is no longer supported and will be removed in a future release: io.quarkus.deployment.annotations.BuildProducer org.kie.kogito.quarkus.deployment.KogitoAssetsProcessor.generatedBeans
Dec 09, 2020 11:06:26 AM io.quarkus.deployment.ExtensionLoader deprecatedProducer
WARN: Producing values from constructors and fields is no longer supported and will be removed in a future release: io.quarkus.deployment.annotations.BuildProducer org.kie.kogito.quarkus.deployment.KogitoAssetsProcessor.resource
Dec 09, 2020 11:06:26 AM io.quarkus.deployment.ExtensionLoader …
```
=> [KOGITO-3985] Remove deprecated field injection usages of Quarkus BuildProducer

kogito-codegen/src/main/java/org/kie/kogito/codegen/ApplicationGenerator.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/AbstractCodegenTest.java, kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/GenerateDeclaredTypes.java, kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/GenerateModelMojo.java, kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/DMNCompilationProvider.java, kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/DecisionTablesCompilationProvider.java, kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java, kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/ProcessCompilationProvider.java, kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/RulesCompilationProvider.java
https://issues.redhat.com/browse/KOGITO-3995
=> [KOGITO-3995] Rename ApplicationGenerator.withGenerator to improve readability

Jenkinsfile.deploy, Jenkinsfile.promote
https://issues.redhat.com/browse/KOGITO-3589
Dependent PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/89
- https://github.com/kiegroup/kogito-runtimes/pull/909
- https://github.com/kiegroup/kogito-apps/pull/554
=> KOGITO-3589 Extract apps from kogito-runtimes

api/kogito-api/src/main/java/org/kie/kogito/event/AbstractDataEvent.java, api/kogito-services/src/main/java/org/kie/kogito/services/event/AbstractProcessDataEvent.java, api/kogito-services/src/main/java/org/kie/kogito/services/event/UserTaskInstanceDataEvent.java, api/kogito-services/src/main/java/org/kie/kogito/services/event/VariableInstanceDataEvent.java
Fix https://issues.redhat.com/browse/KOGITO-4053
=> [KOGITO-4053] Ignore empty fields in CloudEvents

Jenkinsfile.deploy, Jenkinsfile.promote
https://issues.redhat.com/browse/KOGITO-3863
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/99
- https://github.com/kiegroup/kogito-runtimes/pull/947
- https://github.com/kiegroup/kogito-apps/pull/572
- https://github.com/kiegroup/kogito-examples/pull/490
- https://github.com/kiegroup/optaplanner/pull/1071
- https://github.com/kiegroup/kogito-images/pull/289
- https://github.com/kiegroup/kogito-cloud-operator/pull/698
=> KOGITO-3863 Setup timeout to deploy/promote

jbpm/jbpm-flow-builder/src/main/resources/class-templates/RestWorkItemHandlerTemplate.java, kogito-build-parent/pom.xml, kogito-workitems/kogito-rest-workitem/pom.xml, kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandler.java, kogito-workitems/kogito-rest-workitem/src/test/java/org/kogito/workitem/rest/RestTaskHandlerTest.java
Making WIH sync
Please read https://github.com/kiegroup/kogito-runtimes/pull/938 to find out why are we changing WIH to sync
=> [KOGITO-4014] Kogito Runtime Process to wait for a process to finish

kogito-build-parent/pom.xml
related to https://github.com/testcontainers/testcontainers-java/issues/3574
=> KOGITO-4090 - Upgrade testcontainers to version 1.15.1

Jenkinsfile.native
=> Update Jenkinsfile.native to use kie-rhel7 && kie-mem16g

kogito-build-parent/pom.xml
https://issues.redhat.com/browse/KOGITO-4093
=> KOGITO-4093 quarkus bump 1.11.0.Beta2 + smallrye reactive messaging

addons/tracing/tracing-decision-quarkus-addon/src/main/resources/META-INF/microprofile-config.properties
jira: https://issues.redhat.com/browse/KOGITO-4075
This PR aims to simplify the configuration of the tracing addon from the user. The default configuration is now placed inside the module, so the user does not have to specify the kafka topics and so on. 
=> KOGITO-4075 - Add microprofile default config for tracing addon

Jenkinsfile
=> [1.1.x] fix for optaplanner checkout in PR release branch

kogito-build-parent/pom.xml
- https://github.com/kiegroup/kogito-examples/pull/506
- https://github.com/kiegroup/kogito-runtimes/pull/970
https://issues.redhat.com/browse/KOGITO-4128
=> [1.1.x] KOGITO-4128 Bump quarkus 1.11.0.CR1

addons/cloudevents/cloudevents-quarkus-addon/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/QuarkusCloudEventPublisher.java
=> [KOGITO-3911] [master] Cherry-pick: Fix to ack received kafka messages on Quarkus

kogito-build-parent/pom.xml, kogito-cloud-services/kogito-cloud-kubernetes-client/src/test/java/org/kie/kogito/cloud/kubernetes/client/MockKubernetesServerSupport.java, kogito-cloud-services/kogito-cloud-workitems/src/test/java/org/kie/kogito/cloud/workitems/BaseKubernetesDiscoveredServiceTest.java, kogito-cloud-services/kogito-cloud-workitems/src/test/java/org/kie/kogito/cloud/workitems/KNativeDiscoveredServiceWorkItemHandlerTest.java
https://issues.redhat.com/browse/KOGITO-4146
Also integrate https://github.com/kiegroup/kogito-runtimes/pull/959
=> [1.1.x] KOGITO-4146 updated version of kubernetes-client

api/kogito-internal/src/main/java/org/kie/internal/pmml/PMMLCommandExecutor.java, api/kogito-internal/src/main/java/org/kie/internal/pmml/PMMLCommandExecutorFactory.java, api/kogito-internal/src/main/java/org/kie/internal/pmml/PMMLImplementationsUtil.java, drools/kogito-pmml-dependencies/pom.xml, kogito-build-parent/pom.xml
=> [1.1.x] KOGITO-4052 Changed type of kie-pmml-dependencies + Bump kie to 7.48

kogito-build-parent/pom.xml
https://github.com/kiegroup/kogito-runtimes/pull/977
https://github.com/kiegroup/kogito-examples/pull/513
https://issues.redhat.com/browse/KOGITO-4170
----
=> [1.1.x] KOGITO-4170 Bump quarkus 1.11.0.Final

kogito-build-parent/pom.xml
[KOGITO-4181](https://issues.redhat.com/browse/KOGITO-4181)
tuning properties for the sonar scanner to resolve out of mem issue.
=> KOGITO-4181 increase memory for sonar scanner

kogito-build-parent/pom.xml
This shouldn't need bump on kogito-examples because of https://github.com/kiegroup/kogito-examples/pull/510
=> KOGITO-4170 Bump quarkus 1.11.0.Final

kogito-bom/pom.xml
JIRA: https://issues.redhat.com/browse/KOGITO-4187
We have new modules on kogito-apps that need to be added to the bom
Related PR on kogito-apps: https://github.com/kiegroup/kogito-apps/pull/597
=> KOGITO-4187 - Add jitexecutors modules to bom

kogito-build-parent/pom.xml
https://issues.redhat.com/browse/KOGITO-4200
Related PR:
- https://github.com/wmedvede/kogito-apps/pull/1
- https://github.com/kiegroup/kogito-apps/pull/591
- https://github.com/kiegroup/kogito-pipelines/pull/103
=> KOGITO-4200 update maven versions plugin

kogito-build-parent/pom.xml, kogito-cloud-services/kogito-cloud-kubernetes-client/src/test/java/org/kie/kogito/cloud/kubernetes/client/MockKubernetesServerSupport.java, kogito-cloud-services/kogito-cloud-workitems/src/test/java/org/kie/kogito/cloud/workitems/BaseKubernetesDiscoveredServiceTest.java, kogito-cloud-services/kogito-cloud-workitems/src/test/java/org/kie/kogito/cloud/workitems/KNativeDiscoveredServiceWorkItemHandlerTest.java
https://issues.redhat.com/browse/KOGITO-4146
Cherry-pick: https://github.com/kiegroup/kogito-runtimes/pull/974
=> KOGITO-4146 updated version of kubernetes-client

Jenkinsfile, Jenkinsfile-sonarcloud-daily, Jenkinsfile.deploy, Jenkinsfile.drools, Jenkinsfile.native, Jenkinsfile.quarkus
https://issues.redhat.com/browse/KOGITO-4167
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/976
- https://github.com/kiegroup/kogito-apps/pull/589
- https://github.com/kiegroup/kogito-examples/pull/514
Test summary:
- kogito-runtimes-sonarcloud => OK
- kogito-runtimes-deploy => OK
- kogito-native
- master => OK
- 1.1.x => OK
- kogito-drools
- master =>  OK
- 1.1.x => OK
- kogito-quarkus
- master => OK
- 1.1.x => OK
=> KOGITO-4167 Set optaplanner before apps

Jenkinsfile.deploy
See: https://issues.redhat.com/browse/KOGITO-1031
This is an accompanying PR to [the one opened in kogito-pipelines](https://github.com/kiegroup/kogito-pipelines/pull/46). 
- deploys all artifacts locally before zipping them altogether to push to Nexus
* added to provide authentication to push artifacts to PR artifact repository
- replace hardcoded "kogito-runtimes" string with environment variable
I was able to [deploy the artifacts](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/kmok/job/KOGITO-1031-full/job/kogito-runtimes-deploy/79/execution/node/112/log/) to the PR test repository using the code from this PR.
=> [KOGITO-1031] Add Maven local deploy

api/kogito-api/src/main/java/org/kie/api/runtime/rule/AccumulateFunction.java
This is just a forward port of a change in kie-api https://github.com/kiegroup/droolsjbpm-knowledge/commit/dbb5cd1120ea6bb18f743979ced8841008da8219
=> [DROOLS-5953] generalize accumulate function

archetypes/kogito-springboot-archetype/src/main/resources/archetype-resources/pom.xml, kogito-build-parent/pom.xml
Ref: https://issues.redhat.com/browse/KOGITO-4223?focusedCommentId=15676972&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-15676972
A PR to align all ~30 examples is in the works.
=> KOGITO-4223 Kogito SB archetype fail Swagger/OAS ootb

Jenkinsfile.deploy
https://issues.redhat.com/browse/KOGITO-4252
=> KOGITO-4252 Corrected Jenkinsfile.deploy

drools/kogito-pmml-dependencies/pom.xml
Removing outdated comment
- [] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
=> Update kogito-pmml-dependencies pom

kogito-build-parent/pom.xml
https://issues.redhat.com/browse/KOGITO-4319
cherry-pick: https://github.com/kiegroup/kogito-runtimes/pull/1020
=> [1.2.x] KOGITO-4319 Downgrade maven versions plugin

kogito-build-parent/pom.xml
https://issues.redhat.com/browse/KOGITO-4319
=> KOGITO-4319 Downgrade maven versions plugin

.github/workflows/quarkus-snapshot.yaml, Jenkinsfile.quarkus
https://issues.redhat.com/browse/KOGITO-4347
- Quarkus PR: https://github.com/quarkusio/quarkus-ecosystem-ci/pull/40
- New Jenkins job will be created `kogito-quarkus-lts` with `env.QUARKUS_BRANCH=1.11`
=> KOGITO-4347 Test Kogito against Quarkus LTS

.github/workflows/quarkus-snapshot.yaml
=> Update GHAction names

kogito-codegen/src/main/java/org/kie/kogito/codegen/di/CDIDependencyInjectionAnnotator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/di/DependencyInjectionAnnotator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/di/SpringDependencyInjectionAnnotator.java, kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/QueryEndpointGenerator.java, kogito-codegen/src/main/resources/class-templates/rules/RestQueryJavaTemplate.java, kogito-codegen/src/main/resources/class-templates/rules/RestQueryQuarkusTemplate.java, kogito-codegen/src/main/resources/class-templates/rules/RestQuerySpringTemplate.java, kogito-codegen/src/test/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegenTest.java
Cherry pick for https://github.com/kiegroup/kogito-runtimes/pull/1012
=> [1.2.x] KOGITO-4309 - Fix DRL monitoring and add test on codegen cherry pick

drools/kogito-scenario-simulation/pom.xml, kogito-build-parent/pom.xml
=> [1.2.x] KOGITO-4316 Bump 7.49.0.Final

kogito-build-parent/pom.xml
This should fix the native build with Quarkus master.
https://issues.redhat.com/browse/KOGITO-4353
=> KOGITO-4353 Add missing Jackson dependencies

archetypes/kogito-quarkus-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/README.md, archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/src/main/resources/Traffic Violation.dmn, archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/src/test/java/TrafficViolationTest.java, archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/src/test/resources/application.properties, archetypes/kogito-springboot-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, archetypes/kogito-springboot-archetype/src/main/resources/archetype-resources/README.md, archetypes/kogito-springboot-archetype/src/main/resources/archetype-resources/src/main/resources/Traffic Violation.dmn, archetypes/kogito-springboot-archetype/src/main/resources/archetype-resources/src/test/java/GreetingsTest.java, archetypes/kogito-springboot-archetype/src/main/resources/archetype-resources/src/test/java/TrafficViolationTest.java, kogito-build-parent/pom.xml
Ref: https://issues.redhat.com/browse/KOGITO-4350
=> KOGITO-4350 Add sibling DMN sample to BPMN2 in Archetypes

jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ActivityTest.java, jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java, jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/VariableTagsTest.java
[KOGITO-4371](https://issues.redhat.com/browse/KOGITO-4371)
=> KOGITO-4371 - Cleanup of jbpm-bpmn2 tests after KieSession refactor

addons/cloudevents/cloudevents-quarkus-addon/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/QuarkusKogitoExtensionInitializer.java, addons/cloudevents/cloudevents-spring-boot-addon/src/main/java/org/kie/kogito/addon/cloudevents/spring/SpringBootKogitoExtensionInitializer.java
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/1047
- https://github.com/kiegroup/kogito-examples/pull/554
=> KOGITO-4249 Automatically register CloudEvent Jackson Module

.github/workflows/jenkins-tests-PR.yml, .jenkins/dsl/jobs.groovy, .jenkins/dsl/test.sh, .jenkins/tests/src/test/vars/JenkinsfileDeploy.groovy, .jenkins/tests/src/test/vars/JenkinsfilePromote.groovy, Jenkinsfile.deploy, Jenkinsfile.drools, Jenkinsfile.native, Jenkinsfile.promote, Jenkinsfile.quarkus, Jenkinsfile.sonarcloud
https://issues.redhat.com/browse/KOGITO-3034
https://issues.redhat.com/browse/BXMSPROD-1094
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/92
- https://github.com/kiegroup/kogito-runtimes/pull/940
- https://github.com/kiegroup/kogito-apps/pull/581
- https://github.com/kiegroup/optaplanner/pull/1085
- https://github.com/kiegroup/kogito-examples/pull/500
- https://github.com/kiegroup/kogito-images/pull/307
- https://github.com/kiegroup/kogito-cloud-operator/pull/710
**Setup DSL scripts for the different Kogito jobs.**
- Allow easy setup of jobs for own purpose (with different configuration for example)
- Moved parameters as environment
- That allows exact same configuration information for all the jobs, without having to 
- For testing, taking the getting the seed job and …
=> [KOGITO-3034][BXMSPROD-1094] Setup Jenkins DSL scripts

.github/workflows/jenkins-tests-PR.yml, Jenkinsfile.drools, Jenkinsfile.quarkus
=> Correct drools snapshot build + DSL check

addons/persistence/kafka-persistence-addon/pom.xml, addons/persistence/kafka-persistence-addon/src/main/java/org/kie/kogito/persistence/KogitoProcessInstancesFactory.java, addons/persistence/kafka-persistence-addon/src/main/java/org/kie/kogito/persistence/kafka/KafkaPersistenceUtils.java, addons/persistence/kafka-persistence-addon/src/main/java/org/kie/kogito/persistence/kafka/KafkaProcessInstances.java, addons/persistence/kafka-persistence-addon/src/main/java/org/kie/kogito/persistence/kafka/KafkaStreamsStateListener.java, addons/persistence/kafka-persistence-addon/src/main/resources/META-INF/kogito.addon, addons/persistence/kafka-persistence-addon/src/test/java/org/kie/kogito/persistence/KogitoProcessInstancesFactoryTest.java, addons/persistence/kafka-persistence-addon/src/test/java/org/kie/kogito/persistence/kafka/KafkaPersistenceUtilsTest.java, addons/persistence/kafka-persistence-addon/src/test/java/org/kie/kogito/persistence/kafka/KafkaProcessInstancesIT.java, addons/persistence/kafka-persistence-addon/src/test/java/org/kie/kogito/persistence/kafka/KafkaProcessInstancesTest.java, addons/persistence/kafka-persistence-addon/src/test/java/org/kie/kogito/persistence/kafka/KafkaStreamsStateListenerTest.java, addons/persistence/kafka-persistence-addon/src/test/resources/BPMN2-UserTask-Script.bpmn2, addons/persistence/kafka-persistence-addon/src/test/resources/BPMN2-UserTask.bpmn2, addons/persistence/pom.xml, integration-tests/integration-tests-springboot/pom.xml, kogito-build-parent/pom.xml, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/persistence/PersistenceGenerator.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/persistence/proto/ProtoGenerator.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/persistence/proto/ReflectionProtoGenerator.java, kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/persistence/KafkaStreamsTopologyProducerJavaTemplate.java, kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/process/persistence/KafkaPersistenceGeneratorTest.java, kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/JandexProtoGenerator.java, kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/825
- https://github.com/kiegroup/kogito-examples/pull/393
- https://github.com/kiegroup/kie-docs/pull/3178
=> KOGITO-3073 Kafka persistence addon

integration-tests/integration-tests-quarkus-decisions/pom.xml, integration-tests/integration-tests-quarkus-predictions/pom.xml, integration-tests/integration-tests-quarkus-processes/pom.xml, integration-tests/integration-tests-quarkus-rules/pom.xml
JIRA: https://issues.redhat.com/browse/KOGITO-4431
Additional PRs: 
kogito-apps: https://github.com/kiegroup/kogito-apps/pull/646
kogito-examples: https://github.com/kiegroup/kogito-examples/pull/492
=> KOGITO-4431 - Fix native build pom

kogito-bom/pom.xml
=> PLANNER-2316: Task assigning service scaffold and solution loading

addons/cloudevents/cloudevents-spring-boot-addon-it/pom.xml, addons/cloudevents/cloudevents-spring-boot-addon/pom.xml, addons/events/kogito-event-driven-decisions/kogito-event-driven-decisions-springboot-addon/pom.xml, addons/explainability-addon/explainability-springboot-addon/pom.xml, addons/jobs/jobs-management-springboot-addon/pom.xml, addons/monitoring/monitoring-core/monitoring-core-springboot-addon/pom.xml, addons/monitoring/monitoring-elastic/monitoring-elastic-springboot-addon/pom.xml, addons/monitoring/monitoring-prometheus/monitoring-prometheus-springboot-addon/pom.xml, addons/persistence/mongodb-persistence-addon/pom.xml, addons/process-management/pom.xml, addons/process-management/process-management-springboot-addon/pom.xml, addons/tracing/tracing-decision-springboot-addon/pom.xml, archetypes/kogito-springboot-archetype/src/main/resources/archetype-resources/pom.xml, integration-tests/integration-tests-springboot/pom.xml, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/pom.xml, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-kafka-it/pom.xml, kogito-build-parent/pom.xml, kogito-springboot/pom.xml, kogito-test-utils/pom.xml
backport of https://github.com/kiegroup/kogito-runtimes/pull/1059
Merge together with https://github.com/kiegroup/kogito-examples/pull/574 and https://github.com/kiegroup/kogito-apps/pull/659
=> [1.3.x] KOGITO-4251 backport

Jenkinsfile, Jenkinsfile.deploy, Jenkinsfile.drools, Jenkinsfile.native, Jenkinsfile.promote, Jenkinsfile.quarkus, Jenkinsfile.sonarcloud
https://issues.redhat.com/browse/KOGITO-4446
Depends on https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/141
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1076
- https://github.com/kiegroup/kogito-apps/pull/651
- https://github.com/kiegroup/kogito-examples/pull/569
=> KOGITO-4446 clean container images

addons/cloudevents/cloudevents-quarkus-addon/pom.xml, addons/events/kogito-events-reactive-messaging-addon/pom.xml, drools/kogito-pmml-openapi/pom.xml, kogito-build-parent/pom.xml
https://issues.redhat.com/browse/KOGITO-4440
cherry pick of https://github.com/kiegroup/kogito-runtimes/pull/1069
assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/1081
- https://github.com/kiegroup/kogito-apps/pull/661
- https://github.com/kiegroup/kogito-examples/pull/578
=> [1.3.x] KOGITO-4440 Quarkus 1.12.0.Final

Jenkinsfile, Jenkinsfile.deploy, Jenkinsfile.drools, Jenkinsfile.native, Jenkinsfile.promote, Jenkinsfile.quarkus, Jenkinsfile.sonarcloud
https://issues.redhat.com/browse/KOGITO-4446
cherry-pick: https://github.com/kiegroup/kogito-runtimes/pull/1076
Related:
- https://github.com/kiegroup/kogito-runtimes/pull/1083
- https://github.com/kiegroup/kogito-apps/pull/660
- https://github.com/kiegroup/kogito-examples/pull/575
=> [1.3.x] KOGITO-4446 clean container images

kogito-build-parent/pom.xml
https://issues.redhat.com/browse/KOGITO-4507
Downgrade to 1.11.3
https://github.com/kiegroup/kogito-examples/pull/585
=> [1.3.x] KOGITO-4507 Downgrade to Quarkus 1.11.x

addons/pom.xml, drools/pom.xml, jbpm/pom.xml, kogito-codegen-modules/pom.xml, kogito-quarkus-extension/pom.xml, pom.xml
https://github.com/kiegroup/kogito-pipelines/pull/121
https://github.com/kiegroup/kogito-examples/pull/583
https://github.com/kiegroup/optaplanner/pull/1170
https://github.com/kiegroup/kogito-runtimes/pull/1089
=> BXMSPROD-1208 prod profile 1.3.x

addons/pom.xml, drools/pom.xml, jbpm/pom.xml, kogito-codegen-modules/pom.xml, kogito-quarkus-extension/pom.xml, pom.xml
https://github.com/kiegroup/optaplanner/pull/1165
https://github.com/kiegroup/kogito-examples/pull/568
https://github.com/kiegroup/kogito-runtimes/pull/1078
https://github.com/kiegroup/kogito-pipelines/pull/117
=> BXMSPROD-1208 prod profile

kogito-build-parent/pom.xml
https://issues.redhat.com/browse/KOGITO-4504
=> KOGITO-4504  Upgrade Kie 7.50.0.Final

kogito-codegen-modules/kogito-codegen-predictions/src/main/resources/class-templates/PMMLRestResourceQuarkusTemplate.java, kogito-codegen-modules/kogito-codegen-predictions/src/main/resources/class-templates/PMMLRestResourceSpringTemplate.java
@danielezonca @tkobayas  @jiripetrlik
See https://issues.redhat.com/browse/KOGITO-4459
Needed by https://github.com/kiegroup/kogito-examples/pull/580
=> [KOGITO-4459] Removing trailing slash from springboot "raw result" endpoints

kogito-build-parent/pom.xml
https://issues.redhat.com/browse/KOGITO-4504
=> [1.3.x] KOGITO-4504  Upgrade Kie 7.50.0.Final

archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/pom.xml
https://issues.redhat.com/browse/KOGITO-4526
Operator needs this health check by default
cherry-pick: https://github.com/kiegroup/kogito-runtimes/pull/1093
=> [1.3.x] KOGITO-4256 Setup smallrye-health in archetype

archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/pom.xml
https://issues.redhat.com/browse/KOGITO-4526
Operator needs this health check by default
=> KOGITO-4256 Setup smallrye-health in archetype

kogito-build-parent/pom.xml
https://issues.redhat.com/browse/KOGITO-4538
=> KOGITO-4538 Bump OpenAPI 2.0.22

kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus/src/main/java/org/kie/kogito/quarkus/runtime/graal/graal/JsonSmartSubstitutions.java
=> fix master

kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus/pom.xml
=> Fix kogito-quarkus parent

addons/monitoring/monitoring-prometheus/monitoring-prometheus-springboot-addon/src/main/java/org/kie/kogito/monitoring/prometheus/springboot/rest/SpringbootMetricsResource.java
JIRA: https://issues.redhat.com/browse/KOGITO-4450
kogito-examples: https://github.com/kiegroup/kogito-examples/pull/573
=> KOGITO-4450 - Set monitoring prometheus metrics endpoint content type

kogito-build-parent/pom.xml
https://github.com/kiegroup/kogito-runtimes/pull/1095
https://github.com/kiegroup/kogito-apps/pull/670
---
=> [1.3.x] Upgrade to Quarkus 1.11.4

jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/StartEventHandler.java, jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ErrorEventTest.java, jbpm/jbpm-bpmn2/src/test/resources/error/EndError.bpmn2, jbpm/jbpm-bpmn2/src/test/resources/error/EndErrorWithEventSubprocess.bpmn2, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/FaultNodeVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/StartNodeVisitor.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/actions/SignalProcessInstanceAction.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowProcessFactory.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/FaultNodeFactory.java, kogito-codegen-modules/kogito-codegen-integration-tests/src/test/java/org/kie/kogito/codegen/tests/ErrorTest.java, kogito-codegen-modules/kogito-codegen-integration-tests/src/test/resources/error/EndError.bpmn2, kogito-codegen-modules/kogito-codegen-integration-tests/src/test/resources/error/EndErrorInSubprocessWithEventSubprocess.bpmn2, kogito-codegen-modules/kogito-codegen-integration-tests/src/test/resources/error/EndErrorWithEventSubprocess.bpmn2
=> [KOGITO-3858] [KOGITO-4329] [KOGITO-4330] Error Handling

drools/drools-decisiontables/pom.xml, drools/kogito-dmn/pom.xml, drools/kogito-drools-model/pom.xml, drools/kogito-drools/pom.xml, drools/kogito-pmml-api-dependencies/pom.xml, drools/kogito-pmml-dependencies/pom.xml, drools/kogito-pmml-openapi/pom.xml, drools/kogito-pmml/pom.xml, drools/kogito-ruleunits/pom.xml, drools/kogito-scenario-simulation/pom.xml
https://issues.redhat.com/browse/KOGITO-4551
=> KOGITO-4551 Java module name for -runtimes/drools/ artifacts

kogito-ide-config/README.md
=> Fix eclipse plugin link

kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/AddonsConfig.java, kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/utils/AddonsConfigDiscovery.java, kogito-codegen-modules/kogito-codegen-api/src/test/java/org/kie/kogito/codegen/api/AddonsConfigTest.java, kogito-quarkus-parent/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java
JIRA: https://issues.redhat.com/browse/KOGITO-4568
Related PR on kogito-examples: https://github.com/kiegroup/kogito-examples/pull/598
=> KOGITO-4568 - Add tracing and explainability classes for reflection

kogito-build-parent/pom.xml
https://github.com/kiegroup/kogito-runtimes/pull/1115
https://github.com/kiegroup/kogito-apps/pull/692
https://github.com/kiegroup/kogito-examples/pull/601
https://issues.redhat.com/browse/KOGITO-4595
=> KOGITO-4595 Downgrade Quarkus 1.11

addons/pom.xml, drools/pom.xml, jbpm/pom.xml, kogito-codegen-modules/pom.xml, kogito-quarkus-parent/pom.xml, pom.xml
=> BXMSPROD-1208 - adjustments for productization

addons/pom.xml, drools/pom.xml, jbpm/pom.xml, kogito-codegen-modules/pom.xml, kogito-quarkus-extension/pom.xml, pom.xml
=> BXMSPROD-1208 - adjustments for productization of 1.3.x

kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionRestResourceGenerator.java, kogito-codegen-modules/kogito-codegen-decisions/src/main/resources/class-templates/DecisionRestResourceQuarkusTemplate.java, kogito-codegen-modules/kogito-codegen-decisions/src/main/resources/class-templates/DecisionRestResourceSpringTemplate.java
JIRA: https://issues.redhat.com/browse/KOGITO-4581
=> KOGITO-4581 - Fix template exception handling and refactoring

integration-tests/integration-tests-quarkus-decisions/pom.xml, integration-tests/integration-tests-quarkus-decisions/src/main/java/org/kie/kogito/integrationtests/quarkus/FaceMaskTestData.java, integration-tests/integration-tests-quarkus-decisions/src/main/java/org/kie/kogito/integrationtests/quarkus/HospitalStatusTestData.java, integration-tests/integration-tests-quarkus-decisions/src/main/java/org/kie/kogito/integrationtests/quarkus/HospitalsTestData.java, integration-tests/integration-tests-quarkus-decisions/src/main/java/org/kie/kogito/integrationtests/quarkus/Human.java, integration-tests/integration-tests-quarkus-decisions/src/main/java/org/kie/kogito/integrationtests/quarkus/Patient.java, integration-tests/integration-tests-quarkus-decisions/src/main/resources/FaceMask.dmn, integration-tests/integration-tests-quarkus-decisions/src/main/resources/HospitalStatus.dmn, integration-tests/integration-tests-quarkus-decisions/src/main/resources/Hospitals.dmn, integration-tests/integration-tests-quarkus-decisions/src/main/resources/StatusService.dmn, integration-tests/integration-tests-quarkus-decisions/src/test/java/org/kie/kogito/integrationtests/quarkus/FaceMaskTest.java, integration-tests/integration-tests-quarkus-decisions/src/test/java/org/kie/kogito/integrationtests/quarkus/HospitalsStatusTest.java, integration-tests/integration-tests-quarkus-decisions/src/test/java/org/kie/kogito/integrationtests/quarkus/HospitalsTest.java, integration-tests/integration-tests-quarkus-decisions/src/test/java/org/kie/kogito/integrationtests/quarkus/NativeHospitalsStatusIT.java, integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/TaskTest.java, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/main/java/org/kie/kogito/integrationtests/springboot/FaceMaskTestData.java, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/main/java/org/kie/kogito/integrationtests/springboot/HospitalStatusTestData.java, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/main/java/org/kie/kogito/integrationtests/springboot/HospitalsTestData.java, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/main/java/org/kie/kogito/integrationtests/springboot/Human.java, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/main/java/org/kie/kogito/integrationtests/springboot/Patient.java, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/main/resources/FaceMask.dmn, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/main/resources/HospitalStatus.dmn, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/main/resources/Hospitals.dmn, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/main/resources/StatusService.dmn, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/FaceMaskTest.java, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/HospitalsStatusTest.java, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/HospitalsTest.java, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/TaskTest.java, integration-tests/pom.xml
Additional tests of executing models containing:
- Relation Expression
- Collect Hit Policy Decision Table Expressions
- Multiple DRDs
- DMN model including another DMN model
For more details see: https://issues.redhat.com/browse/KOGITO-4569
=> KOGITO-4569: Additional tests

.github/pull_request_template.md, .jenkins/dsl/jobs.groovy, Jenkinsfile
https://issues.redhat.com/browse/KOGITO-4452
In order to test against LTS version of Quarkus.
Command will be `Jenkins run LTS[ tests]`
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/119
- https://github.com/kiegroup/kogito-runtimes/pull/1072
- https://github.com/kiegroup/optaplanner/pull/1201
- https://github.com/kiegroup/kogito-apps/pull/655
- https://github.com/kiegroup/kogito-examples/pull/606
=> KOGITO-4452 Setup LTS PR check

kogito-quarkus-parent/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java
Fixes native build 
<details>
<summary>
</summary>
</details>
=> Add DecisionModelMetadata reflective class

drools/drools-core-static/src/main/java/org/drools/statics/StaticKieAssemblers.java, kogito-build-parent/pom.xml
<details>
<summary>
</summary>
</details>
=> Bump kie 7.51.0.Final

kogito-build-parent/pom.xml
The same file *kogito-build-parent/pom.xml* contained the same property twice.
=> Remove duplicated version.archetype.plugin property

drools/drools-core-static/src/main/java/org/drools/statics/StaticKieAssemblers.java, kogito-build-parent/pom.xml
* Bump kie 7.51.0.Final
* addResource
<details>
<summary>
</summary>
</details>
=> [1.4.x] Bump kie 7.51.0.Final

.github/quarkus-ecosystem-test, integration-tests/integration-tests-kogito-plugin/src/it/integration-tests-kogito-plugin-it/invoker.properties
https://issues.redhat.com/browse/KOGITO-4687
=> KOGITO-4687 Fix Quarkus Ecosystem CI with Quarkus master

.jenkins/dsl/jobs.groovy, Jenkinsfile.quarkus
https://issues.redhat.com/browse/KOGITO-4695
<details>
<summary>
</summary>
</details>
=> KOGITO-4695 Switch quarkus master to main

.github/pull_request_template.md, .jenkins/dsl/jobs.groovy, Jenkinsfile
https://issues.redhat.com/browse/KOGITO-4158
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/127
- https://github.com/kiegroup/kogito-runtimes/pull/1120
- https://github.com/kiegroup/optaplanner/pull/1204
- https://github.com/kiegroup/kogito-apps/pull/699
- https://github.com/kiegroup/kogito-examples/pull/608
=> KOGITO-4158 Setup native PR checks

Jenkinsfile.promote
https://issues.redhat.com/browse/KOGITO-4635
Related PRs:
- https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/146
- https://github.com/kiegroup/kogito-runtimes/pull/1127
- https://github.com/kiegroup/optaplanner/pull/1214
- https://github.com/kiegroup/kogito-apps/pull/712
- https://github.com/kiegroup/kogito-examples/pull/618
- https://github.com/kiegroup/kogito-images/pull/398
- https://github.com/kiegroup/kogito-operator/pull/804
<details>
<summary>
</summary>
* …
=> KOGITO-4635 Allow to override the tag if exists

integration-tests/integration-tests-quarkus-processes/pom.xml
https://issues.redhat.com/browse/KOGITO-4726
see https://github.com/quarkusio/quarkus/issues/12486#issuecomment-802169769
=> KOGITO-4726 missing smallrye http in integration-tests-quarkus-processes (breaks Quarkus master)

kogito-build-parent/pom.xml, kogito-quarkus-parent/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-deployment/src/main/java/org/kie/kogito/quarkus/decisions/deployment/DecisionsCompilationProvider.java, kogito-quarkus-parent/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java, kogito-quarkus-parent/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoCompilationProvider.java, kogito-quarkus-parent/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoQuarkusResourceUtils.java, kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-deployment/src/main/java/org/kie/kogito/quarkus/deployment/ProcessesCompilationProvider.java, kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-integration-test-maven-devmode/src/test/java/io/quarkus/it/kogito/devmode/DevMojoIT.java, kogito-quarkus-parent/kogito-quarkus-rules-extension/kogito-quarkus-rules-deployment/src/main/java/org/kie/kogito/quarkus/rules/deployment/RulesCompilationProvider.java
<details>
<summary>
</summary>
</details>
=> [KOGITO-4512] avoid code generation inside compilation providers

jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/parser/core/ServerlessWorkflowFactory.java
Signed-off-by: Tihomir Surdilovic <tsurdilo@redhat.com>
<details>
<summary>
</summary>
</details>
=> KOGITO-4783 SW - Fix for no argument function refs

addons/task-management/task-management-quarkus-addon/pom.xml, addons/task-management/task-management-quarkus-addon/src/main/java/org/kie/kogito/task/management/TaskManagementResource.java
Changing from constructor injection to field injeciton
=> [KOGITO-4821] TaskManagementResource not compliant with JaCoCo mode

kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java
ref: https://issues.redhat.com/browse/KOGITO-4788
<details>
<summary>
</summary>
</details>
=> KOGITO-4788 DMN avoid spurious validation message for Java binding

addons/cloudevents/pom.xml, addons/events/pom.xml, addons/pom.xml, pom.xml
https://issues.redhat.com/browse/RHPAM-3579
related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1207
- https://github.com/kiegroup/kogito-runtimes/pull/1205
<details>
<summary>
</summary>
</details>
=> RHPAM-3579 Additional prod kogito artifacts for dmn-event-driven-* examples

addons/cloudevents/pom.xml, addons/events/pom.xml, addons/pom.xml, pom.xml
https://issues.redhat.com/browse/RHPAM-3579
related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1207
- https://github.com/kiegroup/kogito-runtimes/pull/1205
<details>
<summary>
</summary>
</details>
=> [1.5.x] RHPAM-3579 Additional prod kogito artifacts for dmn-event-driven-* examples

integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-kafka-it/src/test/java/org/kie/kogito/integrationtests/springboot/PingPongMessageTest.java, kogito-build-parent/pom.xml
related https://github.com/kiegroup/optaplanner/pull/1260
<details>
<summary>
</summary>
</details>
=> [1.5.x] KOGITO-4902 Bump kie7 to 7.52.0.Final

kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoInfinispanContainer.java, kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoKafkaContainer.java
JIRA: https://issues.redhat.com/browse/KOGITO-4911
<details>
<summary>
</summary>
</details>
=> KOGITO-4911 - add test container wait condition

Jenkinsfile, addons/cloudevents/cloudevents-spring-boot-addon-it/pom.xml, addons/explainability-addon/explainability-quarkus-addon/pom.xml, addons/persistence/infinispan-quarkus-health-addon/pom.xml, addons/task-management/task-management-quarkus-addon/pom.xml, archetypes/kogito-quarkus-archetype/pom.xml, archetypes/kogito-quarkus-dm-archetype/pom.xml, archetypes/kogito-springboot-archetype/pom.xml, archetypes/kogito-springboot-dm-archetype/pom.xml, archetypes/pom.xml, integration-tests/integration-tests-kogito-plugin/pom.xml, integration-tests/integration-tests-kogito-plugin/src/it/integration-tests-kogito-plugin-it/pom.xml, integration-tests/integration-tests-quarkus-decisions/pom.xml, integration-tests/integration-tests-quarkus-predictions/pom.xml, integration-tests/integration-tests-quarkus-processes/pom.xml, integration-tests/integration-tests-quarkus-rules/pom.xml, integration-tests/integration-tests-springboot/pom.xml, jbpm/jbpm-bpmn2/pom.xml, kogito-build-parent/pom.xml, kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-integration-test-hot-reload/pom.xml, kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-integration-test-maven-devmode/pom.xml, kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-integration-test-maven-devmode/src/test/java/io/quarkus/it/kogito/devmode/DevMojoIT.java, kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-integration-test/pom.xml, kogito-quarkus-parent/kogito-quarkus-predictions-extension/kogito-quarkus-predictions-integration-test/pom.xml, kogito-quarkus-parent/pom.xml
Cherry-pick of #1188 
<details>
<summary>
</summary>
</details>
=> [1.5.x] KOGITO-4847 Fix local builds for integration tests

kogito-bom/pom.xml
<details>
<summary>
</summary>
</details>
=> PLANNER-2359: User system integration/synchronization (initial application.properties based implementation)

kogito-quarkus-parent/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java, kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-deployment/src/main/java/org/kie/kogito/quarkus/deployment/ProcessesAssetsProcessor.java
<details>
<summary>
</summary>
</details>
=> KOGITO-4870 It's not possible to execute processes by using the quarkus

kogito-bom/pom.xml, kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/quarkus/PostgreSqlQuarkusTestResource.java
Jira: https://issues.redhat.com/browse/KOGITO-4337
Description: PostgreSQL persistence support for Job Service. Build three separate artifacts for in-memory, Infinispan and PostgreSQL.
<details>
<summary>
</summary>
<b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time …
=> KOGITO-4337: PostgreSQL persistence support for Job Service

archetypes/kogito-springboot-archetype/src/main/resources/archetype-resources/pom.xml, archetypes/kogito-springboot-dm-archetype/src/main/resources/archetype-resources/pom.xml
See: https://issues.redhat.com/browse/KOGITO-4958
<details>
<summary>
</summary>
</details>
=> [KOGITO-4958] Add Spring Boot Actuator as default dependency

kogito-quarkus-parent/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java
https://issues.redhat.com/browse/KOGITO-4995
<details>
<summary>
</summary>
</details>
=> [KOGITO-4995] Fix tracing event serialization in native mode

.jenkins/dsl/jobs.groovy, Jenkinsfile
Depends on https://github.com/kiegroup/kogito-pipelines/pull/147
<details>
<summary>
</summary>
</details>
=> Setup timeout values to PR check

kogito-build-parent/pom.xml
Assembly:
- https://github.com/kiegroup/kie-jenkins-scripts/pull/947
- https://github.com/kiegroup/kogito-runtimes/pull/1172
=> KOGITO-4767 - Upgrade GraalVM to version 20.3.1.2

integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-kafka-it/src/test/java/org/kie/kogito/integrationtests/springboot/PingPongMessageTest.java, kogito-build-parent/pom.xml
related: https://github.com/kiegroup/optaplanner/pull/1256
<details>
<summary>
</summary>
</details>
=> KOGITO-4092 Bump kie7 to 7.52.0.Final

kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/Constants.java, kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoGenericContainer.java, kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoInfinispanContainer.java, kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoKafkaContainer.java, kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoKeycloakContainer.java, kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoMongoDBContainer.java, kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoPostgreSqlContainer.java, kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoRedisSearchContainer.java, kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/springboot/KafkaSpringBootTestResource.java, kogito-test-utils/src/test/java/org/kie/kogito/testcontainers/InfinispanContainerTest.java, kogito-test-utils/src/test/java/org/kie/kogito/testcontainers/KeycloakContainerTest.java, kogito-test-utils/src/test/java/org/kie/kogito/testcontainers/KogitoRedisSearchContainerTest.java, kogito-test-utils/src/test/java/org/kie/kogito/testcontainers/quarkus/InfinispanQuarkusTestResourceTest.java, kogito-test-utils/src/test/java/org/kie/kogito/testcontainers/quarkus/KeycloakQuarkusTestResourceTest.java, kogito-test-utils/src/test/java/org/kie/kogito/testcontainers/quarkus/RedisQuarkusTestResourceTest.java, kogito-test-utils/src/test/java/org/kie/kogito/testcontainers/springboot/InfinispanSpringBootTestResourceTest.java, kogito-test-utils/src/test/java/org/kie/kogito/testcontainers/springboot/KeycloakSpringBootTestResourceTest.java, kogito-test-utils/src/test/java/org/kie/kogito/testcontainers/springboot/RedisSpringBootTestResourceTest.java
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/1257
- https://github.com/kiegroup/kogito-apps/pull/779
- https://github.com/kiegroup/kogito-examples/pull/664
=> KOGITO-4945 - Unify Testcontainers usage

api/kogito-api/src/main/java/org/kie/kogito/rules/RuleUnit.java, drools/kogito-ruleunits/src/main/java/org/kie/kogito/rules/units/impl/AbstractRuleUnit.java, drools/kogito-ruleunits/src/main/java/org/kie/kogito/rules/units/impl/AbstractRuleUnits.java
<details>
<summary>
</summary>
</details>
=> [KOGITO-4956] avoid registering anonymous rule units

addons/cloudevents/pom.xml, addons/events/pom.xml, kogito-codegen-modules/pom.xml, pom.xml
Signed-off-by: Alberto Morales Perez <almorale@redhat.com>
<details>
<summary>
</summary>
</details>
=> [1.5.x] Kogito 1.5.0 productization changes

kogito-build-parent/pom.xml
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/1253
- https://github.com/kiegroup/kogito-apps/pull/788
=> Failsafe and Surefire plugins upgrade

addons/cloudevents/pom.xml, addons/events/pom.xml, kogito-codegen-modules/pom.xml, pom.xml
Signed-off-by: Alberto Morales Perez <almorale@redhat.com>
As this was needed for 1.5.0 productization it has been checked in the backport first: https://github.com/kiegroup/kogito-runtimes/pull/1261
<details>
<summary>
</summary>
<b>This check should be used only if a big change is done as …
=> Kogito 1.5.0 productization changes

jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/AbstractNodeHandler.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/xml/XmlProcessReader.java, kogito-build-parent/pom.xml
https://issues.redhat.com/browse/KOGITO-5079
<details>
<summary>
</summary>
</details>
=> [KOGITO-5079] Bump 7.54.0.Beta1

addons/monitoring/monitoring-core/monitoring-core-common/src/test/java/org/kie/kogito/monitoring/core/common/integration/BigDecimalHandlerTest.java, kogito-build-parent/pom.xml, kogito-cloud-services/kogito-cloud-kubernetes-client/src/main/java/org/kie/kogito/cloud/kubernetes/client/KogitoKubeConfig.java
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/1287
- https://github.com/kiegroup/kogito-apps/pull/807
=> Missing io. prefix config to match eclipse.importorder

drools/kogito-pmml/src/main/java/org/kie/kogito/pmml/KieRuntimeFactoryBuilder.java, kogito-codegen-modules/kogito-codegen-predictions/src/test/java/org/kie/kogito/codegen/prediction/PredictionCodegenTest.java
https://issues.redhat.com/browse/RHDM-1727
@danielezonca @kostola  @jiripetrlik
Quick fix for PMMLRuleMapper retrieval/path separator
=> [RHDM-1727] Fixing test/RuleMapper retrieval

jbpm/process-serialization-protobuf/pom.xml, jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/serialization/process/impl/ProtobufProcessInstanceReader.java, jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/serialization/process/impl/ProtobufProcessInstanceWriter.java, jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/serialization/process/impl/ProtobufVariableReader.java, jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/serialization/process/impl/ProtobufVariableWriter.java, jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/serialization/process/impl/marshallers/ProtobufObjectMarshallerStrategy.java, jbpm/process-serialization-protobuf/src/test/java/org/kie/kogito/serialization/process/ProcessInstanceMarshallTest.java
Bad datatype calculation plus guard test for variable marshall/unmarshall
=> [KOGITO-5118] Unmarshall variables lead to bad data type calculation

.github/workflows/apps-pr.yml, .github/workflows/examples-pr.yml, .github/workflows/optaplanner-pr.yml, .github/workflows/runtimes-pr.yml
https://issues.redhat.com/browse/KOGITO-5130
<details>
<summary>
</summary>
</details>
=> [KOGITO-5130] Add cleanup step to GitHub action build

kogito-build/kogito-build-parent/pom.xml
Related PR
- https://github.com/kiegroup/optaplanner/pull/1326
- https://github.com/kiegroup/kogito-runtimes/pull/1308
<details>
<summary>
</summary>
<b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a …
=> [master] Bump KIE 7.54.0.Final

.github/workflows/apps-pr.yml, .github/workflows/examples-pr.yml, .github/workflows/optaplanner-pr.yml, .github/workflows/runtimes-pr.yml
https://issues.redhat.com/browse/KOGITO-5120
PR list:
- https://github.com/kiegroup/kogito-pipelines/pull/168
- https://github.com/kiegroup/kogito-runtimes/pull/1310
- https://github.com/kiegroup/kogito-apps/pull/823
- https://github.com/kiegroup/kogito-examples/pull/698
=> [KOGITO-5120] Centralise GitHub Action common build options

kogito-codegen-modules/kogito-codegen-integration-tests/src/test/java/org/kie/kogito/codegen/RuleUnitCompilerIT.java, kogito-codegen-modules/kogito-codegen-integration-tests/src/test/java/org/kie/kogito/codegen/data/Person.java, kogito-codegen-modules/kogito-codegen-integration-tests/src/test/resources/org/kie/kogito/codegen/unit/RuleUnitQueryNoRules.drl
Related 
https://github.com/kiegroup/drools/pull/3541
<details>
<summary>
</summary>
</details>
=> [KOGITO-3791] Accumulate in a query used for automatic generation of REST endpoint of Rule Units

jbpm/jbpm-flow-builder/src/test/java/org/jbpm/integrationtests/ProcessFlowControlTest.java
Forward port of https://github.com/kiegroup/jbpm/pull/1931
=> [DROOLS-6331][cherry-pick] Remove useless test methods

kogito-build-parent/pom.xml
Related PR
- https://github.com/kiegroup/kogito-runtimes/pull/1309
- https://github.com/kiegroup/optaplanner/pull/1327
<details>
<summary>
</summary>
<b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a …
=> [1.7.x][master] Bump KIE 7.54.0.Final

.github/workflows/jenkins-tests-PR.yml, .jenkins/tests/pom.xml, .jenkins/tests/setup_pipeline_env.sh
Similar to https://github.com/kiegroup/kogito-pipelines/pull/164
<details>
<summary>
</summary>
</details>
=> Correct GHAction for Jenkinsfile testing

archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/pom.xml, archetypes/kogito-quarkus-dm-archetype/src/main/resources/archetype-resources/pom.xml
Jira: https://issues.redhat.com/browse/KOGITO-5140
Cherry-pick of #1317 .
<details>
<summary>
</summary>
</details>
=> [1.5.x] KOGITO-5140 defer expansion of properties with versions in quarkus archetypes

kogito-build-parent/pom.xml
Upgrading to use latest micro release of Quarkus.
<details>
<summary>
</summary>
</details>
=> [1.5.x] KOGITO-5141 Upgrade Quarkus to 1.11.6.Final

kogito-build/kogito-build-parent/pom.xml
Details at https://app.snyk.io/vuln/SNYK-JAVA-COMTHOUGHTWORKSXSTREAM-1088337
- [X ] You have read the [contributors guide](CONTRIBUTING.md)
<details>
<summary>
</summary>
</details>
=> Upgrade xstream to 1.4.16

archetypes/kogito-quarkus-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/resources/index.html, archetypes/kogito-springboot-archetype/src/main/resources/META-INF/maven/archetype-metadata.xml, archetypes/kogito-springboot-archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/resources/index.html
Jira: https://issues.redhat.com/browse/KOGITO-5114
=> KOGITO-5114: Add default index.html to springboot and quarkus kogito archetypes

addons/persistence/infinispan-persistence-addon/src/test/java/org/kie/kogito/infinispan/CacheProcessInstancesIT.java, addons/persistence/infinispan-quarkus-health-addon/src/test/resources/application.properties, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-infinispan/src/test/resources/application.properties, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/pom.xml, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-kafka-it/pom.xml, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-norest-it/pom.xml, kogito-build/kogito-build-parent/pom.xml, kogito-test-utils/src/main/resources/testcontainers/infinispan/infinispan-local.xml
Assembly:
- https://github.com/kiegroup/kogito-examples/pull/707
- https://github.com/kiegroup/kogito-runtimes/pull/1333
- https://github.com/kiegroup/kogito-apps/pull/846
=> KOGITO-4341 Infinispan upgrade to version 12

addons/mail/mail-quarkus-addon/src/main/java/org/kie/kogito/mail/QuarkusMailSender.java, addons/mail/mail-quarkus-addon/src/test/java/org/kie/kogito/mail/QuarkusMailSenderTest.java
Fixing problem with Uni subscription and adding unit test
Merge with  https://github.com/kiegroup/kogito-examples/pull/721
=> [KOGITO-5270] Quarkus mail addon is not sending email

.github/workflows/apps-pr.yml, .github/workflows/examples-pr.yml, .github/workflows/optaplanner-pr.yml, .github/workflows/runtimes-pr.yml
- https://github.com/kiegroup/kogito-pipelines/pull/182
- https://github.com/kiegroup/kogito-examples/pull/723
- https://github.com/kiegroup/kogito-apps/pull/876
- https://github.com/kiegroup/kogito-runtimes/pull/1358
- https://github.com/kiegroup/optaplanner/pull/1365
<details>
<summary>
</summary> …
=> github-action-build-chain updated to v2.6.2

.github/pull_request_template.md, .jenkins/dsl/jobs.groovy, Jenkinsfile
https://issues.redhat.com/browse/KOGITO-5070
This will allow to run Jenkins pr check, if `multijob-pr` label is set, in separate jobs.
Also, each project check is responsible to set correct Jenkinsfile and this avoids to rewrite the commands to run in each repo for the downstream projects.
_For now, this does not replace the current global PR check. It is only activated with the `multijob-pr` label._
Depends on https://github.com/kiegroup/kogito-pipelines/pull/148
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1284
- https://github.com/kiegroup/optaplanner/pull/1304
- https://github.com/kiegroup/kogito-apps/pull/805
- https://github.com/kiegroup/kogito-examples/pull/671
Please make sure that your PR meets the …
=> KOGITO-5070 Setup multijob pipeline

.github/workflows/full-downstream.yml
https://issues.redhat.com/browse/BXMSPROD-1355
related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/184
- https://github.com/kiegroup/kogito-apps/pull/879
- https://github.com/kiegroup/kogito-examples/pull/725
- https://github.com/kiegroup/kogito-runtimes/pull/1360
=> [BXMSPROD-1355][1.7.x] GA flow dynamic mapping

api/kogito-api/src/main/java/org/kie/kogito/conf/ConfigBean.java, api/kogito-api/src/main/java/org/kie/kogito/conf/StaticConfigBean.java, kogito-codegen-modules/kogito-codegen-core/src/main/java/org/kie/kogito/codegen/core/ApplicationConfigGenerator.java, kogito-codegen-modules/kogito-codegen-core/src/main/java/org/kie/kogito/codegen/core/ObjectMapperGenerator.java, kogito-codegen-modules/kogito-codegen-core/src/main/resources/class-templates/config/ConfigBeanQuarkusTemplate.java, kogito-codegen-modules/kogito-codegen-core/src/main/resources/class-templates/config/ConfigBeanSpringTemplate.java, kogito-codegen-modules/kogito-codegen-core/src/main/resources/class-templates/config/GlobalObjectMapperQuarkusTemplate.java, kogito-codegen-modules/kogito-codegen-core/src/main/resources/class-templates/config/GlobalObjectMapperSpringTemplate.java
Disable fail on empty beans is all cases.
=> [KOGITO-5302] Disable fail on empty beans

addons/persistence/jdbc-persistence-addon/src/main/java/org/kie/kogito/persistence/KogitoProcessInstancesFactory.java, addons/persistence/jdbc-persistence-addon/src/main/java/org/kie/kogito/persistence/jdbc/JDBCProcessInstances.java, addons/persistence/jdbc-persistence-addon/src/main/resources/sql/create_tables.sql, addons/persistence/jdbc-persistence-addon/src/test/java/org/kie/persistence/jdbc/JdbcProcessInstancesIT.java, addons/persistence/jdbc-persistence-addon/src/test/java/org/kie/persistence/jdbc/JdbcProcessInstancesWithLockIT.java, addons/persistence/jdbc-persistence-addon/src/test/java/org/kie/persistence/jdbc/TestHelper.java, addons/persistence/postgresql-persistence-addon/src/main/java/org/kie/kogito/persistence/postgresql/PostgreProcessInstances.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/persistence/PersistenceGenerator.java
<details>
<summary>
</summary>
</details>
=> [KOGITO-5196] - JDBC addon with optmistic locking

addons/persistence/mongodb-persistence-addon/pom.xml, addons/persistence/mongodb-persistence-addon/src/main/java/org/kie/kogito/mongodb/MongoDBProcessInstances.java, addons/persistence/mongodb-persistence-addon/src/main/java/org/kie/kogito/mongodb/transaction/MongoDBTransactionManager.java, addons/persistence/mongodb-persistence-addon/src/main/java/org/kie/kogito/persistence/KogitoProcessInstancesFactory.java, addons/persistence/mongodb-persistence-addon/src/test/java/org/kie/kogito/mongodb/KogitoProcessInstancesFactoryIT.java, addons/persistence/mongodb-persistence-addon/src/test/java/org/kie/kogito/mongodb/MongoDBProcessInstancesIT.java, addons/persistence/mongodb-persistence-addon/src/test/java/org/kie/kogito/mongodb/PersistentProcessInstancesIT.java, addons/persistence/mongodb-persistence-addon/src/test/java/org/kie/kogito/mongodb/transaction/MongoDBTransactionManagerIT.java, addons/persistence/mongodb-persistence-addon/src/test/java/org/kie/kogito/mongodb/transaction/MongoDBTransactionManagerTest.java, kogito-build/kogito-build-parent/pom.xml, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/persistence/PersistenceGenerator.java, kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/process/persistence/MongoDBPersistenceGeneratorTest.java, kogito-test-utils/pom.xml, kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoMongoDBContainer.java, kogito-test-utils/src/test/java/org/kie/kogito/testcontainers/KogitoMongoDBContainerTest.java, kogito-test-utils/src/test/java/org/kie/kogito/testcontainers/quarkus/MongoDBQuarkusTestResourceTest.java, kogito-test-utils/src/test/java/org/kie/kogito/testcontainers/springboot/MongoDBSpringBootTestResourceTest.java
Implement plugable transaction management for MongoDB to support outbox pattern.
Jira: https://issues.redhat.com/browse/KOGITO-3759
=> [KOGITO-3759] Implement plugable transaction management for MongoDB persistence

archetypes/kogito-quarkus-dm-archetype/README.md, archetypes/kogito-springboot-dm-archetype/README.md
<details>
<summary>
</summary> …
=> fix typo in READMEs

addons/persistence/infinispan-persistence-addon/src/main/java/org/kie/kogito/infinispan/CacheProcessInstances.java, addons/persistence/infinispan-persistence-addon/src/main/java/org/kie/kogito/persistence/KogitoProcessInstancesFactory.java, addons/persistence/infinispan-persistence-addon/src/test/java/org/kie/kogito/infinispan/CacheProcessInstancesIT.java, addons/persistence/infinispan-persistence-addon/src/test/java/org/kie/kogito/infinispan/CacheProcessInstancesWithLockIT.java, addons/persistence/infinispan-persistence-addon/src/test/java/org/kie/kogito/infinispan/KogitoProcessInstancesFactoryTest.java, addons/persistence/infinispan-persistence-addon/src/test/java/org/kie/kogito/infinispan/MockCacheProcessInstancesTest.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/persistence/PersistenceGenerator.java
<details>
<summary>
</summary>
</details>
=> [KOGITO-5197] - Infinispan addon with optmistic locking

addons/persistence/mongodb-persistence-addon/src/main/java/org/kie/kogito/mongodb/MongoDBProcessInstances.java, addons/persistence/mongodb-persistence-addon/src/main/java/org/kie/kogito/persistence/KogitoProcessInstancesFactory.java, addons/persistence/mongodb-persistence-addon/src/test/java/org/kie/kogito/mongodb/KogitoProcessInstancesFactoryIT.java, addons/persistence/mongodb-persistence-addon/src/test/java/org/kie/kogito/mongodb/MongoDBProcessInstancesIT.java, addons/persistence/mongodb-persistence-addon/src/test/java/org/kie/kogito/mongodb/PersistentProcessInstancesIT.java, addons/persistence/mongodb-persistence-addon/src/test/java/org/kie/kogito/mongodb/PersistentProcessInstancesWithLockIT.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/persistence/PersistenceGenerator.java
=> [KOGITO-4006] - PoC around using optimistic locking with MongoDB

kogito-build/kogito-build-parent/pom.xml
Includes
https://github.com/kiegroup/kogito-runtimes/pull/1291
https://github.com/kiegroup/kogito-runtimes/pull/1293
https://github.com/kiegroup/kogito-runtimes/pull/1294
https://github.com/kiegroup/kogito-runtimes/pull/1323
https://github.com/kiegroup/kogito-runtimes/pull/1326
https://github.com/kiegroup/kogito-runtimes/pull/1344
=> Consolidate Snyk PRs with updates of dependencies

addons/quarkus/persistence/kafka/src/main/java/org/kie/kogito/persistence/KogitoProcessInstancesFactory.java, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-kafka-persistence/src/test/java/org/kie/kogito/it/KafkaPersistenceIT.java, kogito-build/kogito-build-parent/pom.xml
- https://github.com/kiegroup/kogito-runtimes/pull/1394
- https://github.com/kiegroup/kogito-apps/pull/900
- https://github.com/kiegroup/kogito-examples/pull/742
<details>
<summary>
</summary> …
=> KOGITO-5405 Bump quarkus 2.0.0.Final

Jenkinsfile, Jenkinsfile.deploy, Jenkinsfile.drools, Jenkinsfile.native, Jenkinsfile.promote, Jenkinsfile.quarkus, Jenkinsfile.sonarcloud
<details>
<summary>
</summary> …
=> Setup Jenkins timestamps

addons/quarkus/persistence/kafka/src/main/java/org/kie/kogito/persistence/KogitoProcessInstancesFactory.java, archetypes/kogito-quarkus-dm-archetype/pom.xml, archetypes/kogito-springboot-dm-archetype/pom.xml, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-kafka-persistence/src/test/java/org/kie/kogito/it/KafkaPersistenceIT.java, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-persistence-it/integration-tests-springboot-processes-infinispan/pom.xml, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-persistence-it/integration-tests-springboot-processes-mongodb/pom.xml, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-persistence-it/integration-tests-springboot-processes-persistence-common/pom.xml, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-persistence-it/integration-tests-springboot-processes-postgresql/pom.xml, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-persistence-it/pom.xml, kogito-build/kogito-build-parent/pom.xml
- https://github.com/kiegroup/kogito-runtimes/pull/1395
- https://github.com/kiegroup/kogito-apps/pull/902
- https://github.com/kiegroup/kogito-examples/pull/741
=> [1.8.x] KOGITO-5405 Bump quarkus 2.0.0.Final 

Jenkinsfile, Jenkinsfile.deploy, Jenkinsfile.drools, Jenkinsfile.native, Jenkinsfile.promote, Jenkinsfile.quarkus, Jenkinsfile.sonarcloud
cherry-pick: https://github.com/kiegroup/kogito-runtimes/pull/1396
=> [1.8.x] Setup Jenkins timestamps

addons/quarkus/events/smallrye/src/main/java/org/kie/kogito/events/rm/ReactiveMessagingEventPublisher.java, addons/springboot/events/kafka/src/main/java/org/kie/kogito/events/spring/KafkaEventPublisher.java
JIRA: https://issues.redhat.com/browse/KOGITO-5388
=> [KOGITO-5388] Ignored cloudevents notified on WARN level

integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-persistence-it/integration-tests-springboot-processes-infinispan/pom.xml, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-persistence-it/integration-tests-springboot-processes-jdbc/pom.xml, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-persistence-it/integration-tests-springboot-processes-mongodb/pom.xml, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-persistence-it/integration-tests-springboot-processes-persistence-common/pom.xml, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-persistence-it/integration-tests-springboot-processes-postgresql/pom.xml, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-persistence-it/pom.xml
<details>
<summary>
</summary> …
=> KOGITO-5404 Remove parent from Springboot Persistence ITs

README.md
See: https://issues.redhat.com/browse/KOGITO-5389
With the "Issues" section of this repository being closed soon (see @ricardozanini's email in the BSIG mailing list about this), users should be directed to our other Kogito communities to ask for help.
I also removed unnecessary line breaks and changed the headers in the README to use the `h2` Markdown tag instead of a horizontal line. It produces the same effect - see my test README [here](https://github.com/Kevin-Mok/kogito-runtimes/tree/KOGITO-5389-headers#kogito) where the first header is the `h2` Markdown tag and the second is the original header with the horizontal line. In total, these changes don't modify the resulting HTML README, but they make the raw Markdown README cleaner. This breaks the "Pull Request does not include fixes …
=> [KOGITO-5389] Add "Asking for Help" section to README

addons/quarkus/cloudevents/multi/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/QuarkusMultiCloudEventPublisher.java
This is quick fix for a dummy error I found while doing performance testing
=> [KOGITO-5459] MultiCloudEvent addon fails if there is no consumer

kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionRestResourceGenerator.java
https://issues.redhat.com/browse/KOGITO-5462
<details>
<summary>
</summary> …
=> KOGITO-5462 Swagger/OAS annotation to honour platform serving context path

Jenkinsfile.deploy, Jenkinsfile.promote
https://issues.redhat.com/browse/KOGITO-4094
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/962
- https://github.com/kiegroup/optaplanner/pull/1095
- https://github.com/kiegroup/kogito-apps/pull/590
- https://github.com/kiegroup/kogito-examples/pull/515
=> KOGITO-4094 Avoid to deploy artifacts if author is not `kiegroup` and no artifacts repository has been given

.jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-5408
There will be one PR check job per branch instead of a global one.
This will help with updates of PR checks.
Depends on: https://github.com/kiegroup/kogito-pipelines/pull/201
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1399
- https://github.com/kiegroup/optaplanner/pull/1398
- https://github.com/kiegroup/kogito-apps/pull/905
- https://github.com/kiegroup/kogito-examples/pull/746
<details>
<summary>
</summary> …
=> KOGITO-5408 Branch dependent PR jobs

Jenkinsfile, kogito-build-parent/pom.xml, kogito-cloud-services/kogito-cloud-kubernetes-client/src/test/java/org/kie/kogito/cloud/kubernetes/client/MockKubernetesServerSupport.java, kogito-cloud-services/kogito-cloud-workitems/src/test/java/org/kie/kogito/cloud/workitems/KubernetesDiscoveredServiceWorkItemHandlerTest.java
Ticket: https://issues.redhat.com/browse/BXMSPROD-1394
<details>
<summary>
</summary>
Please add …
=> [1.5.x] BXMSPROD-1394 Quarkus to 1.11.7 from 1.11.6

.jenkins/dsl/jobs.groovy
**JIRA**: https://issues.redhat.com/browse/PLANNER-2467
Depends on: 
- https://github.com/kiegroup/kogito-pipelines/pull/204
- https://github.com/kiegroup/optaplanner/pull/1414
**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_
* https://github.com/kiegroup/kie-jenkins-scripts/pull/1025
* https://github.com/jboss-integration/rhba/pull/42
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1688
* https://github.com/kiegroup/optaweb-vehicle-routing/pull/526
* https://github.com/kiegroup/optaweb-employee-rostering/pull/651
* https://github.com/kiegroup/optaplanner/pull/1414
* https://github.com/kiegroup/kogito-runtimes/pull/1423
Please make sure that your PR meets the following …
=> PLANNER-2467 Jenkinsfiles moved to .ci/jenkins

.jenkins/dsl/jobs.groovy
cherry-pick: https://github.com/kiegroup/kogito-runtimes/pull/1399
https://issues.redhat.com/browse/KOGITO-5408
There will be one PR check job per branch instead of a global one.
This will help with updates of PR checks.
**Depends on: https://github.com/kiegroup/kogito-pipelines/pull/203**
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1404
- https://github.com/kiegroup/optaplanner/pull/1399
- https://github.com/kiegroup/kogito-apps/pull/908
- https://github.com/kiegroup/kogito-examples/pull/748
<details>
<summary>
</summary>
* …
=> [1.8.x] KOGITO-5408 Branch dependent PR jobs

kogito-build/kogito-build-parent/pom.xml
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/1401
- https://github.com/kiegroup/kogito-apps/pull/906
- https://github.com/kiegroup/kogito-examples/pull/747
=> KOGITO-5413 - Upgrade Java release version to v11

jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/serialization/process/impl/ProtobufProcessInstanceReader.java
if the variables are not in the message we need to check with the right call "hasXXX"
=> [KOGITO-4537] Claim operation seems to add empty String to some HumanTask fields

addons/common/persistence/infinispan/pom.xml
Jira: https://issues.redhat.com/browse/KOGITO-5471
<details>
<summary>
</summary> …
=> KOGITO-5471:`NoClassDefFoundError` in travel agency example

.github/workflows/quarkus-snapshot.yaml, .jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-5485
<details>
<summary>
</summary> …
=> KOGITO-5485 Disable LTS jobs

Jenkinsfile.deploy, Jenkinsfile.promote
https://issues.redhat.com/browse/KOGITO-5239
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1340
- https://github.com/kiegroup/kogito-apps/pull/855
- https://github.com/kiegroup/kogito-examples/pull/773
<details>
<summary>
</summary>
<b>This check should be used only if a big …
=> KOGITO-5239 Review deploy/promote timeouts

.jenkins/dsl/Jenkinsfile.seed
https://issues.redhat.com/browse/KOGITO-5480
cherry-pick: https://github.com/kiegroup/kogito-runtimes/pull/1429
<details>
<summary>
</summary>
* <b>Run …
=> [1.5.x] KOGITO-5480 Allow automatic DSL refresh

.jenkins/dsl/Jenkinsfile.seed
https://issues.redhat.com/browse/KOGITO-5480
cherry-pick: https://github.com/kiegroup/kogito-runtimes/pull/1429
<details>
<summary>
</summary>
* <b>Run …
=> [1.8.x] KOGITO-5480 Allow automatic DSL refresh

.jenkins/dsl/Jenkinsfile.seed
https://issues.redhat.com/browse/KOGITO-5480
cherry-pick: https://github.com/kiegroup/kogito-runtimes/pull/1429
<details>
<summary>
</summary>
* <b>Run …
=> [1.9.x] KOGITO-5480 Allow automatic DSL refresh

kogito-build/kogito-build-parent/pom.xml
See: https://issues.redhat.com/browse/KOGITO-5511
Downgrading to SB 2.3.x to align with the Runtimes release. I've kept the Junit 5 migration since SB 2.3.x supports it. There's no reason to revert that.
<details>
<summary>
</summary> …
=> [KOGITO-5511] - Downgrade SpringBoot to 2.3.x

kogito-build/kogito-build-parent/pom.xml
=> [1.9.x][KOGITO-5511] Downgrade SpringBoot to 2.3.10

kogito-build/kogito-build-parent/pom.xml
bundle:
- https://github.com/kiegroup/kogito-runtimes/pull/1422
- https://github.com/kiegroup/optaplanner/pull/1413
- https://github.com/kiegroup/optaplanner-quickstarts/pull/133
=> Bump Quarkus 2.0.1.Final

kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-integration-test-maven-devmode/src/test/java/io/quarkus/it/kogito/devmode/DevMojoIT.java
https://issues.redhat.com/browse/KOGITO-5530
<details>
<summary>
</summary> …
=> [KOGITO-5530] Increase DevMojoIT timeout

kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-integration-test-maven-devmode/src/test/java/io/quarkus/it/kogito/devmode/DevMojoIT.java
cherry-pick: https://github.com/kiegroup/kogito-runtimes/pull/1445
<details>
<summary>
</summary>
* <b>Run (or rerun) native specific test(s)</b> …
=> [1.9.x] Increase DevMojoIT timeout (#1445)

drools/kogito-scenario-simulation/pom.xml, kogito-build/kogito-kie7-bom/pom.xml
<details>
<summary>
</summary> …
=> [1.9.x] Bump KIE 7.57.0.Final

.jenkins/dsl/jobs.groovy, Jenkinsfile
https://issues.redhat.com/browse/KOGITO-5540
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1453
- https://github.com/kiegroup/optaplanner/pull/1442
- https://github.com/kiegroup/kogito-apps/pull/948
<details>
<summary>
</summary> …
=> KOGITO-5540 Disable Sonarcloud on release branches

Jenkinsfile
https://issues.redhat.com/browse/KOGITO-5532
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1447
- https://github.com/kiegroup/optaplanner/pull/1432
- https://github.com/kiegroup/kogito-apps/pull/943
- https://github.com/kiegroup/kogito-examples/pull/798
- https://github.com/kiegroup/kogito-images/pull/597
<details>
<summary>
</summary> …
=> KOGITO-5532 Corrected PR check author handling

drools/kogito-scenario-simulation/pom.xml, kogito-build/kogito-kie7-bom/pom.xml
<details>
<summary>
</summary> …
=> [master] Bump KIE 7.57.0.Final

.jenkins/dsl/jobs.groovy, Jenkinsfile
https://issues.redhat.com/browse/KOGITO-5540
cherry-pick: https://github.com/kiegroup/kogito-runtimes/pull/1453
<details>
<summary>
</summary>
* <b>Run …
=> [1.9.x] KOGITO-5540 Disable Sonarcloud on release branches

.jenkins/dsl/jobs.groovy, Jenkinsfile
https://issues.redhat.com/browse/KOGITO-5540
cherry-pick: https://github.com/kiegroup/kogito-runtimes/pull/1453
<details>
<summary>
</summary>
* <b>Run …
=> [1.5.x] KOGITO-5540 Disable Sonarcloud on release branches

.jenkins/dsl/jobs.groovy, Jenkinsfile.deploy, Jenkinsfile.drools, Jenkinsfile.native, Jenkinsfile.promote, Jenkinsfile.quarkus, Jenkinsfile.sonarcloud
https://issues.redhat.com/browse/KOGITO-5326
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/212
- https://github.com/kiegroup/kogito-runtimes/pull/1449
- https://github.com/kiegroup/optaplanner/pull/1436
- https://github.com/kiegroup/kogito-apps/pull/945
- https://github.com/kiegroup/kogito-examples/pull/800
- https://github.com/kiegroup/kogito-images/pull/602
- https://github.com/kiegroup/kogito-operator/pull/944
- https://github.com/kiegroup/rhpam-kogito-operator/pull/56
<details>
<summary>
</summary>
* <b>Run (or rerun) specific …
=> KOGITO-5326 Setup deploy/promote notifications on demand

Jenkinsfile.deploy
https://issues.redhat.com/browse/KOGITO-5567
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1466
- https://github.com/kiegroup/optaplanner/pull/1452
- https://github.com/kiegroup/kogito-examples/pull/808
<details>
<summary>
</summary> …
=> KOGITO-5567 Skip tests on Maven deploy

kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/context/KogitoBuildContext.java, kogito-codegen-modules/kogito-codegen-core/src/main/java/org/kie/kogito/codegen/core/ApplicationGenerator.java, kogito-codegen-modules/kogito-codegen-core/src/test/java/org/kie/kogito/codegen/core/ApplicationGeneratorTest.java, kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java, kogito-codegen-modules/kogito-codegen-decisions/src/test/java/org/kie/kogito/codegen/decision/DecisionCodegenTest.java, kogito-codegen-modules/kogito-codegen-predictions/src/main/java/org/kie/kogito/codegen/prediction/PredictionCodegen.java, kogito-codegen-modules/kogito-codegen-predictions/src/test/java/org/kie/kogito/codegen/prediction/PredictionCodegenTest.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java, kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/process/events/CodegenMessageStartEventTest.java, kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/process/events/CodegenUserTaskTest.java, kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegen.java, kogito-codegen-modules/kogito-codegen-rules/src/test/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegenTest.java, kogito-codegen-modules/kogito-codegen-sample/kogito-codegen-sample-generator/src/main/java/org/kie/kogito/codegen/sample/generator/SampleCodegen.java, kogito-codegen-modules/kogito-codegen-sample/kogito-codegen-sample-generator/src/test/java/org/kie/kogito/codegen/sample/generator/SampleCodegenTest.java
Allow users to disable REST endpoint generation for a specific resource using this syntax
`kogito.generate.decisions=false`
where "decisions" is a `Generator` `NAME`
Jira:
https://issues.redhat.com/browse/KOGITO-5538
related PR:
https://github.com/kiegroup/kogito-examples/pull/806
https://github.com/kiegroup/kogito-runtimes/pull/1458
https://github.com/kiegroup/kie-docs/pull/3804
<details>
<summary>
</summary>
* <b>Quarkus …
=> KOGITO-5538 Make REST generation optional for each type of resource

.github/pull_request_template.md, .github/workflows/quarkus-snapshot.yaml, .jenkins/dsl/test.sh, .jenkins/tests/setup_pipeline_env.sh, CONTRIBUTING.md, Jenkinsfile.drools, README.md, kogito-cloud-services/kogito-cloud-kubernetes-client/src/main/java/org/kie/kogito/cloud/kubernetes/client/graal/KubernetesClientCertUtilsSubstitutions.java, kogito-cloud-services/kogito-cloud-workitems/src/main/java/org/kie/kogito/cloud/workitems/service/discovery/IstioServiceDiscovery.java, kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/OpenApiSpecDescriptor.java, kogito-codegen-modules/kogito-codegen-openapi/src/main/resources/custom-templates/resteasy/README.md, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/util/ServerlessWorkflowUtils.java, quarkus/extensions/README.md
**PLEASE DO NOT MERGE. THIS WILL BE DONE WHEN `master` will be renamed as `main`**
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/188
- https://github.com/kiegroup/kogito-runtimes/pull/1365
- https://github.com/kiegroup/optaplanner/pull/1372
- https://github.com/kiegroup/optaweb-employee-rostering/pull/660
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/532
- https://github.com/kiegroup/optaplanner-quickstarts/pull/144
- https://github.com/kiegroup/kogito-apps/pull/882
- https://github.com/kiegroup/kogito-examples/pull/729
- https://github.com/kiegroup/kogito-images/pull/516
- https://github.com/kiegroup/kogito-operator/pull/905
- https://github.com/kiegroup/rhpam-kogito-operator/pull/44
Please make sure …
=> BXMSPROD-1265: Conscious language initiative

.jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-5486
Depends on https://github.com/kiegroup/kogito-pipelines/pull/209
<details>
<summary>
</summary>
* <b>Run …
=> KOGITO-5486 Setup LTS job against LTS branch

.jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-5535
related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/222
- https://github.com/kiegroup/kogito-runtimes/pull/1473
=> KOGITO-5535 Jenkins excluded_regions

.github/workflows/apps-pr.yml, .github/workflows/examples-pr.yml, .github/workflows/optaplanner-pr.yml, .github/workflows/runtimes-pr.yml
https://issues.redhat.com/browse/KOGITO-5535
<details>
<summary>
</summary> …
=> KOGITO-5535 pull_request paths-ignore

kogito-bom/pom.xml, springboot/bom/README.md, springboot/bom/pom.xml, springboot/pom.xml, springboot/starters/README.md, springboot/starters/kogito-decisions-spring-boot-starter/pom.xml, springboot/starters/kogito-predictions-spring-boot-starter/pom.xml, springboot/starters/kogito-processes-spring-boot-starter/pom.xml, springboot/starters/kogito-rules-spring-boot-starter/pom.xml, springboot/starters/kogito-serverless-workflow-spring-boot-starter/pom.xml, springboot/starters/kogito-spring-boot-starter/pom.xml, springboot/starters/kogito-springboot-starter/README.md, springboot/starters/kogito-springboot-starter/pom.xml, springboot/starters/kogito-springboot-starter/src/main/java/org/kie/kogito/springboot/starter/DeprecatedKogitoSpringBootStarter.java, springboot/starters/pom.xml
See: https://issues.redhat.com/browse/KOGITO-5301
Blocked by:
- https://github.com/kiegroup/kogito-runtimes/pull/1451
In this PR we introduce the newly `spring-boot-starters` and deprecate the old one. Ideally, we must follow [Spring Community naming](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.developing-auto-configuration.custom-starter.naming) and use `*-spring-boot-starter`.
This is just an initial work around the starters, that's why I haven't added "persistence", "monitoring" and so on. These can be easily added to the project's dependency based on the user's needs. I intend to also write a doc section about starters + addons usage.
About our addons, it's worth mentioning a quote from [SB …
=> [KOGITO-5301] - Introduce Kogito Spring Boot Starters

kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/persistence/proto/ProtoGenerator.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/persistence/proto/ReflectionProtoGenerator.java, kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/data/Person.java, kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/data/Travels.java, kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/process/persistence/proto/ReflectionProtoGeneratorTest.java
https://issues.redhat.com/browse/KOGITO-5570
Assembly:
- https://github.com/kiegroup/kogito-apps/pull/961
- https://github.com/kiegroup/kogito-runtimes/pull/1468
=> KOGITO-5570 Avoid setting indexing as true for all fields

quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/ProcessesAssetsProcessor.java
[KOGITO-5574](https://issues.redhat.com/browse/KOGITO-5574)
<details>
<summary>
</summary>
Please add …
=> KOGITO-5574 - Dump persistence generated classes to disk with Quarkus

quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions/src/main/resources/META-INF/quarkus-extension.yaml, quarkus/extensions/kogito-quarkus-extension/kogito-quarkus/src/main/resources/META-INF/quarkus-extension.yaml, quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions/src/main/resources/META-INF/quarkus-extension.yaml, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes/src/main/resources/quarkus-extension.yaml, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules/src/main/resources/META-INF/quarkus-extension.yaml
ref https://issues.redhat.com/browse/KOGITO-5560
Left UNchanged for 
https://github.com/kiegroup/kogito-runtimes/blob/22ea3901db6410efccaeeaa287a294e540c69a82/quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/src/main/resources/META-INF/quarkus-extension.yaml#L13
as requested
<details>
<summary>
</summary> …
=> KOGITO-5560 remove 'preview'label from community website

jbpm/jbpm-flow/src/test/java/org/kie/kogito/process/validation/ValidationContextTest.java, kogito-build/kogito-build-parent/pom.xml
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1465
- https://github.com/kiegroup/optaplanner/pull/1451
- https://github.com/kiegroup/optaplanner-quickstarts/pull/145
- https://github.com/kiegroup/kogito-apps/pull/964
- https://github.com/kiegroup/kogito-examples/pull/810
<details>
<summary>
</summary>
* <b>Run (or rerun) LTS specific …
=> Bump Quarkus 2.1.0.Final

.jenkins/dsl/jobs.groovy, Jenkinsfile.native
https://issues.redhat.com/browse/KOGITO-5597
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1482
- https://github.com/kiegroup/optaplanner/pull/1472
- https://github.com/kiegroup/kogito-apps/pull/965
- https://github.com/kiegroup/kogito-examples/pull/818
<details>
<summary>
</summary>
* <b>Run (or rerun) LTS specific test(s)</b> …
=> KOGITO-5597 Separate native checks

jbpm/jbpm-flow-builder/src/main/resources/class-templates/RestWorkItemHandlerTemplate.java, kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/di/impl/SpringDependencyInjectionAnnotator.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java, kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandlerUtils.java
Quick fix for generating the Vertx instance is not present in the
injection context
=> [KOGITO-5592]  REST WorkItemHandler for SpringBoot

integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/pom.xml, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/test/java/org/kie/kogito/it/PersistenceTest.java, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-postgresql/src/main/resources/application.properties, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-postgresql/src/test/resources/application.properties, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/persistence/PersistenceGenerator.java, kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/process/persistence/PostgrePersistenceGeneratorTest.java, kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/quarkus/PostgreSqlQuarkusTestResource.java
Assembly:
- https://github.com/kiegroup/kogito-examples/pull/815
- https://github.com/kiegroup/kogito-runtimes/pull/1472
- https://github.com/kiegroup/kie-docs/pull/3812
=> KOGITO-5564 Use Quarkus PgPool instead of creating a new one

kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/GeneratedFile.java, kogito-codegen-modules/kogito-codegen-core/src/main/java/org/kie/kogito/codegen/core/utils/GeneratedFileWriter.java
Avoid using "/", which is not OS independent.
https://issues.redhat.com/browse/KOGITO-5343
=> [KOGITO-5343] BPMN project build problem on Windows

integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/pom.xml, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/test/java/org/kie/kogito/it/PersistenceTest.java, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-postgresql/src/main/resources/application.properties, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-postgresql/src/test/resources/application.properties, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/persistence/PersistenceGenerator.java, kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/process/persistence/PostgrePersistenceGeneratorTest.java, kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/quarkus/PostgreSqlQuarkusTestResource.java
Cherry-pick from main
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/1494
- https://github.com/kiegroup/kogito-examples/pull/825
=> [1.10.x] KOGITO-5564 Use Quarkus PgPool instead of creating a new one

kogito-build/kogito-build-parent/pom.xml
Assembly:
- https://github.com/kiegroup/kogito-examples/pull/821
- https://github.com/kiegroup/kogito-runtimes/pull/1488
- https://github.com/kiegroup/kogito-apps/pull/969
=> KOGITO-5569 Upgrade Infinispan

.jenkins/dsl/jobs.groovy, Jenkinsfile.native
https://issues.redhat.com/browse/KOGITO-5635
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/229
- https://github.com/kiegroup/kogito-runtimes/pull/1491
- https://github.com/kiegroup/optaplanner/pull/1483
- https://github.com/kiegroup/kogito-apps/pull/973
- https://github.com/kiegroup/kogito-examples/pull/827
<details>
<summary>
</summary> …
=> KOGITO-5635 Added native LTS check

.github/workflows/apps-pr.yml, .github/workflows/examples-pr.yml, .github/workflows/optaplanner-pr.yml, .github/workflows/runtimes-pr.yml
related to https://github.com/kiegroup/kogito-runtimes/pull/1464
=> GH workflows paths-ignore improved

integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/main/resources/EmbeddedProcess.bpmn, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/test/java/org/kie/kogito/it/PersistenceTest.java, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-kafka-persistence/src/test/java/org/kie/kogito/it/KafkaPersistenceIT.java, jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/serialization/process/impl/ProtobufProcessInstanceReader.java, jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/serialization/process/impl/ProtobufProcessInstanceWriter.java
composite nodes instance should no have instantiate the variable scope instances as some of them does not need to.
Jira: https://issues.redhat.com/browse/KOGITO-5639
=> [KOGITO-5639] NullPointerException when marshalling a process instance state inside an embedded process

.github/workflows/issues.yml
https://issues.redhat.com/browse/KOGITO-5672
<details>
<summary>
</summary> …
=> KOGITO-5672 Implement GHA for open github issues for Zulip bot

jbpm/jbpm-flow/pom.xml, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/util/ComparablePeriodSerializer.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/util/TypeTransformer.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/RuleSetNodeInstance.java
jira: https://issues.redhat.com/browse/KOGITO-5366
=> [KOGITO-5366]  Incorrect object type returned in a DMN business-rule task of a BPMN (RuleSetNode Instance)

integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/main/resources/EmbeddedProcess.bpmn, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/test/java/org/kie/kogito/it/PersistenceTest.java, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-kafka-persistence/src/test/java/org/kie/kogito/it/KafkaPersistenceIT.java, jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/serialization/process/impl/ProtobufProcessInstanceReader.java, jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/serialization/process/impl/ProtobufProcessInstanceWriter.java
Jira: composite nodes instance should no have instantiate the variable scope instances as some of them does not need to.
Jira: https://issues.redhat.com/browse/KOGITO-5639
backport of https://github.com/kiegroup/kogito-runtimes/pull/1498
=> [1.10.x] [KOGITO-5639] NullPointerException when marshalling a process instance state inside an embedded process

kogito-build/kogito-kie7-bom/pom.xml
<details>
<summary>
</summary> …
=> [main] Bump KIE to 7.58.0.Final

kogito-build/kogito-build-parent/pom.xml
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/1505
- https://github.com/kiegroup/kogito-apps/pull/977
=> KOGITO-5662 - Upgrade to Quarkus 2.1.1

jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/serialization/process/impl/marshallers/ProtobufDateMarshallerStrategy.java, jbpm/process-serialization-protobuf/src/test/java/org/kie/kogito/serialization/process/ProcessInstanceMarshallTest.java
Jira: https://issues.redhat.com/browse/KOGITO-5677
=> [KOGITO-5677] ProcessInstanceMarshallTest - incorrect marshaller chosen for some types

kogito-build/kogito-kie7-bom/pom.xml
(cherry picked from commit 0d6e72d46ebea0792fad7f5a83734acf42d0c29d)
<details>
<summary>
</summary>
* <b>Run (or rerun) native specific test(s)</b> …
=> [1.10.x] Bump KIE to 7.58.0.Final (#1509)

jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/serialization/process/protobuf/ProtostreamProtobufAdapterTypeProvider.java, jbpm/process-serialization-protobuf/src/test/java/org/kie/kogito/serialization/process/protobuf/ProtostreamProtobufAdapterTypeProviderTest.java, jbpm/process-serialization-protobuf/src/test/resources/META-INF/application-types.proto, jbpm/process-serialization-protobuf/src/test/resources/META-INF/kogito-types.proto
<details>
<summary>
**problem description**: please see Jira https://issues.redhat.com/browse/KOGITO-5320
**problem solution**: resolved by a) making the lookup name a full-qualified name and b) ensuring that the kogito-types.proto is present as dependency when the application-types.proto is processed
</summary>
</details>
=> [KOGITO-5320] protobuf data type lookup fix

kogito-codegen-modules/kogito-codegen-core/src/main/resources/class-templates/config/GlobalObjectMapperQuarkusTemplate.java, kogito-codegen-modules/kogito-codegen-core/src/main/resources/class-templates/config/GlobalObjectMapperSpringTemplate.java, quarkus/addons/events/smallrye/src/main/java/org/kie/kogito/events/rm/ReactiveMessagingEventPublisher.java, springboot/addons/events/kafka/src/main/java/org/kie/kogito/events/spring/KafkaEventPublisher.java
https://issues.redhat.com/browse/KOGITO-5699
=> [KOGITO-5699] Inject object mapper for events addon

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/AbstractVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/CompositeContextNodeVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessVisitor.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/transformation/JsonResolver.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/RuleSetNodeInstance.java, jbpm/jbpm-flow/src/test/java/org/jbpm/process/core/transformation/JsonResolverTest.java, jbpm/jbpm-flow/src/test/java/org/jbpm/process/test/Person.java, kogito-workitems/kogito-rest-workitem/pom.xml, kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandler.java, kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandlerUtils.java, kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/bodybuilders/DefaultWorkItemHandlerBodyBuilder.java, kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/bodybuilders/ParamsRestWorkItemHandlerBodyBuilder.java, kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/bodybuilders/RestWorkItemHandlerBodyBuilder.java, kogito-workitems/kogito-rest-workitem/src/test/java/org/kogito/workitem/rest/RestWorkItemHandlerTest.java, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/ProcessesAssetsProcessor.java
Related: https://github.com/kiegroup/kogito-examples/pull/809
Main changes on:
- RuleSetNodeInstance
- RestWorkItemHandler
---
<details>
<summary>
</summary> …
=> [KOGITO-5255] Process integration with Decisions - Improvements

drools/kogito-pmml-openapi/src/test/java/org/kie/kogito/pmml/openapi/CommonTestUtility.java, drools/kogito-pmml-openapi/src/test/java/org/kie/kogito/pmml/openapi/PMMLOASUtilsTest.java, kogito-build/kogito-kie7-bom/pom.xml
- [Jira task](https://issues.redhat.com/browse/KOGITO-5703)
=> KOGITO-5703: fix PMML MiningField and bump kie7 version 7.59.0.Beta1

quarkus/test/src/main/java/org/kie/kogito/test/quarkus/kafka/KafkaTestClient.java, springboot/test/src/main/java/org/kie/kogito/test/springboot/kafka/KafkaTestClient.java, springboot/test/src/main/java/org/kie/kogito/testcontainers/springboot/KafkaSpringBootTestResource.java, springboot/test/src/test/java/org/kie/kogito/test/springboot/kafka/KafkaTestClientTest.java, springboot/test/src/test/java/org/kie/kogito/testcontainers/springboot/KafkaSpringBootTestResourceTest.java
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/1544
- https://github.com/kiegroup/kogito-apps/pull/992
- https://github.com/kiegroup/kogito-examples/pull/854
=> KOGITO-5664 - Rename KafkaClient package to avoid Sonar conflict

.ci/jenkins/Jenkinsfile, .ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.drools, .ci/jenkins/Jenkinsfile.native, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.sonarcloud, kogito-build/kogito-dependencies-bom/pom.xml
<details>
<summary>
</summary> …
=> Bump Quarkus 2.2.0.Final

drools/drools-core/src/main/java/org/drools/core/kogito/factory/KogitoFactHandleFactory.java, kogito-build/kogito-kie7-bom/pom.xml
<details>
<summary>
</summary> …
=> [1.11.x] Bump KIE 7.59.0.Final

.ci/jenkins/Jenkinsfile, .ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.drools, .ci/jenkins/Jenkinsfile.native, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.sonarcloud, kogito-build/kogito-dependencies-bom/pom.xml
* Bump Quarkus 2.2.0.Final
* updated jenkinsfiles
Co-authored-by: radtriste <tradisso@redhat.com>
(cherry picked from commit cc984d0152559e675d27453fd3413a9b312cc7d9)
<details>
<summary>
</summary>
* <b>Native checks</b> …
=> [1.11.x] Bump Quarkus 2.2.0.Final (#1559)

drools/drools-core/src/main/java/org/drools/core/kogito/factory/KogitoFactHandleFactory.java, kogito-build/kogito-kie7-bom/pom.xml
<details>
<summary>
</summary> …
=> [main] Bump KIE 7.59.0.Final

springboot/addons/events/kafka/src/main/java/org/kie/kogito/events/spring/KafkaEventPublisher.java, springboot/addons/messaging/implementation/src/main/java/org/kie/kogito/addon/cloudevents/spring/SpringKafkaCloudEventEmitter.java
See [JIRA](https://issues.redhat.com/browse/KOGITO-5797) for description of this PR
=> [KOGITO-5797] Allow change topic name for event process springboot addon

quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/pom.xml
Signed-off-by: Alberto Morales Perez <almorale@redhat.com>
=> [RHPAM-3890] Use BOM managed version for non-productized Quarkus test artifacts

jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/AbstractNodeHandler.java, jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/DataObjectHandler.java, jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/DefinitionsHandler.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/DataTypeResolver.java, jbpm/jbpm-flow/src/test/java/org/jbpm/process/core/datatype/DataTypeResolverTest.java, jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/serialization/process/impl/ProtobufVariableReader.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java
see https://issues.redhat.com/browse/KOGITO-5777
=> [KOGITO-5777] Centralize data type resolution

jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ActivityTest.java, jbpm/jbpm-bpmn2/src/test/resources/BPMN2-GatewayFEEL-wrong.bpmn2, jbpm/jbpm-bpmn2/src/test/resources/BPMN2-GatewayFEEL.bpmn2, jbpm/jbpm-flow-builder/pom.xml, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/SplitNodeVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/dialect/feel/FEELDialectCanonicalUtils.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/process/builder/dialect/ProcessDialectRegistry.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/process/builder/dialect/feel/FeelCompilationException.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/process/builder/dialect/feel/FeelProcessDialect.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/process/builder/dialect/feel/FeelReturnValueEvaluatorBuilder.java, jbpm/jbpm-flow-builder/src/test/java/org/jbpm/compiler/canonical/ProcessToExecModelGeneratorTest.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/FeelErrorEvaluatorListener.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/FeelReturnValueEvaluator.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/FeelReturnValueEvaluatorException.java, kogito-build/kogito-kie7-bom/pom.xml
JIRA: https://issues.redhat.com/browse/KOGITO-5565
I've taken care of porting the relevant bits of jBPM v7 to Kogito about FEEL evaluation for gateways, and then I've adapted where I could see fit to the kogito idioms, for as much as I could understand myself.
**Please reference commit titles for the code that has been kogito-ported from jBPM v7 to here.**
Far from a complete implementation of everything we can *actually* do, but I hope it is welcome in order to start to cover the gap.
<details>
<summary>
</summary>
* <b>Quarkus LTS …
=> KOGITO-5565 FEEL support as expr language in Gateway

kogito-build/kogito-dependencies-bom/pom.xml
<details>
<summary>
</summary> …
=> [1.11.x] Bump Quarkus 2.2.0.Final

integration-tests/integration-tests-quarkus-processes/src/main/resources/BPMN2GatewayFEEL.bpmn2, integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/GatewayFEELIT.java, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/main/resources/BPMN2GatewayFEEL.bpmn2, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/GatewayFEELIT.java
https://issues.redhat.com/browse/KOGITO-5806
follows up on 
* specifically: https://github.com/kiegroup/kogito-runtimes/pull/1562#issuecomment-910069114
<details>
<summary>
</summary> …
=> KOGITO-5806 FEEL in gateway, integration tests

quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions/src/main/resources/META-INF/quarkus-extension.yaml, quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions/src/main/resources/META-INF/quarkus-extension.yaml, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules/src/main/resources/META-INF/quarkus-extension.yaml
https://issues.redhat.com/browse/KOGITO-5827
<details>
<summary>
</summary> …
=> KOGITO-5827 Link Kogito Quarkus extensions guide in YAMLs

kogito-build/kogito-dependencies-bom/pom.xml
Fix for https://github.com/kiegroup/kogito-runtimes/pull/1596/files ...
<details>
<summary>
</summary>
* <b>Run (or rerun) native specific test(s)</b> …
=> Fix Bump Quarkus 2.2.2.Final

api/kogito-api-incubation-processes-services/pom.xml, api/kogito-api-incubation-processes-services/src/main/java/org/kie/kogito/incubation/processes/services/StraightThroughProcessService.java, api/kogito-api-incubation-processes-services/src/test/java/org/kie/kogito/incubation/processes/services/TestTypes.java, api/kogito-api-incubation-processes/pom.xml, api/kogito-api-incubation-processes/src/main/java/org/kie/kogito/incubation/processes/LocalProcessId.java, api/kogito-api-incubation-processes/src/main/java/org/kie/kogito/incubation/processes/ProcessId.java, api/kogito-api-incubation-processes/src/main/java/org/kie/kogito/incubation/processes/ProcessIds.java, api/kogito-api-incubation-processes/src/main/java/org/kie/kogito/incubation/processes/ProcessInstanceId.java, api/kogito-api-incubation-processes/src/main/java/org/kie/kogito/incubation/processes/ProcessInstanceIds.java, api/pom.xml, kogito-bom/pom.xml, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-integration-test/pom.xml, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-integration-test/src/main/java/org/acme/GreetingResource.java, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-integration-test/src/main/resources/application.properties, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-integration-test/src/main/resources/org/acme/travels/scripts.bpmn, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-integration-test/src/test/java/org/acme/GreetingResourceTest.java, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-integration-test/src/test/java/org/acme/NativeGreetingResourceIT.java, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes/pom.xml, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes/src/main/java/org/kie/kogito/core/process/incubation/quarkus/support/QuarkusProcessIdFactory.java, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes/src/main/java/org/kie/kogito/core/process/incubation/quarkus/support/QuarkusStraightThroughProcessService.java, quarkus/extensions/kogito-quarkus-processes-extension/pom.xml
Blocked by:
- see #1546 for an architectural overview
<details>
<summary>
</summary>
* <b>Full Kogito testing</b> (with cloud images …
=> KOGITO-5748 Public API: Straight-Through Process Modules (Incubation)

api/kogito-api-incubation-predictions-services/pom.xml, api/kogito-api-incubation-predictions-services/src/main/java/org/kie/kogito/incubation/predictions/services/PredictionService.java, api/kogito-api-incubation-predictions-services/src/test/java/org/kie/kogito/incubation/predictions/services/TestTypes.java, api/kogito-api-incubation-predictions/pom.xml, api/kogito-api-incubation-predictions/src/main/java/org/kie/kogito/incubation/predictions/LocalPredictionId.java, api/kogito-api-incubation-predictions/src/main/java/org/kie/kogito/incubation/predictions/PredictionIds.java, api/pom.xml, kogito-bom/pom.xml, quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions-integration-test/pom.xml, quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions-integration-test/src/main/java/org/kie/kogito/quarkus/pmml/CustomEndpoint.java, quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions-integration-test/src/test/java/org/kie/kogito/quarkus/pmml/CustomEndpointIT.java, quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions/pom.xml, quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions/src/main/java/org/kie/kogito/core/prediction/incubation/quarkus/support/QuarkusPredictionIdFactory.java, quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions/src/main/java/org/kie/kogito/core/prediction/incubation/quarkus/support/QuarkusPredictionIds.java, quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions/src/main/java/org/kie/kogito/core/prediction/incubation/quarkus/support/QuarkusPredictionService.java
https://issues.redhat.com/browse/KOGITO-5750
Notes:
- see #1546 for an architectural overview
- The names of the classes and modules (e.g. Predictions vs PMML) are for demo purposes only, and can be changed
<details>
<summary>
</summary>
* <b>Run (or rerun) native …
=> KOGITO-5750 Public API: PMML Modules (Incubation)

api/kogito-api-incubation-decisions-services/pom.xml, api/kogito-api-incubation-decisions-services/src/main/java/org/kie/kogito/incubation/decisions/services/DecisionService.java, api/kogito-api-incubation-decisions-services/src/test/java/org/kie/kogito/incubation/decisions/services/TestTypes.java, api/kogito-api-incubation-decisions/pom.xml, api/kogito-api-incubation-decisions/src/main/java/org/kie/kogito/incubation/decisions/DecisionIds.java, api/kogito-api-incubation-decisions/src/main/java/org/kie/kogito/incubation/decisions/DecisionServiceIds.java, api/kogito-api-incubation-decisions/src/main/java/org/kie/kogito/incubation/decisions/LocalDecisionId.java, api/kogito-api-incubation-decisions/src/main/java/org/kie/kogito/incubation/decisions/LocalDecisionServiceId.java, api/pom.xml, kogito-bom/pom.xml, quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test/pom.xml, quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test/src/main/java/org/kie/kogito/quarkus/dmn/CustomEndpoint.java, quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test/src/test/java/org/kie/kogito/quarkus/dmn/CustomEndpointIT.java, quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions/pom.xml, quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions/src/main/java/org/kie/kogito/core/decision/incubation/quarkus/support/QuarkusDecisionIdFactory.java, quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions/src/main/java/org/kie/kogito/core/decision/incubation/quarkus/support/QuarkusDecisionService.java
Notes:
- see #1546 for an architectural overview
- The names of the classes and modules (e.g. Decisions vs DMN) are for demo purposes only, and can be changed
<details>
<summary>
</summary> …
=> KOGITO-5749 Public API: DMN Modules (Incubation)

api/kogito-api-incubation-rules-services/pom.xml, api/kogito-api-incubation-rules-services/src/main/java/org/kie/kogito/incubation/rules/services/RuleUnitService.java, api/kogito-api-incubation-rules-services/src/test/java/org/kie/kogito/incubation/rules/services/RuleUnitServiceInterfaceTest.java, api/kogito-api-incubation-rules-services/src/test/java/org/kie/kogito/incubation/rules/services/TestTypes.java, api/kogito-api-incubation-rules/pom.xml, api/kogito-api-incubation-rules/src/main/java/org/kie/kogito/incubation/rules/InvalidRuleUnitIdException.java, api/kogito-api-incubation-rules/src/main/java/org/kie/kogito/incubation/rules/QueryId.java, api/kogito-api-incubation-rules/src/main/java/org/kie/kogito/incubation/rules/QueryIds.java, api/kogito-api-incubation-rules/src/main/java/org/kie/kogito/incubation/rules/RuleUnitId.java, api/kogito-api-incubation-rules/src/main/java/org/kie/kogito/incubation/rules/RuleUnitIds.java, api/pom.xml, kogito-bom/pom.xml, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules-integration-test/src/main/java/org/kie/kogito/quarkus/drools/CustomEndpoint.java, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules-integration-test/src/test/java/org/kie/kogito/quarkus/drools/CustomEndpointIT.java, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules/pom.xml, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules/src/main/java/org/kie/kogito/core/rules/incubation/quarkus/support/QuarkusRuleUnitIdFactory.java, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules/src/main/java/org/kie/kogito/core/rules/incubation/quarkus/support/QuarkusRuleUnitService.java, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules/src/main/java/org/kie/kogito/core/rules/incubation/quarkus/support/RuleUnitDataJacksonModule.java, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules/src/main/java/org/kie/kogito/core/rules/incubation/quarkus/support/RuleUnitDataObjectMapper.java
Notes:
- see #1546 for an architectural overview
<details>
<summary>
</summary> …
=> KOGITO-5751 Public API: Rule (unit) Modules (Incubation)

drools/drools-core/src/main/java/org/drools/core/kogito/factory/KogitoEventFactHandle.java, drools/drools-core/src/main/java/org/drools/core/kogito/factory/KogitoFactHandleFactory.java, kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegen.java, kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/KogitoPackageSources.java, kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/ProjectRuntimeGenerator.java, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules-integration-test-session/src/main/java/org/kie/kogito/quarkus/drools/ProbeCounter.java, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules-integration-test-session/src/main/java/org/kie/kogito/quarkus/drools/ProbeEvent.java, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules-integration-test-session/src/main/java/org/kie/kogito/quarkus/drools/StockTick.java, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules-integration-test-session/src/main/resources/META-INF/kmodule.xml, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules-integration-test-session/src/main/resources/org/drools/cep/cep.drl, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules-integration-test-session/src/main/resources/org/drools/probe/probe.drl, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules-integration-test-session/src/test/java/org/kie/kogito/quarkus/drools/NativeRuntimeIT.java, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules-integration-test-session/src/test/java/org/kie/kogito/quarkus/drools/RuntimeIT.java
<details>
<summary>
</summary> …
=> [KOGITO-5906] Enabling Event Fact type

quarkus/addons/messaging/integration-tests/pom.xml
See https://issues.redhat.com/browse/KOGITO-5935
Small fix to consider Jan's PR: 
- https://github.com/kiegroup/kogito-runtimes/pull/1584
=> [KOGITO-5935] Adding Kogito Quarkus Add-Ons to the quarkus test list

addons/README.md, quarkus/addons/README.md, springboot/addons/README.md
After the recent changes in the add-on structure, we missed some updates on the README files.
=> Fix leftovers on Add-ons README

integration-tests/integration-tests-quarkus-processes/src/main/resources/application.properties
<details>
<summary>
</summary> …
=> Update native memory to avoid GC overhead with Mandrel

.github/workflows/quarkus-snapshot.yaml
https://issues.redhat.com/browse/KOGITO-5487
Depends on https://github.com/quarkusio/quarkus-ecosystem-ci/pull/65
<details>
<summary>
</summary>
* …
=> [KOGITO-5487] Enable LTS check

addons/common/events/README.md, kogito-bom/pom.xml
Minor leftovers from original PR: https://github.com/kiegroup/kogito-runtimes/pull/1610
=> KOGITO-5533: implement evaluation of rules via CloudEvents (part 2)

quarkus/addons/messaging/integration-tests/pom.xml
Backport of https://github.com/kiegroup/kogito-runtimes/pull/1616
=> [KOGITO-5935] Adding Kogito Quarkus Add-Ons to the quarkus test list [1.11.x]

kogito-build/kogito-dependencies-bom/pom.xml
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1634
- https://github.com/kiegroup/optaplanner/pull/1593
- https://github.com/kiegroup/kogito-apps/pull/1044
- https://github.com/kiegroup/kogito-examples/pull/909
- https://github.com/kiegroup/optaplanner-quickstarts/pull/190
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/570
<details>
<summary>
</summary>
Please add …
=> Bump Quarkus 2.3.0.Final

kogito-build/kogito-dependencies-bom/pom.xml
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1646
- https://github.com/kiegroup/optaplanner/pull/1600
- https://github.com/kiegroup/kogito-examples/pull/917
- https://github.com/kiegroup/optaplanner-quickstarts/pull/195
<details>
<summary>
</summary> …
=> [1.11.x] Bump Quarkus 2.2.3.Final

.ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-5680
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/233
- https://github.com/kiegroup/kogito-runtimes/pull/1514
- https://github.com/kiegroup/optaplanner/pull/1503
- https://github.com/kiegroup/kogito-examples/pull/908
- https://github.com/kiegroup/optaplanner-quickstarts/pull/188
<details>
<summary>
</summary> …
=> [KOGITO-5680] Quarkus/Kie7 update Jenkins jobs

kogito-build/kogito-dependencies-bom/pom.xml, kogito-serverless-workflow/kogito-jq-expression/pom.xml, kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqExpressionHandler.java, kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqParsedExpression.java, kogito-serverless-workflow/kogito-jq-expression/src/test/java/org/kie/kogito/expr/jq/JqExpressionHandlerTest.java, kogito-serverless-workflow/kogito-jsonpath-expression/pom.xml, kogito-serverless-workflow/kogito-jsonpath-expression/src/test/java/org/kie/kogito/expr/jsonpath/JsonpathExpressionHandlerTest.java
Adding JQ implementation. 
Since Im going to implement callback first, lets merge this small one and use another PR to create the addons to set the injected scope into the expression handler.
=> [KOGITO-5550] Implementing JQ expression handling

drools/kogito-pmml/src/test/java/org/kie/kogito/pmml/CommonTestUtility.java
@danielezonca 
Needed by 
https://github.com/kiegroup/drools/pull/3978
=> [8.x][DROOLS-6641] Update testing KiePMMLModel

addons/common/tracing/typedvalue-api/src/main/java/org/kie/kogito/tracing/typedvalue/BaseTypedValue.java, addons/common/tracing/typedvalue-api/src/main/java/org/kie/kogito/tracing/typedvalue/CollectionValue.java, addons/common/tracing/typedvalue-api/src/main/java/org/kie/kogito/tracing/typedvalue/StructureValue.java, addons/common/tracing/typedvalue-api/src/main/java/org/kie/kogito/tracing/typedvalue/TypedValue.java, addons/common/tracing/typedvalue-api/src/main/java/org/kie/kogito/tracing/typedvalue/UnitValue.java, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java
See https://issues.redhat.com/browse/FAI-628
This PR adds a new base class re-used in `kogito-apps` for Counterfactuals.
The changes to `kogito-apps` are [here](https://github.com/kiegroup/kogito-apps/pull/1061).
<details>
<summary>
</summary>
Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] tests</b>
* <b>Run (or …
=> FAI-628: Refactor use of TypedValue/TypedVariable

jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/AbstractCompositeNodeFactory.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ServerlessWorkflowParser.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CallbackHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/EventHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/OperationHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandlerFactory.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/ServerlessWorkflowParsingTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/resources/exec/callback.sw.json
Example in https://github.com/kiegroup/kogito-examples/pull/966
=> [KOGITO-6174] Implementing CallbackState

kogito-bom/pom.xml, kogito-build/kogito-dependencies-bom/pom.xml, kogito-serverless-workflow/kogito-jq-expression/pom.xml, kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqParsedExpression.java, kogito-serverless-workflow/kogito-jq-expression/src/test/java/org/kie/kogito/expr/jq/JqExpressionHandlerTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/suppliers/InjectActionSupplier.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/pom.xml, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/JsonNodeResolver.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/InjectAction.java, kogito-workitems/kogito-jackson-utils/pom.xml, kogito-workitems/kogito-jackson-utils/src/main/java/org/kie/kogito/jackson/utils/MergeUtils.java, kogito-workitems/kogito-jackson-utils/src/main/java/org/kie/kogito/jackson/utils/ObjectMapperFactory.java, kogito-workitems/kogito-openapi-workitem/pom.xml, kogito-workitems/kogito-openapi-workitem/src/main/java/org/kogito/workitem/openapi/JsonNodeResultHandler.java, kogito-workitems/pom.xml, quarkus/bom/pom.xml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/pom.xml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/pom.xml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/src/main/java/org/kie/kogito/expr/jq/JqQuarkusExtension.java
Example in https://github.com/kiegroup/kogito-examples/pull/969
=> [KOGITO-6195] Adding JQ Expression native support

.github/ci-prerequisites.sh, .github/workflows/quarkus-snapshot.yaml
<details>
<summary>
</summary> …
=> Fix Quarkus ecosystem

api/kogito-api/src/main/java/org/kie/kogito/rules/RuleUnitInstance.java, drools/kogito-ruleunits/src/main/java/org/kie/kogito/rules/units/EventListDataStream.java, drools/kogito-ruleunits/src/main/java/org/kie/kogito/rules/units/KieSessionBasedRuleUnitInstance.java, drools/kogito-ruleunits/src/main/java/org/kie/kogito/rules/units/ReteEvaluatorBasedRuleUnitInstance.java, kogito-codegen-modules/kogito-codegen-integration-tests/src/test/java/org/kie/kogito/codegen/RuleUnitCompilerIT.java, kogito-codegen-modules/kogito-codegen-integration-tests/src/test/java/org/kie/kogito/codegen/data/StockTick.java, kogito-codegen-modules/kogito-codegen-integration-tests/src/test/java/org/kie/kogito/codegen/data/ValueDrop.java, kogito-codegen-modules/kogito-codegen-integration-tests/src/test/java/org/kie/kogito/codegen/unit/StockUnit.java, kogito-codegen-modules/kogito-codegen-integration-tests/src/test/resources/org/kie/kogito/codegen/unit/Stock.drl
<details>
<summary>
</summary> …
=> [KOGITO-6080] cep on kogito

jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/validation/RuleFlowProcessValidator.java, kogito-build/kogito-dependencies-bom/pom.xml, kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionRestResourceGenerator.java, kogito-codegen-modules/kogito-codegen-predictions/src/test/java/org/kie/kogito/codegen/prediction/PredictionContainerGeneratorTest.java, kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/ProjectRuntimeGenerator.java, kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/QueryEndpointGenerator.java
<details>
<summary>
</summary> …
=> [DROOLS-6693] upgrade to JavaParser 3.23.1

integration-tests/integration-tests-quarkus-gradle/integration-tests-quarkus-gradle-project/build.gradle, kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegen.java, kogito-codegen-modules/kogito-codegen-rules/src/test/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegenTest.java, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoQuarkusResourceUtils.java, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/MissingRestCapabilityException.java, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/test/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessorTest.java
https://issues.redhat.com/browse/KOGITO-6236
PRs
- https://github.com/kiegroup/kogito-runtimes/pull/1703
- https://github.com/kiegroup/optaplanner/pull/1662
- https://github.com/kiegroup/kogito-examples/pull/976
<details>
<summary>
</summary> …
=> [KOGITO-6236] Compilation error if quarkus-resteasy is present but quarkus-resteasy-jackson is not

.github/workflows/kogito-apps-pr.yml, .github/workflows/kogito-examples-pr.yml, .github/workflows/kogito-runtimes-pr.yml, .github/workflows/optaplanner-pr.yml
Reverts kiegroup/kogito-runtimes#1692
=> Revert "BXMSPROD-1540 composite actions centralized github actions"

integration-tests/integration-tests-quarkus-processes/pom.xml, quarkus/extensions/kogito-quarkus-extension/kogito-quarkus-integration-test-maven-devmode/src/test/resources/projects/classic-inst/src/main/resources/application.properties, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/pom.xml, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/KogitoBuildTimeConfig.java, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/KogitoDevServicesBuildTimeConfig.java, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/KogitoDevServicesProcessor.java, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/ProcessesAssetsProcessor.java, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/devservices/DataIndexInMemoryContainer.java, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/resources/dev-templates/dataindex.html, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/resources/dev-templates/embedded.html, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-integration-test-hot-reload/src/test/resources/application.properties, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes/pom.xml, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes/src/main/java/org/kie/kogito/quarkus/processes/devservices/DataIndexEventPublisher.java, quarkus/test/src/main/java/org/kie/kogito/testcontainers/quarkus/KafkaQuarkusTestResource.java
Cherry-pick https://github.com/kiegroup/kogito-runtimes/pull/1689
=> [1.14.x] KOGITO-5508 Data Index Dev Service

drools/drools-core/src/main/java/org/drools/core/kogito/factory/KogitoFactHandleFactory.java
**JIRA**: https://issues.redhat.com/browse/DROOLS-6610
https://github.com/kiegroup/drools/pull/4030
https://github.com/kiegroup/kogito-runtimes/pull/1730
=> [DROOLS-6610] remove duplications in FactHandle factories

integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/GatewayFEELIT.java, quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test/src/test/java/org/kie/kogito/quarkus/dmn/KogitoDMNCodeCodestartIT.java
<details>
<summary>
</summary> …
=> [1.14.x] Disable failing tests for release

kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ParserContext.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ServerlessWorkflowParser.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CallbackHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/DelayHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/EventHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/InjectHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/OperationHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/ParallelHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandlerFactory.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/SubflowHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/SwitchHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/suppliers/CompensationActionSupplier.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/ServerlessWorkflowParsingTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/resources/exec/compensation.end.sw.json, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/resources/exec/compensation.sw.json
Example in https://github.com/kiegroup/kogito-examples/pull/989
=> [KOGITO-6207] Handling compensation for serverless workflow

kogito-serverless-workflow/README.md
<details>
<summary>
</summary> …
=> [KOGITO-6303] Document Kogito SW implementation

integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-infinispan/src/test/resources/application.properties, kogito-build/kogito-dependencies-bom/pom.xml, kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoInfinispanContainer.java, kogito-test-utils/src/main/resources/testcontainers/infinispan/infinispan-local.xml
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/1751
- https://github.com/kiegroup/kogito-apps/pull/1133
- https://github.com/kiegroup/kogito-examples/pull/998
- https://github.com/kiegroup/kie-docs/pull/4041
=> KOGITO-6310 Upgrade Infinispan to version 13

integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-infinispan/src/test/resources/application.properties, kogito-build/kogito-dependencies-bom/pom.xml, kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoInfinispanContainer.java, kogito-test-utils/src/main/resources/testcontainers/infinispan/infinispan-local.xml
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/1748
- https://github.com/kiegroup/kogito-apps/pull/1131
- https://github.com/kiegroup/kogito-examples/pull/995
=> [1.14.x] KOGITO-6310 Upgrade Infinispan to version 13

quarkus/test/src/main/java/org/kie/kogito/test/quarkus/kafka/KafkaTestClient.java, springboot/test/src/main/java/org/kie/kogito/test/springboot/kafka/KafkaTestClient.java
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/1743
- https://github.com/kiegroup/kogito-examples/pull/994
=> KOGITO-6130 Create Kafka test consumer and producer on demand

kogito-serverless-workflow/README.md
Small improvements in the SW doc.
=> Improvement in the SW current state doc

CONTRIBUTING.md, addons/common/process-management/README.md, addons/common/task-management/README.md, api/kogito-api/src/test/java/org/kie/kogito/process/workitem/PoliciesTest.java
<details>
<summary>
</summary> …
=> [1.11.x] BAPL-1990 conscious language

CONTRIBUTING.md, addons/common/process-management/README.md, addons/common/task-management/README.md, api/kogito-api/src/test/java/org/kie/kogito/process/workitem/PoliciesTest.java
<details>
<summary>
</summary> …
=> BAPL-1990 conscious language

drools/drools-core/src/main/java/org/drools/core/spi/KogitoProcessContextImpl.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ReflectionUtils.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/descriptors/ServiceTaskDescriptor.java, jbpm/jbpm-flow-builder/src/test/java/org/jbpm/compiler/canonical/ReflectionUtilsTest.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/ReturnValueConstraintEvaluator.java, jbpm/jbpm-flow/src/main/java/org/jbpm/util/ContextFactory.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/NodeInstanceImpl.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/ActionNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/DynamicNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/ForEachNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/LambdaSubProcessNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/MilestoneNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/RuleSetNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/WorkItemNodeInstance.java
See callback example modified at https://github.com/kiegroup/kogito-examples/pull/1012
=> [KOGITO-6332] Adding context to service method

kogito-codegen-modules/kogito-codegen-integration-tests/src/test/resources/serverless/multiple-operations.sw.json, kogito-codegen-modules/kogito-codegen-integration-tests/src/test/resources/serverless/multiple-operations.sw.yml, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/json/JsonUtils.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CallbackHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/DelayHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/EventHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/ForEachStateHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/InjectHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/MakeNodeResult.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/OperationHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/ParallelHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/SubflowHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/SwitchHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/suppliers/ExpressionActionSupplier.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/resources/exec/multiple-operations.sw.json, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/resources/exec/multiple-operations.sw.yml, kogito-workitems/kogito-jackson-utils/src/main/java/org/kie/kogito/jackson/utils/MergeUtils.java
Adding state filtering support
See modified example here https://github.com/kiegroup/kogito-examples/pull/1017
=> [KOGITO-3917] Adding state filtering

.ci/jenkins/Jenkinsfile.quarkus
<details>
<summary>
</summary> …
=> Corrected Jenkinsfile.quarkus

.ci/jenkins/Jenkinsfile.native
<details>
<summary>
</summary> …
=> [1.11.x] Increase Jenkins node memory

.ci/jenkins/Jenkinsfile.sonarcloud
<details>
<summary>
</summary> …
=> Corrected Jenkinsfile.sonarcloud

jbpm/process-serialization-protobuf/pom.xml, jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/serialization/process/impl/marshallers/ProtobufJsonNodeMessageMarshaller.java, jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/serialization/process/protobuf/KogitoNodeInstanceContentsProtobuf.java, jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/serialization/process/protobuf/KogitoProcessInstanceProtobuf.java, jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/serialization/process/protobuf/KogitoTypesProtobuf.java, jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/serialization/process/protobuf/KogitoWorkItemsProtobuf.java, jbpm/process-serialization-protobuf/src/main/resources/META-INF/services/org.kie.kogito.serialization.process.ObjectMarshallerStrategy, jbpm/process-serialization-protobuf/src/main/resources/org/kie/kogito/serialization/process/protobuf/kogito_types.proto, jbpm/process-serialization-protobuf/src/test/java/org/kie/kogito/serialization/process/ProcessInstanceMarshallTest.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/persistence/ExclusionTypeUtils.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/persistence/MarshallerGenerator.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/persistence/proto/ReflectionProtoGenerator.java, kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/data/JacksonData.java, kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/process/persistence/proto/AbstractProtoGeneratorTest.java, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/JandexProtoGenerator.java
Jira: https://issues.redhat.com/browse/KOGITO-6346
=> [KOGITO-6346] Setting up MongoDB/PostgreSQL persistence for Serverless workflow errors for generating proto

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.native, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.quarkus, .ci/jenkins/Jenkinsfile.sonarcloud
https://issues.redhat.com/browse/KOGITO-6398
<details>
<summary>
</summary> …
=> KOGITO-6398 Remove Maven Download outputs

integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/GatewayFEELIT.java
`main` branch fwd port of https://github.com/kiegroup/kogito-runtimes/pull/1790
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple …
=> KOGITO-6422 GatewayFEELIT ConnectException: Connection refused 

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/AbstractVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessVisitor.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/DataType.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/type/BooleanDataType.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/type/EnumDataType.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/type/FloatDataType.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/type/IntegerDataType.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/type/ObjectDataType.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/type/StringDataType.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/type/UndefinedDataType.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java, kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandler.java
Codegen was changed to generate ObjectDataType with proper class (which implies changing ObjectDataType). This way reflection is avoid altogether. 
Native integration test on https://github.com/kiegroup/kogito-examples/pull/1036
=> [KOGITO-6430] Fixing native problems in REST WIH

.ci/jenkins/Jenkinsfile.deploy
<details>
<summary>
</summary> …
=> [1.11.x] corrected Jenkinsfile.deploy

api/kogito-api/src/main/java/org/kie/kogito/auth/SecurityPolicy.java, api/kogito-api/src/main/java/org/kie/kogito/process/ProcessService.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/ProcessServiceImpl.java, kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/ReactiveRestResourceQuarkusTemplate.java, kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceQuarkusTemplate.java, kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceSpringTemplate.java, kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceUserTaskQuarkusTemplate.java, kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceUserTaskSpringTemplate.java
- simplify process delegate
- remove methods, update templates
- inline method
- use SecurityPolicy instead of user, groups
=> KOGITO-6324 Simplify Process Service Delegate for REST endpoints

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/descriptors/AbstractServiceTaskDescriptor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/descriptors/OpenApiTaskDescriptor.java, jbpm/jbpm-flow-builder/src/test/java/org/jbpm/compiler/canonical/descriptors/OpenApiTaskDescriptorTest.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/DataTypeResolver.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/ExpressionReturnValueEvaluator.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/node/ForEachNode.java, jbpm/process-workitems/src/main/java/org/kie/kogito/process/workitems/impl/expr/Expression.java, jbpm/process-workitems/src/main/java/org/kie/kogito/process/workitems/impl/expr/ExpressionHandler.java, jbpm/process-workitems/src/main/java/org/kie/kogito/process/workitems/impl/expr/ExpressionHandlerFactory.java, jbpm/process-workitems/src/main/java/org/kie/kogito/process/workitems/impl/expr/ExpressionWorkItemResolver.java, kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqExpression.java, kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqExpressionHandler.java, kogito-serverless-workflow/kogito-jq-expression/src/main/resources/META-INF/services/org.kie.kogito.process.workitems.impl.expr.ExpressionHandler, kogito-serverless-workflow/kogito-jq-expression/src/test/java/org/kie/kogito/expr/jq/JqExpressionHandlerTest.java, kogito-serverless-workflow/kogito-jsonpath-expression/src/main/java/org/kie/kogito/expr/jsonpath/JsonPathExpression.java, kogito-serverless-workflow/kogito-jsonpath-expression/src/main/java/org/kie/kogito/expr/jsonpath/JsonPathExpressionHandler.java, kogito-serverless-workflow/kogito-jsonpath-expression/src/main/resources/META-INF/services/org.kie.kogito.process.workitems.impl.expr.ExpressionHandler, kogito-serverless-workflow/kogito-jsonpath-expression/src/test/java/org/kie/kogito/expr/jsonpath/JsonPathExpressionHandlerTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/JsonNodeResolver.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/ObjectResolver.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/BaseExpressionAction.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/deployment/ServerlessWorkflowAssetsProcessor.java
I also changed ExpressionHandler interface to avoid double compilation when checking if expression is valid
=> [KOGITO-6411] Using serviceloader to load ExpressionHandler

kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqExpression.java, kogito-serverless-workflow/kogito-jsonpath-expression/src/main/java/org/kie/kogito/expr/jsonpath/JsonPathExpression.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/ActionUtils.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/main/java/org/kie/kogito/serverless/workflow/utils/ExpressionHandlerUtils.java, kogito-workitems/kogito-jackson-utils/src/main/java/org/kie/kogito/jackson/utils/JsonObjectUtils.java, kogito-workitems/kogito-jackson-utils/src/test/java/org/kie/kogito/jackson/utils/MergeUtilsTest.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/java/org/kie/kogito/workflows/services/AgePerson.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/java/org/kie/kogito/workflows/services/AgePersonService.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/java/org/kie/kogito/workflows/services/Person.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/java/org/kie/kogito/workflows/services/PersonService.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/pojoService.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/pojoServiceFilter.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/NativePojoServiceIT.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/PojoServiceIT.java
Quick fix for some merging issues than Tiago found 
Thanks a lot Tiago for the help on testing this
=> [KOGITO-6455] Fixing issue when merging custom service

kogito-build/kogito-kie-bom/pom.xml
Related PRs:
https://github.com/kiegroup/drools/pull/4075
https://github.com/kiegroup/kogito-runtimes/pull/1805
https://github.com/kiegroup/optaplanner/pull/1735
=> [DROOLS-6707] move tms in its own module

kogito-build/kogito-dependencies-bom/pom.xml, kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqExpressionHandler.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/src/main/java/org/kie/kogito/expr/jq/JqQuarkusExtension.java
Beans were not being scanned
Modifying example with https://github.com/kiegroup/kogito-examples/pull/1056
=> [KOGITO-6444] Jq native scope was not being injected

jbpm/jbpm-flow/src/main/java/org/kie/kogito/event/impl/CloudEventConsumer.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CallbackHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/EventHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/SwitchHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/ServerlessWorkflowParsingTest.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/main/java/org/kie/kogito/serverless/workflow/utils/ExpressionHandlerUtils.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/pom.xml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/event.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/eventMultiple.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/ConversationFlowIT.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/EventFlowIT.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/PojoServiceIT.java
Removing constrains that prevented using event state as not start state node.
=> [KOGITO-6454] Allowing event state as not start state

kogito-build/README.md
Corrects https://issues.redhat.com/browse/KOGITO-6483.
=> KOGITO-6483 - Corrected broken links in kogito-build/README.md

jbpm/jbpm-flow/pom.xml, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/LightProcessRuntimeContext.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/context/variable/VariableScopeInstance.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcess.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ServerlessWorkflowParser.java, kogito-workitems/kogito-jackson-utils/src/main/java/org/kie/kogito/jackson/utils/JsonNodeConverter.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/helloworld.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/HelloWorldIT.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/NativeEventFlowIT.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/NativeHelloWorldIT.java
Creating defaulf value for workflowvar
=> [KOGITO-6336] Adding default value for workflow war

kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/generator/OpenApiClientGeneratorWrapper.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java
Codegen will continue and print an warn about invalid attributes.
=> KOGITO-6457 Skip validating OpenAPI spec file

kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/GeneratedFileBuilder.java, kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/OpenApiClientCodegen.java, kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/io/AbstractPathResolver.java
Fixes #1825 
See: https://issues.redhat.com/browse/KOGITO-6491
<details>
<summary>
</summary>
[build-chain …
=> [KOGITO-6491] Fix paths handling on Windows for OpenAPI Codegen

integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/main/resources/MultipleInstanceSubProcess.bpmn, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/test/java/org/kie/kogito/it/PersistenceTest.java, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-kafka-persistence/src/test/java/org/kie/kogito/it/KafkaPersistenceIT.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/ForEachNodeInstance.java
<details>
<summary>
</summary> …
=> [KOGITO-5467] fix multiple instance subprocess with user task and persistence enabled

addons/common/jobs/api/pom.xml, addons/common/jobs/api/src/main/java/org/kie/kogito/jobs/api/event/AbstractJobCloudEventBuilder.java, addons/common/jobs/api/src/main/java/org/kie/kogito/jobs/api/event/AbstractProcessInstanceContextJobCloudEventBuilder.java, addons/common/jobs/api/src/main/java/org/kie/kogito/jobs/api/event/CancelJobRequestEvent.java, addons/common/jobs/api/src/main/java/org/kie/kogito/jobs/api/event/CreateProcessInstanceJobRequestEvent.java, addons/common/jobs/api/src/main/java/org/kie/kogito/jobs/api/event/JobCloudEvent.java, addons/common/jobs/api/src/main/java/org/kie/kogito/jobs/api/event/ProcessInstanceContextJobCloudEvent.java, addons/common/jobs/api/src/main/java/org/kie/kogito/jobs/api/event/serialization/DeserializationException.java, addons/common/jobs/api/src/main/java/org/kie/kogito/jobs/api/event/serialization/JobCloudEventDeserializer.java, addons/common/jobs/api/src/main/java/org/kie/kogito/jobs/api/event/serialization/JobCloudEventSerializer.java, addons/common/jobs/api/src/main/java/org/kie/kogito/jobs/api/event/serialization/SerializationException.java, addons/common/jobs/api/src/test/java/org/kie/kogito/jobs/api/event/AbstractJobCloudEventTest.java, addons/common/jobs/api/src/test/java/org/kie/kogito/jobs/api/event/AbstractProcessInstanceContextJobCloudEventTest.java, addons/common/jobs/api/src/test/java/org/kie/kogito/jobs/api/event/CancelJobRequestEventTest.java, addons/common/jobs/api/src/test/java/org/kie/kogito/jobs/api/event/CreateProcessInstanceJobRequestEventTest.java, addons/common/jobs/api/src/test/java/org/kie/kogito/jobs/api/event/serialization/JobCloudEventDeserializerTest.java, addons/common/jobs/api/src/test/java/org/kie/kogito/jobs/api/event/serialization/JobCloudEventSerializerTest.java, addons/common/jobs/api/src/test/java/org/kie/kogito/jobs/api/event/serialization/SerializationTestConstants.java, addons/common/jobs/api/src/test/resources/org/kie/kogito/jobs/api/event/serialization/CancelJobRequestEvent.json, addons/common/jobs/api/src/test/resources/org/kie/kogito/jobs/api/event/serialization/CreateProcessInstanceJobRequestEvent.json, addons/common/jobs/api/src/test/resources/org/kie/kogito/jobs/api/event/serialization/UnexpectedTypeRequestEvent.json
<details>
<summary>
</summary> …
=> KOGITO-5962: Job Service Messaging API for Jobs Scheduling

.github/workflows/kogito-apps-pr.yml, .github/workflows/kogito-examples-pr.yml, .github/workflows/kogito-runtimes-pr.yml, .github/workflows/optaplanner-pr.yml
https://issues.redhat.com/browse/BXMSPROD-1603
Depends on https://github.com/kiegroup/kogito-pipelines/pull/345
Modified version to avoid build errors. See also https://github.com/kiegroup/kogito-runtimes/pull/1729
=> BXMSPROD-1603 Composite actions centralized github actions

kogito-maven-plugin/pom.xml
**JIRA**: https://issues.redhat.com/browse/DROOLS-6765
Related PRs
https://github.com/kiegroup/drools/pull/4109
https://github.com/kiegroup/kogito-runtimes/pull/1845
=> [DROOLS-6765] Update POI from 4.1.2 to 5.1.0
