addons/common/tracing/decision-common/pom.xml, addons/common/tracing/decision-common/src/main/java/org/kie/kogito/tracing/decision/event/EventUtils.java, api/kogito-events-api/pom.xml, api/kogito-events-api/src/main/java/org/kie/kogito/event/cloudevents/utils/CloudEventUtils.java, api/kogito-events-api/src/test/java/org/kie/kogito/event/cloudevents/utils/CloudEventUtilsTest.java, kogito-codegen-modules/kogito-codegen-core/pom.xml, kogito-codegen-modules/kogito-codegen-core/src/main/resources/class-templates/config/GlobalObjectMapperQuarkusTemplate.java, kogito-codegen-modules/kogito-codegen-core/src/main/resources/class-templates/config/GlobalObjectMapperSpringTemplate.java, quarkus/addons/tracing-decision/runtime/src/test/java/org/kie/kogito/tracing/decision/BaseQuarkusDecisionTracingTest.java, quarkus/addons/tracing-decision/runtime/src/test/java/org/kie/kogito/tracing/decision/QuarkusDecisionTracingOneOfEachTypeTest.java, quarkus/addons/tracing-decision/runtime/src/test/java/org/kie/kogito/tracing/decision/QuarkusDecisionTracingTest.java, quarkus/addons/tracing-decision/runtime/src/test/resources/OneOfEachType.dmn, springboot/addons/tracing-decision/src/test/java/org/kie/kogito/tracing/decision/BaseSpringBootDecisionTracingTest.java, springboot/addons/tracing-decision/src/test/java/org/kie/kogito/tracing/decision/SpringBootDecisionTracingOneOfEachTypeTest.java, springboot/addons/tracing-decision/src/test/java/org/kie/kogito/tracing/decision/SpringBootDecisionTracingTest.java, springboot/addons/tracing-decision/src/test/resources/OneOfEachType.dmn
See https://issues.redhat.com/browse/KOGITO-6490
This is an attempt at a more generalised solution following #1762 
This will need refactoring after https://github.com/kiegroup/kogito-runtimes/pull/1828 is merged.
<details>
<summary>
</summary> …
=> KOGITO-6490: kogito-addons-quarkus-tracing-decision: LocalDate* are on available in the ObjectMapper

integration-tests/integration-tests-quarkus-processes/src/main/java/org/kie/kogito/integrationtests/HelloService.java, integration-tests/integration-tests-quarkus-processes/src/main/java/org/kie/kogito/integrationtests/excetpion/ServiceException.java, integration-tests/integration-tests-quarkus-processes/src/main/resources/saga-error-handling.bpmn2, integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/SagaIT.java, integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/TaskIT.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/AbstractNodeVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/AbstractVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/CompositeContextNodeVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessVisitor.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowNodeContainerFactory.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowProcessFactory.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/CompensationEventListener.java
Assembly
https://github.com/kiegroup/kogito-runtimes/pull/1736
https://github.com/kiegroup/kogito-examples/pull/988
<details>
<summary>
</summary>
[build-chain …
=> [KOGITO-3767] Compensations from event sub-processes improvements for Saga

.github/workflows/quarkus-snapshot.yaml
<details>
<summary>
</summary> …
=> Disabled LTS check

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml
- [] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [] Pull Request contains link to the JIRA issue
<details>
<summary>
</summary>
[build-chain …
=> KOGITO-6513 Add Github Issue Templates

.github/ISSUE_TEMPLATE/config.yml
<details>
<summary>
</summary> …
=> Fix ISSUES_TEMPLATES/config.yml typo

kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/SwitchHandler.java
End attribute was not being considered. It has been given priority over
transition.
See modified example at  https://github.com/kiegroup/kogito-examples/pull/1084
=> [KOGITO-6357] Supporting end attribute in OnError

drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/AbstractDecisionModels.java, kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionContainerGenerator.java, quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test/src/main/resources/a.dmn, quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test/src/test/java/org/kie/kogito/quarkus/dmn/DMNIT.java
backport of https://github.com/kiegroup/kogito-runtimes/pull/1700 to `1.11.x` for product-7.12.1.GA
(draft since branch is hold)
https://issues.redhat.com/browse/RHDM-1847
<details>
<summary>
</summary> …
=> [1.11.x] RHDM-1847 KOGITO-6145 DMN codegen heuristic for DMN Editor encoding

drools/kogito-pmml/src/test/java/org/kie/kogito/pmml/PmmlPredictionModelTest.java
@danielezonca
Needed by
kiegroup/drools#4126
<details>
<summary>
</summary> …
=> [DROOLS-5193] Implement required methods

kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java, kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionContainerGenerator.java, kogito-codegen-modules/kogito-codegen-decisions/src/test/java/org/kie/kogito/codegen/decision/DecisionCodegenTest.java, quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-deployment/src/main/java/org/kie/kogito/quarkus/decisions/deployment/DecisionsAssetsProcessor.java
https://issues.redhat.com/browse/KOGITO-6574
https://kie.zulipchat.com/#narrow/stream/236603-kogito-ci/topic/.5Bmain.5D.20Kogito.20Runtimes/near/268246799
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally …
=> KOGITO-6574 DMN nativeimage NoSuchMethodException: <stronglytype>.init()

integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/main/java/org/kie/kogito/HelloService.java, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/main/resources/HelloActivity.bpmn, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/main/resources/MultipleInstanceEmbeddedSubProcess.bpmn, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/main/resources/MultipleInstanceSubProcess.bpmn, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/test/java/org/kie/kogito/it/PersistenceTest.java, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-kafka-persistence/src/test/java/org/kie/kogito/it/KafkaPersistenceIT.java, jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/AbstractNodeHandler.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/impl/DataDefinition.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/impl/IOSpecification.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/LambdaSubProcessNodeInstance.java
Jira; https://issues.redhat.com/browse/KOGITO-6546
=> KOGITO-6546 Review IOSpecification

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/AbstractVisitor.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/DataType.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/DataTypeResolver.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/DataTypeUtils.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/type/ObjectDataType.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/util/TypeTransformer.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/validation/RuleFlowProcessValidator.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/impl/DefaultAssignmentProducer.java, kogito-workitems/kogito-jackson-utils/src/main/java/org/kie/kogito/jackson/utils/JsonObjectUtils.java, kogito-workitems/kogito-jackson-utils/src/test/java/org/kie/kogito/jackson/utils/JsonNodeConverterTest.java, kogito-workitems/kogito-jackson-utils/src/test/java/org/kie/kogito/jackson/utils/JsonObjectUtilsTest.java, kogito-workitems/kogito-jackson-utils/src/test/java/org/kie/kogito/jackson/utils/Person.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/deployment/ServerlessWorkflowAssetsProcessor.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/java/org/kie/kogito/workflows/services/AgePerson.java
cherry-pick: https://github.com/kiegroup/kogito-runtimes/pull/1884
<details>
<summary>
</summary> …
=> [1.16.x] [KOGITO-6561] Fix native compilation issue for json node (#1884)

integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/main/java/org/kie/kogito/HelloService.java, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/main/resources/HelloActivity.bpmn, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/main/resources/MultipleInstanceEmbeddedSubProcess.bpmn, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/main/resources/MultipleInstanceSubProcess.bpmn, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/test/java/org/kie/kogito/it/PersistenceTest.java, integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-kafka-persistence/src/test/java/org/kie/kogito/it/KafkaPersistenceIT.java, jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/AbstractNodeHandler.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/impl/DataDefinition.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/impl/IOSpecification.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/LambdaSubProcessNodeInstance.java
=> [1.16.x] KOGITO-6546 Review IOSpecification (#1885)

.ci/jenkins/dsl/jobs.groovy
Upstream PR:
https://github.com/kiegroup/kogito-pipelines/pull/351
Downstream PRs:
https://github.com/kiegroup/optaplanner/pull/1800
=> PLANNER-2641 OptaPlanner depends on Drools, not Kogito

jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/TaskHandler.java, jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ActivityTest.java, jbpm/jbpm-bpmn2/src/test/resources/subprocess/BPMN2-MainGroupAssignment.bpmn2, jbpm/jbpm-bpmn2/src/test/resources/subprocess/BPMN2-SubprocessGroupAssignment.bpmn2, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/WorkItemNodeInstance.java
Jira: https://issues.redhat.com/browse/KOGITO-6611
=> [KOGITO-6611] Broken dynamic group assignment for User tasks

jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/TaskHandler.java, jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ActivityTest.java, jbpm/jbpm-bpmn2/src/test/resources/subprocess/BPMN2-MainGroupAssignment.bpmn2, jbpm/jbpm-bpmn2/src/test/resources/subprocess/BPMN2-SubprocessGroupAssignment.bpmn2, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/WorkItemNodeInstance.java
Jira: https://issues.redhat.com/browse/KOGITO-6611
cherry-pick https://github.com/kiegroup/kogito-runtimes/commit/5ba2a50f9efd1767bff54c1e780974917e40da11
=> [1.16.x] [KOGITO-6611] Broken dynamic group assignment for User tasks

kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/ServerlessWorkflowCodegenUtils.java, kogito-serverless-workflow/README.md, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/ActionType.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java
See examples at https://github.com/kiegroup/kogito-examples/pull/1104
=> [KOGITO-6654] Adding custom format support

quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java
cherry-pick: https://github.com/kiegroup/kogito-runtimes/pull/1946
<details>
<summary>
</summary> …
=> [1.16.x] KOGITO-6656 Kogito "incubation" API DMN test failing in native mode

integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/main/java/org/kie/kogito/SerializationConfig.java
Jira: https://issues.redhat.com/browse/KOGITO-6641
=> [KOGITO-6641] Native persistence is failing with java.util.ArrayList no valid constructor

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.native, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.quarkus, .ci/jenkins/Jenkinsfile.sonarcloud
<details>
<summary>
</summary> …
=> [1.16.x] Update Jenkins CI to 3.8.1

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.native, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.quarkus, .ci/jenkins/Jenkinsfile.sonarcloud, README.md
https://issues.redhat.com/browse/KOGITO-5531
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/214
- https://github.com/kiegroup/kogito-runtimes/pull/1446
- https://github.com/kiegroup/optaplanner/pull/1815
- https://github.com/kiegroup/kogito-apps/pull/942
- https://github.com/kiegroup/kogito-examples/pull/797
=> KOGITO-5531 Update Jenkins CI to Maven 3.8.1

.ci/jenkins/Jenkinsfile, .ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.drools, .ci/jenkins/Jenkinsfile.native, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.quarkus, .ci/jenkins/Jenkinsfile.sonarcloud, README.md
https://issues.redhat.com/browse/KOGITO-5531
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/1961
- https://github.com/kiegroup/optaplanner/pull/1819
- https://github.com/kiegroup/kogito-apps/pull/1223
- https://github.com/kiegroup/kogito-examples/pull/1108
- https://github.com/kiegroup/kogito-operator/pull/1124
=> [1.11.x] KOGITO-5531 Update Jenkins CI to Maven 3.8.1 (#1446)

.ci/jenkins/dsl/jobs.groovy, .github/workflows/kogito-apps-pr.yml
https://issues.redhat.com/browse/KOGITO-6686
Related PRs:
- https://github.com/kiegroup/kogito-apps/pull/1222
- https://github.com/kiegroup/kogito-runtimes/pull/1960
- https://github.com/kiegroup/drools/pull/4173
- https://github.com/kiegroup/optaplanner/pull/1818
=> KOGITO-6686 Setup Apps PR check timeout to 210m

.github/workflows/quarkus-snapshot.yaml
<details>
<summary>
</summary> …
=> Enable back quarkus LTS check

.github/workflows/quarkus-snapshot.yaml
<details>
<summary>
</summary> …
=> GHA: Checkout Drools as part of quarkus-snapshot check

quarkus/addons/tracing-decision/deployment/pom.xml, quarkus/addons/tracing-decision/deployment/src/main/resources/application.properties
See https://issues.redhat.com/browse/FAI-711
I also changed the property name to better reflect kiegroup's conventions.
<details>
<summary>
</summary>
[build-chain …
=> FAI-711: tracing-addon: Bump to use kogito-trusty-postgresql 1.16.0 container

kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/io/HTTPResolver.java, kogito-codegen-modules/kogito-codegen-openapi/src/test/java/org/kie/kogito/codegen/openapi/client/OpenApiSpecMockServer.java, kogito-codegen-modules/kogito-codegen-openapi/src/test/java/org/kie/kogito/codegen/openapi/client/io/PathResolverTest.java
See: https://issues.redhat.com/browse/KOGITO-6725
<details>
<summary>
</summary>
[build-chain …
=> [KOGITO-6725] Fix OpenAPI HTTP Resolver Accept Headers

jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/serialization/process/protobuf/ProtostreamProtobufAdapterTypeProvider.java, jbpm/process-serialization-protobuf/src/test/java/org/kie/kogito/serialization/process/protobuf/ProtostreamProtobufAdapterTypeProviderTest.java
<details>
<summary>
</summary> …
=> KOGITO-6721: Process core persistence .proto files are not found in Windows

kogito-serverless-workflow/README.md
JIRA: https://issues.redhat.com/browse/KOGITO-6566
<details>
<summary>
</summary> …
=> KOGITO-6566 Updated current status of Serverless Workflow to v0.8

kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/EventHandler.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/eventMultiple.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/EventFlowIT.java
Small one to take into account multiple onEvents (we were currently only considering the first one)
Notice the usage of exclusive: false in integration test
=> [KOGITO-6728] Processing multiple on-events

kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/EventHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/SwitchHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/suppliers/ExpressionActionSupplier.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/ServerlessWorkflowUtils.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/main/java/org/kie/kogito/serverless/workflow/utils/ExpressionHandlerUtils.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/eventMultiple.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/greet.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/GreetRestIT.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/NativeGreetRestIT.java
Replacement of fn:functioncall will be done at build time. Reference to reference are allowed.
=> [KOGITO-6663] Implementing function reference

addons/common/events/mongodb/src/main/java/org/kie/kogito/events/mongodb/MongoDBEventPublisher.java, addons/common/events/mongodb/src/main/java/org/kie/kogito/events/mongodb/codec/CodecUtils.java, addons/common/events/mongodb/src/test/java/org/kie/kogito/events/mongodb/codec/CodecUtilsTest.java, addons/common/events/mongodb/src/test/java/org/kie/kogito/events/mongodb/codec/ProcessInstanceDataEventCodecTest.java, addons/common/events/mongodb/src/test/java/org/kie/kogito/events/mongodb/codec/UserTaskInstanceDataEventCodecTest.java, addons/common/events/mongodb/src/test/java/org/kie/kogito/events/mongodb/codec/VariableInstanceDataEventCodecTest.java, addons/common/messaging/src/test/java/org/kie/kogito/addon/cloudevents/CloudEventConverterTest.java, api/kogito-events-api/src/main/java/org/kie/kogito/event/AbstractDataEvent.java, api/kogito-events-api/src/main/java/org/kie/kogito/event/DataEvent.java, api/kogito-events-api/src/main/java/org/kie/kogito/event/cloudevents/CloudEventMeta.java, api/kogito-events-api/src/main/java/org/kie/kogito/event/cloudevents/SpecVersionDeserializer.java, api/kogito-events-api/src/main/java/org/kie/kogito/event/cloudevents/SpecVersionSerializer.java, api/kogito-events-api/src/main/java/org/kie/kogito/event/cloudevents/utils/CloudEventUtils.java, api/kogito-events-api/src/test/java/org/kie/kogito/event/cloudevents/utils/CloudEventUtilsTest.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/event/impl/CloudEventConsumer.java, jbpm/jbpm-flow/src/test/java/org/kie/kogito/event/impl/EventImplTest.java, kogito-build/kogito-dependencies-bom/pom.xml, kogito-codegen-modules/kogito-codegen-integration-tests/src/test/java/org/kie/kogito/codegen/tests/PublishEventIT.java, quarkus/addons/messaging/common/src/main/java/org/kie/kogito/addon/quarkus/messaging/common/AbstractQuarkusCloudEventReceiver.java
Assembly
https://github.com/kiegroup/kogito-examples/pull/1119
https://github.com/kiegroup/kogito-runtimes/pull/1947
<details>
<summary>
</summary>
[build-chain …
=> KOGITO-6476 making DataEvent to extend Cloud Event Attribues from the SDK

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/AbstractVisitor.java, kogito-codegen-modules/kogito-codegen-integration-tests/src/test/java/org/kie/kogito/codegen/tests/ServiceTaskIT.java, kogito-codegen-modules/kogito-codegen-integration-tests/src/test/resources/servicetask/MultiParamServiceProcess.bpmn2
<details>
<summary>
</summary> …
=> [KOGITO-6769] Removing generic type

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/descriptors/AbstractServiceTaskDescriptor.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/coverter/TypeConverterRegistry.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/expr/Expression.java, kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqExpression.java, kogito-serverless-workflow/kogito-jsonpath-expression/src/main/java/org/kie/kogito/expr/jsonpath/JsonPathExpression.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/pom.xml, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/JsonNodeResolver.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/ObjectResolver.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/test/java/org/kie/kogito/serverless/workflow/JsonNodeJqResolverTest.java, kogito-workitems/kogito-jackson-utils/src/main/java/org/kie/kogito/jackson/utils/JsonObjectUtils.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/fahrenheit-to-celsius.sw.json
Issue was that we were not generating a proper string representation of the json node. 
Besides that, some refactor of duplicated code was done and some tests were refined.
=> [KOGITO-6775] OpenApi only accepts single level arguments

jbpm/jbpm-flow-builder/pom.xml, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ModelMetaData.java, jbpm/jbpm-flow-builder/src/test/java/org/jbpm/compiler/canonical/ProcessToExecModelGeneratorTest.java, kogito-build/kogito-dependencies-bom/pom.xml, kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/context/KogitoBuildContext.java, kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/utils/KogitoCodeGenConstants.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/InputModelClassGenerator.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ModelClassGenerator.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/OutputModelClassGenerator.java, quarkus/bom/pom.xml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/pom.xml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties
See: https://issues.redhat.com/browse/KOGITO-6772
In this PR we add an annotation to allow the Swagger parser to define the `JsonNode` object.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the …
=> [KOGITO-6772] Adding Schema annotation to model when JsonNode

kogito-serverless-workflow/kogito-serverless-workflow-utils/src/main/java/org/kie/kogito/serverless/workflow/utils/ExpressionHandlerUtils.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/main/java/org/kie/kogito/serverless/workflow/utils/KogitoProcessContextResolver.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/test/java/org/kie/kogito/serverless/workflow/utils/KogitoProcessContextResolverTest.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/expression.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/ExpressionRestIT.java
See modified example at https://github.com/kiegroup/kogito-examples/pull/1134
=> [KOGITO-6774] Adding context magic word

drools/kogito-scenario-simulation/src/test/resources/dmnPmml/KiePMMLRegressionTest.scesim, drools/kogito-scenario-simulation/src/test/resources/dmnPmml/KiePMMLTreeTest.scesim, drools/kogito-scenario-simulation/src/test/resources/importedDMN/TrafficViolationTest.scesim, drools/kogito-scenario-simulation/src/test/resources/importedDMNInputsDecisions/Using Imported.scesim, drools/kogito-scenario-simulation/src/test/resources/sampleTest/Violation Scenarios.scesim
Scesim unmarshaller extracts the scesim version from the XML prolog instead of ScenarioSimulationNode
**JIRA**: https://issues.redhat.com/browse/KOGITO-6781
https://github.com/kiegroup/drools/pull/4205
https://github.com/kiegroup/kogito-runtimes/pull/2011
https://github.com/kiegroup/kogito-examples/pull/1128
<details>
<summary>
</summary> …
=> KOGITO-6781: XML Prolog support for .scesim files

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/WorkItemNodeVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/descriptors/AbstractServiceTaskDescriptor.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/pojoServiceFilter.sw.json
<details>
<summary>
</summary> …
=> [KOGITO-6801] Fixing classcast exception when using non string literal

jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/persistence/SerializableProtostreamBaseMarshaller.java, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/ProcessesAssetsProcessor.java
<details>
<summary>
</summary> …
=> KOGITO-6778 adding SpecVersionSerializer for reflection

quarkus/addons/tracing-decision/deployment/pom.xml
See https://issues.redhat.com/browse/FAI-730
<details>
<summary>
</summary> …
=> FAI-730: tracing-addon: Bump to use kogito-trusty-postgresql 1.17.0 container

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/descriptors/AbstractServiceTaskDescriptor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/descriptors/SupplierUtils.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/expr/ExpressionWorkItemResolver.java, kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqExpression.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/JsonNodeResolver.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/ObjectResolver.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/test/java/org/kie/kogito/serverless/workflow/JsonNodeJqResolverTest.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/test/java/org/kie/kogito/serverless/workflow/JsonNodeJsonPathResolverTest.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/main/java/org/kie/kogito/serverless/workflow/utils/ExpressionHandlerUtils.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/main/java/org/kie/kogito/serverless/workflow/utils/KogitoProcessContextResolver.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/test/java/org/kie/kogito/serverless/workflow/utils/KogitoProcessContextResolverTest.java, kogito-workitems/kogito-jackson-utils/src/main/java/org/kie/kogito/jackson/utils/JsonObjectUtils.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/expression.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/fahrenheit-to-celsius.sw.json
See example at https://github.com/kiegroup/kogito-examples/pull/1137
=> [KOGITO-6810] Expression handling changes

kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/io/HttpContentLoader.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/io/ResourceCache.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/io/ResourceCacheFactory.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/test/java/org/kie/kogito/serverless/workflow/io/ResourceCacheFactoryTest.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/pom.xml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/pom.xml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/src/main/java/org/kie/kogito/serverless/workflow/io/QuarkusResourceCache.java
Using Quarkus cache for http retrieval
=> [KOGITO-6750] Implementing http cache

api/kogito-services/src/main/java/org/kie/kogito/services/event/impl/AbstractMessageProducer.java, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-kafka-it/src/main/resources/application.properties, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties, quarkus/test/pom.xml, quarkus/test/src/main/java/org/kie/kogito/test/quarkus/kafka/KafkaConsumerLoop.java, quarkus/test/src/main/java/org/kie/kogito/test/quarkus/kafka/KafkaTestClient.java, springboot/addons/messaging/implementation/src/main/java/org/kie/kogito/addon/cloudevents/spring/SpringKafkaConsumerConfig.java, springboot/addons/messaging/integration-tests/src/it/cloudevents-spring-boot-addon-it-invoked/src/main/resources/application.properties, springboot/test/pom.xml, springboot/test/src/main/java/org/kie/kogito/test/springboot/kafka/KafkaConsumerLoop.java, springboot/test/src/main/java/org/kie/kogito/test/springboot/kafka/KafkaTestClient.java
Assembly:
- https://github.com/kiegroup/kogito-examples/pull/1142
- https://github.com/kiegroup/kogito-runtimes/pull/2041
=> KOGITO-6825 Await message sent callback

.github/workflows/quarkus-snapshot.yaml
=> KOGITO-6843 Increase timeout on Quarkus Ecosystem CI

kogito-build/kogito-build-no-bom-parent/pom.xml, kogito-build/kogito-dependencies-bom/pom.xml
https://issues.redhat.com/browse/FAI-722
This PR should be merge together with https://github.com/kiegroup/kogito-apps/pull/1250
=> FAI-722: Set containers name as property

quarkus/addons/messaging/deployment/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/deployment/ChannelInfo.java, quarkus/addons/messaging/deployment/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/deployment/ChannelMappingStrategy.java, quarkus/addons/messaging/deployment/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/deployment/KogitoAddOnMessagingProcessor.java
See JIRA description and comments
Updated example using functionality https://github.com/kiegroup/kogito-examples/pull/1152
=> [KOGITO-6835] Mapping trigger to channel

addons/common/messaging/src/main/java/org/kie/kogito/addon/cloudevents/converters/ProcessDataJsonNodeConverter.java, api/kogito-services/src/main/java/org/kie/kogito/services/event/ProcessDataEventConverter.java, api/kogito-services/src/main/java/org/kie/kogito/services/event/impl/AbstractMessageConsumer.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/TriggerMetaData.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/Metadata.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/event/impl/CloudEventConsumer.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/event/impl/DefaultEventConsumerFactory.java, jbpm/jbpm-flow/src/test/java/org/kie/kogito/event/impl/EventImplTest.java, kogito-build/kogito-dependencies-bom/pom.xml, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/MessageConsumerGenerator.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ServerlessWorkflowParser.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/CallbackStateServerlessWorkflowParsingTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/resources/exec/callback-state-timeouts.sw.json, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/resources/exec/callback-state-timeouts.sw.yml, quarkus/addons/messaging/common/src/main/java/org/kie/kogito/addon/quarkus/messaging/common/ProcessDataEventConverterProducer.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/eventMultiple.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/CallbackStateTimeoutsIT.java
@tiagodolphine Just letting you know that Im working on that
=> [KOGITO-6680] Implement data only functionality

quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java
<details>
<summary>
</summary> …
=> KOGITO-6829 Fix native build failing for kogito-examples missing classes for reflection

.ci/jenkins/dsl/jobs.groovy
- https://github.com/kiegroup/kogito-pipelines/pull/397
- https://github.com/kiegroup/kogito-runtimes/pull/2062
- https://github.com/kiegroup/optaplanner/pull/1866
- https://github.com/kiegroup/optaplanner-quickstarts/pull/300
- https://github.com/kiegroup/kogito-examples/pull/1160
- https://github.com/kiegroup/kogito-images/pull/1155
=> [1.13.x] Remove native checks

kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqExpressionHandler.java, kogito-serverless-workflow/kogito-jsonpath-expression/src/main/java/org/kie/kogito/expr/jsonpath/JsonPathExpression.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/suppliers/ProduceEventActionSupplier.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/BuildExpressionsTest.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/JsonNodeResolver.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/test/java/org/kie/kogito/serverless/workflow/RuntimeExpressionsTest.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/main/java/org/kie/kogito/serverless/workflow/utils/CachedExpressionHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/main/java/org/kie/kogito/serverless/workflow/utils/ExpressionHandlerUtils.java, kogito-workitems/kogito-jackson-utils/src/main/java/org/kie/kogito/jackson/utils/JsonNodeVisitor.java, kogito-workitems/kogito-jackson-utils/src/test/java/org/kie/kogito/jackson/utils/JsonNodeVisitorTest.java
Most cases were already working. 
I added some test to ensure this is the case
I'm also ensuring function references are replaced when used in function arguments.
=> [KOGITO-6802] Ensure magic words are replaced

addons/common/persistence/filesystem/src/test/java/org/kie/persistence/filesystem/FileSystemProcessInstancesTest.java, addons/common/persistence/infinispan/src/test/java/org/kie/kogito/infinispan/CacheProcessInstancesIT.java, addons/common/persistence/infinispan/src/test/java/org/kie/kogito/infinispan/MockCacheProcessInstancesTest.java, addons/common/persistence/mongodb/src/test/java/org/kie/kogito/mongodb/MongoDBProcessInstancesIT.java, addons/common/process-management/src/main/java/org/kie/kogito/process/management/BaseProcessInstanceManagementResource.java, addons/common/process-management/src/test/java/org/kie/kogito/process/management/BaseProcessInstanceManagementResourceTest.java, jbpm/jbpm-bpmn2/src/main/java/org/kie/kogito/process/bpmn2/BpmnProcess.java, jbpm/jbpm-bpmn2/src/main/java/org/kie/kogito/process/bpmn2/BpmnProcessCompiler.java, jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/canonical/ActivityGenerationModelTest.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcess.java, jbpm/process-serialization-protobuf/src/main/java/org/kie/kogito/serialization/process/impl/ProtobufProcessInstanceReader.java, kogito-codegen-modules/kogito-codegen-integration-tests/src/test/java/org/kie/kogito/codegen/process/ProcessGenerationIT.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java, quarkus/addons/process-management/runtime/src/test/java/org/kie/kogito/process/management/ProcessInstanceManagementResourceTest.java
Use get() lazy singleton call instead
=> [KOGITO-5866] Make process() method protected

addons/common/human-task-prediction/api/pom.xml, addons/common/monitoring/core/pom.xml, addons/common/monitoring/core/src/main/java/org/kie/kogito/monitoring/core/common/process/MetricsProcessEventListener.java, addons/common/monitoring/core/src/test/java/org/kie/kogito/monitoring/core/common/process/MetricsProcessEventListenerTest.java, addons/common/persistence/filesystem/pom.xml, addons/common/persistence/infinispan/pom.xml, addons/common/persistence/jdbc/pom.xml, addons/common/persistence/mongodb/pom.xml, addons/common/persistence/postgresql/pom.xml, api/kogito-api/src/main/java/org/kie/kogito/internal/process/runtime/KogitoWorkItemNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/WorkItemNodeInstance.java, kogito-maven-plugin/pom.xml, quarkus/addons/persistence/kafka/runtime/pom.xml
Backport of https://github.com/kiegroup/kogito-runtimes/pull/2063
=> [1.13.x] KOGITO-6805 Remove dependencies to jbpm-flow

integration-tests/integration-tests-quarkus-processes/src/main/resources/application.properties, integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-kafka-it/src/main/resources/application.properties, kogito-build/kogito-build-no-bom-parent/pom.xml, kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/Constants.java, kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoKafkaContainer.java, kogito-test-utils/src/test/java/org/kie/kogito/testcontainers/KogitoKafkaContainerTest.java, quarkus/addons/messaging/integration-tests/src/main/resources/application.properties, quarkus/test/pom.xml, quarkus/test/src/main/java/org/kie/kogito/test/quarkus/kafka/KafkaConsumerLoop.java, quarkus/test/src/main/java/org/kie/kogito/test/quarkus/kafka/KafkaTestClient.java, quarkus/test/src/test/java/org/kie/kogito/testcontainers/quarkus/KafkaQuarkusTestResourceTest.java, springboot/addons/messaging/implementation/src/main/java/org/kie/kogito/addon/cloudevents/spring/SpringKafkaConsumerConfig.java, springboot/addons/messaging/integration-tests/src/it/cloudevents-spring-boot-addon-it-invoked/src/main/resources/application.properties, springboot/test/pom.xml, springboot/test/src/main/java/org/kie/kogito/test/springboot/kafka/KafkaConsumerLoop.java, springboot/test/src/main/java/org/kie/kogito/test/springboot/kafka/KafkaTestClient.java, springboot/test/src/test/java/org/kie/kogito/testcontainers/springboot/KafkaSpringBootTestResourceTest.java
Assembly:
- https://github.com/kiegroup/kogito-examples/pull/1169
- https://github.com/kiegroup/kogito-runtimes/pull/2072
=> [1.13.x] KOGITO-6825 Review messaging IT test to avoid random failures

kogito-build/kogito-dependencies-bom/pom.xml
JIRA: https://issues.redhat.com/browse/KOGITO-6855
---------
<details>
<summary>
</summary> …
=> KOGITO-6855 Updated quarkus-reactive-messaging-http to 1.0.3

api/kogito-events-api/src/main/java/org/kie/kogito/event/AbstractDataEvent.java, quarkus/addons/messaging/common/src/main/java/org/kie/kogito/addon/quarkus/messaging/common/message/CloudEventHttpOutgoingDecorator.java, quarkus/addons/messaging/common/src/test/java/org/kie/kogito/addon/quarkus/messaging/common/message/CloudEventHttpOutgoingDecoratorTest.java, quarkus/addons/messaging/common/src/test/resources/application.properties
Signed-off-by: Helber Belmiro <helber.belmiro@gmail.com>
cherry-pick: https://github.com/kiegroup/kogito-runtimes/pull/2071
<details>
<summary>
</summary>
[build-chain …
=> [1.19.x] KOGITO-6849 Fixed CloudEvent lacking of "Content-Type" header (#2071)

jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/expr/Expression.java, kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqExpression.java, kogito-serverless-workflow/kogito-jsonpath-expression/src/main/java/org/kie/kogito/expr/jsonpath/JsonPathExpression.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/SWFProduceEventAction.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/workitemparams/JsonNodeResolver.java
examples updated here https://github.com/kiegroup/kogito-examples/pull/1189
=> [KOGITO-6906] Removing needs for quotes on WORKFLOW replacement

quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/ProcessesAssetsProcessor.java
<details>
<summary>
</summary> …
=> [KOGITO-6921]process-rest-workitem-multi-quarkus failing on native build

jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/Metadata.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ServerlessWorkflowParser.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/ServerlessWorkflowUtils.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/DataInputSchemaAction.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/io/ClassPathContentLoader.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/io/FallbackContentLoader.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/io/FileContentLoader.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/io/HttpContentLoader.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/io/URIContentLoader.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/io/URIContentLoaderFactory.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/test/java/org/kie/kogito/serverless/workflow/io/URIContentLoaderTest.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/main/java/org/kie/kogito/serverless/workflow/utils/ExpressionHandlerUtils.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/test/java/org/kie/kogito/serverless/workflow/utils/ExpressionHandlerUtilsTest.java, kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/auth/AuthDecorator.java, kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/auth/OAuth2AuthDecorator.java, kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/auth/PasswordOAuth2AuthDecorator.java
TODOs will be updated when we change version of the sdk
=> [KOGITO-6549] Adding auth suppport for httpcontentloader

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/SplitNodeVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/descriptors/ExpressionReturnValueSupplier.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/SwitchHandler.java
<details>
<summary>
</summary> …
=> [KOGITO-6924] Avoid code generation for constraints

kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java
Swiching arguments processing order so now functionArgs take precedence over auth properties
=> [KOGITO-6926] Using functionArgs as Auth info

quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/ProcessesAssetsProcessor.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/AbstractCallbackStateIT.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/SwitchStateEventConditionBasedIT.java
- Integration tests fixes
- Relates to KOGITO-6886
<details>
<summary>
</summary> …
=> KOGITO-6740: [SW] Implement Switch state eventTimeouts

kogito-build/kogito-kie-bom/pom.xml
- https://github.com/kiegroup/drools/pull/4286
- https://github.com/kiegroup/optaplanner/pull/1907
- https://github.com/kiegroup/optaplanner-quickstarts/pull/316
- https://github.com/kiegroup/optaweb-employee-rostering/pull/784
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/674
- https://github.com/kiegroup/kogito-apps/pull/1291
- https://github.com/kiegroup/kogito-examples/pull/1205
- https://github.com/kiegroup/kogito-runtimes/pull/2121
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and …
=> bumped up org.kie to next 8.20.0-SNAPSHOT

kogito-build/kogito-build-no-bom-parent/pom.xml, kogito-build/kogito-dependencies-bom/pom.xml, kogito-test-utils/pom.xml, kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoGenericContainer.java, kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoMongoDBContainer.java, kogito-test-utils/src/main/resources/testcontainers.properties, kogito-test-utils/src/test/java/org/kie/kogito/testcontainers/KogitoMongoDBContainerTest.java, quarkus/test/src/test/java/org/kie/kogito/testcontainers/quarkus/MongoDBQuarkusTestResourceTest.java, springboot/test/src/test/java/org/kie/kogito/testcontainers/springboot/MongoDBSpringBootTestResourceTest.java
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/2113
- https://github.com/kiegroup/kogito-apps/pull/1286
=> KOGITO-6922 - Use default image name/version from properties file

jbpm/jbpm-bpmn2/pom.xml, jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/objects/Person.java, jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/structureref/StructureRefTest.java, jbpm/jbpm-flow-builder/pom.xml, kogito-build/kogito-dependencies-bom/pom.xml
Replacement for https://github.com/kiegroup/kogito-runtimes/pull/1959
=> KOGITO-6936 - Drop Xstream

kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ServerlessWorkflowParser.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/validation/WorkflowValidator.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/ServerlessWorkflowUtils.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/main/java/org/kie/kogito/serverless/workflow/utils/ExpressionHandlerUtils.java
Although the SDK always return null for constant.getRefValue, this code can be merged, so the parser is ready when the sdk is fixed
=> [KOGITO-6945] Suppor for constants.getRefValue

.ci/jenkins/tests/pom.xml
<details>
This is a fix by upgrading Guava in CI tests for https://github.com/kiegroup/kogito-runtimes/security/dependabot/25
<summary>
</summary>
[build-chain …
=> Upgrading guava to 24.1.1 in CI testsuite

quarkus/addons/jobs/messaging/deployment/pom.xml, quarkus/addons/jobs/messaging/deployment/src/main/java/org/kie/kogito/jobs/messaging/quarkus/deployment/KogitoAddOnJobsMessagingProcessor.java, quarkus/addons/jobs/messaging/runtime/pom.xml
- native image generation addings
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or …
=> KOGITO-5963: [SW] Jobs Addon based in Messaging / Kafka

api/kogito-services/src/main/java/org/kie/kogito/services/event/impl/ProcessInstanceEventBatch.java, kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/java/org/kie/kogito/codegen/tests/PublishEventIT.java
Merge with https://github.com/kiegroup/kogito-examples/pull/1229
=> [KOGITO-6999] Publishing variable events

quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoQuarkusResourceUtils.java
Protobuf files are needed, so changing default value of the property to false
=> [KOGITO-6989] Enabling dump files by default

quarkus/addons/explainability/runtime/src/main/resources/META-INF/quarkus-extension.yaml
[KOGITO-6352](https://issues.redhat.com/browse/KOGITO-6352)
This one was still left uncategorized and with a wrong description.
<details>
<summary>
</summary> …
=> KOGITO-6352 - Uncategorized extensions on Quarkus Platform

quarkus/addons/explainability/runtime/src/main/resources/META-INF/quarkus-extension.yaml
Backport of #2171 
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with …
=> [1.21.x] KOGITO-6352 - Uncategorized extensions on Quarkus Platform

.ci/jenkins/Jenkinsfile.quarkus
to include drools check
+ corrected examples check
=> Updated quarkus check

kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/pathresolvers/DefaultPathParamResolver.java, kogito-workitems/kogito-rest-workitem/src/test/java/org/kogito/workitem/rest/pathresolvers/DefaultPathParamResolverTest.java
sometimes loss parm render
<details>
<summary>
</summary> …
=> [KOGITO-7054]fix: rest api DefaultPathParamResolver render wrong

kogito-serverless-workflow/kogito-jq-expression/src/test/java/org/kie/kogito/expr/jq/JqExpressionHandlerTest.java
Jira: [KOGITO-7061](https://issues.redhat.com/browse/KOGITO-7061)
Increasing test coverage for kogito-jq-expression module. Coverage metrics to be reported once PR check succeeds.
<details>
<summary>
</summary> …
=> KOGITO-7061 increase unit test coverage in kogito-jq-expression

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.promote
https://issues.redhat.com/browse/KOGITO-7100
Related PRs:
- https://github.com/kiegroup/drools/pull/4355
- https://github.com/kiegroup/optaplanner/pull/1966
- https://github.com/kiegroup/kogito-runtimes/pull/2187
- https://github.com/kiegroup/kogito-apps/pull/1330
- https://github.com/kiegroup/kogito-examples/pull/1244
- https://github.com/kiegroup/kogito-images/pull/1251
- https://github.com/kiegroup/kogito-operator/pull/1183
=> [KOGITO-7100] Jenkinsfiles: Corrected boolean env var handling

kogito-build/kogito-dependencies-bom/pom.xml, quarkus/test/src/main/java/org/kie/kogito/test/quarkus/QuarkusTestProperty.java, quarkus/test/src/main/java/org/kie/kogito/test/resources/ConditionalQuarkusTestResource.java, quarkus/test/src/test/java/org/kie/kogito/test/resources/ConditionalQuarkusTestResourceTest.java
cherry-pick: https://github.com/kiegroup/kogito-runtimes/pull/2178
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/437
- https://github.com/kiegroup/drools/pull/4357
- https://github.com/kiegroup/kogito-runtimes/pull/2188
- https://github.com/kiegroup/optaplanner/pull/1967
- https://github.com/kiegroup/optaplanner-quickstarts/pull/330
- https://github.com/kiegroup/kogito-apps/pull/1331
- https://github.com/kiegroup/kogito-examples/pull/1245
=> [1.21.x] Bump Quarkus version to 2.9.0.Final

.ci/jenkins/Jenkinsfile.quarkus
<details>
<summary>
</summary> …
=> Correct kogito-apps checks with quarkus

kogito-build/kogito-dependencies-bom/pom.xml, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/OpenAPIOperationId.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/openapi/WorkflowOpenApiHandlerGenerator.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/openapi/WorkflowOpenApiSpecInputProvider.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/src/main/java/io/quarkus/restclient/runtime/RestClientBuilderFactory.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/src/main/java/org/kie/kogito/serverless/workflow/openapi/OpenApiWorkItemHandler.java
This fixes:
- Issue when using non pojo body
- Generating default api in separated packages
- Filling up headers with kogito metadata
Examples updated with https://github.com/kiegroup/kogito-examples/pull/1246
=> [KOGITO-7081] Fixing issues related with quarkiverse integration

kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandler.java
See rationale at JIRA https://issues.redhat.com/browse/KOGITO-7112
=> [KOGITO-7112] RestWorkItemHandler default port changed to 80

kogito-serverless-workflow/kogito-jq-expression/src/test/java/org/kie/kogito/expr/jq/JqExpressionHandlerTest.java, kogito-serverless-workflow/kogito-jsonpath-expression/src/test/java/org/kie/kogito/expr/jsonpath/JsonPathExpressionHandlerTest.java
JIRA: [KOGITO-7061](https://issues.redhat.com/browse/KOGITO-7061)
<details>
<summary>
</summary> …
=> KOGITO-7061 - Increase test coverage in kogito-jq-expression - follow-up

quarkus/addons/messaging/common/src/main/java/org/kie/kogito/addon/quarkus/messaging/common/message/CloudEventHttpOutgoingDecorator.java
Quick fix, the default value of the variable is true, so we need to disable only if the variable is false.
=> Quick fix for cloud event decorator

.ci/jenkins/Jenkinsfile.native, .ci/jenkins/dsl/jobs.groovy, .github/workflows/quarkus-snapshot.yaml
https://issues.redhat.com/browse/KOGITO-7110
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/438
- https://github.com/kiegroup/drools/pull/4364
- https://github.com/kiegroup/kogito-runtimes/pull/2192
- https://github.com/kiegroup/kogito-apps/pull/1332
- https://github.com/kiegroup/kogito-examples/pull/1247
- https://github.com/kiegroup/kogito-images/pull/1252
- https://github.com/kiegroup/kogito-operator/pull/1184
- https://github.com/kiegroup/optaplanner/pull/1969
=> KOGITO-7110 Correct nightly DSL generation

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/AbstractVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/descriptors/ExpressionUtils.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/Metadata.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/expr/Expression.java, kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/FunctionJsonNode.java, kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqExpression.java, kogito-serverless-workflow/kogito-jq-expression/src/test/java/org/kie/kogito/expr/jq/JqExpressionHandlerTest.java, kogito-serverless-workflow/kogito-jsonpath-expression/pom.xml, kogito-serverless-workflow/kogito-jsonpath-expression/src/main/java/org/kie/kogito/expr/jsonpath/JsonPathExpression.java, kogito-serverless-workflow/kogito-jsonpath-expression/src/main/java/org/kie/kogito/expr/jsonpath/WorkflowJacksonJsonNodeJsonProvider.java, kogito-serverless-workflow/kogito-jsonpath-expression/src/test/java/org/kie/kogito/expr/jsonpath/JsonPathExpressionHandlerTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ServerlessWorkflowParser.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/SWFProduceEventAction.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/workitemparams/JsonNodeResolver.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/test/java/org/kie/kogito/serverless/workflow/JsonNodeJqResolverTest.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/main/java/org/kie/kogito/serverless/workflow/utils/ExpressionHandlerUtils.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/main/java/org/kie/kogito/serverless/workflow/utils/KogitoProcessContextResolver.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/test/java/org/kie/kogito/serverless/workflow/utils/ExpressionHandlerUtilsTest.java
With this approach change, many of the hacks we have are gone for good (still jsonpath handling, for legacy reasons, include some of them, but they are minor)
=> [KOGITO-7139] JsonPath/JQ implementation

kogito-build/kogito-dependencies-bom/pom.xml
Small change to upgrade the extension and leverage the latest features.
See: https://issues.redhat.com/browse/KOGITO-7113
=> [KOGITO-7113] - Upgrade OpenAPI Quarkus Extension

kogito-build/kogito-dependencies-bom/pom.xml
Assembly:
- https://github.com/kiegroup/drools/pull/4418
- https://github.com/kiegroup/optaplanner/pull/2002
- https://github.com/kiegroup/optaplanner-quickstarts/pull/346
- https://github.com/kiegroup/kogito-examples/pull/1270
- https://github.com/kiegroup/kogito-runtimes/pull/2226
=> [1.22.x] Bump Quarkus version to 2.9.2.Final

jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/ExpressionReturnValueEvaluator.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/validation/RuleFlowProcessValidator.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/JoinInstance.java, kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqExpression.java, kogito-serverless-workflow/kogito-jsonpath-expression/src/main/java/org/kie/kogito/expr/jsonpath/JsonPathExpression.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/ParallelHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/suppliers/ExpressionReturnValueEvaluatorSupplier.java, kogito-workitems/kogito-jackson-utils/src/main/java/org/kie/kogito/jackson/utils/JsonObjectUtils.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/parallel.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/ParallelStateIT.java
Adding expression support for numCompleted (and integration test)
=> [KOGITO-6980] Support completion type and num completed for parallel

quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/WorkflowCodeGenUtils.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/helloworld.sw.json
<details>
<summary>
</summary> …
=> [KOGITO-7243] Checking againts null getFunctions

.ci/jenkins/Jenkinsfile.quarkus
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/459
- https://github.com/kiegroup/kogito-runtimes/pull/2228
=> Quarkus Jenkins check take BUILD_MVN_OPTS into account

api/kogito-api/src/main/java/org/kie/kogito/correlation/CompositeCorrelation.java, api/kogito-api/src/main/java/org/kie/kogito/correlation/Correlation.java, api/kogito-services/src/test/java/org/kie/kogito/services/event/impl/ProcessEventDispatcherTest.java
<details>
<summary>
</summary> …
=> Order should be guaranteed when generating key

integration-tests/integration-tests-quarkus-openapi-client/src/main/resources/application.properties, kogito-build/kogito-dependencies-bom/pom.xml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/pom.xml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/specs/token-propagation-external-service1.yaml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/specs/token-propagation-external-service2.yaml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/specs/token-propagation-external-service3.yaml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/specs/token-propagation-external-service4.yaml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/specs/token-propagation-external-service5.yaml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/token-propagation.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/ConversationFlowIT.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/ExternalServiceMock.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/KeycloakServiceMock.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/OperationsMockService.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/TokenPropagationExternalServicesMock.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/TokenPropagationIT.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/WorkflowTestUtils.java
<details>
<summary>
</summary> …
=> KOGITO-7057: [KSW][OpenAPI] - Add Token Propagation support to OpenAPI Extension

.ci/jenkins/Jenkinsfile.quarkus
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/478
- https://github.com/kiegroup/kogito-runtimes/pull/2249
- https://github.com/kiegroup/kogito-examples/pull/1282
=> Allow to disable persistence/events check in examples

quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/GrpcServerPortResource.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/RPCGreetIT.java
<details>
<summary>
</summary> …
=> gRPC native integration test fixes

.ci/jenkins/Jenkinsfile.quarkus, .ci/jenkins/dsl/jobs.groovy
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/464
- https://github.com/kiegroup/drools/pull/4437
- https://github.com/kiegroup/kogito-runtimes/pull/2243
- https://github.com/kiegroup/optaplanner/pull/2014
- https://github.com/kiegroup/kogito-apps/pull/1366
Jobs to test:
=> [PLANNER-2727] Extract optaplanner from Kogito CI

kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java, kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionRestResourceGenerator.java
**JIRA**: https://issues.redhat.com/browse/KOGITO-7154
* https://github.com/kiegroup/drools/pull/4450
* https://github.com/kiegroup/kogito-runtimes/pull/2258 (this PR)
* https://github.com/kiegroup/kie-docs/pull/4224
<details>
<summary>
</summary>
[build-chain …
=> KOGITO-7154 DMN algo for OAS/Swagger naming

kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CompositeContextNodeHandler.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/java/org/kie/kogito/workflows/services/AgePerson.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/java/org/kie/kogito/workflows/services/AgePersonService.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/java/org/kie/kogito/workflows/services/Person.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/pojoServiceFilter.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/PojoServiceIT.java
The HashMap should be a LinkedHashMap or the order of the parameters will not necessarily be respected. 
This is difficult to test, since it will fail or not depending on the name of the parameters (the order in the hash in the map), so I added and extra parameter to the multi param scenario
=> [KOGITO-7397] Fixing bug in order of parameters

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessVisitor.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowProcessFactory.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ServerlessWorkflowParser.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/SwitchHandler.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/keepActive.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/parallel.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/KeepActiveIT.java
Added a simple integration test
=> [KOGITO-6677] Implementing keep active

api/kogito-events-api/src/main/java/org/kie/kogito/event/EventEmitter.java, quarkus/addons/messaging/common/src/main/java/org/kie/kogito/addon/quarkus/messaging/common/AbstractQuarkusCloudEventEmitter.java, quarkus/addons/messaging/common/src/main/java/org/kie/kogito/addon/quarkus/messaging/common/message/CloudEventHttpOutgoingDecorator.java, quarkus/addons/messaging/common/src/test/java/org/kie/kogito/addon/quarkus/messaging/common/message/CloudEventHttpOutgoingDecoratorTest.java, quarkus/addons/messaging/deployment/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/deployment/KogitoAddOnMessagingProcessor.java, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/src/main/java/org/kie/kogito/quarkus/conf/KogitoBuildTimeConfig.java, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/src/main/java/org/kie/kogito/quarkus/conf/KogitoRuntimeConfig.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/.gitignore, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/pom.xml, quarkus/integration-tests/integration-tests-quarkus-processes/pom.xml
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/2274
- https://github.com/kiegroup/kogito-examples/pull/1297
=> KOGITO-7401 Adjust Kogito Quarkus config prefix

drools/kogito-drools/pom.xml, drools/kogito-pmml/src/main/java/org/kie/kogito/pmml/KieRuntimeFactoryBuilder.java, kogito-build/kogito-kie-bom/pom.xml, kogito-codegen-modules/kogito-codegen-predictions/src/main/java/org/kie/kogito/codegen/prediction/PredictionCodegen.java, kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/java/org/kie/kogito/codegen/AbstractCodegenIT.java, kogito-codegen-modules/kogito-codegen-rules/pom.xml, kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/DroolsModelBuilder.java, kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/ProjectRuntimeGenerator.java, kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/QueryGenerator.java, kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/RuleCodegen.java, kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/RuleCodegenUtils.java, kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/RuleUnitGenerator.java, kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/RuleUnitPojoGenerator.java, kogito-codegen-modules/kogito-codegen-rules/src/main/resources/class-templates/rules/RuleUnitOnKieSessionJavaTemplate.java, kogito-codegen-modules/kogito-codegen-rules/src/main/resources/class-templates/rules/RuleUnitOnReteEvaluatorJavaTemplate.java
**JIRA**: https://issues.redhat.com/browse/DROOLS-7030
Related PRs:
https://github.com/kiegroup/drools/pull/4481
https://github.com/kiegroup/kogito-runtimes/pull/2287
=> [DROOLS-7030] split code generation and runtime of executable model

.github/quarkus-ecosystem-test, .github/workflows/quarkus-snapshot.yaml
<details>
<summary>
</summary> …
=> Update Quarkus ecosystem LTS job

kogito-bom/pom.xml
Part of an ensemble:
* https://github.com/kiegroup/kogito-runtimes/pull/2286
* https://github.com/kiegroup/kogito-apps/pull/1393
* https://github.com/kiegroup/kogito-examples/pull/1305
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for …
=> Rename swf-quarkus-extension to kogito-quarkus-serverless-workflow-devui

quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test/src/test/java/org/kie/kogito/quarkus/dmn/KogitoDMNCodeCodestartIT.java
@ia3andy could you kindly confirm this fully enact on your suggestions mentioned in this https://github.com/quarkusio/quarkus/pull/25397#issuecomment-1119331367 , please?
https://issues.redhat.com/browse/KOGITO-7404
<details>
<summary>
</summary>
[build-chain …
=> KOGITO-7404 update CODEstart test sync to Quarkus 2.10

addons/common/events/README.md, addons/common/explainability/README.md, addons/common/jobs/README.md, addons/common/knative/README.md, addons/common/kubernetes/README.md, addons/common/mail/README.md, addons/common/messaging/README.md, addons/common/monitoring/README.md, addons/common/persistence/README.md, addons/common/process-management/README.md, addons/common/process-svg/README.md, addons/common/task-management/README.md, addons/common/tracing/README.md, kogito-serverless-workflow/README.md
JIRA: https://issues.redhat.com/browse/KOGITO-6884
The examples location in kogito-examples has changed. So, we need to review all the links on the KIE blog and in the following repos:
https://github.com/kiegroup/kogito-runtimes
https://github.com/kiegroup/kogito-examples
https://github.com/kiegroup/kie-docs/tree/main-kogito
https://github.com/kiegroup/kogito-docs
----------
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross …
=> KOGITO-6884 Updated links to examples

addons/common/persistence/filesystem/src/test/java/org/kie/persistence/filesystem/FileSystemProcessInstancesTest.java, addons/common/persistence/jdbc/src/main/java/org/kie/kogito/persistence/jdbc/DDLRunner.java, addons/common/persistence/jdbc/src/main/java/org/kie/kogito/persistence/jdbc/DatabaseType.java, addons/common/persistence/jdbc/src/main/java/org/kie/kogito/persistence/jdbc/GenericRepository.java, addons/common/persistence/jdbc/src/main/java/org/kie/kogito/persistence/jdbc/JDBCProcessInstances.java, addons/common/persistence/jdbc/src/main/java/org/kie/kogito/persistence/jdbc/Repository.java, addons/common/persistence/jdbc/src/main/java/org/kie/kogito/persistence/jdbc/correlation/CorrelationRepository.java, addons/common/persistence/jdbc/src/main/java/org/kie/kogito/persistence/jdbc/correlation/JDBCCorrelationService.java, addons/common/persistence/jdbc/src/main/java/org/kie/kogito/persistence/jdbc/correlation/PostgreSQLCorrelationRepository.java, addons/common/persistence/jdbc/src/main/resources/sql/create_tables_PostgreSQL.sql, addons/common/persistence/jdbc/src/test/java/org/kie/persistence/jdbc/AbstractProcessInstancesIT.java, addons/common/persistence/jdbc/src/test/java/org/kie/persistence/jdbc/correlation/JDBCCorrelationServiceIT.java, addons/common/persistence/postgresql/src/test/java/org/kie/persistence/postgresql/PostgresqlProcessInstancesIT.java, api/kogito-api/src/main/java/org/kie/kogito/correlation/CompositeCorrelation.java, api/kogito-api/src/main/java/org/kie/kogito/correlation/SimpleCorrelation.java, api/kogito-services/src/main/java/org/kie/kogito/services/event/correlation/MD5CorrelationEncoder.java, api/kogito-services/src/main/java/org/kie/kogito/services/uow/ProcessInstanceWorkUnit.java, api/kogito-services/src/test/java/org/kie/kogito/services/event/correlation/MD5CorrelationEncoderTest.java, api/kogito-services/src/test/java/org/kie/kogito/services/event/impl/ProcessEventDispatcherTest.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java, quarkus/addons/persistence/jdbc/runtime/src/main/java/org/kie/kogito/persistence/quarkus/JDBCorrelationServiceProducer.java
Related
https://github.com/kiegroup/kogito-examples/pull/1276
<details>
<summary>
</summary> …
=> [KOGITO-6783] Enhance PostgreSQL persistence addon to support correlation

quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/ProcessesAssetsProcessor.java
<details>
<summary>
</summary> …
=> [KOGITO-7478] Fix CorrelationIT for native build

.ci/jenkins/Jenkinsfile.quarkus
<details>
<summary>
</summary> …
=> KOGITO-7496 Update quarkus nightly to compare dependencies

quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/ClassAnnotatedWorkflowHandlerGenerator.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/openapi/WorkflowOpenApiHandlerGenerator.java
Fixes a typo in `org.kie.kogito.quarkus.serverless.workflow.ClassAnnotatedWorkflowHandlerGenerator`.
-------------
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case …
=> Fixed typo in class name

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.native, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.quarkus, .ci/jenkins/Jenkinsfile.sonarcloud, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/dsl/test.sh
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/269
- https://github.com/kiegroup/drools/pull/4518
- https://github.com/kiegroup/kogito-runtimes/pull/1622
- https://github.com/kiegroup/kogito-apps/pull/1405
- https://github.com/kiegroup/kogito-examples/pull/1323
- https://github.com/kiegroup/kogito-operator/pull/1239
- https://github.com/kiegroup/optaplanner/pull/2061
=> KOGITO-5780 Set JDK and Maven tools as env vars

.github/workflows/jenkins-tests-PR.yml
<details>
<summary>
</summary> …
=> [1.24.x] Update GHA DSL check to use composite action (#2311)

.ci/jenkins/Jenkinsfile.quarkus
cherry-pick: https://github.com/kiegroup/kogito-runtimes/pull/2310
<details>
<summary>
</summary> …
=> [1.24.x] KOGITO-7496 Update quarkus nightly (#2310)

jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/RuleSetNodeInstance.java
…uleTask
<details>
<summary>
</summary> …
=> KOGITO-7569 Memory leak when running processes with rules in BusinessRuleTask

quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/src/main/java/org/kie/kogito/quarkus/conf/KogitoBuildTimeConfig.java, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/src/main/java/org/kie/kogito/quarkus/conf/KogitoPersistenceBuildTimeConfig.java, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/src/main/java/org/kie/kogito/quarkus/conf/KogitoPersistenceRuntimeConfig.java
Fixes https://github.com/kiegroup/kogito-runtimes/issues/2324
=> KOGITO-7575 - Add persistence related config properties to Quarkus

kogito-build/kogito-kie-bom/pom.xml
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/2338
- https://github.com/kiegroup/kogito-apps/pull/1412
=> KOGITO-7502 - Add kie-pmml-evaluator-assembler to kie-bom

quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test/src/test/java/org/kie/kogito/quarkus/dmn/KogitoDMNCodeCodestartIT.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/pom.xml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/ServerlessWorkflowCodestartTest.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/src/main/codestarts/quarkus/kogito-serverless-workflow-codestart/codestart.yml
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/2332
- https://github.com/kiegroup/drools/pull/4539
=> KOGITO-7537 - Downgrade Codestart test API

quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/KogitoDevServicesProcessor.java
=> [1.24.x] KOGITO-7541 - Expose host port for Data Index Dev Service (#2331)

quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/src/main/java/org/kie/kogito/quarkus/conf/KogitoBuildTimeConfig.java, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/src/main/java/org/kie/kogito/quarkus/conf/KogitoServerlessWorkflowBuildTimeConfig.java
This removes the unrecognized property warning for these two ones.
=> [KOGITO-7592] Adding serverless workflow build time properties

quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/fahrenheit-to-celsius.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/CorrelationIT.java
Testing arguments as expression string for open api
Decreasing correlation initial delay (will decrease execution time in
=> Testing tweaks

kogito-serverless-workflow/kogito-serverless-workflow-runtime/pom.xml, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/rpc/ProtobufUtilRPCConverter.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/rpc/RPCConverter.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/rpc/RPCConverterFactory.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/rpc/RPCWorkItemHandler.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/java/org/kie/kogito/workflows/services/GreeterService.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/greeting.proto, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/rpcgreet.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/RPCGreetIT.java
* [KOGITO-7535] Handling enums for grpc
* [KOGITO-7535] Integration test
* [KOGITO-7535] New approach
* [KOGITO-7535] Deleting dead code
* [KOGITO-7535] Some styling
<details>
<summary>
</summary> …
=> [1.24x.][KOGITO-7535] Handling enums for grpc (#2326)

.ci/jenkins/dsl/jobs.groovy
This reverts commit b757a8674e8002f23274e65b6bbcf3f056c454f7.
<details>
<summary>
</summary> …
=> [1.13.x] Revert "Remove native checks (#2062)"

.ci/jenkins/dsl/jobs.groovy
This reverts commit b757a8674e8002f23274e65b6bbcf3f056c454f7.
<details>
<summary>
</summary> …
=> [1.13.x-blue] Revert "Remove native checks (#2062)"

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessVisitor.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowProcessFactory.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/WorkflowInputModelValidator.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/WorkflowProcess.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/WorkflowValidator.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/impl/WorkflowProcessImpl.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ServerlessWorkflowParser.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/suppliers/DataInputSchemaValidatorSupplier.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/DataInputSchemaValidator.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/test/java/org/kie/kogito/serverless/workflow/actions/DataInputSchemaValidatorTest.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/test/resources/expression.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/ExpressionRestIT.java
This adds validation to workflow process before the process instance is created
=> [KOGITO-7624] Adding validator to process

kogito-build/kogito-dependencies-bom/pom.xml, springboot/bom/pom.xml
Cherry pick https://github.com/kiegroup/kogito-runtimes/pull/2325
=> [1.13.x-blue] KOGITO-7536 - Downgrade Spring Boot version to 2.5.12

kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/rpc/DefaultEnumRpcDecorator.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/rpc/RPCDecorator.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/rpc/RPCWorkItemHandler.java, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/src/main/java/org/kie/kogito/quarkus/conf/KogitoRPCRuntimeConfig.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/rpc/WorkflowRPCHandlerGenerator.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/java/org/kie/kogito/workflows/services/GreeterService.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/greeting.proto, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/rpcgreet.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/EmitEnumProfile.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/EmitEnumRPCGreetIT.java
This property enable inclusion of default enum value in grpc response
=> [KOGITO-7538] Adding property kogito.grpc.enum.includeDefault

api/kogito-api/src/main/java/org/kie/kogito/process/ProcessInstance.java, api/kogito-api/src/main/java/org/kie/kogito/process/ProcessService.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/ProcessServiceImpl.java, kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceQuarkusTemplate.java, kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceSpringTemplate.java, quarkus/integration-tests/integration-tests-quarkus-processes/src/main/resources/AdHocFragments.bpmn, quarkus/integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/BasicRestIT.java
This generates a PATCH method in the REST resource class.
=> [KOGITO-7713] Adding PATCH for process model

quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/src/main/java/org/kie/kogito/quarkus/conf/KogitoEventingRuntimeConfig.java, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/src/main/java/org/kie/kogito/quarkus/conf/KogitoRuntimeConfig.java
<details>
<summary>
</summary> …
=> [KOGITO-7620] Eventing thread pool configs to KogitoRuntimeConfig

kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/ActionUtils.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/BaseExpressionAction.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/CollectorAction.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/MergeAction.java
While manually testing Kogito-7524, I realize there is a case that is not currently covered and will not trigger an event change when it should. 
This PR is a quick fix, because Kogito-7524 may not be merged after all (we need to discuss, there are issues I will try do summarize [here](https://github.com/kiegroup/kogito-runtimes/pull/2380))
=> [KOGITO-7523] Collector action should setValue to trigger event change

.gitignore, quarkus/addons/common/deployment/src/main/java/org/kie/kogito/quarkus/addons/common/deployment/AnyEngineKogitoAddOnProcessor.java, quarkus/addons/common/deployment/src/main/java/org/kie/kogito/quarkus/addons/common/deployment/RequireCapabilityKogitoAddOnProcessor.java
W/o this a build step might not be executed and actually lead to an application build error.
=> Make sure verifyCapabilities build steps are tied to producing a build item

kogito-build/kogito-build-no-bom-parent/pom.xml, quarkus/extensions/kogito-quarkus-test-list/pom.xml
https://issues.redhat.com/browse/KOGITO-7769
To new 1.0.0 version, where version of artifacts is included. See also https://github.com/ppalaga/rpkgtests-maven-plugin/pull/16
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each …
=> KOGITO-7769 Update rpkgtests maven plugin version

quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/KogitoDevServicesProcessor.java, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/devservices/DataIndexInMemoryContainer.java
Assembly:
- https://github.com/kiegroup/kogito-apps/pull/1439
- https://github.com/kiegroup/kogito-runtimes/pull/2401
=> KOGITO-7734 - Override gateway api url for dev service

.ci/jenkins/Jenkinsfile.init-branch, .ci/jenkins/dsl/jobs.groovy
Example init commit: https://github.com/kiegroup/kogito-runtimes/pull/2410/commits/7cac14d81d572b83bc856118c34feec33f360196
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/591
- https://github.com/kiegroup/drools/pull/4631
- https://github.com/kiegroup/kogito-runtimes/pull/2410
- https://github.com/kiegroup/kogito-apps/pull/1443
- https://github.com/kiegroup/kogito-examples/pull/1380
- https://github.com/kiegroup/kogito-images/pull/1323
- https://github.com/kiegroup/kogito-operator/pull/1264
- https://github.com/kiegroup/kogito-docs/pull/176
=> KOGITO-7785 Setup init-branch job

.github/workflows/quarkus-snapshot.yaml
<details>
<summary>
</summary> …
=> Quarkus ecosystem LTS: Add data-index image

addons/common/process-svg/pom.xml, addons/common/process-svg/src/main/java/org/kie/kogito/svg/AbstractProcessSvgService.java, addons/common/process-svg/src/main/java/org/kie/kogito/svg/processor/AbstractSVGProcessor.java, kogito-build/kogito-dependencies-bom/pom.xml, quarkus/addons/process-svg/deployment/src/main/java/org/kie/kogito/svg/deployment/KogitoAddOnProcessSVGProcessor.java, quarkus/addons/process-svg/runtime/pom.xml
=> [1.27.x] KOGITO-7874 - Use parent first classloader for xml-apis (#2420)

kogito-build/kogito-build-no-bom-parent/pom.xml, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/JandexProtoGenerator.java
Fixes https://github.com/kiegroup/kogito-runtimes/issues/2436
=> KOGITO-7888 - Use Jandex to find enum ordinal

kogito-build/kogito-build-no-bom-parent/pom.xml, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/JandexProtoGenerator.java
=> [1.27.x] KOGITO-7888 - Use Jandex to find enum ordinal

.ci/jenkins/Jenkinsfile.native
- https://github.com/kiegroup/drools/pull/4675
- https://github.com/kiegroup/kogito-runtimes/pull/2450
- https://github.com/kiegroup/kogito-apps/pull/1454
- https://github.com/kiegroup/kogito-examples/pull/1391
=> [1.27.x] Jenkins Nightly Native should use BUILD_MVN_OPTS

.ci/jenkins/Jenkinsfile.native
- https://github.com/kiegroup/drools/pull/4677
- https://github.com/kiegroup/kogito-runtimes/pull/2452
- https://github.com/kiegroup/kogito-apps/pull/1456
- https://github.com/kiegroup/kogito-examples/pull/1392
=> Jenkins Nightly Native should use BUILD_MVN_OPTS (#2450)

kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/io/HttpContentLoader.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/main/java/org/kie/kogito/serverless/workflow/utils/BuildEvaluator.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/test/java/org/kie/kogito/serverless/workflow/utils/BuildEvaluatorTest.java
=> [KOGITO-7894] Support SECRET replacement on auth values

drools/kogito-drools/src/main/java/org/kie/kogito/drools/core/data/DataSourceFactoryImpl.java, drools/kogito-drools/src/main/java/org/kie/kogito/drools/core/data/EventListDataStream.java, drools/kogito-drools/src/main/java/org/kie/kogito/drools/core/data/FieldDataStore.java, drools/kogito-drools/src/main/java/org/kie/kogito/drools/core/data/ListDataStore.java, drools/kogito-drools/src/main/java/org/kie/kogito/drools/core/data/ListDataStream.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/RuleUnitHandler.java
**JIRA**: https://issues.redhat.com/browse/KOGITO-6242
**Related PRs**:
https://github.com/kiegroup/drools/pull/4676
https://github.com/kiegroup/kogito-runtimes/pull/2451
=> [KOGITO-6242] refactor datasources + implement retention policy

kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ServerlessWorkflowParser.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/schema/OpenApiModelSchemaGenerator.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/ServerlessWorkflowUtils.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/ServerlessWorkflowParsingTest.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/SWFConstants.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/deployment/ServerlessWorkflowAssetsProcessor.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/src/main/java/org/kie/kogito/serverless/workflow/openapi/ServerlessWorkflowOASFilter.java
JIRA: https://issues.redhat.com/browse/KOGITO-7675
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple …
=> [1.27.x] [KOGITO-7675] Fixed generation of OpenAPI input model schema

kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/rest/GeneratedRestOperationHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/rest/RestOperationHandlerFactory.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/ServerlessWorkflowUtils.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/operationid/FileNameWorkflowOperationIdTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/operationid/FullURIWorkflowOperationIdTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/operationid/FunctionOperationIdTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/operationid/SpecTitleOperationIdTest.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/ClassAnnotatedWorkflowHandlerGenerator.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/WorkflowCodeGenUtils.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/WorkflowHandlerGeneratedFile.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/WorkflowHandlerGenerator.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/deployment/ServerlessWorkflowAssetsProcessor.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/openapi/WorkflowOpenApiHandlerGenerator.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/rpc/WorkflowRPCHandlerGenerator.java
Related to https://github.com/quarkiverse/quarkus-openapi-generator/pull/137
=> KOGITO-7890 - Use operation id as work item handler name

kogito-build/kogito-dependencies-bom/pom.xml, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/rest/GeneratedRestOperationHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/rest/RestOperationHandlerFactory.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/ServerlessWorkflowUtils.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/operationid/FileNameWorkflowOperationIdTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/operationid/FullURIWorkflowOperationIdTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/operationid/FunctionOperationIdTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/operationid/SpecTitleOperationIdTest.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/ClassAnnotatedWorkflowHandlerGenerator.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/WorkflowCodeGenUtils.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/WorkflowHandlerGeneratedFile.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/WorkflowHandlerGenerator.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/deployment/ServerlessWorkflowAssetsProcessor.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/openapi/WorkflowOpenApiHandlerGenerator.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/rpc/WorkflowRPCHandlerGenerator.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/fahrenheit-to-celsius.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/specs/multiplication.yaml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/specs/subtraction.yaml, quarkus/integration-tests/integration-tests-quarkus-openapi-client/pom.xml, quarkus/integration-tests/integration-tests-quarkus-openapi-client/src/main/resources/openapi2-sec.sw.json
Cherry pick of https://github.com/kiegroup/kogito-runtimes/pull/2443
=> [1.27.x] KOGITO-7890 - Use operation id as work item handler name

quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/pom.xml, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/KogitoDevServicesProcessor.java
Cherry-pick of https://github.com/kiegroup/kogito-runtimes/pull/2458
=> [1.27.x] KOGITO-7911 - Allow to override Data Index image version

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/RuleSetNodeVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/RuleUnitMetaModel.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/process/builder/dialect/java/AbstractJavaProcessBuilder.java, kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/RuleUnitDTOSourceClass.java, kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/RuleUnitHelper.java, kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/RuleUnitPojoGenerator.java
**JIRA**: https://issues.redhat.com/browse/DROOLS-7155
**Related PRs**
https://github.com/kiegroup/drools/pull/4693
https://github.com/kiegroup/kogito-runtimes/pull/2470
=> [DROOLS-7155] add complete support for generics types in globals

.github/pull_request_template.md
- https://github.com/kiegroup/drools/pull/4697
- https://github.com/kiegroup/kogito-runtimes/pull/2478
- https://github.com/kiegroup/kogito-apps/pull/1464
- https://github.com/kiegroup/kogito-examples/pull/1405
=> KOGITO-7906 Update PR template

quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions-deployment/src/main/java/org/kie/kogito/quarkus/predictions/deployment/PredictionsAssetsProcessor.java
@cristianonicolai Remove "info" logs from PredictionsAssetsProcessor
<details>
<summary>
</summary> …
=> [log-cleanup] Remove log verbosity

quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/rpc/WorkflowRPCCodeGenProvider.java
<details>
<summary>
</summary> …
=> [KOGITO-7955] Fixing grpc windows path issue

kogito-build/kogito-dependencies-bom/pom.xml
See: https://issues.redhat.com/browse/KOGITO-7971
In this PR, we update the SmallRye OpenAPI dependency so that it can work with Quarkus LTS.
I had to add a few more dependencies to override the others and align the whole structure.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) …
=> [KOGITO-7971] Align smallrye openapi components to Quarkus 2.7 LTS

kogito-build/kogito-dependencies-bom/pom.xml
=> [1.27.x][KOGITO-7971] Align smallrye openapi components to Quarkus 2.7 LTS

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ForEachNodeVisitor.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/context/variable/Variable.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/coverter/CloneHelper.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/coverter/CloneHelperFactory.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/coverter/TypeConverterRegistry.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/type/ObjectDataType.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/context/variable/VariableScopeInstance.java, jbpm/jbpm-flow/src/test/java/org/jbpm/process/core/datatype/impl/coverter/CloneHelperTest.java
<details>
<summary>
</summary> …
=> [1.27.x][SRVLOGIC-43] Native issue with clone

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ForEachNodeVisitor.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/context/variable/Variable.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/coverter/CloneHelper.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/coverter/CloneHelperFactory.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/coverter/CloneHelperRegister.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/coverter/TypeConverterRegistry.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/type/ObjectDataType.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/context/variable/VariableScopeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/ForEachNodeFactory.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/node/ForEachNode.java, jbpm/jbpm-flow/src/test/java/org/jbpm/process/core/datatype/impl/coverter/CloneHelperTest.java
Fixing native build failing in load class.
This avoid that issue by taking the class from the object being cloned.
=> [SRVLOGIC-43] Native issue with clone

kogito-build/kogito-dependencies-bom/pom.xml
Related to https://github.com/quarkusio/quarkus-platform/pull/623
=> KOGITO-8007 Upgrade JQ Quarkus version

.ci/jenkins/Jenkinsfile.specific_nightly
https://issues.redhat.com/browse/KOGITO-8010
- https://github.com/kiegroup/kogito-pipelines/pull/627
- https://github.com/kiegroup/drools/pull/4718
- https://github.com/kiegroup/kogito-runtimes/pull/2514
- https://github.com/kiegroup/kogito-apps/pull/1476
- https://github.com/kiegroup/kogito-examples/pull/1416
=> KOGITO-8010 Correct Quarkus checks pipelines

kogito-build/kogito-dependencies-bom/pom.xml
Cherry-pick from https://github.com/kiegroup/kogito-runtimes/pull/2507
=> [1.28.x] KOGITO-8007 Upgrade JQ Quarkus version

addons/common/events/rules/src/main/java/org/kie/kogito/eventdriven/rules/AbstractEventDrivenQueryExecutor.java, kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/QueryEventDrivenExecutorGenerator.java, kogito-codegen-modules/kogito-codegen-rules/src/main/resources/class-templates/rules/EventDrivenExecutorQuarkusTemplate.java
@evacchi this should fix the broken example.
=> [DROOLS-7176] reintroduce AbstractEventDrivenQueryExecutor

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.init-branch, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.sonarcloud, .ci/jenkins/Jenkinsfile.specific_nightly
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/631
- https://github.com/kiegroup/drools/pull/4723
- https://github.com/kiegroup/kogito-runtimes/pull/2525
- https://github.com/kiegroup/kogito-apps/pull/1483
- https://github.com/kiegroup/kogito-examples/pull/1423
- https://github.com/kiegroup/kogito-images/pull/1342
- https://github.com/kiegroup/kogito-operator/pull/1293
- https://github.com/kiegroup/kogito-docs/pull/218
- https://github.com/kiegroup/kie-tools/pull/1249
- https://github.com/kiegroup/optaplanner/pull/2219
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/760
- https://github.com/kiegroup/optaplanner-quickstarts/pull/415
=> KOGITO-8043 Jenkins node master -> built-in

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.init-branch, .ci/jenkins/Jenkinsfile.native, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.quarkus, .ci/jenkins/Jenkinsfile.sonarcloud
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/632
- https://github.com/kiegroup/kogito-pipelines/pull/633
- https://github.com/kiegroup/drools/pull/4724
- https://github.com/kiegroup/kogito-runtimes/pull/2526
- https://github.com/kiegroup/kogito-apps/pull/1484
- https://github.com/kiegroup/kogito-examples/pull/1424
- https://github.com/kiegroup/kogito-images/pull/1343
- https://github.com/kiegroup/kogito-operator/pull/1294
- https://github.com/kiegroup/kogito-docs/pull/219
=> [1.27.x] KOGITO-8043 Jenkins node master -> built-in

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.init-branch, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.sonarcloud, .ci/jenkins/Jenkinsfile.specific_nightly
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/634
- https://github.com/kiegroup/kogito-pipelines/pull/636
- https://github.com/kiegroup/drools/pull/4725
- https://github.com/kiegroup/kogito-runtimes/pull/2527
- https://github.com/kiegroup/kogito-apps/pull/1485
- https://github.com/kiegroup/kogito-examples/pull/1425
- https://github.com/kiegroup/kogito-images/pull/1344
- https://github.com/kiegroup/kogito-operator/pull/1295
- https://github.com/kiegroup/kogito-docs/pull/220
=> [1.28.x] KOGITO-8043 Jenkins node master -> built-in

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.drools, .ci/jenkins/Jenkinsfile.native, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.quarkus, .ci/jenkins/Jenkinsfile.sonarcloud, .ci/jenkins/dsl/Jenkinsfile.seed
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/637
- https://github.com/kiegroup/kogito-runtimes/pull/2528
- https://github.com/kiegroup/kogito-examples/pull/1426
- https://github.com/kiegroup/kogito-images/pull/1345
- https://github.com/kiegroup/kogito-operator/pull/1296
- https://github.com/kiegroup/optaplanner/pull/2222
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/762
- https://github.com/kiegroup/optaplanner-quickstarts/pull/417
=> [1.13.x] KOGITO-8043 Jenkins node master -> built-in

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.drools, .ci/jenkins/Jenkinsfile.native, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.quarkus, .ci/jenkins/Jenkinsfile.sonarcloud, .ci/jenkins/dsl/Jenkinsfile.seed
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/638
- https://github.com/kiegroup/kogito-runtimes/pull/2529
- https://github.com/kiegroup/kogito-examples/pull/1427
- https://github.com/kiegroup/kogito-images/pull/1346
- https://github.com/kiegroup/kogito-operator/pull/1297
=> [1.13.x-blue] KOGITO-8043 Jenkins node master -> built-in

.ci/jenkins/Jenkinsfile.specific_nightly, .ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-7703
Related: 
- https://github.com/kiegroup/drools/pull/4727
- https://github.com/kiegroup/kogito-runtimes/pull/2375
- https://github.com/kiegroup/kogito-apps/pull/1486
- https://github.com/kiegroup/kogito-examples/pull/1428
- https://github.com/kiegroup/kogito-pipelines/pull/642
=> KOGITO-7703 Quarkus nightlies: Use integration branch

addons/common/persistence/filesystem/src/main/java/org/kie/kogito/persistence/filesystem/FileSystemProcessInstances.java, api/kogito-api-incubation-application/src/main/java/org/kie/kogito/incubation/application/AppRoot.java, api/kogito-api-incubation-rules/src/main/java/org/kie/kogito/incubation/rules/data/DataId.java, api/kogito-api/src/main/java/org/kie/kogito/jobs/AsyncJobId.java, drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/DMNKogito.java, jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/handler/SignallingTaskHandlerDecorator.java, jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/handler/WorkItemHandlerRuntimeException.java, jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/AbstractNodeHandler.java, jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/XmlBPMNProcessDumper.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/xml/XmlWorkflowProcessDumper.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/xml/compiler/XmlDumper.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/xml/compiler/rules/RestrictionConnectiveHandler.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/xml/core/ExtensibleXmlParser.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/xml/processes/AbstractNodeHandler.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/LightProcessRuntime.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessRuntimeImpl.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/FeelReturnValueEvaluator.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/node/AsyncEventNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/node/RuleSetNode.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/DummyEventListener.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/SubProcessNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/TimerNodeInstance.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessInstanceGenerator.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessResourceGenerator.java, kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/RuleUnitInstanceGenerator.java, quarkus/addons/common/deployment/src/main/java/org/kie/kogito/quarkus/addons/common/deployment/KogitoCapability.java, quarkus/addons/persistence/kafka/runtime/src/main/java/org/kie/kogito/persistence/kafka/KafkaProcessInstances.java, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoCompilationProvider.java, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/ProcessesAssetsProcessor.java, quarkus/test/src/main/java/org/kie/kogito/test/resources/ConditionalQuarkusTestResource.java
https://issues.redhat.com/browse/KOGITO-8060
Goal here is to reduce the number of code smells in Kogito-runtimes.
Addressed in this PR are the following code smells:
Unused "private" fields should be removed (18):
https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1068&id=org.kie.kogito%3Akogito-runtimes
I have addressed this by removing the unused private fields.
Modifiers should be declared in the correct order (15):
https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1124&id=org.kie.kogito%3Akogito-runtimes
I have addressed this by using Java's recommended order.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and …
=> Kogito-8060 Sonarcloud - Fixing code smells related to unused private variables and modifiers declared in "incorrect" order

addons/common/events/rules/src/main/java/org/kie/kogito/eventdriven/rules/AbstractEventDrivenQueryExecutor.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/RuleSetNodeInstance.java, kogito-codegen-modules/kogito-codegen-rules/src/main/resources/class-templates/rules/RestQueryJavaTemplate.java, kogito-codegen-modules/kogito-codegen-rules/src/main/resources/class-templates/rules/RestQueryQuarkusTemplate.java, kogito-codegen-modules/kogito-codegen-rules/src/main/resources/class-templates/rules/RestQuerySpringTemplate.java, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules/src/main/java/org/kie/kogito/core/rules/incubation/quarkus/support/StatefulRuleUnitServiceImpl.java
**JIRA**: https://issues.redhat.com/browse/DROOLS-7193
Related PRs:
https://github.com/kiegroup/drools/pull/4735
https://github.com/kiegroup/kogito-runtimes/pull/2541
=> [DROOLS-7193] make RuleUnitInstance to extend Autoclosable

.ci/jenkins/Jenkinsfile.setup-branch, .ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-7798
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/602
- https://github.com/kiegroup/drools/pull/4713
- https://github.com/kiegroup/kogito-runtimes/pull/2502/files
- https://github.com/kiegroup/kogito-apps/pull/1471/files
- https://github.com/kiegroup/kogito-examples/pull/1414
- https://github.com/kiegroup/kogito-images/pull/1340
- https://github.com/kiegroup/kogito-operator/pull/1288
- https://github.com/kiegroup/kogito-docs/pull/214
=> KOGITO-7798 Refactor setup branch job

kogito-serverless-workflow/kogito-jq-expression/src/test/java/org/kie/kogito/expr/jq/JqExpressionHandlerTest.java, kogito-serverless-workflow/kogito-jsonpath-expression/src/test/java/org/kie/kogito/expr/jsonpath/JsonPathExpressionHandlerTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/BuildExpressionsTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/ServerlessWorkflowParsingTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/operationid/FileNameWorkflowOperationIdTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/operationid/FullURIWorkflowOperationIdTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/operationid/FunctionOperationIdTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/operationid/SpecTitleOperationIdTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/operationid/WorkflowOperationIdFactoryProviderTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/parser/handlers/validation/SwitchValidatorTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/utils/TimeoutsConfigResolverTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/utils/WorkflowUtilsTest.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/test/java/org/kie/kogito/serverless/workflow/JsonNodeJqResolverTest.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/test/java/org/kie/kogito/serverless/workflow/JsonNodeJsonPathResolverTest.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/test/java/org/kie/kogito/serverless/workflow/actions/DataInputSchemaValidatorTest.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/test/java/org/kie/kogito/serverless/workflow/io/ResourceCacheFactoryTest.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/test/java/org/kie/kogito/serverless/workflow/io/URIContentLoaderTest.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/test/java/org/kie/kogito/serverless/workflow/utils/BuildEvaluatorTest.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/test/java/org/kie/kogito/serverless/workflow/utils/ExpressionHandlerUtilsTest.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/test/java/org/kie/kogito/serverless/workflow/utils/KogitoProcessContextResolverTest.java
@ricardozanini @cristianonicolai 
issue: [KOGITO-8087](https://issues.redhat.com/browse/KOGITO-8087)
This patch migrates kogito-runtime tests inside kogito-server-workflow to assertj assertions.
It removes use of junit assertions and hamcrest assertions.
Where possible it simplifies the assertion using assertj features.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version …
=> KOGITO-8087 Migrate tests inside kogito-server-workflow to assertj assertions

jbpm/jbpm-flow/src/main/java/org/jbpm/util/JsonSchemaUtil.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/json/JsonSchemaGenerator.java
We should not use Path for classpath resolve
<details>
<summary>
</summary> …
=> [KOGITO-7950] Cannot build uber-jar on windows

kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/MessageConsumerGenerator.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/ServerlessWorkflowUtils.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/pom.xml
We did not detect this bug earlier because integration test is incorrectly adding deployment dependency during test phase
<details>
<summary>
</summary>
[build-chain …
=> [KOGITO-8136] Fixing dependency issue when using dataOnly true

quarkus/extensions/kogito-quarkus-extension/kogito-quarkus-deployment/pom.xml, quarkus/extensions/kogito-quarkus-extension/kogito-quarkus/pom.xml, quarkus/extensions/kogito-quarkus-extension/pom.xml, quarkus/extensions/pom.xml
Minor fix to include `kogito-quarkus-extension` to the productized profile. I had to remove the ITs from this profile since they require other modules that we had to leave out.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we …
=> Fix productized profile to include quarkus extension

jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/JoinFactory.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/SplitFactory.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/CallbackHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/EventHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/NodeFactoryUtils.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/CallbackStateServerlessWorkflowParsingTest.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/eventMultipleExclusive.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/eventMultipleTimeout.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/eventMultipleTimeoutExclusive.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/EventFlowIT.java
Note This only works for non starting event states
For starting events, see https://issues.redhat.com/browse/KOGITO-8137
=> [KOGITO-3921] Implementing Event State timeout

.ci/jenkins/Jenkinsfile.specific_nightly
- https://github.com/kiegroup/drools/pull/4757
- https://github.com/kiegroup/kogito-runtimes/pull/2573
- https://github.com/kiegroup/kogito-apps/pull/1495
- https://github.com/kiegroup/kogito-examples/pull/1447
=> Update Specific nightly reproducer

kogito-bom/pom.xml, springboot/starters/README.md
Jira related: https://issues.redhat.com/browse/KOGITO-8154
<details>
<summary>
</summary> …
=> KOGITO-8154: Removed discontinued referenced artifacts from kogito-bom

kogito-build/kogito-dependencies-bom/pom.xml
Jira: https://issues.redhat.com/browse/KOGITO-8172
-----------------
<details>
<summary>
</summary> …
=> [KOGITO-8172] Updated quarkus-openapi-generator to 0.12.0

kogito-serverless-workflow/README.md
Changing readme to reflect that
<details>
<summary>
</summary> …
=> [KOGITO-8159] Do not support non exclusive event state as start state

addons/common/marshallers/avro/src/main/resources/spec.avsc, api/kogito-events-core/src/test/java/org/kie/kogito/event/impl/DataEventTestUtils.java, quarkus/test/src/main/java/org/kie/kogito/test/quarkus/kafka/KafkaConsumerLoop.java, quarkus/test/src/main/java/org/kie/kogito/test/quarkus/kafka/KafkaTestClient.java, quarkus/test/src/main/java/org/kie/kogito/test/quarkus/kafka/KafkaTypedTestClient.java
Merge with https://github.com/kiegroup/kogito-examples/pull/1454
=> [KOGITO-8198] Fixing problem in avro schema for ints

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessMetaData.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java, quarkus/addons/messaging/deployment/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/deployment/ChannelInfo.java, quarkus/addons/messaging/deployment/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/deployment/KogitoAddOnMessagingProcessor.java
Merge with https://github.com/kiegroup/kogito-examples/pull/1455
=> [KOGITO-8203] Allowing multiple consumer/producers for the same trigger

addons/common/marshallers/avro/src/main/resources/spec.avsc, api/kogito-events-core/src/test/java/org/kie/kogito/event/impl/DataEventTestUtils.java, jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java, jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/StartEventTest.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessMetaData.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/test/util/DefaultCountDownProcessEventListener.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java, quarkus/addons/messaging/deployment/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/deployment/ChannelInfo.java, quarkus/addons/messaging/deployment/src/main/java/org/kie/kogito/addon/cloudevents/quarkus/deployment/KogitoAddOnMessagingProcessor.java, quarkus/test/src/main/java/org/kie/kogito/test/quarkus/kafka/KafkaConsumerLoop.java, quarkus/test/src/main/java/org/kie/kogito/test/quarkus/kafka/KafkaTestClient.java, quarkus/test/src/main/java/org/kie/kogito/test/quarkus/kafka/KafkaTypedTestClient.java
<details>
<summary>
</summary> …
=> 1 30 x update

addons/common/marshallers/avro/src/main/java/org/kie/kogito/event/avro/AvroIO.java, kogito-bom/pom.xml, quarkus/addons/marshallers/avro/deployment/pom.xml, quarkus/addons/marshallers/avro/deployment/src/main/java/org/kie/kogito/addon/avro/quarkus/deployment/AvroSchemaProcessor.java, quarkus/addons/marshallers/avro/pom.xml, quarkus/addons/marshallers/avro/runtime/pom.xml, quarkus/addons/marshallers/pom.xml, quarkus/addons/pom.xml
Merge with https://github.com/kiegroup/kogito-examples/pull/1467
=> [KOGITO-8210] Fixing native issue related with Avro schema

quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/serialization-config.json
Adding serialization-config.json for integration test that use java serialization for marshalling
=> [KOGITO-8213] Make serialization work on native mode

kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/rpc/RPCWorkItemHandler.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/rpc/ProtocUtils.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/java/org/kie/kogito/workflows/services/GreeterService.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/greeting.proto, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/message.proto
Imports were being incorrectly ignored.
=> [KOGITO-8199] Properly supporting import in grpc

jbpm/jbpm-flow/src/main/java/org/jbpm/util/WidMVELEvaluator.java
**JIRA**: https://issues.redhat.com/browse/DROOLS-7124
Related PRs:
https://github.com/kiegroup/drools/pull/4809
https://github.com/kiegroup/kogito-runtimes/pull/2607
=> [DROOLS-7124] remove use of deprecated JDK SecurityManager

quarkus/addons/kubernetes/runtime/src/main/java/org/kie/kogito/addons/quarkus/k8s/KubeDiscoveryConfigSourceInterceptor.java
Signed-off-by: spolti <fspolti@redhat.com>
See: https://issues.redhat.com/browse/KOGITO-8208
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is …
=> [KOGITO-8208] - [SW] - NPE on Service Discovery when running native mode

quarkus/addons/messaging/deployment/pom.xml, quarkus/addons/messaging/runtime/pom.xml, quarkus/addons/messaging/runtime/src/main/java/org/kie/kogito/addon/quarkus/messaging/QuarkusCloudEventEmitter.java
<details>
<summary>
</summary> …
=> Fixing compilation issue with EmitterConfiguration

quarkus/addons/messaging/runtime/src/main/java/org/kie/kogito/addon/quarkus/messaging/QuarkusCloudEventEmitter.java
<details>
<summary>
</summary> …
=> Fixing test

jbpm/jbpm-flow/src/test/java/org/kie/kogito/process/impl/AbstractProcessInstanceTest.java
<details>
<summary>
</summary> …
=> Changing private to default

.ci/jenkins/dsl/jobs.groovy, .github/workflows/kogito-examples-pr.yml
https://issues.redhat.com/browse/KOGITO-8222
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/690
- https://github.com/kiegroup/drools/pull/4808
- https://github.com/kiegroup/kogito-runtimes/pull/2606
- https://github.com/kiegroup/kogito-apps/pull/1502
- https://github.com/kiegroup/kogito-examples/pull/1410
=> [KOGITO-8222] Test parallel examples build

addons/common/marshallers/avro/src/main/java/org/kie/kogito/event/avro/AvroIO.java, addons/common/marshallers/avro/src/main/resources/jsonNode.avsc, addons/common/marshallers/avro/src/test/java/org/kie/kogito/event/avro/AvroMarshallUnmarshallTest.java, api/kogito-events-core/src/test/java/org/kie/kogito/event/impl/DataEventTestUtils.java, quarkus/addons/marshallers/avro/deployment/src/main/java/org/kie/kogito/addon/avro/quarkus/deployment/AvroSchemaProcessor.java
<details>
<summary>
</summary> …
=> [KOGITO-8241] Supporting binary mode for jsonNode in avro

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/descriptors/ExpressionUtils.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/expr/Expression.java, kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqExpression.java, kogito-serverless-workflow/kogito-jsonpath-expression/src/main/java/org/kie/kogito/expr/jsonpath/JsonPathExpression.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/suppliers/CollectorActionSupplier.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/suppliers/ExpressionActionSupplier.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/resources/exec/single-eventstate-multi-eventrefs.sw.yml, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/resources/exec/single-eventstate.sw.yml, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/SysoutAction.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/expression.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/subflow2.sw.yml
This also validates expressions on build time
=> [KOGITO-8243] Supporting hardcode strings in sysout

api/kogito-api/pom.xml, api/kogito-api/src/main/java/org/kie/kogito/rules/RuleUnitConfig.java, api/kogito-api/src/main/java/org/kie/kogito/rules/RuleUnits.java, kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/KieModuleModelWrapper.java, kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/RuleUnitGenerator.java, kogito-codegen-modules/kogito-codegen-rules/src/main/resources/class-templates/rules/RuleUnitContainerJavaTemplate.java, kogito-codegen-modules/kogito-codegen-rules/src/main/resources/class-templates/rules/RuleUnitContainerQuarkusTemplate.java, kogito-codegen-modules/kogito-codegen-rules/src/main/resources/class-templates/rules/RuleUnitContainerSpringTemplate.java, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules/src/main/java/org/kie/kogito/core/rules/incubation/quarkus/support/DataSourceServiceImpl.java, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules/src/main/java/org/kie/kogito/core/rules/incubation/quarkus/support/QuarkusRuleUnitService.java, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules/src/main/java/org/kie/kogito/core/rules/incubation/quarkus/support/RuleUnitServiceImpl.java, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules/src/main/java/org/kie/kogito/core/rules/incubation/quarkus/support/StatefulRuleUnitServiceImpl.java
**JIRA**: https://issues.redhat.com/browse/DROOLS-7248
Related PRs:
https://github.com/kiegroup/drools/pull/4842
https://github.com/kiegroup/kogito-runtimes/pull/2664
=> [DROOLS-7248] make kogito-api independent from drools-ruleunits-impl

addons/common/persistence/jdbc/src/main/resources/sql/create_tables_Oracle.sql
Adjusting the process_id and process_version columns size to varchar2(3000)
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool …
=> KOGITO-8312: Index on Process instance could not be created with Oracle persistence

.ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-6959
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/732
- https://github.com/kiegroup/drools/pull/4851
- https://github.com/kiegroup/kogito-runtimes/pull/2675
- https://github.com/kiegroup/kogito-apps/pull/1547
- https://github.com/kiegroup/kogito-examples/pull/1494
=> KOGITO-6959 Nightly job moved to build-chain

.github/workflows/kogito-examples-pr.yml
<details>
<summary>
</summary> …
=> Correct GHA Kogito Examples downstream check

kogito-build/kogito-dependencies-bom/pom.xml, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/asyncapi/AsyncChannelInfo.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/asyncapi/AsyncInfo.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/asyncapi/AsyncInfoConverter.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/asyncapi/AsyncInfoResolver.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/asyncapi/CachedAsyncInfoResolver.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ParserContext.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/ActionResourceFactory.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/types/AsyncAPITypeHandler.java, quarkus/bom/pom.xml, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoBuildContextAttributeBuildItem.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/pom.xml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/asyncapi/AsyncAPIInfoConverter.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/asyncapi/AsyncAPIProcessor.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/asyncapi/AsyncInputStreamSupplier.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/asyncapi/WorkflowAsyncApiSpecInputProvider.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/resources/META-INF/services/io.quarkiverse.asyncapi.generator.input.AsyncApiSpecInputProvider, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/asyncConsumer.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/specs/asyncAPI.yaml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/AssuredTestUtils.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/AsyncAPIIT.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/EventFlowIT.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/pom.xml
Integration of Kogito runtimes with version 0.0.1 of Async API Quarkiverse extension
https://github.com/quarkiverse/quarkus-asyncapi
=> [KOGITO-8319] Integrating with Async api quarkiverse extension

kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/asyncapi/CachedAsyncInfoResolver.java
<details>
<summary>
</summary> …
=> Fixing null pointer exception if converter is null

quarkus/addons/kubernetes/runtime/src/main/java/org/kie/kogito/addons/quarkus/k8s/KubeDiscoveryConfigCache.java, quarkus/addons/kubernetes/runtime/src/main/java/org/kie/kogito/addons/quarkus/k8s/KubeDiscoveryConfigSourceInterceptor.java, quarkus/addons/kubernetes/runtime/src/test/java/org/kie/kogito/addons/quarkus/k8s/KubeDiscoveryConfigCacheTest.java
Jira: https://issues.redhat.com/browse/KOGITO-8361
--------
<details>
<summary>
</summary> …
=> KOGITO-8361 Fixed possible ArrayIndexOutOfBoundsException

.github/workflows/kogito-apps-pr.yml, .github/workflows/kogito-examples-pr.yml, .github/workflows/kogito-runtimes-pr.yml, kogito-build/kogito-dependencies-bom/pom.xml
- https://github.com/kiegroup/kogito-pipelines/pull/753
- https://github.com/kiegroup/kogito-pipelines/pull/751
- https://github.com/kiegroup/drools/pull/4881
- https://github.com/kiegroup/kogito-runtimes/pull/2700
- https://github.com/kiegroup/kogito-examples/pull/1518
- https://github.com/kiegroup/kogito-images/pull/1396
=> [1.32.x] Bump Quarkus version to 2.13.5.Final

kogito-build/kogito-dependencies-bom/pom.xml, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/asyncapi/AsyncChannelInfo.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/asyncapi/AsyncInfo.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/asyncapi/AsyncInfoConverter.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/asyncapi/AsyncInfoResolver.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/asyncapi/CachedAsyncInfoResolver.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ParserContext.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/ActionResourceFactory.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/types/AsyncAPITypeHandler.java, quarkus/bom/pom.xml, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoBuildContextAttributeBuildItem.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/pom.xml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/asyncapi/AsyncAPIInfoConverter.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/asyncapi/AsyncAPIProcessor.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/asyncapi/AsyncInputStreamSupplier.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/asyncapi/WorkflowAsyncApiSpecInputProvider.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/resources/META-INF/services/io.quarkiverse.asyncapi.generator.input.AsyncApiSpecInputProvider, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/asyncConsumer.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/specs/asyncAPI.yaml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/AssuredTestUtils.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/AsyncAPIIT.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/EventFlowIT.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/pom.xml
Cherry pick for 1.32, using jandex2 version of async api
Depends on the release of https://github.com/quarkiverse/quarkus-asyncapi/pull/22
=> [1.32.x][KOGITO-8319] Integrating with Async api quarkiverse extension (#2679)

.ci/jenkins/Jenkinsfile.specific_nightly, .ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-8368
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/750
- https://github.com/kiegroup/drools/pull/4878
- https://github.com/kiegroup/kogito-runtimes/pull/2707
- https://github.com/kiegroup/kogito-apps/pull/1574
- https://github.com/kiegroup/kogito-examples/pull/1525
=> KOGITO-8368 Quarkus checks to use integration branch

kogito-build/kogito-dependencies-bom/pom.xml
Should fix error message that polute logs
<details>
<summary>
</summary> …
=> Updating to 0.0.2 version of asyncapi

kogito-bom/pom.xml
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/2703
- https://github.com/kiegroup/kogito-apps/pull/1567
=> KOGITO-7766 - Data Index as Quarkus extension

kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/SwitchHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/ServerlessWorkflowParsingTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/SwitchStateServerlessWorkflowParsingTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/resources/exec/eventbased-switch-state.sw.json, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/resources/exec/eventbased-switch-state.sw.yml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/foreach_child.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/foreach_parent.sw.json
Fix problem identified by this JIRA. 
Also correct minor indenting on some examples
=> [KOGITO-8381] Fixing multiple incoming on Switch state

api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/AbstractDescriptorRegistry.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/HasData.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/HasPayload.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/Job.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/JobLookupId.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/PayloadData.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/Recipient.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/RecipientDescriptor.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/Retry.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/Schedule.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/event/CreateJobEvent.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/event/DeleteJobEvent.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/event/JobCloudEvent.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/recipient/http/HttpRecipient.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/recipient/http/HttpRecipientBinaryPayloadData.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/recipient/http/HttpRecipientPayloadData.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/recipient/http/HttpRecipientStringPayloadData.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/recipient/kafka/KafkaRecipient.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/recipient/kafka/KafkaRecipientBinaryPayloadData.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/recipient/kafka/KafkaRecipientPayloadData.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/recipient/kafka/KafkaRecipientStringPayloadData.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/recipient/sink/SinkRecipient.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/recipient/sink/SinkRecipientPayloadData.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/schedule/cron/CronSchedule.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/schedule/timer/TimerSchedule.java, api/kogito-jobs-service-api/src/test/java/org/kie/kogito/jobs/service/api/event/serialization/JobCloudEventDeserializerTest.java, api/kogito-jobs-service-api/src/test/java/org/kie/kogito/jobs/service/api/event/serialization/JobCloudEventSerializerTest.java, api/kogito-jobs-service-api/src/test/java/org/kie/kogito/jobs/service/api/event/serialization/SerializationTestConstants.java, api/kogito-jobs-service-api/src/test/resources/org/kie/kogito/jobs/service/api/event/serialization/CreateJobEvent.json, api/kogito-jobs-service-api/src/test/resources/org/kie/kogito/jobs/service/api/event/serialization/CreateJobEventDataContent.json
- Modifications to support plugable recipients and the corresponding payload types
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build …
=> KOGITO-8245: New Public API Data Model

kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessResourceGenerator.java, kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/process/ProcessResourceGeneratorTest.java, kogito-codegen-modules/kogito-codegen-processes/src/test/resources/ProcessWithDocumentation.bpmn, kogito-codegen-modules/kogito-codegen-processes/src/test/resources/ProcessWithoutDocumentation.bpmn, kogito-codegen-modules/kogito-codegen-processes/src/test/resources/signalevent/BoundarySignalEventOnTask.bpmn2
[Jira issue](https://issues.redhat.com/browse/KOGITO-8428)
On some situations it is useful to overwrite rest templates, for instance a spring app that uses **WebFlux** framework, then signal template method could look like the following:
```
public Mono<$Type$Output> signal(@PathVariable("id") final String id, final @RequestBody(required = false) $signalType$ data) {
return Mono.fromCallable(() ->
...
);
}
```
but right now `ProcessResourceGenerator` class uses fixed output type derived from `modelfqcn` rather than `cloned.getType()`
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just …
=> KOGITO-8428 Honor rest signal template method return type

quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/pom.xml
<details>
<summary>
</summary> …
=> [1.32.x] Update data-index devservices version for prod

kogito-build/kogito-dependencies-bom/pom.xml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/openAPIEnumParameter.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/specs/enum-parameter.yaml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/EnumEchoServiceMock.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/OpenAPIEnumParameterIT.java
Jira: https://issues.redhat.com/browse/KOGITO-8418
This PR:
* Updates quarkus-openapi-generator to 1.1.0
* Adds a test to verify if the update fixes the issue
----
<details>
<summary>
</summary> …
=> KOGITO-8418 Fixed issue with enum parameter in OpenAPI

quarkus/extensions/kogito-quarkus-workflow-extension-common/kogito-quarkus-workflow-common-deployment/pom.xml
Jira: https://issues.redhat.com/browse/KOGITO-8471
<details>
<summary>
</summary> …
=> [KOGITO-8471] remove productized profile for data-index-ephemeral.image property

kogito-build/kogito-dependencies-bom/pom.xml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/openAPIEnumParameter.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/specs/enum-parameter.yaml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/EnumEchoServiceMock.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/OpenAPIEnumParameterIT.java
Backport of: 
https://github.com/kiegroup/kogito-runtimes/pull/2717
Jira: https://github.com/kiegroup/kogito-runtimes/pull/2717
---------
<details>
<summary>
</summary> …
=> [1.33.x] KOGITO-8418 Updated quarkus-openapi-generator to 1.1.0 (#2717)

api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/recipient/http/HttpRecipientBinaryPayloadData.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/recipient/http/HttpRecipientStringPayloadData.java
https://github.com/kiegroup/kogito-apps/pull/1542
https://github.com/kiegroup/kogito-runtimes/pull/2678
<details>
<summary>
</summary>
[build-chain …
=> [KOGITO-8262] ajustments to the new job service public API

kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/SwitchHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/ServerlessWorkflowParsingTest.java
=> [KOGITO-8499] Supporting multiple events on end node

quarkus/extensions/kogito-quarkus-extension/kogito-quarkus-integration-test-maven-devmode/pom.xml, quarkus/extensions/kogito-quarkus-extension/kogito-quarkus-integration-test-maven-devmode/src/test/java/io/quarkus/it/kogito/devmode/DevMojoIT.java
See https://issues.redhat.com/browse/KOGITO-8481
<details>
<summary>
</summary>
[build-chain …
=> [KOGITO-8481] Fix DevModeIT tests to delegate handle ports to Quarkus child process

quarkus/addons/kubernetes/deployment/src/test/resources/application.properties, quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test-hot-reload/src/test/java/org/kie/kogito/quarkus/decisions/hotreload/NewFileHotReloadIT.java, quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test-hot-reload/src/test/java/org/kie/kogito/quarkus/decisions/hotreload/SimpleHotReloadIT.java, quarkus/extensions/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-integration-test-hot-reload/src/test/java/org/kie/kogito/quarkus/decisions/hotreload/SimpleModifyHotReloadIT.java, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules-integration-test-hot-reload/src/test/java/org/kie/kogito/quarkus/rules/hotreload/HotReloadIT.java, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules-integration-test-hot-reload/src/test/java/org/kie/kogito/quarkus/rules/hotreload/newunit/NewUnitIT.java
See: https://issues.redhat.com/browse/KOGITO-8507
Also, there are a few formatting changes in other tests using the ShrinkWrap class.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for …
=> [KOGITO-8507] Disable Devservices from Kubernetes Addon

addons/common/persistence/jdbc/src/main/java/org/kie/kogito/persistence/jdbc/GenericRepository.java
<details>
<summary>
</summary> …
=> KOGITO-8459 fix sqlIncludingVersion

.github/workflows/kogito-apps-pr.yml, .github/workflows/kogito-examples-pr.yml, .github/workflows/kogito-runtimes-pr.yml
https://issues.redhat.com/browse/KOGITO-8534
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/789
- https://github.com/kiegroup/drools/pull/4944
- https://github.com/kiegroup/kogito-runtimes/pull/2765
- https://github.com/kiegroup/kogito-apps/pull/1607
- https://github.com/kiegroup/kogito-examples/pull/1549
=> KOGITO-8534 Update default Maven to 3.8.7

jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/coverter/CloneHelper.java, jbpm/jbpm-flow/src/test/java/org/jbpm/process/core/datatype/impl/coverter/CloneHelperTest.java
<details>
<summary>
</summary> …
=> [KOGITO-8536] Handling IllegalAccess different than Invocation exception

jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/JbpmBpmn2TestCase.java
**JIRA**: https://issues.redhat.com/browse/DROOLS-7317
=> [DROOLS-7317] unify SessionConfiguation and SessionConfiguationImpl

.ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-8550
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/797
- https://github.com/kiegroup/drools/pull/4956
- https://github.com/kiegroup/kogito-runtimes/pull/2773
- https://github.com/kiegroup/kogito-apps/pull/1612
- https://github.com/kiegroup/kogito-examples/pull/1552
=> KOGITO-8550 Generic Integration branch job

quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoQuarkusResourceUtils.java
See: https://issues.redhat.com/browse/KOGITO-8183
-- WIP --
We need to define with Quarkus team the correct mutable-jar/remote-dev behavior. It's working so far, but I still need to figure out a few things.
PRs:
- https://github.com/kiegroup/drools/pull/4895
<details>
<summary>
</summary> …
=> [KOGITO-8183] Add Mutable JAR and remote-dev support to Kogito applications

kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/resources/exec/switch-state-event-condition-timeouts-end.sw.json, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/resources/exec/switch-state-event-condition-timeouts-end.sw.yml, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/resources/exec/switch-state-event-condition-timeouts-transition.sw.json, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/resources/exec/switch-state-event-condition-timeouts-transition.sw.yml, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/resources/exec/switch-state-event-condition-timeouts-transition2.sw.json, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/resources/exec/switch-state-event-condition-timeouts-transition2.sw.yml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/SwitchStateEventConditionBasedIT.java, quarkus/test/src/main/java/org/kie/kogito/test/quarkus/kafka/KafkaTypedTestClient.java
<details>
<summary>
</summary> …
=> KOGITO-8552: Fix test issues in the SwitchStateEventConditionBasedIT

kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/asyncapi/AsyncChannelInfo.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/asyncapi/AsyncAPIInfoConverter.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/AssuredTestUtils.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/AsyncAPIIT.java
=> [KOGITO-8556] AsyncAPI now publish on the right topic

api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/recipient/http/HttpRecipient.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/recipient/http/HttpRecipientJsonPayloadData.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/recipient/http/HttpRecipientPayloadData.java
<details>
<summary>
</summary> …
=> KOGITO-8518: Add the ability to send json content as payload to the HttpRecpient and new API

.github/workflows/kogito-runtimes-pr.yml, .github/workflows/surefire.yml
JIRA: https://issues.redhat.com/browse/BXMSPROD-728
The idea is that after build chain is run, test reports will be archived in the PR check workflow. Upon completion of the PR check, a `workflow_run` will trigger a surefire workflow and analyze the test reports and publish annotations via check runs.
To be merged after: 
* https://github.com/kiegroup/kogito-pipelines/pull/783
=> [BXMSPROD-728] enable surefire report publishing

api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/Job.java, api/kogito-jobs-service-api/src/test/java/org/kie/kogito/jobs/service/api/event/serialization/JobCloudEventDeserializerTest.java, api/kogito-jobs-service-api/src/test/resources/org/kie/kogito/jobs/service/api/event/serialization/CreateJobEvent.json, api/kogito-jobs-service-api/src/test/resources/org/kie/kogito/jobs/service/api/event/serialization/CreateJobEventDataContent.json, quarkus/addons/jobs/knative-eventing/deployment/src/main/java/org/kie/kogito/jobs/knative/eventing/quarkus/deployment/KogitoAddOnJobsKnativeEventingProcessor.java, quarkus/addons/jobs/knative-eventing/deployment/src/test/java/org/kie/kogito/jobs/knative/eventing/quarkus/deployment/KogitoAddOnJobsKnativeEventingProcessorTest.java, quarkus/addons/jobs/management/deployment/src/main/java/org/kie/kogito/jobs/management/quarkus/deployment/KogitoAddOnJobsManagementProcessor.java, quarkus/addons/jobs/messaging/deployment/src/main/java/org/kie/kogito/jobs/messaging/quarkus/deployment/KogitoAddOnJobsMessagingProcessor.java
<details>
<summary>
</summary> …
=> KOGITO-8579: Public API States alignment

kogito-bom/pom.xml, kogito-build/kogito-build-no-bom-parent/pom.xml
**JIRA:** [KOGITO-8606](https://issues.redhat.com/browse/KOGITO-8606)
<details>
<summary>
</summary> …
=> KOGITO-8606 - Remove JavaDoc plugin from Kogito as it is not used

.ci/jenkins/dsl/jobs.groovy, .github/pull_request_template.md
[kogito-pipelines](https://github.com/kiegroup/kogito-pipelines/pull/796)
[kogito-apps](https://github.com/kiegroup/kogito-apps/pull/1613)
[kogito-runtimes](https://github.com/kiegroup/kogito-runtimes/pull/2778)
[kogito-examples](https://github.com/kiegroup/kogito-examples/pull/1554)
<details>
<summary>
</summary> …
=> [KOGITO-8377]: Merged native and mandrel checks

jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/DroolsDeclaredTypeSequenceFlowExpressionTest.java, jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/JbpmBpmn2TestCase.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/xml/XmlRuleFlowProcessDumper.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/xml/compiler/SemanticKnowledgeBuilderConfigurationImpl.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/xml/compiler/SemanticKnowledgeBuilderFactoryService.java, jbpm/jbpm-flow-builder/src/test/java/org/jbpm/integrationtests/ProcessUpgradeTest.java, jbpm/jbpm-flow-builder/src/test/java/org/jbpm/process/builder/JavaActionBuilderTest.java, jbpm/jbpm-flow-builder/src/test/java/org/jbpm/process/builder/JavaReturnValueConstraintEvaluatorBuilderTest.java, jbpm/jbpm-flow-builder/src/test/java/org/jbpm/process/builder/KnowledgeBuilderTest.java, jbpm/jbpm-flow-builder/src/test/java/org/jbpm/process/builder/MVELActionBuilderTest.java, jbpm/jbpm-flow-builder/src/test/java/org/jbpm/process/builder/MVELDecisionBuilderTest.java, jbpm/jbpm-flow-builder/src/test/java/org/jbpm/process/builder/MVELReturnValueConstraintEvaluatorBuilderTest.java, jbpm/jbpm-flow-builder/src/test/java/org/jbpm/test/util/AbstractBaseTest.java, jbpm/jbpm-flow-builder/src/test/java/org/jbpm/xml/DumperTestHelper.java, jbpm/jbpm-flow-builder/src/test/java/org/jbpm/xml/XmlPackageReaderTest.java
**JIRA**: https://issues.redhat.com/browse/DROOLS-7337
=> [DROOLS-7337] Options and Configuration improvement

quarkus/addons/tracing-decision/deployment/pom.xml, quarkus/addons/tracing-decision/deployment/src/main/java/org/kie/kogito/tracing/decision/quarkus/deployment/KogitoDevServicesProcessor.java, quarkus/extensions/kogito-quarkus-extension-spi/src/main/java/org/kie/kogito/quarkus/extensions/spi/deployment/KogitoDataIndexServiceAvailableBuildItem.java, quarkus/extensions/kogito-quarkus-extension-spi/src/main/java/org/kie/kogito/quarkus/extensions/spi/deployment/TrustyServiceAvailableBuildItem.java, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/resources/dev-templates/dataindex.html, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/resources/dev-templates/dataindex.html, quarkus/extensions/kogito-quarkus-workflow-extension-common/kogito-quarkus-workflow-common-deployment/src/main/java/org/kie/kogito/quarkus/workflow/deployment/AbstractDevServicesProcessor.java, quarkus/extensions/kogito-quarkus-workflow-extension-common/kogito-quarkus-workflow-common-deployment/src/main/java/org/kie/kogito/quarkus/workflow/deployment/devservices/DataIndexInMemoryContainer.java
Assembly:
- https://github.com/kiegroup/kogito-apps/pull/1633
- https://github.com/kiegroup/kogito-runtimes/pull/2809
=> KOGITO-8668 - Disable Data Index devservice when extension is present

quarkus/addons/process-svg/runtime/src/main/java/org/kie/kogito/svg/dataindex/QuarkusDataIndexClient.java, quarkus/addons/process-svg/runtime/src/main/java/org/kie/kogito/svg/rest/ProcessSvgResource.java, quarkus/addons/process-svg/runtime/src/test/java/org/kie/kogito/svg/dataindex/QuarkusDataIndexClientTest.java, quarkus/addons/process-svg/runtime/src/test/java/org/kie/kogito/svg/rest/ProcessSvgResourceTest.java
Assembly:
- https://github.com/kiegroup/kogito-examples/pull/1574
- https://github.com/kiegroup/kogito-runtimes/pull/2813
- https://github.com/kiegroup/kogito-apps/pull/1634
=> KOGITO-8680 - Move authentication handling to resource class

.github/workflows/pr-jenkins.yml
<details>
<summary>
</summary> …
=> changed jdk to 8

.ci/jenkins/dsl/jobs.groovy, .github/workflows/pr-jenkins.yml
https://issues.redhat.com/browse/KOGITO-8717
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/890
- https://github.com/kiegroup/drools/pull/5034
- https://github.com/kiegroup/kogito-runtimes/pull/2822
- https://github.com/kiegroup/kogito-apps/pull/1642
- https://github.com/kiegroup/kogito-examples/pull/1583
- https://github.com/kiegroup/optaplanner/pull/2640
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/851
- https://github.com/kiegroup/optaplanner-quickstarts/pull/524
=> KOGITO-8717 Enable sonarcloud on demand

kogito-build/kogito-dependencies-bom/pom.xml, quarkus/bom/pom.xml
Adding managed dependency for the extension to Kogito
See example here https://github.com/kiegroup/kogito-examples/pull/1584
=> [KOGITO-8565] Using embedded SQL extension for SWF IT

addons/common/source-files/src/main/java/org/kie/kogito/addon/source/files/SourceFile.java, addons/common/source-files/src/main/java/org/kie/kogito/addon/source/files/SourceFilesProvider.java, addons/common/source-files/src/main/java/org/kie/kogito/addon/source/files/SourceFilesProviderImpl.java, addons/common/source-files/src/test/java/org/kie/kogito/addon/source/files/SourceFilesProviderImplTest.java, kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/SourceFileCodegenBindEvent.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java, quarkus/addons/source-files/deployment/src/main/java/org/kie/kogito/addon/source/files/deployment/SourceFileCodegenBindListenerImpl.java, quarkus/addons/source-files/deployment/src/test/java/org/kie/kogito/addon/source/files/deployment/SourceFileCodegenBindListenerImplTest.java, quarkus/addons/source-files/runtime/src/main/java/org/kie/kogito/addon/source/files/SourceFilesResource.java, quarkus/addons/source-files/runtime/src/test/java/org/kie/kogito/addon/source/files/SourceFilesResourceTest.java
JIRA: https://issues.redhat.com/browse/KOGITO-8559
https://github.com/kiegroup/kogito-apps/pull/1643 depends on this PR.
-------------
<details>
<summary>
</summary> …
=> KOGITO-8559 Fixed issue in Source Files Add-on when dealing with large files

quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-integration-test-hot-reload/pom.xml, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-integration-test-hot-reload/src/test/java/io/quarkus/it/kogito/process/KogitoDevServiceTest.java
**JIRA:** [KOGITO-8727](https://issues.redhat.com/browse/KOGITO-8727)
Another option would be to use just:
```xml
<properties>
<data-index-ephemeral.image/>
</properties>
<systemPropertyVariables>
<quarkus.kogito.devservices.image-name>${data-index-ephemeral.image}</quarkus.kogito.devservices.image-name>
</systemPropertyVariables>
```
While it is much shorter and Quarkus is able to resolve such a property from system properties, it relies on the fact that `quarkus.kogito.devservices.image-name` is an `Optional<String>` which Quarkus treats as empty in case the property is declared without any value. In this case, the default image will be used as defined in the Quarkus extension. However, this requires to have quite a good knowledge of Quarkus configuration. Therefore, I find it more …
=> KOGITO-8727 - Allow to override image in the Data Index Dev Service test

quarkus/addons/knative/serving/runtime/src/test/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/KnativeServiceDiscoveryTestUtil.java, quarkus/addons/kubernetes/runtime/src/test/java/org/kie/kogito/addons/quarkus/k8s/KnativeServiceDiscoveryTest.java
Jira: https://issues.redhat.com/browse/KOGITO-8761
-------------
<details>
<summary>
</summary> …
=> KOGITO-8761 Reverted call to a new method that doesn't exist in Quarkus LTS

api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/Job.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/recipient/http/HttpRecipient.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/recipient/sink/SinkRecipient.java
<details>
<summary>
</summary> …
=> KOGITO-8597: Jobs Service OpenAPI document generation addings

.ci/jenkins/Jenkinsfile.promote
**JIRA**: [KOGITO-3135](https://issues.redhat.com/browse/KOGITO-3135)
[kogito-runtimes](https://github.com/kiegroup/kogito-runtimes/pull/2823)
[kogito-apps](https://github.com/kiegroup/kogito-apps/pull/1656)
[kogito-examples](https://github.com/kiegroup/kogito-examples/pull/1600)
Makes only sense to merge after https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/266 was merged
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of …
=> KOGITO-3135: creates release on GitHub

.ci/jenkins/Jenkinsfile.promote
<details>
<summary>
</summary> …
=> Path KOGITO-3135 - Create releases

.ci/environments/quarkus-3/before.sh, .ci/environments/quarkus-3/quarkus3.yml, .ci/jenkins/dsl/jobs.groovy
<details>
<summary>
</summary> …
=> KOGITO-8679 Quarkus 3 env preparation

kogito-build/kogito-dependencies-bom/pom.xml
**JIRA**:  
[https://issues.redhat.com/browse/RHDM-1958](https://issues.redhat.com/browse/RHDM-1958)
[https://issues.redhat.com/browse/RHPAM-4641](https://issues.redhat.com/browse/RHPAM-4641)
* https://github.com/kiegroup/kogito-runtimes/pull/2826
* https://github.com/kiegroup/kogito-runtimes/pull/2827
* https://github.com/kiegroup/kogito-runtimes/pull/2828
You can check Kiegroup organization repositories CI status from [Chain Status webpage](https://kiegroup.github.io/droolsjbpm-build-bootstrap/)
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could …
=> [1.13.x][RHPAM-4641] Upgrading RESTEasy version.

kogito-build/kogito-dependencies-bom/pom.xml
**JIRA**:  
[https://issues.redhat.com/browse/RHDM-1958](https://issues.redhat.com/browse/RHDM-1958)
[https://issues.redhat.com/browse/RHPAM-4641](https://issues.redhat.com/browse/RHPAM-4641)
* https://github.com/kiegroup/kogito-runtimes/pull/2826
* https://github.com/kiegroup/kogito-runtimes/pull/2827
* https://github.com/kiegroup/kogito-runtimes/pull/2828
You can check Kiegroup organization repositories CI status from [Chain Status webpage](https://kiegroup.github.io/droolsjbpm-build-bootstrap/)
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could …
=> [RHPAM-4641] Upgrading RESTEasy version.

.ci/environments/quarkus-3/before.sh
- https://github.com/kiegroup/drools/pull/5075
- https://github.com/kiegroup/kogito-pipelines/pull/914
- https://github.com/kiegroup/kogito-runtimes/pull/2862
- https://github.com/kiegroup/kogito-apps/pull/1663
- https://github.com/kiegroup/kogito-examples/pull/1608
=> Quarkus 3: Updated version to Alpha5

kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandler.java, kogito-workitems/kogito-rest-workitem/src/test/java/org/kogito/workitem/rest/RestWorkItemHandlerTest.java
As proposed on [JIRA ](https://issues.redhat.com/browse/KOGITO-8845)
=> [KOGITO-8845] RestWorkItemHandler does not use proper VariableScope

kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/types/RestTypeHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/ServerlessWorkflowUtils.java, kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandler.java
This allow setting global http port for all functions through property
=> [KOGITO-8846] Add kogito.sw.fucntions.port property

jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/node/AsyncEventNodeInstance.java, kogito-bom/pom.xml, quarkus/addons/jobs/common/rest-callback/src/main/java/org/kie/kogito/jobs/quarkus/common/CallbackJobsServiceResource.java, quarkus/addons/jobs/common/rest-callback/src/test/java/org/kie/kogito/jobs/quarkus/common/CallbackJobsServiceResourceTest.java, quarkus/addons/jobs/management/runtime/src/main/java/org/kie/kogito/jobs/management/quarkus/VertxJobsService.java
<details>
<summary>
</summary> …
=> [KOGITO-8609] Job service embedded quarkus addon

kogito-serverless-workflow/kogito-serverless-workflow-executor/src/main/java/org/kie/kogito/serverless/workflow/fluent/ActionBuilder.java, kogito-serverless-workflow/kogito-serverless-workflow-executor/src/main/java/org/kie/kogito/serverless/workflow/fluent/BranchActionBuilder.java, kogito-serverless-workflow/kogito-serverless-workflow-executor/src/main/java/org/kie/kogito/serverless/workflow/fluent/ParallelStateBuilder.java, kogito-serverless-workflow/kogito-serverless-workflow-executor/src/test/java/org/kie/kogito/serverless/workflow/executor/StaticFluentWorkflowApplicationTest.java
<details>
<summary>
</summary> …
=> [KOGITO-8855] Adding subprocess support

jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/node/AsyncEventNodeInstance.java, kogito-build/kogito-dependencies-bom/pom.xml, quarkus/addons/jobs/common/rest-callback/src/test/java/org/kie/kogito/jobs/quarkus/common/CallbackJobsServiceResourceTest.java, quarkus/addons/persistence/jdbc/runtime/src/main/java/org/kie/kogito/persistence/quarkus/KogitoAddOnPersistenceJDBCConfigSource.java
https://github.com/kiegroup/kogito-runtimes/pull/2883
https://github.com/kiegroup/kogito-apps/pull/1677
https://github.com/kiegroup/kogito-examples/pull/1614
<details>
<summary>
</summary> …
=> [KOGITO-8795] Use different datasources on embedded addons for data-index and job service

kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java
Jira: https://issues.redhat.com/browse/KOGITO-8813
-------------
<details>
<summary>
</summary> …
=> KOGITO-8813 Improved message about compensation nodes transition

kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/types/JavaTypeHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/resources/META-INF/services/org.kie.kogito.serverless.workflow.parser.FunctionTypeHandler, kogito-serverless-workflow/kogito-serverless-workflow-executor/src/main/java/org/kie/kogito/serverless/workflow/executor/JavaFunctionExtension.java, kogito-serverless-workflow/kogito-serverless-workflow-executor/src/main/java/org/kie/kogito/serverless/workflow/executor/StaticFunctionWorkItemHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-executor/src/main/java/org/kie/kogito/serverless/workflow/executor/StaticWorkflowApplication.java, kogito-serverless-workflow/kogito-serverless-workflow-executor/src/main/java/org/kie/kogito/serverless/workflow/fluent/FunctionBuilder.java, kogito-serverless-workflow/kogito-serverless-workflow-executor/src/main/java/org/kie/kogito/serverless/workflow/fluent/FunctionDefinitionEx.java, kogito-serverless-workflow/kogito-serverless-workflow-executor/src/main/java/org/kie/kogito/serverless/workflow/fluent/WorkflowBuilder.java, kogito-serverless-workflow/kogito-serverless-workflow-executor/src/test/java/org/kie/kogito/serverless/workflow/executor/StaticFluentWorkflowApplicationTest.java
Supporting direct java function
This uses a new custom type, called Java, to support direct method invocations.
=> [KOGITO-8878] Supporting java function

kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/types/ServiceTypeHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/WorkItemBuilder.java, kogito-serverless-workflow/kogito-serverless-workflow-executor/src/test/java/org/kie/kogito/serverless/workflow/executor/StaticFluentWorkflowApplicationTest.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/WorkflowWorkItemHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/workitemparams/ExpressionWorkItemResolver.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/workitemparams/ObjectResolver.java, kogito-workitems/kogito-jackson-utils/src/main/java/org/kie/kogito/jackson/utils/JsonObjectUtils.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/java/org/kie/kogito/workflows/services/SquareService.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/squareService.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/PojoServiceIT.java
As described in the JIRA, array items were not evaluated as expressions.
=> [KOGITO-8889] Supporting expression in array items

kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ServerlessWorkflowParser.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/ServerlessWorkflowUtils.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/WorkflowFormat.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/AbstractServerlessWorkflowParsingTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/utils/WorkflowUtilsTest.java, kogito-serverless-workflow/kogito-serverless-workflow-executor/src/main/java/org/kie/kogito/serverless/workflow/executor/StaticFunctionWorkItemHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-executor/src/main/java/org/kie/kogito/serverless/workflow/fluent/ActionBuilder.java, kogito-serverless-workflow/kogito-serverless-workflow-executor/src/main/java/org/kie/kogito/serverless/workflow/fluent/WorkflowBuilder.java, kogito-serverless-workflow/kogito-serverless-workflow-executor/src/test/java/org/kie/kogito/serverless/workflow/executor/StaticFluentWorkflowApplicationTest.java, kogito-serverless-workflow/kogito-serverless-workflow-executor/src/test/java/org/kie/kogito/serverless/workflow/executor/StaticWorkflowApplicationTest.java
Adding writer method to ServerlessWorkflowUtils. 
https://github.com/kiegroup/kogito-runtimes/pull/2890/files#diff-11bd63aaa4e3eb1407f4688616a2b87250f45cc4467541eaa6d7156d16157e69R108
=> [KOGITO-8903] Adding workflow writer utility

api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/Job.java, api/kogito-jobs-service-api/src/test/java/org/kie/kogito/jobs/service/api/event/TestConstants.java, api/kogito-jobs-service-api/src/test/java/org/kie/kogito/jobs/service/api/event/serialization/JobCloudEventDeserializerTest.java, api/kogito-jobs-service-api/src/test/java/org/kie/kogito/jobs/service/api/event/serialization/JobCloudEventSerializerTest.java, api/kogito-jobs-service-api/src/test/resources/org/kie/kogito/jobs/service/api/event/serialization/CreateJobEvent.json, api/kogito-jobs-service-api/src/test/resources/org/kie/kogito/jobs/service/api/event/serialization/CreateJobEventDataContent.json
<details>
<summary>
</summary> …
=> KOGITO-8630: Http Recipient timeout set from the API

.ci/jenkins/Jenkinsfile.promote
<details>
<summary>
</summary> …
=> Promote Release: Fix setup data-index image tag

kogito-serverless-workflow/kogito-serverless-workflow-executor/src/main/java/org/kie/kogito/serverless/workflow/fluent/FunctionBuilder.java
I merged the previous one without removing code smells
=> [KOGITO-8923] Removing leftover generic

kogito-serverless-workflow/kogito-serverless-workflow-executor/src/main/java/org/kie/kogito/serverless/workflow/fluent/ActionBuilder.java, kogito-serverless-workflow/kogito-serverless-workflow-executor/src/main/java/org/kie/kogito/serverless/workflow/fluent/WorkflowBuilder.java, kogito-serverless-workflow/kogito-serverless-workflow-executor/src/test/java/org/kie/kogito/serverless/workflow/executor/StaticFluentWorkflowApplicationTest.java
<details>
<summary>
</summary> …
=> [KOGITO-8930] Renaming objetNode and arrayNode methods

jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/DummyKnowledgeRuntime.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/KogitoProcessRuntimeImpl.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessRuntimeImpl.java
Related PRs:
https://github.com/kiegroup/drools/pull/5141
https://github.com/kiegroup/kogito-runtimes/pull/2912
=> improve globals for reliable session + minor refactor

jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/factory/ForEachNodeFactory.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ServerlessWorkflowParser.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/ForEachStateHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/ServerlessWorkflowUtils.java, kogito-serverless-workflow/kogito-serverless-workflow-executor/src/test/java/org/kie/kogito/serverless/workflow/executor/StaticFluentWorkflowApplicationTest.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/main/java/org/kie/kogito/serverless/workflow/utils/KogitoProcessContextResolver.java
=> [KOGITO-8928] Allow actions in for each to access result of prev one

.ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-8951
Related PRs:
- https://github.com/kiegroup/kogito-runtimes/pull/2916
- https://github.com/kiegroup/kogito-apps/pull/1688
- https://github.com/kiegroup/kogito-examples/pull/1628
=> [KOGITO-8951] Quarkus 3: Temporary disabling checks

quarkus/addons/knative/serving/runtime/src/test/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/KnativeServerlessWorkflowCustomFunctionTest.java, quarkus/addons/kubernetes/runtime/src/test/java/org/kie/kogito/addons/quarkus/k8s/discovery/KnativeServiceDiscoveryTest.java, quarkus/addons/kubernetes/test-utils/src/main/java/org/kie/kogito/addons/quarkus/k8s/test/utils/KnativeResourceDiscoveryTestUtil.java
Jira: https://issues.redhat.com/browse/KOGITO-8759
-----------
<details>
<summary>
</summary> …
=> KOGITO-8759 Changed KnativeResourceDiscoveryTestUtil#createServiceIfNotExists to return void

quarkus/addons/kubernetes/runtime/src/main/java/org/kie/kogito/addons/quarkus/k8s/KubernetesProtocol.java, quarkus/addons/kubernetes/runtime/src/main/java/org/kie/kogito/addons/quarkus/k8s/config/ConfigValueExpander.java, quarkus/addons/kubernetes/runtime/src/main/java/org/kie/kogito/addons/quarkus/k8s/config/KubeDiscoveryConfigCache.java, quarkus/addons/kubernetes/runtime/src/main/java/org/kie/kogito/addons/quarkus/k8s/config/KubeDiscoveryConfigSourceInterceptor.java, quarkus/addons/kubernetes/runtime/src/test/java/org/kie/kogito/addons/quarkus/k8s/config/ConfigValueExpanderTest.java
Jira: https://issues.redhat.com/browse/KOGITO-8956
----------
<details>
<summary>
</summary> …
=> KOGITO-8956 Changed KubeDiscoveryConfigSourceInterceptor to ignore properties that are not used for discovery

api/kogito-api/src/main/java/org/kie/kogito/internal/utils/ConversionUtils.java, api/kogito-api/src/test/java/org/kie/kogito/internal/utils/ConversionUtilsTest.java
Fixes https://github.com/kiegroup/kie-issues/issues/156. 
- When the convert method is executed on IBM JDK, the order of iteration of methods is different. For Integer, the original implementation picked a wrong method (Integer.getInteger()), which caused a wrong behaviour and test fail. 
- This PR uses valueOf() method specifically for numbers. 
- Adds more tests for various number types. 
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to …
=> [kie-issues-156] Use specific conversion method for numbers

api/kogito-api/src/main/java/org/kie/kogito/internal/utils/ConversionUtils.java, api/kogito-api/src/test/java/org/kie/kogito/internal/utils/ConversionUtilsTest.java
Small refactor to make fix shorted and better integrated with existing code
=> [kie-issues-156] Follow up PR

api/kogito-api/src/main/java/org/kie/kogito/internal/utils/ConversionUtils.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcess.java, kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/java/org/kie/kogito/codegen/tests/SubProcessIT.java, quarkus/integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/main/resources/HelloProcess.bpmn, quarkus/integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/main/resources/ReusableSubProcessWithServiceTaks.bpmn, quarkus/integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/main/resources/application.properties, quarkus/integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-processes-persistence-common/src/test/java/org/kie/kogito/it/PersistenceTest.java, quarkus/integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-jdbc/src/main/resources/application.properties, quarkus/integration-tests/integration-tests-quarkus-processes-persistence/integration-tests-quarkus-processes-postgresql/src/main/resources/application.properties
<details>
<summary>
</summary> …
=> [KOGITO-7945] Service Task hangs infinitely in the active state if it is after a subprocess

quarkus/addons/kubernetes/runtime/src/main/java/org/kie/kogito/addons/quarkus/k8s/config/ServiceDiscoveryConfigBuilder.java
Jira: https://issues.redhat.com/browse/KOGITO-8983
--------------
<details>
<summary>
</summary> …
=> KOGITO-8983 Registered ServiceDiscoveryConfigBuilder for reflection

quarkus/addons/kubernetes/runtime/src/test/java/org/kie/kogito/addons/quarkus/k8s/config/KubeDiscoveryConfigCacheUpdaterTest.java
Jira: https://issues.redhat.com/browse/KOGITO-8443
This PR only adds tests for the requested feature, since that feature was automatically implemented as a consequence of https://github.com/kiegroup/kogito-runtimes/pull/2889.
PR to update docs:
- https://github.com/kiegroup/kogito-docs/pull/326
----------------
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the …
=> KOGITO-8443 Added tests for Knative to property expansion

addons/common/events/decisions/pom.xml, addons/common/events/mongodb/pom.xml, addons/common/events/predictions/pom.xml, addons/common/explainability/pom.xml, addons/common/persistence/mongodb/pom.xml, kogito-serverless-workflow/kogito-jq-expression/pom.xml, kogito-serverless-workflow/kogito-jsonpath-expression/pom.xml, kogito-serverless-workflow/kogito-serverless-workflow-executor/pom.xml, kogito-serverless-workflow/kogito-serverless-workflow-runtime/pom.xml, quarkus/addons/knative/eventing/deployment/pom.xml, quarkus/addons/knative/serving/runtime/pom.xml, quarkus/extensions/kogito-quarkus-workflow-extension-common/kogito-quarkus-workflow-common-deployment/pom.xml, quarkus/integration-tests/integration-tests-quarkus-processes-reactive/pom.xml
Depends on https://github.com/kiegroup/drools/pull/5179
=> [KOGITO-9022] Include assertj-core in missing poms

addons/common/persistence/infinispan/src/main/java/org/kie/kogito/infinispan/CacheProcessInstances.java, addons/common/persistence/pom.xml, addons/common/persistence/rocksdb/pom.xml, addons/common/persistence/rocksdb/src/main/java/org/kie/kogito/persistence/rocksdb/RocksDBProcessInstances.java, addons/common/persistence/rocksdb/src/main/java/org/kie/kogito/persistence/rocksdb/RocksDBProcessInstancesFactory.java, addons/common/persistence/rocksdb/src/main/resources/META-INF/kogito.addon, addons/common/persistence/rocksdb/src/test/java/org/kie/kogito/persistence/rocksdb/RockDBProcessInstancesTest.java, addons/common/persistence/rocksdb/src/test/resources/BPMN2-UserTask.bpmn2, addons/common/persistence/rocksdb/src/test/resources/logback-test.xml, kogito-bom/pom.xml, kogito-build/kogito-dependencies-bom/pom.xml
The most anticipated addon ever ;)
The quarkus addon (basically produce the ProcessInstanceFactory and checking native mode) will be done with a follow up PR
=> [KOGITO-8566] RocksDB addon

.ci/jenkins/dsl/jobs.groovy
- https://github.com/kiegroup/kogito-pipelines/pull/944
- https://github.com/kiegroup/kogito-runtimes/pull/2944
- https://github.com/kiegroup/kogito-apps/pull/1703
- https://github.com/kiegroup/kogito-examples/pull/1645
=> Quarkus3: Remove PR checks until stable

quarkus/addons/persistence/jdbc/runtime/pom.xml, quarkus/addons/persistence/jdbc/runtime/src/main/java/org/kie/kogito/persistence/quarkus/KogitoAddOnPersistenceJDBCConfigSourceFactory.java, quarkus/addons/persistence/jdbc/runtime/src/test/java/org/kie/kogito/persistence/quarkus/KogitoAddOnPersistenceJDBCConfigSourceFactoryTest.java
Jira: https://issues.redhat.com/browse/KOGITO-9021
---------
<details>
<summary>
</summary> …
=> KOGITO-9021 Added support for existing "quarkus.flyway.locations" property values

addons/common/persistence/rocksdb/src/main/java/org/kie/kogito/persistence/rocksdb/RocksDBProcessInstancesFactory.java, kogito-bom/pom.xml, quarkus/addons/persistence/pom.xml, quarkus/addons/persistence/rocksdb/deployment/pom.xml, quarkus/addons/persistence/rocksdb/deployment/src/main/java/org/kie/kogito/persistence/quarkus/rocksdb/KogitoAddOnPersistenceRocksDBProcessor.java, quarkus/addons/persistence/rocksdb/pom.xml, quarkus/addons/persistence/rocksdb/runtime/pom.xml, quarkus/addons/persistence/rocksdb/runtime/src/main/java/org/kie/kogito/persistence/quarkus/rocksdb/RocksDbConfig.java, quarkus/addons/persistence/rocksdb/runtime/src/main/java/org/kie/kogito/persistence/quarkus/rocksdb/RocksDbProcessInstancesFactoryProducer.java, quarkus/addons/persistence/rocksdb/runtime/src/main/resources/META-INF/quarkus-extension.yaml
Rockds db addon for quarkus. 
See modified example for testing it https://github.com/kiegroup/kogito-examples/pull/1648
=> [KOGITO-9029] Rocksdb addon for quarkus

jbpm/jbpm-flow-builder/src/test/java/org/jbpm/compiler/canonical/ProcessToExecModelGeneratorTest.java, jbpm/jbpm-flow/pom.xml, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/validation/RuleFlowProcessValidator.java, kogito-codegen-modules/kogito-codegen-processes/pom.xml, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/JavaRuleFlowProcessValidator.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java, kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/process/JavaRuleFlowProcessValidatorTest.java
The java invalid variable check has been moved from runtime validation to codegen validation
=> [KOGITO-9049] Remove javaparser dependency from jbpm-flow

quarkus/addons/knative/serving/runtime/src/main/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/KnativeServiceRegistry.java, quarkus/addons/knative/serving/runtime/src/test/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/KnativeServerlessWorkflowCustomFunctionTest.java
Jira: https://issues.redhat.com/browse/KOGITO-9030
PR to update the examples:
- https://github.com/kiegroup/kogito-examples/pull/1644
This PR lays the groundwork for https://issues.redhat.com/browse/KOGITO-8766
-------
<details>
<summary>
</summary>
[build-chain …
=> KOGITO-9030 Added support for full GVK to Knative custom function

.ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-9075
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/949
- https://github.com/kiegroup/drools/pull/5203
- https://github.com/kiegroup/kogito-apps/pull/1710
- https://github.com/kiegroup/kogito-runtimes/pull/2955
- https://github.com/kiegroup/kogito-examples/pull/1651
=> KOGITO-9075 Correct Build Mvn Opts override

kogito-build/kogito-dependencies-bom/pom.xml
https://issues.redhat.com/browse/RHPAM-4638
<details>
<summary>
</summary> …
=> RHPAM-4638 version.com.thoughtworks.xstream to 1.4.20

kogito-build/kogito-dependencies-bom/pom.xml, springboot/bom/pom.xml
**JIRA**: 
- https://issues.redhat.com/browse/RHPAM-4536
Kogito runtimes is still depending on `snakeyaml:1.28` due to :
- `spring-boot-starter:2.5.x`
```
[INFO]    \- org.springframework.boot:spring-boot-starter-web:jar:2.5.12:compile
[INFO]       +- org.springframework.boot:spring-boot-starter:jar:2.5.12:compile
....
[INFO]       |  \- org.yaml:snakeyaml:jar:1.28:compile
```
- `jackson-dataformat-yaml:2.13.1`
```
[INFO] +- org.kie.kogito:kogito-cloud-kubernetes-client:jar:1.13.1-SNAPSHOT:compile
[INFO] |  \- io.fabric8:kubernetes-client:jar:5.12.4:compile
....
[INFO] |     +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.13.1:compile
[INFO] |     |  \- org.yaml:snakeyaml:jar:1.28:compile
```
Since there is no …
=> [1.13.x][RHPAM-4536] upgrade snakeyaml to 1.33 and jackson to 2.14.2

kogito-build/kogito-dependencies-bom/pom.xml, springboot/bom/pom.xml
**Backport:** https://github.com/kiegroup/kogito-runtimes/pull/2960
**JIRA:**
- https://issues.redhat.com/browse/RHPAM-4695
<details>
<summary>
</summary>
[build-chain …
=> [1.13.x-blue][RHPAM-4695] upgrade snakeyaml to 1.33 and jackson to 2.14.2

.ci/environments/quarkus-3/before.sh, .ci/environments/quarkus-3/patches/0001_before_sh.patch, .ci/environments/quarkus-3/patches/0016_update_dependencies_version.patch, .ci/environments/quarkus-3/quarkus3.yml, .ci/jenkins/Jenkinsfile.quarkus-3.rewrite.standalone, .ci/jenkins/dsl/jobs.groovy
Somehow it was missing ...
- https://github.com/kiegroup/drools/pull/5219
- https://github.com/kiegroup/kogito-runtimes/pull/2969
=> Quarkus 3: Update script to 3.0.0.Final

kogito-build/kogito-dependencies-bom/pom.xml
Related to https://github.com/kiegroup/kogito-runtimes/pull/2956
https://issues.redhat.com/browse/RHPAM-4638
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you …
=> [1.13.x-blue][RHPAM-4638] version.com.thoughtworks.xstream to 1.4.20

addons/common/jobs/api/src/main/java/org/kie/kogito/jobs/api/JobCallbackPayload.java, addons/common/jobs/api/src/main/java/org/kie/kogito/jobs/api/JobCallbackResourceDef.java, addons/common/jobs/api/src/main/java/org/kie/kogito/jobs/api/utils/ReflectionUtils.java, addons/common/jobs/api/src/test/java/org/kie/kogito/jobs/api/JobCallbackResourceDefTest.java, addons/common/jobs/management-common/src/main/java/org/kie/kogito/jobs/management/RestJobsService.java, addons/common/jobs/management-common/src/test/java/org/kie/kogito/jobs/management/RestJobsServiceTest.java, quarkus/addons/jobs/common/messaging/src/main/java/org/kie/kogito/jobs/messaging/quarkus/AbstractReactiveMessagingJobsService.java, quarkus/addons/jobs/common/messaging/src/test/java/org/kie/kogito/jobs/messaging/quarkus/AbstractReactiveMessagingJobsServiceTest.java, quarkus/addons/jobs/common/rest-callback/src/main/java/org/kie/kogito/jobs/quarkus/common/CallbackJobsServiceResource.java, quarkus/addons/jobs/knative-eventing/deployment/src/main/java/org/kie/kogito/jobs/knative/eventing/quarkus/deployment/KogitoAddOnJobsKnativeEventingProcessor.java, quarkus/addons/jobs/knative-eventing/deployment/src/test/java/org/kie/kogito/jobs/knative/eventing/quarkus/deployment/KogitoAddOnJobsKnativeEventingProcessorTest.java, quarkus/addons/jobs/management/deployment/src/main/java/org/kie/kogito/jobs/management/quarkus/deployment/KogitoAddOnJobsManagementProcessor.java, quarkus/addons/jobs/management/deployment/src/test/java/org/kie/kogito/jobs/management/quarkus/deployment/KogitoAddOnJobsManagementProcessorTest.java, quarkus/addons/jobs/management/runtime/src/main/java/org/kie/kogito/jobs/management/quarkus/VertxJobsService.java, quarkus/addons/jobs/management/runtime/src/test/java/org/kie/kogito/jobs/management/quarkus/VertxJobsServiceTest.java, quarkus/addons/jobs/messaging/deployment/src/main/java/org/kie/kogito/jobs/messaging/quarkus/deployment/KogitoAddOnJobsMessagingProcessor.java, quarkus/addons/jobs/messaging/deployment/src/test/java/org/kie/kogito/jobs/messaging/quarkus/deployment/KogitoAddOnJobsMessagingProcessorTest.java, springboot/addons/jobs/src/main/java/org/kie/kogito/jobs/management/springboot/CallbackJobsServiceResource.java, springboot/addons/jobs/src/main/java/org/kie/kogito/jobs/management/springboot/SpringRestJobsService.java
- quarkus native build fixes
<details>
<summary>
</summary> …
=> KOGITO-9007: StateBasedNodeInstance not working with multiple instances es including timers (native build)

kogito-bom/pom.xml
**JIRA:** [KOGITO-9111](https://issues.redhat.com/browse/KOGITO-9111)
<details>
<summary>
</summary> …
=> KOGITO-9111 - kogito-bom references non-existing artifacts

quarkus/addons/knative/serving/runtime/src/main/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/KnativeServiceRequestClient.java, quarkus/addons/knative/serving/runtime/src/main/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/PlainJsonKnativeServiceRequestClient.java, quarkus/addons/knative/serving/runtime/src/test/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/KnativeServerlessWorkflowCustomFunctionTest.java
There are also problems when sending json array as body in a post
=> [KOGIGO-9149] Support arrays as knative response

jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/DataTypeResolver.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/datatype/impl/type/EnumDataType.java, jbpm/jbpm-flow/src/test/java/org/jbpm/process/core/datatype/DataTypeResolverTest.java
New constructor that accepts enum class.
=> [KOGITO-6583] Enhacing enum data type

.ci/environments/quarkus-3/before.sh, .ci/environments/quarkus-3/patches/0021_spring_boot_remove_keycloak_adapter.patch, .ci/environments/quarkus-3/project-recipe.yml, .ci/jenkins/Jenkinsfile.quarkus-3.rewrite.pr, .ci/jenkins/Jenkinsfile.quarkus-3.rewrite.standalone, .ci/jenkins/dsl/jobs.groovy
Related:
- https://github.com/kiegroup/drools/pull/5200
- https://github.com/kiegroup/kogito-runtimes/pull/2962
- https://github.com/kiegroup/kogito-apps/pull/1707
- https://github.com/kiegroup/kogito-apps/pull/1707
=> [KOGITO-9061] Quarkus 3: Corrections

.ci/environments/quarkus-3/patches/0016_update_dependencies_version.patch
<details>
<summary>
</summary> …
=> Quarkus 3: Fix dependencies bom patch

quarkus/addons/knative/serving/runtime/src/main/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/Operation.java, quarkus/addons/knative/serving/runtime/src/test/java/org/kie/kogito/addons/quarkus/knative/serving/customfunctions/OperationTest.java
Jira: https://issues.redhat.com/browse/KOGITO-9183
------------
<details>
<summary>
</summary> …
=> KOGITO-9183 Removed org.kie.kogito.addons.quarkus.knative.serving.customfunctions.Operation#namespace

.ci/environments/quarkus-3/patches/0013_kube_addon.patch, .ci/environments/quarkus-3/patches/0015_javax.inject_to_jakarta.inject-api.deps.patch
<details>
<summary>
</summary> …
=> Quarkus 3: Fix patches

quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/DivisionMockService.java
=> [KOGITO-9167] Fixing native test error

quarkus/integration-tests/integration-tests-quarkus-legacy-rules/src/main/java/org/kie/kogito/legacy/rules/TmsEndpoint.java
<details>
<summary>
</summary> …
=> Fixing formatting issue

addons/common/pom.xml, quarkus/addons/jobs/pom.xml, quarkus/addons/pom.xml
**JIRA:** https://issues.redhat.com/browse/BXMSPROD-2055
**Referenced Pull Requests:**
- https://github.com/kiegroup/kogito-runtimes/pull/3003
- https://github.com/kiegroup/kogito-apps/pull/1724
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the …
=> [BXMSPROD-2055] include jobs in prod profile

kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/main/java/org/kie/kogito/serverless/workflow/executor/StaticWorkflowApplication.java
I was not happy with the quick implementation I did for StaticApplication.awaitTermination
=> [KOGITO-9214] Remove polling in waitForFinish

kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/test/java/org/kie/kogito/serverless/workflow/executor/StaticFluentWorkflowApplicationTest.java, kogito-serverless-workflow/kogito-serverless-workflow-fluent/src/main/java/org/kie/kogito/serverless/workflow/fluent/ActionBuilder.java, kogito-serverless-workflow/kogito-serverless-workflow-fluent/src/main/java/org/kie/kogito/serverless/workflow/fluent/ConditionTransitionBuilder.java, kogito-serverless-workflow/kogito-serverless-workflow-fluent/src/main/java/org/kie/kogito/serverless/workflow/fluent/DefaultConditionTransitionBuilder.java, kogito-serverless-workflow/kogito-serverless-workflow-fluent/src/main/java/org/kie/kogito/serverless/workflow/fluent/EventBranchBuilder.java, kogito-serverless-workflow/kogito-serverless-workflow-fluent/src/main/java/org/kie/kogito/serverless/workflow/fluent/EventDefBuilder.java, kogito-serverless-workflow/kogito-serverless-workflow-fluent/src/main/java/org/kie/kogito/serverless/workflow/fluent/FunctionBuilder.java, kogito-serverless-workflow/kogito-serverless-workflow-fluent/src/main/java/org/kie/kogito/serverless/workflow/fluent/StateBuilder.java, kogito-serverless-workflow/kogito-serverless-workflow-fluent/src/main/java/org/kie/kogito/serverless/workflow/fluent/TransitionBuilder.java, kogito-serverless-workflow/kogito-serverless-workflow-fluent/src/main/java/org/kie/kogito/serverless/workflow/fluent/WorkflowBuilder.java
Allow reusing of state builders by tracking the number of times build is invoked
=> [KOGITO-9208] Reusing state builders

.ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-9221
- https://github.com/kiegroup/kogito-pipelines/pull/974
- https://github.com/kiegroup/drools/pull/5251
- https://github.com/kiegroup/kogito-runtimes/pull/3015
- https://github.com/kiegroup/kogito-apps/pull/1731
- https://github.com/kiegroup/kogito-examples/pull/1674
=> KOGITO-9221 Quarkus 3: Setup main nightly pipeline

jbpm/jbpm-flow-builder/src/main/resources/class-templates/RestWorkItemHandlerTemplate.java, kogito-serverless-workflow/kogito-serverless-workflow-executor-rest/src/main/java/org/kie/kogito/serverless/workflow/executor/StaticRestWorkItemHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-executor-rest/src/test/java/org/kie/kogito/serverless/workflow/executor/RestFluentWorkflowApplicationTest.java, kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandler.java, kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandlerUtils.java, kogito-workitems/kogito-rest-workitem/src/test/java/org/kogito/workitem/rest/RestWorkItemHandlerTest.java, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/pom.xml, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/src/main/java/org/kie/kogito/quarkus/runtime/SSLWebClientOptionsProducer.java, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes/pom.xml, quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes/src/main/java/org/kie/kogito/quarkus/processes/SSLWebClientOptionsProducer.java, springboot/starters/kogito-processes-spring-boot-starter/pom.xml, springboot/starters/kogito-processes-spring-boot-starter/src/main/java/org/kie/kogito/process/KogitoBeanProducer.java
The lack of ssl support for RestWorkItemHadler was found during Parodos integration exercise
=> [KOGITO-9220] Adding ssl client to RestWorkItemHandler

kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/types/SysOutTypeHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/test/java/org/kie/kogito/serverless/workflow/executor/StaticFluentWorkflowApplicationTest.java
=> [KOGITO-9216] Fixing missing message exception

jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/expr/Expression.java, kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqExpression.java, kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqExpressionHandler.java, kogito-serverless-workflow/kogito-jsonpath-expression/src/main/java/org/kie/kogito/expr/jsonpath/JsonPathExpression.java, kogito-serverless-workflow/kogito-jsonpath-expression/src/main/java/org/kie/kogito/expr/jsonpath/JsonPathExpressionHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/suppliers/SysoutActionSupplier.java, kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/test/java/org/kie/kogito/serverless/workflow/executor/StaticFluentWorkflowApplicationTest.java, kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/test/resources/interpolation.sw.json, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/actions/SysoutAction.java
Expression is validated at parsing time
Hardcoded single words (which are not equal to a jq predefined function) are properly printed.
=> [KOGITO-9234] Improve expression evaluation in sysout

kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessResourceGenerator.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/TagResourceGenerator.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/deployment/ServerlessWorkflowAssetsProcessor.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/openapi/ServerlessWorkflowOASFilter.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/serverless/workflow/parser/schema/OpenApiModelSchemaGenerator.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/pom.xml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/schema/expressionInput.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/schema/expressionOutput.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/SwaggerIT.java
=> [KOGITO-9157] Tag grouping

.github/workflows/pr-backporting.yml, .github/workflows/pr-downstream.yml, .github/workflows/pr-jenkins.yml, .github/workflows/pr-kogito-runtimes.yml
Related PR:
- https://github.com/kiegroup/kie-ci/pull/1495
=> Updating references to the new kie-ci actions folder.

.ci/environments/quarkus-3/patches/0022_spring_boot_it_fix.patch
<details>
<summary>
</summary> …
=> Quarkus 3: Added Spring Boot IT fix

jbpm/jbpm-flow/src/test/java/org/jbpm/test/util/AbstractBaseTest.java
This PR is needed as a result of https://github.com/kiegroup/drools/pull/5244
=> DROOLS-7450 Split kbase from core

.ci/environments/quarkus-3/patches/0018_spring_boot_archetype_fix.patch, .ci/environments/quarkus-3/patches/0023_springboot_webflux.patch
<details>
<summary>
</summary> …
=> Quarkus 3: Spring Boot archetype fix

kogito-build/kogito-dependencies-bom/pom.xml, kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/AbstractKieMojo.java
Fixes: 
- https://github.com/kiegroup/kie-issues/issues/292
- https://github.com/kiegroup/kie-issues/issues/293
- https://github.com/kiegroup/kie-issues/issues/294
Fixes three CVEs in kogito-runtimes. 
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build …
=> [kie-issues#292,kie-issues#293,kie-issues#294] Fix of CVE-2018-10237, CVE-2023-25194, CVE-2022-34169

quarkus/addons/jobs/knative-eventing/deployment/src/main/java/org/kie/kogito/jobs/knative/eventing/quarkus/deployment/KogitoAddOnJobsKnativeEventingProcessor.java, quarkus/addons/jobs/knative-eventing/deployment/src/test/java/org/kie/kogito/jobs/knative/eventing/quarkus/deployment/KogitoAddOnJobsKnativeEventingProcessorTest.java, quarkus/addons/knative/eventing/deployment/src/main/java/org/kie/kogito/addons/quarkus/knative/eventing/deployment/KogitoAddOnKnativeEventingProcessor.java, quarkus/addons/knative/eventing/deployment/src/test/java/org/kie/kogito/addons/quarkus/knative/eventing/deployment/KogitoAddOnKnativeEventingProcessorTest.java, quarkus/addons/knative/eventing/integration-tests/pom.xml, quarkus/addons/knative/eventing/integration-tests/src/main/resources/application.properties, quarkus/addons/knative/eventing/integration-tests/src/main/resources/hello.sw.json, quarkus/addons/knative/eventing/integration-tests/src/test/java/org/kie/kogito/addons/quarkus/knative/eventing/AbstractKSinkInjectionHealthCheckIT.java, quarkus/addons/knative/eventing/integration-tests/src/test/java/org/kie/kogito/addons/quarkus/knative/eventing/KSinkInjectionHealthCheckDefaultConfigIT.java, quarkus/addons/knative/eventing/integration-tests/src/test/java/org/kie/kogito/addons/quarkus/knative/eventing/KSinkInjectionHealthCheckDisabledIT.java, quarkus/addons/knative/eventing/integration-tests/src/test/java/org/kie/kogito/addons/quarkus/knative/eventing/KSinkInjectionHealthCheckEnabledIT.java
<details>
<summary>
</summary> …
=> KOGITO-9143: K_SINK health check fails for serverless workflows that receive events but don't send any events

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.sonarcloud
https://issues.redhat.com/browse/KOGITO-9275
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/980
- https://github.com/kiegroup/drools/pull/5279
- https://github.com/kiegroup/kogito-runtimes/pull/3032
- https://github.com/kiegroup/kogito-apps/pull/1754
- https://github.com/kiegroup/kogito-examples/pull/1682
=> KOGITO-9275 Jenkins: Switch jobs to use RHEL8

.ci/environments/quarkus-3/patches/0016_update_dependencies_version.patch
<details>
<summary>
</summary> …
=> Quarkus 3: Updated patch

.ci/jenkins/dsl/jobs.groovy
<details>
<summary>
</summary> …
=> PR checks: Restrict Apps UI build memory

kogito-build/kogito-dependencies-bom/pom.xml, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/pom.xml
Fixes CVE-2023-1370.
Fixes https://github.com/kiegroup/kie-issues/issues/313
Adding of json-smart dependency was needed, because class [1] uses classes from it. It relied on those classes be brought in transitively from json-path dependency.
[1] https://github.com/kiegroup/kogito-runtimes/blob/10a5192f8ea6a82de54a74a4fae6473e2451c072/quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/src/main/java/org/kie/kogito/quarkus/runtime/graal/graal/JsonSmartSubstitutions.java#L25
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories …
=> [kie-issues#313] CVE-2023-1370 Upgrade json-smart and json-path.

quarkus/addons/messaging/common/src/main/java/org/kie/kogito/addon/quarkus/messaging/common/AbstractQuarkusCloudEventEmitter.java
Smallrye default ack handler is silently failing, therefore we have to override it to print error log
=> [KOGITO-9312] Override default nack handler

kogito-build/kogito-dependencies-bom/pom.xml
**JIRA**: https://issues.redhat.com/browse/DROOLS-7456
* requires first a new version of MVEL: https://github.com/mvel/mvel/pull/330
* https://github.com/kiegroup/drools/pull/5267
* https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/48
* https://github.com/kiegroup/kie-benchmarks/pull/245
* https://github.com/kiegroup/kogito-runtimes/pull/3053
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to …
=> DROOLS-7456 avoid kie maven plugin to crash on jdk17 project

grafana-api/src/main/java/org/kie/kogito/grafana/GrafanaConfigurationWriter.java, jbpm/jbpm-flow/src/test/java/org/jbpm/process/WorkItemTest.java, quarkus/extensions/kogito-quarkus-rules-extension/kogito-quarkus-rules/src/main/java/org/kie/kogito/core/rules/incubation/quarkus/support/RuleUnitServiceImpl.java
Fixes https://github.com/kiegroup/kie-issues/issues/341
Fixes Blocker and Critical things reported by Sonar:
- GrafanaConfigurationWriter: Fix unsecure Random instance. 
- WorkItemTest: Remove unnecessary fail assert. 
- RuleUnitServiceImpl: Close RuleUnit with try-with-resources.
<details>
<summary>
</summary> …
=> [kie-issues#341] Fix Blocker and Critical Bugs reported by Sonar

.github/workflows/kogito-examples-pr.yml, .github/workflows/kogito-runtimes-pr.yml, .github/workflows/optaplanner-pr.yml
Related PR:
- https://github.com/kiegroup/kogito-runtimes/pull/2965
=> [1.13.x][BXMSPROD-2057] Updating references to the new kie-ci actions folder

kogito-build/kogito-dependencies-bom/pom.xml
Fixes https://github.com/kiegroup/kie-issues/issues/336
=> Fixes CVE kiegroup/kie-issues#336 - Updating everit-json-schema

addons/common/process-svg/pom.xml, addons/common/process-svg/src/main/java/org/kie/kogito/svg/AbstractProcessSvgService.java, addons/common/process-svg/src/main/java/org/kie/kogito/svg/SVGImageProcessor.java, addons/common/process-svg/src/test/java/org/kie/kogito/svg/ProcessSvgServiceTest.java, addons/common/process-svg/src/test/java/org/kie/kogito/svg/SvgTransformationTest.java, kogito-build/kogito-dependencies-bom/pom.xml, kogito-test-utils/pom.xml, kogito-test-utils/src/main/java/org/kie/kogito/test/utils/CustomSVGDiffer.java, kogito-test-utils/src/main/java/org/kie/kogito/test/utils/CustomSVGMatcher.java, quarkus/addons/process-svg/deployment/src/main/java/org/kie/kogito/svg/deployment/KogitoAddOnProcessSVGProcessor.java, quarkus/addons/process-svg/runtime/pom.xml, quarkus/integration-tests/integration-tests-quarkus-processes-reactive/pom.xml, quarkus/integration-tests/integration-tests-quarkus-processes-reactive/src/test/java/org/kie/kogito/integrationtests/quarkus/reactive/ProcessSvgAddonIT.java, quarkus/integration-tests/integration-tests-quarkus-processes/pom.xml, quarkus/integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/ProcessSvgAddonIT.java, springboot/addons/process-svg/pom.xml, springboot/integration-tests/src/it/integration-tests-springboot-processes-it/pom.xml, springboot/integration-tests/src/it/integration-tests-springboot-processes-it/src/test/java/org/kie/kogito/integrationtests/springboot/ProcessSvgAddonTest.java
Fixes https://github.com/kiegroup/kie-issues/issues/333
=> [kie-issues-333] Fix CVE by removing Batik dependency

.ci/environments/quarkus-3/patches/0001_before_sh.patch, .ci/environments/quarkus-3/patches/0016_update_dependencies_version.patch, .ci/environments/quarkus-3/patches/0024_python_addon_fix.patch
<details>
<summary>
</summary> …
=> Quarkus3: Updated deps patch

quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/pom.xml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/pom.xml
In this PR, we remove the direct dependency from Kogito Kubernetes Addon.
Depends on this PR:
See https://issues.redhat.com/browse/KOGITO-9315
<details>
<summary>
</summary> …
=> [KOGITO-9315] - Remove Kogito Kubernetes Addon from SW Extension

.ci/jenkins/Jenkinsfile.deploy
Issue introduced in https://github.com/kiegroup/kogito-runtimes/pull/3040
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which …
=> CI: Fix deploy script

springboot/integration-tests/src/it/integration-tests-springboot-processes-it/pom.xml, springboot/integration-tests/src/it/integration-tests-springboot-processes-it/src/test/java/org/kie/kogito/integrationtests/springboot/ProcessSvgAddonTest.java
Related to changes introduced by https://github.com/kiegroup/kogito-runtimes/pull/3049
=> Fix compilation issue on SVG SpringBoot test

kogito-build/kogito-dependencies-bom/pom.xml
<details>
<summary>
</summary> …
=> [KOGITO-9316] - bump quarkus-embedded-postgresql

quarkus/addons/pom.xml
Assembly:
- https://github.com/kiegroup/kogito-apps/pull/1787
- https://github.com/kiegroup/kogito-runtimes/pull/3084
- https://github.com/kiegroup/kogito-examples/pull/1704
=> KOGITO-9416 - Remove SVG extension from prod profile

quarkus/addons/python/runtime/src/main/resources/META-INF/native-image/jni-config.json
Adding more classes for open vino example (https://github.com/kiegroup/kogito-examples/pull/1698) to work on native mode
=> [KOGITO-9319] Native registration

kogito-build/kogito-dependencies-bom/pom.xml
See https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-2976
=> Fixing guava vulnerability

kogito-build/kogito-dependencies-bom/pom.xml
Jira: https://issues.redhat.com/browse/KOGITO-9480
--------
<details>
<summary>
</summary> …
=> KOGITO-9480 Bump quarkus-reactive-messaging-http version to 1.1.5

kogito-build/kogito-dependencies-bom/pom.xml
Jira: https://issues.redhat.com/browse/KOGITO-9567
-------
<details>
<summary>
</summary> …
=> KOGITO-9567 Align gson versions

quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-extension-live-reload-test/pom.xml
<details>
<summary>
</summary> …
=> Added implicit dependency

.ci/jenkins/Jenkinsfile.deploy
<details>
<summary>
</summary> …
=> Correct deploy pipeline

.ci/jenkins/Jenkinsfile.promote
For Python modules handling
<details>
<summary>
</summary> …
=> Correct promote pipeline

addons/common/process-management/src/main/java/org/kie/kogito/process/management/BaseProcessInstanceManagementResource.java, quarkus/addons/process-management/runtime/src/main/java/org/kie/kogito/process/management/ProcessInstanceManagementResource.java, quarkus/addons/process-management/runtime/src/test/java/org/kie/kogito/process/management/ProcessInstanceManagementResourceTest.java, springboot/addons/process-management/src/main/java/org/kie/kogito/process/management/ProcessInstanceManagementRestController.java
<details>
<summary>
</summary> …
=> KOGITO-9665 Deffer the injection of Processes in the Process Management Addon

.ci/jenkins/Jenkinsfile.deploy
<details>
<summary>
</summary> …
=> CI: fix typo

jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java
<details>
<summary>
</summary> …
=> KOGITO-9659: Workflow timeout not working using external Job Service (management-addon)

.ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.setup-branch, .ci/jenkins/tests/src/test/vars/JenkinsfilePromote.groovy
https://issues.redhat.com/browse/KOGITO-9676
- https://github.com/kiegroup/kogito-pipelines/pull/1023
- https://github.com/kiegroup/kogito-runtimes/pull/3162
- https://github.com/kiegroup/kogito-apps/pull/1821
- https://github.com/kiegroup/kogito-examples/pull/1758
- https://github.com/kiegroup/kogito-images/pull/1665
- https://github.com/kiegroup/kogito-operator/pull/1509
- https://github.com/kiegroup/kogito-serverless-operator/pull/222
=> KOGITO-9676 CI: Promote call setup-branch job

.ci/environments/quarkus-3/patches/0001_before_sh.patch, .ci/environments/quarkus-3/patches/0004_javax.enterprise_to_jakarta.enterprise.patch, .ci/environments/quarkus-3/patches/0022_spring_boot_it_fix.patch, .ci/environments/quarkus-3/project-recipe.yml, .ci/environments/quarkus-3/quarkus3.yml
<details>
<summary>
</summary> …
=> Quarkus 3: update patches

kogito-build/kogito-dependencies-bom/pom.xml
<details>
<summary>
</summary> …
=> Bumping quarkus-embedded-postgresql to 0.0.9

kogito-build/kogito-dependencies-bom/pom.xml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/openapi/WorkflowOpenApiHandlerGenerator.java
Jira: https://issues.redhat.com/browse/KOGITO-9699
There are breaking changes in the new version.
No updates to docs or examples should be needed.
-------------
<details>
<summary>
</summary> …
=> KOGITO-9699 Upgraded quarkus-openapi-generator

quarkus/addons/knative/serving/deployment/src/main/java/org/kie/kogito/addons/quarkus/knative/serving/deployment/customfunctions/KnativeTypeHandler.java, quarkus/addons/knative/serving/integration-tests/pom.xml, quarkus/addons/microprofile-config-service-catalog/integration-tests/pom.xml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/openapi/WorkflowOpenApiHandlerGenerator.java
This PR fixes tests that are failing for quarkus-lts
----------------
<details>
<summary>
</summary> …
=> Fixed tests for quarkus-lts

.ci/environments/quarkus-3/before.sh
<details>
<summary>
</summary> …
=> Quarkus 3: Fix before build

kogito-bom/pom.xml
Assembly:
- https://github.com/kiegroup/kogito-runtimes/pull/3209
- https://github.com/kiegroup/kogito-apps/pull/1853
=> KOGITO-8979 - Data Index Infinispan persistence addon

kogito-bom/pom.xml
Assembly:
- https://github.com/kiegroup/kogito-apps/pull/1852
- https://github.com/kiegroup/kogito-runtimes/pull/3208
=> KOGITO-8979 - Data Index MongoDB persistence addon

.ci/jenkins/Jenkinsfile, .ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.quarkus-3.rewrite.pr, .ci/jenkins/Jenkinsfile.quarkus-3.rewrite.standalone, .ci/jenkins/Jenkinsfile.setup-branch, .ci/jenkins/dsl/jobs.groovy
- https://github.com/kiegroup/kogito-runtimes/pull/3206
- https://github.com/kiegroup/kogito-apps/pull/1876
- https://github.com/kiegroup/kogito-examples/pull/1790
- https://github.com/kiegroup/kogito-images/pull/1697
- https://github.com/kiegroup/kogito-operator/pull/1527
- https://github.com/kiegroup/kogito-serverless-operator/pull/249
- https://github.com/kiegroup/drools/pull/5518
- https://github.com/asf-transfer/optaplanner/pull/2967
=> [apache_migration] Apache migration test

.ci/jenkins/dsl/jobs.groovy
Invoking a template function to generate PR job in main branch.
Job is implemented using github branch source plugin, creating a regular trigger to check for new PRs coming both from origin itself and forks.
=> PR multibranchPipelineJob

springboot/archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/resources/index.html
Bump from 1.12.1 to .13.2 due to vulnerabilities:
- https://security.snyk.io/package/npm/jquery-ui/1.12.1
Bellow is screenshot of running generated sample app by springboot archetype
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for …
=> Bump jquery-ui to 1.13.2

.ci/jenkins/Jenkinsfile
kiegroup/kie-issues#585
Extending timeout for jenkins PR checks.
=> kie-issues#585 extend PR check timeout

.ci/jenkins/Jenkinsfile
apache/incubator-kie-issues#598 
Adding a post build cleanup of workspace.
=> kie-issues#598: Add post build cleanup to PR checks

springboot/archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/resources/index.html
This is a cherry-pick of: https://github.com/apache/incubator-kie-kogito-runtimes/pull/3226
Bump from 1.12.1 to .13.2 due to vulnerabilities:
- https://security.snyk.io/package/npm/jquery-ui/1.12.1
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of …
=> [1.40.x] Bump jquery-ui to 1.13.2

kogito-build/kogito-dependencies-bom/pom.xml, quarkus/integration-tests/integration-tests-quarkus-openapi-client/src/main/resources/specs/swagger2.0-security-no-auth.yaml, quarkus/integration-tests/integration-tests-quarkus-openapi-client/src/main/resources/specs/swagger2.0-security.yaml
Upgrade to latest open api release. 
Swagger parser and model has to be added too
=> [KOGITO-9803] Upgrade open api releases

kogito-build/kogito-dependencies-bom/pom.xml
<details>
<summary>
</summary> …
=> [KOGITO-9863] updating Quarkus to 2.6.11.Final

quarkus/addons/microprofile-config-service-catalog/deployment/pom.xml
This module is part of the kogito-runtimes project
<details>
<summary>
</summary> …
=> remove version when using kogito-addons-quarkus-microprofile-config-service-catalog as a dependency

kogito-build/kogito-kie-bom/pom.xml, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/pom.xml, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoQuarkusResourceUtils.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/deployment/livereload/LiveReloadProcessor.java, quarkus/extensions/kogito-quarkus-workflow-extension-common/kogito-quarkus-workflow-common-deployment/src/main/java/org/kie/kogito/quarkus/workflow/deployment/WorkflowProcessor.java
**JIRA**: https://issues.redhat.com/browse/DROOLS-6834
Related PRs:
https://github.com/apache/incubator-kie-drools/pull/5564
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3261
=> [DROOLS-6834] remove drl prefix from drools quarkus extension

kogito-build/kogito-dependencies-bom/pom.xml
=> Fix #3280 New SWF sdk release

kogito-codegen-modules/kogito-codegen-decisions/src/main/resources/class-templates/DecisionRestResourceQuarkusTemplate.java, kogito-codegen-modules/kogito-codegen-decisions/src/main/resources/class-templates/DecisionRestResourceSpringTemplate.java
Closes https://github.com/apache/incubator-kie-issues/issues/698
<details>
<summary>
</summary> …
=> [kie-issues#698] Fix SCA quality issue on generated code

kogito-build/kogito-dependencies-bom/pom.xml
Fixes #3284
Bump Openapi Generator to 1.13.4
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you …
=> #3284 Bump Openapi Generator to 1.13.4

springboot/addons/events/kafka/src/main/java/org/kie/kogito/events/spring/KafkaEventPublisher.java, springboot/starters/kogito-processes-spring-boot-starter/src/main/java/org/kie/kogito/process/ProcessDefinitionRegistration.java
<details>
<summary>
</summary> …
=> [KOGITO-9816] Adding ProcessDefinitionRegistration to springboot

addons/common/kubernetes/pom.xml, kogito-build/kogito-dependencies-bom/pom.xml, quarkus/bom/pom.xml, springboot/addons/kubernetes/pom.xml, springboot/bom/pom.xml
SpringBoot and Quarkus use a completely different version of Fabric8, so I've removed from our main build BOM and push to the specific framework BOM instead.
As a bonus, I've removed a workaround to fix CVE-2022-25857.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always …
=> Fixing Fabric8 version alignment on Quarkus and SB

quarkus/addons/microprofile-config-service-catalog/deployment/pom.xml, quarkus/addons/microprofile-config-service-catalog/deployment/src/main/java/org/kie/kogito/addons/quarkus/microprofile/config/service/catalog/MicroProfileConfigServiceCatalogProcessor.java, quarkus/addons/microprofile-config-service-catalog/runtime/src/main/resources/META-INF/kogito.addon, quarkus/addons/microprofile-config-service-catalog/runtime/src/main/resources/META-INF/quarkus-extension.yaml
<details>
<summary>
</summary> …
=> kie-issues-3314: Add the missing extension information to the kogito-addons-quarkus-microprofile-config-service-catalog

kogito-serverless-workflow/kogito-serverless-workflow-openapi-parser/src/test/java/org/kie/kogito/serverless/workflow/CallbackStateServerlessWorkflowParsingTest.java
<details>
<summary>
</summary> …
=> There is not need to to do that check

kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java
Removing the `@Lazy` annotation from the `RestWorkItemHandler` constructors. This was making Spring-boot inject an uninitialized proxy of the `WebClientOptions` without calling the default producer. 
This change doesn't affect Quarkus codegen.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and …
=> [Spring-Boot 3] Removing `@Lazy` injections on `RestWorkItemHandler` constructors

kogito-build/kogito-dependencies-bom/pom.xml
Fixes 
https://github.com/apache/incubator-kie-kogito-runtimes/issues/3327
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool …
=> [Issues-3327] Bump Swagger to 2.2.19

kogito-build/kogito-build-no-bom-parent/pom.xml
<details>
<summary>
</summary> …
=> kie-issues-3343: Move main to maven.compiler.release -> 17

quarkus/addons/events/process/runtime/src/main/java/org/kie/kogito/events/config/EventsRuntimeConfig.java
<details>
<summary>
</summary> …
=> kie-issues-789: kogito-addons-quarkus-events-process has EventsRuntimeConfigRoot with wrong prefix and name

addons/common/jobs/api/src/main/java/org/kie/kogito/jobs/api/JobCallbackResourceDef.java
issue : https://github.com/apache/incubator-kie-issues/issues/711
=> [incubator-kie-issues-711] Refactroing job service to allow collocated service for Quarkus

kogito-build/kogito-dependencies-bom/pom.xml
https://github.com/apache/incubator-kie-kogito-apps/pull/1941 depends on this one
=> [Fix_#1923] Upgrading to latest version of sql embedded extension

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/assembler/DuplicateProcess.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/ProcessLoadError.java, kogito-codegen-modules/kogito-codegen-rules/src/main/java/org/kie/kogito/codegen/rules/QueryGenerator.java
Fixes https://github.com/apache/incubator-kie-issues/issues/814
NEeded by https://github.com/apache/incubator-kie-drools/pull/5647
<details>
<summary>
</summary>
[build-chain …
=> [incubator-kie-issues#814] Fix NPE on BaseKnowledgeBuilderResultImpl.hashCode()

kogito-build/kogito-dependencies-bom/pom.xml
New version of postgres embbeded extension
=> Update to embedded 0.1.3

kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java
Fixes https://github.com/apache/incubator-kie-kogito-runtimes/issues/3337
=> [Fix_#3337] Avoid creating duplicate consumer

addons/common/persistence/pom.xml, addons/common/pom.xml, api/pom.xml, drools/pom.xml, kogito-codegen-modules/pom.xml, kogito-serverless-workflow/pom.xml, pom.xml, quarkus/addons/events/pom.xml, quarkus/addons/jobs/pom.xml, quarkus/addons/persistence/pom.xml, quarkus/addons/pom.xml, quarkus/extensions/kogito-quarkus-extension/pom.xml, quarkus/extensions/pom.xml, quarkus/integration-tests/pom.xml
Fixes: https://github.com/apache/incubator-kie-issues/issues/838
Related PRs:
- https://github.com/apache/incubator-kie-kogito-runtimes/pull/3360
- https://github.com/apache/incubator-kie-kogito-apps/pull/1959
- https://github.com/apache/incubator-kie-kogito-examples/pull/1855
<details>
<summary>
</summary> …
=> [kie-issues-838] remove productized profile managing modules

kogito-bom/pom.xml, quarkus/addons/common/kogito-addons-quarkus-common-health/.gitignore, quarkus/addons/common/kogito-addons-quarkus-common-health/pom.xml, quarkus/addons/common/kogito-addons-quarkus-common-health/src/main/java/org/kie/kogito/addon/quarkus/common/config/AbstractAliasConfigSource.java, quarkus/addons/common/kogito-addons-quarkus-common-health/src/main/java/org/kie/kogito/addon/quarkus/common/config/AbstractAliasConfigSourceFactory.java, quarkus/addons/common/kogito-addons-quarkus-common-health/src/main/java/org/kie/kogito/addon/quarkus/common/health/AbstractAvailabilityHealthCheck.java, quarkus/addons/common/kogito-addons-quarkus-common-health/src/test/java/org/kie/kogito/addon/quarkus/common/health/AbstractAvailabilityHealthCheckTest.java, quarkus/addons/common/kogito-addons-quarkus-data-index-health/.gitignore, quarkus/addons/common/kogito-addons-quarkus-data-index-health/pom.xml, quarkus/addons/common/kogito-addons-quarkus-data-index-health/src/main/java/org/kie/kogito/addon/quarkus/index/health/DataIndexAvailabilityHealthCheck.java, quarkus/addons/common/kogito-addons-quarkus-data-index-health/src/main/java/org/kie/kogito/addon/quarkus/index/health/DataIndexAvailabilityHealthCheckConfigSource.java, quarkus/addons/common/kogito-addons-quarkus-data-index-health/src/main/java/org/kie/kogito/addon/quarkus/index/health/DataIndexAvailabilityHealthCheckConfigSourceFactory.java, quarkus/addons/common/kogito-addons-quarkus-data-index-health/src/main/resources/META-INF/beans.xml, quarkus/addons/common/kogito-addons-quarkus-data-index-health/src/main/resources/META-INF/services/io.smallrye.config.ConfigSourceFactory, quarkus/addons/common/kogito-addons-quarkus-data-index-health/src/test/java/org/kie/kogito/addon/quarkus/index/health/DataIndexServiceAvailabilityHealthCheckTest.java, quarkus/addons/common/kogito-addons-quarkus-jobs-service-health/.gitignore, quarkus/addons/common/kogito-addons-quarkus-jobs-service-health/pom.xml, quarkus/addons/common/kogito-addons-quarkus-jobs-service-health/src/main/java/org/kie/kogito/addon/quarkus/jobs/health/JobsServiceAvailabilityHealthCheck.java, quarkus/addons/common/kogito-addons-quarkus-jobs-service-health/src/main/java/org/kie/kogito/addon/quarkus/jobs/health/JobsServiceAvailabilityHealthCheckConfigSource.java, quarkus/addons/common/kogito-addons-quarkus-jobs-service-health/src/main/java/org/kie/kogito/addon/quarkus/jobs/health/JobsServiceAvailabilityHealthCheckConfigSourceFactory.java, quarkus/addons/common/kogito-addons-quarkus-jobs-service-health/src/main/resources/META-INF/beans.xml, quarkus/addons/common/kogito-addons-quarkus-jobs-service-health/src/main/resources/META-INF/services/io.smallrye.config.ConfigSourceFactory, quarkus/addons/common/kogito-addons-quarkus-jobs-service-health/src/test/java/org/kie/kogito/addon/quarkus/jobs/health/JobsServiceAvailabilityHealthCheckTest.java, quarkus/addons/common/pom.xml, quarkus/addons/jobs/knative-eventing/runtime/pom.xml, quarkus/addons/jobs/knative-eventing/runtime/src/main/resources/application.properties, quarkus/addons/knative/eventing/runtime/pom.xml, quarkus/addons/knative/eventing/runtime/src/main/resources/application.properties
<details>
<summary>
</summary> …
=> kie-kogito-runtimes-3365: Add startup health checks to ensure data-index and jobs-service availability

kogito-build/kogito-dependencies-bom/pom.xml, quarkus/integration-tests/integration-tests-quarkus-openapi-client/src/test/java/org/kie/kogito/quarkus/it/openapi/client/ApiWithSecurityContextIT.java
=> Bump openapi generator version

kogito-build/kogito-dependencies-bom/pom.xml
This version adds more tracing for debugging
=> Upgrading quarkus http version

quarkus/addons/messaging/common/src/main/java/org/kie/kogito/addon/quarkus/messaging/common/AbstractQuarkusCloudEventEmitter.java
Use toString rather than name for the spec version
=> Using toString rather than name

.ci/jenkins/Jenkinsfile, .ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/Jenkinsfile.promote, .ci/jenkins/Jenkinsfile.setup-branch, .ci/jenkins/Jenkinsfile.weekly.deploy
part of https://github.com/apache/incubator-kie-issues/issues/777
=> kie-issues#777: Allow restricting jenkins agent labels for pipelines

kogito-build/kogito-dependencies-bom/pom.xml
Related PRs:
- https://github.com/apache/incubator-kie-drools/pull/5697
- https://github.com/apache/incubator-kie-kogito-runtimes/pull/3408
<details>
<summary>
</summary>
[build-chain …
=> [CVE-2024-25710] update common compress to 1.26.0

kogito-bom/pom.xml
Closes https://github.com/apache/incubator-kie-issues/issues/932
Merge with:
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3410
https://github.com/apache/incubator-kie-kogito-apps/pull/1997
https://github.com/apache/incubator-kie-kogito-examples/pull/1877
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle …
=> incubator-kie-issues#932: Rename Quarkus Extension in `kogito-apps`

api/kogito-api/src/main/java/org/kie/kogito/Model.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/NodeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/NodeInstanceContainer.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/models/JsonNodeModel.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/division.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/RetriggerIT.java
Fixes https://github.com/apache/incubator-kie-kogito-runtimes/issues/3390
It also fixes PATCH rest API ( it was detected it does not work while testing this PR)
=> [Fix #3390] Fixing patch and retrigger REST APIs

kogito-bom/pom.xml
Merge with:
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3423
https://github.com/apache/incubator-kie-kogito-apps/pull/2008
https://github.com/apache/incubator-kie-kogito-examples/pull/1887
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest …
=> [NO_ISSUE]: Rollback missing `sonataflow-quarkus-devui` groupId

quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/test/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessorTest.java
Relates to 
https://github.com/apache/incubator-kie-drools/pull/5777
Fixes https://github.com/apache/incubator-kie-issues/issues/1003
<details>
<summary>
</summary> …
=> [incubator-kie-issues#1003] Fix missing header

kogito-test-utils/src/test/java/org/kie/kogito/testcontainers/KogitoMongoDBContainerTest.java
[SRVLOGIC-253](https://issues.redhat.com/browse/SRVLOGIC-253)
<details>
<summary>
</summary> …
=> [SRVLOGIC-253] Skip shouldGetDockerImageName test if no docker

addons/common/process-management/src/main/java/org/kie/kogito/process/management/BaseProcessInstanceManagementResource.java, quarkus/addons/process-management/runtime/src/main/java/org/kie/kogito/process/management/ProcessInstanceManagementResource.java, springboot/addons/process-management/src/main/java/org/kie/kogito/process/management/ProcessInstanceManagementRestController.java
Fixes https://github.com/apache/incubator-kie-kogito-runtimes/issues/3473
=> [Fix_3473] Fixing build

kogito-bom/pom.xml
Closes: https://github.com/apache/incubator-kie-issues/issues/1078
Please remove the devui references from kogito-runtimes as the devui modules are migrated to kie-tools.
**Important:**
This PR requires https://github.com/apache/incubator-kie-kogito-examples/pull/1900
<details>
<summary>
</summary> …
=> kie-issues#1078: Cleanup kogito-runtimes repo removing devui references

jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/NodeInstanceImpl.java
=> Removing print stack trace

addons/common/monitoring/core/src/main/java/org/kie/kogito/monitoring/core/common/process/MetricsProcessEventListener.java, quarkus/integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/MonitoringIT.java, springboot/integration-tests/src/it/integration-tests-springboot-processes-it/src/test/java/org/kie/kogito/integrationtests/springboot/MonitoringTest.java
Fix https://github.com/apache/incubator-kie-issues/issues/1101
=> [Fix apache/incubator_kie_issues#1101] Adding error counter

kogito-build/kogito-dependencies-bom/pom.xml
Bumping  `quarkus-embedded-postgresql` version to help fixing the named datasource's for `data-index-inmemory` & `jobs-service-embedded` configuration.
After Quarkus 3.8.4 upgrade without this quotes the datasource configuration generated by quarkus-embedded-posgresql extension isn't available at startup, making the quarkus not being able to initialize the named DataSources.
Ensemble:
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3499
https://github.com/apache/incubator-kie-kogito-apps/pull/2042
https://github.com/apache/incubator-kie-kogito-examples/pull/1913
<details>
<summary>
</summary>
Build Chain tool does …
=> [NO_ISSUE] fixing named datasource's configuration for `data-index-inmemory` & `jobs-service-embedded`.

jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/feel/FeelProcessValidator.java, jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/feel/FeelReturnValueEvaluator.java
Fixes https://github.com/apache/incubator-kie-issues/issues/1187
Relates to https://github.com/apache/incubator-kie-drools/pull/5926
@elguardian @ricardozanini @fjtirado FYI
<details>
<summary>
</summary> …
=> [incubator-kie-issues#1187] Fix FEEL instantiation

kogito-build/kogito-dependencies-bom/pom.xml
Related: https://github.com/apache/incubator-kie-issues/issues/1197
Ensemble:
https://github.com/apache/incubator-kie-drools/pull/5934
https://github.com/apache/incubator-kie-optaplanner/pull/3085 
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3509
=> CVE-2023-6481 logback upgrade.

kogito-build/kogito-dependencies-bom/pom.xml
https://github.com/apache/incubator-kie-issues/issues/1200
=> CVE-2024-31573: xmlunit-core upgrade.

kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/models/JsonNodeModel.java
Fixes https://github.com/apache/incubator-kie-kogito-runtimes/issues/3513
=> [Fix #3513] Different jsonnode instance for parent and children process

quarkus/addons/jobs/knative-eventing/runtime/src/main/java/org/kie/kogito/jobs/knative/eventing/quarkus/KnativeEventingJobsService.java
<details>
<summary>
</summary> …
=> kie-kogito-runtimes-3521: Align jobs service knative eventing http connector config with runtime events config

jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/AbstractNodeHandler.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/AbstractNodeVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/process/builder/transformation/DataTransformerCompiler.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/process/builder/transformation/DataTransformerCompilerRegistry.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/process/builder/transformation/DefaultDataTransformerCompiler.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/process/builder/transformation/JavaDataTransformerCompiler.java, jbpm/jbpm-flow-builder/src/main/resources/META-INF/services/org.jbpm.process.builder.transformation.DataTransformerCompiler, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/transformation/JavaDataTransformer.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/impl/DataDefinition.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/node/Transformation.java, jbpm/jbpm-tests/src/test/bpmn/org/jbpm/bpmn2/activity/BPMN2-BoundarySignalEventOnTaskWithTransformation.bpmn, jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java, jbpm/jbpm-tools/jbpm-tools-maven-plugin/pom.xml, jbpm/jbpm-tools/jbpm-tools-maven-plugin/src/test/resources/unit/project/src/main/bpmn/BPMN2-BoundarySignalEventOnTaskWithTransformation.bpmn
Closes: https://github.com/apache/incubator-kie-issues/issues/1146
=> [incubator-kie-issues-1146] Add support for transformations in input/output in activities

.github/workflows/pr-kogito-runtimes.yml
Closes: https://github.com/apache/incubator-kie-issues/issues/1273
=> [incubator-kie-issues-1273] Add validate formatting to kogito runtimes and kogito-apps

kogito-build/kogito-dependencies-bom/pom.xml
Fixes: https://github.com/apache/incubator-kie-issues/issues/1282
Related: https://github.com/apache/incubator-kie-optaplanner/pull/3097
=> kie-issues#1282: updating spring boot version that address some important CVEs

quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/KogitoDevServicesProcessor.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/deployment/ServerlessWorkflowDevServicesProcessor.java, quarkus/extensions/kogito-quarkus-workflow-extension-common/kogito-quarkus-workflow-common-deployment/src/main/java/org/kie/kogito/quarkus/workflow/deployment/AbstractDevServicesProcessor.java
Closes https://github.com/apache/incubator-kie-issues/issues/1283
This PR Verifies that the GraphQL UI can be added into the Quarkus `devui` before adding it, this way we don't add it twice when the runtime works in conjunction with the Data Index Addons
Ensemble:
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3540
https://github.com/apache/incubator-kie-kogito-apps/pull/2068
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those …
=> incubator-kie-issues#1283: Fix Kogito Addons Quarkus Data Index `DevMode`

drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/DMNKogito.java
Fixes https://github.com/apache/incubator-kie-issues/issues/1294
<details>
<summary>
</summary> …
=> [incubator-kie-issues#1294] Allow RuntimeTypeCheckOption configurationn via environment property

jbpm/jbpm-tests/src/main/java/org/jbpm/bpmn2/services/AlwaysThrowingComponent.java, jbpm/jbpm-tests/src/main/java/org/jbpm/bpmn2/services/LoggingComponent.java, jbpm/jbpm-tests/src/test/bpmn/org/jbpm/bpmn2/error/BPMN2-EndError.bpmn2, jbpm/jbpm-tests/src/test/bpmn/org/jbpm/bpmn2/error/BPMN2-ErrorVariable.bpmn2, jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/ErrorEventTest.java, jbpm/jbpm-tools/jbpm-tools-maven-plugin/src/main/java/org/jbpm/tools/maven/ClassLoaderHelper.java, jbpm/jbpm-tools/jbpm-tools-maven-plugin/src/main/java/org/jbpm/tools/maven/ProcessCodeGenerationSupport.java, jbpm/jbpm-tools/jbpm-tools-maven-plugin/src/main/java/org/jbpm/tools/maven/ProcessCodegenMojo.java, jbpm/jbpm-tools/jbpm-tools-maven-plugin/src/main/java/org/jbpm/tools/maven/ProcessCodegenTestMojo.java
Closes https://github.com/apache/incubator-kie-issues/issues/1278
=> [incubator-kie-issues-1278] Support for codegen in project class loading handler descriptors. (error event)

.github/workflows/pr-kogito-runtimes.yml, pom.xml
Fixes https://github.com/apache/incubator-kie-issues/issues/1348
This PR also remove the multithreading, since it is not compatible with reproducible build configuration: during reproducible build, the `kogito-runtimes/target/kogito-runtimes-{version}.buildcompare` file is overwritten in thread-unsafe way
@jstastny-cz FYI
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest …
=> [incubator-kie-issues#1348] Enforce reproducible build

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/dsl/jobs.groovy
Depends on:
* apache/incubator-kie-kogito-pipelines#1206
Where `release` share pipeline library was added with gpg specific methods to import keys,etc.
=> NO_ISSUE: use release shared library

jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/ActivityTest.java
migrated some BPMN processes which are being compiled using legacy v7 to code generation approach, using new branch incubator-kie-issues-1131-3
Issue: https://github.com/apache/incubator-kie-issues/issues/1131
=> [incubator-kie-issues-1131] test migration from V7 to code generation-3

jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowProcessFactory.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/compensation.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/CompensationRestIT.java
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3576
=> [Fix #3576] Searching for unique id in recursive way

.ci/jenkins/Jenkinsfile.deploy, .ci/jenkins/dsl/jobs.groovy
Part of: https://github.com/apache/incubator-kie-issues/issues/1397
=> [10.0.x] kie-issues#1397: Adjust release pipelines for the Apache 10 release

addons/common/human-task-prediction/api/pom.xml, addons/common/human-task-prediction/smile/pom.xml, addons/common/persistence/filesystem/pom.xml, addons/common/persistence/infinispan/pom.xml, addons/common/persistence/jdbc/pom.xml, addons/common/persistence/mongodb/pom.xml, addons/common/persistence/postgresql/pom.xml, addons/common/persistence/rocksdb/pom.xml, addons/common/process-management/pom.xml, addons/common/task-management/pom.xml, jbpm/jbpm-deps-groups/jbpm-deps-group-bpmn2-compiler/pom.xml, jbpm/jbpm-deps-groups/jbpm-deps-group-compiler/pom.xml, jbpm/jbpm-deps-groups/jbpm-deps-group-engine/pom.xml, jbpm/jbpm-deps-groups/pom.xml, jbpm/pom.xml, kogito-bom/pom.xml, kogito-codegen-modules/kogito-codegen-processes/pom.xml, kogito-serverless-workflow/kogito-jq-expression/pom.xml, kogito-serverless-workflow/kogito-jsonpath-expression/pom.xml, kogito-serverless-workflow/kogito-serverless-workflow-builder/pom.xml, kogito-serverless-workflow/kogito-serverless-workflow-runtime/pom.xml, kogito-serverless-workflow/kogito-serverless-workflow-utils/pom.xml, kogito-workitems/kogito-rest-workitem/pom.xml, quarkus/addons/jobs/management/runtime/pom.xml, quarkus/addons/process-management/runtime/pom.xml, quarkus/extensions/kogito-quarkus-workflow-extension-common/kogito-quarkus-workflow-common/pom.xml, springboot/addons/jobs/pom.xml, springboot/starters/kogito-processes-spring-boot-starter/pom.xml
Closes: https://github.com/apache/incubator-kie-issues/issues/1396
=> [incubator-kie-issues-1396] Creating group deps for jBPM to make easy to change internal project structure

kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/models/JsonNodeModel.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/main/java/org/kie/kogito/serverless/workflow/SWFConstants.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/main/java/org/kie/kogito/serverless/workflow/utils/InputKogitoProcessContextResolver.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/main/resources/META-INF/services/org.kie.kogito.serverless.workflow.utils.KogitoProcessContextResolverExtension, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/test/java/org/kie/kogito/serverless/workflow/test/MockBuilder.java, kogito-serverless-workflow/kogito-serverless-workflow-utils/src/test/java/org/kie/kogito/serverless/workflow/utils/KogitoProcessContextResolverTest.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/expression.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/ExpressionRestIT.java
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3590
=> [Fix #3590] Adding $input support

addons/common/persistence/jdbc/pom.xml, kogito-build/kogito-dependencies-bom/pom.xml
Quarkus dependencies should not be in common addons
<details>
<summary>
</summary> …
=> Removing quarkus dependency from common addon

.github/pull_request_template.md, CONTRIBUTING.md
Closes [Fix_#3443](https://github.com/apache/incubator-kie-kogito-runtimes/issues/3443)
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a …
=> [Fix_#3443] Update template and contribution guides with github issues

addons/common/monitoring/core/src/main/java/org/kie/kogito/monitoring/core/common/process/MetricsProcessEventListener.java
Fixes https://github.com/apache/incubator-kie-kogito-runtimes/issues/3605
=> [Fix #3605] Use concurrent hash map

quarkus/addons/dynamic/integration-tests/src/test/java/org/kie/kogito/process/dynamic/DynamicCallResourceTest.java
<details>
<summary>
</summary> …
=> Add edge tests for new dynamic addon

addons/common/persistence/mongodb/src/main/java/org/kie/kogito/mongodb/correlation/MongoDBCorrelationRepository.java, addons/common/persistence/mongodb/src/main/java/org/kie/kogito/mongodb/correlation/MongoDBCorrelationService.java, addons/common/persistence/mongodb/src/test/java/org/kie/kogito/mongodb/correlation/MongoDBCorrelationServiceIT.java, quarkus/addons/persistence/mongodb/runtime/src/main/java/org/kie/kogito/persistence/quarkus/MongoDBCorrelationServiceProducer.java
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3469
<details>
<summary>
</summary>
[build-chain …
=> Add correlation persistence for MongoDB

kogito-build/kogito-dependencies-bom/pom.xml, kogito-serverless-workflow/kogito-jq-expression/pom.xml
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3602
=> [Fix #3602] Adding jq extra functions

quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/pom.xml
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3624
=> [Fix 3624] Removing rest-easy-client from sonataflow extension

addons/common/process-dynamic/src/main/java/org/kie/kogito/process/dynamic/ProcessInstanceDynamicCallHelper.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/expr/ExpressionHandlerFactory.java, quarkus/addons/dynamic/runtime/src/main/java/org/kie/kogito/process/dynamic/ProcessInstanceDynamicCallsResource.java
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3628
=> [Fix #3628] Avoiding concurrency issues with Instance and ServiceLoader

jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/ErrorEventTest.java
Migrated tests within ErrorEventTest.java
The test can be identified by referring to ErrorEventTestTest.java:
https://github.com/apache/incubator-kie-kogito-runtimes/blob/main/jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/ErrorEventTest.java
=> [incubator-kie-issues-1131] test migration from V7 to code generation-16

jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/StartEventTest.java
Migrated tests within StartEventTest.java
The test can be identified by referring to StartEventTest.java:
https://github.com/apache/incubator-kie-kogito-runtimes/blob/main/jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/StartEventTest.java
=> [incubator-kie-issues-1131] test migration from V7 to code generation-29

addons/common/events/mongodb/pom.xml, addons/common/monitoring/core/pom.xml, addons/common/tracing/tracing-api/pom.xml, api/kogito-events-api/pom.xml, api/kogito-events-core/pom.xml, kogito-build/kogito-dependencies-bom/pom.xml, kogito-serverless-workflow/kogito-serverless-workflow-monitoring/pom.xml, quarkus/addons/monitoring/core/pom.xml, springboot/addons/monitoring/core/pom.xml
Issue: https://github.com/apache/incubator-kie-issues/issues/1465
Alignment with latest Quarkus LTS release - 3.8.6.
Related PRs: 
https://github.com/apache/incubator-kie-drools/pull/6067
https://github.com/apache/incubator-kie-optaplanner/pull/3123
https://github.com/apache/incubator-kie-kogito-apps/pull/2097
https://github.com/apache/incubator-kie-kogito-examples/pull/2008
https://github.com/apache/incubator-kie-kogito-images/pull/1801
=>  [kie-issues#1465] Align with Quarkus 3.8.6. #6067 

springboot/integration-tests/integration-tests-springboot-processes-persistence-it/pom.xml
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can …
=> [tmp_fix_repr] NO-ISSUE: temporary disabling integration-tests-springboot-processes-filesystem

kogito-test-utils/src/main/java/org/kie/kogito/test/utils/CustomSVGDiffer.java
Closes https://github.com/apache/incubator-kie-issues/issues/1496
=> Ignore namespace differences during SVG comparison

jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/DummyKnowledgeRuntime.java, kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/java/org/kie/kogito/codegen/AbstractCodegenIT.java
Related to https://github.com/apache/incubator-kie-drools/pull/6103
=> [KIE-1492] Allow KieRuntimeBuilder to also create and provide StatelessKieSession

jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/ProcessInstanceImpl.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/Metadata.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ServerlessWorkflowParser.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/compensation.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/compensation_aborted.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/CompensationRestIT.java
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3674
=>  [Fix #3674] Signalling compensation on abort

.ci/jenkins/Jenkinsfile.deploy, jbpm/pom.xml, springboot/pom.xml
Cherry-pick of: d679d3db24b857dbcf6c20b376a8e2ef07848a5f
=> [10.0.x][incubator-kie-issues#1504] Conditionally build all or only reproducible modules based on only.reproducible flag - only for release build 

kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java, kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java
Fix format Codegen files after https://github.com/apache/incubator-kie-kogito-runtimes/pull/3671
=> Fix format codegen files

api/kogito-api/src/main/java/org/kie/kogito/process/ProcessService.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/ProcessServiceImpl.java
Closes: https://github.com/apache/incubator-kie-issues/issues/1516
=> [incubator-kie-issues-1516] Remove obsolete code in process service

api/kogito-events-api/src/main/java/org/kie/kogito/event/usertask/UserTaskInstanceStateEventBody.java, api/kogito-events-core/src/main/java/org/kie/kogito/event/impl/adapter/AbstractDataEventAdapter.java, api/kogito-events-core/src/main/java/org/kie/kogito/event/impl/adapter/ProcessNodeEnteredEventDataEventAdapter.java, api/kogito-events-core/src/main/java/org/kie/kogito/event/impl/adapter/ProcessNodeLeftEventDataEventAdapter.java, api/kogito-events-core/src/main/java/org/kie/kogito/event/impl/adapter/UserTaskStateEventDataEventAdapter.java
Closes: https://github.com/apache/incubator-kie-issues/issues/1508
=> [incubator-kie-issues-1508] GraphQL external reference id retrieve in data index and audit. (runtimes part)

jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java, kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/java/org/kie/kogito/codegen/tests/UserTaskIT.java
Closes: https://github.com/apache/incubator-kie-issues/issues/1518
=> [incubator-kie-issues-1518] Testing external reference between userTasks and processes.

kogito-serverless-workflow/kogito-serverless-workflow-executor-python/pom.xml, quarkus/addons/python/integration-tests/pom.xml
Fix https://github.com/apache/incubator-kie-issues/issues/1539
Merge with https://github.com/apache/incubator-kie-kogito-examples/pull/2022
=> [incubator-kie-issues#1539] Fix PIP on CI

addons/common/monitoring/core/src/main/java/org/kie/kogito/monitoring/core/common/process/MetricsProcessEventListener.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/FaultNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/SplitInstance.java
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3725
=> [Fix #3725] Setting leaveTime in Split and Fault node instance

addons/common/tracing/decision-common/src/main/java/org/kie/kogito/tracing/decision/event/evaluate/EvaluateEventType.java, addons/common/tracing/decision-common/src/test/java/org/kie/kogito/tracing/decision/event/evaluate/EvaluateEventTypeTest.java, addons/common/tracing/tracing-api/src/main/java/org/kie/kogito/tracing/event/trace/TraceExecutionStepType.java
FIxes [incubator-kie-issues#1528](https://github.com/apache/incubator-kie-issues/issues/1528)
Needed by https://github.com/apache/incubator-kie-drools/pull/6124
<details>
<summary>
</summary> …
=> [incubator-kie-issues#1528] Adapt tracing code. Fix tests

kogito-serverless-workflow/kogito-serverless-workflow-executor-python/pom.xml, quarkus/addons/python/integration-tests/pom.xml
This reverts commit e532628d69f21fefe41b7211a40f42793543bfcf.
See https://kie.zulipchat.com/#narrow/channel/382044-kogito-dev/topic/CI.20issue.20with.20python/near/478013807
=> Revert "[incubator-kie-issues#1539] Fix PIP on CI (#3729)"

api/kogito-api/src/main/java/org/kie/kogito/auth/IdentityProviderFactory.java, api/kogito-api/src/main/java/org/kie/kogito/auth/impl/IdentityProviderFactoryImpl.java, api/kogito-api/src/main/java/org/kie/kogito/auth/impl/KogitoAuthConfig.java, api/kogito-api/src/test/java/org/kie/kogito/auth/impl/IdentityProviderFactoryImplTest.java, kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceQuarkusTemplate.java, kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceSpringTemplate.java, kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceWorkItemQuarkusTemplate.java, kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceWorkItemSpringTemplate.java, kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/usertask/RestResourceUserTaskQuarkusTemplate.java, kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/usertask/RestResourceUserTaskSpringTemplate.java, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/src/main/java/org/kie/kogito/quarkus/auth/QuarkusIdentityProviderFactoryProducer.java, quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/src/main/java/org/kie/kogito/quarkus/config/KogitoAuthRuntimeConfig.java, springboot/starters/kogito-processes-spring-boot-starter/src/main/java/org/kie/kogito/spring/auth/SpringIdentityProviderFactoryProducer.java
Closes https://github.com/apache/incubator-kie-issues/issues/1597
<details>
<summary>
</summary>
[build-chain …
=> [incubator-kie-issues-1597] Enforce authentication in User Tasks rest endpoints

quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/pom.xml
Closes/Fixes/Resolves #3723
<details>
<summary>
</summary> …
=> [Fix #3723] Add resteasy-multipart-provider

quarkus/addons/flyway/runtime/src/main/java/org/kie/flyway/quarkus/KieFlywayQuarkusRuntimeConfig.java
<details>
<summary>
</summary> …
=> [NO_ISSUE] Set the kie.flyway.enabled to false by default.

kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/compensation.sw.json
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3789
=> [Fix #3789] Accept join node on compensation states

.github/workflows/ci_check_license_headers.yaml, .gitignore, .rat-excludes, LICENSE, NOTICE, jbpm/jbpm-tests/src/test/bpmn/org/jbpm/bpmn2/activity/BPMN2-BoundarySignalEventOnTaskWithTransformation.bpmn, jbpm/jbpm-tests/src/test/bpmn/org/jbpm/bpmn2/escalation/BPMN2-Multiescalation.bpmn2, jbpm/jbpm-tests/src/test/bpmn/org/jbpm/bpmn2/escalation/BPMN2-TopLevelEscalation.bpmn2, jbpm/jbpm-tests/src/test/bpmn/org/jbpm/bpmn2/flow/BPMN2-IntegerStructureRef.bpmn2, jbpm/jbpm-tests/src/test/bpmn/org/jbpm/bpmn2/flow/BPMN2-ObjectStructureRef.bpmn2, kogito-build/kogito-build-no-bom-parent/pom.xml, pom.xml
This is backport of #3714 
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests …
=> [10.0.x] kie-issues#1613: Add `CI :: License headers` GitHub Actions workflow

.rat-excludes, LICENSE, drools/kogito-pmml/src/test/resources/org/kie/kogito/pmml/test_regression.pmml, drools/kogito-pmml/src/test/resources/org/kie/kogito/pmml/test_tree.pmml, drools/kogito-scenario-simulation/src/test/resources/dmnPmml/test_regression.pmml, drools/kogito-scenario-simulation/src/test/resources/dmnPmml/test_tree.pmml, kogito-codegen-modules/kogito-codegen-predictions/src/test/resources/prediction/test_miningmodel.pmml, kogito-codegen-modules/kogito-codegen-predictions/src/test/resources/prediction/test_regression.pmml, kogito-codegen-modules/kogito-codegen-predictions/src/test/resources/prediction/test_scorecard.pmml, quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions-integration-test/src/main/resources/PMMLRegression.pmml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/src/main/resources/META-INF/beans.xml, quarkus/integration-tests/integration-tests-quarkus-norest/src/main/resources/PMMLRegression.pmml, quarkus/integration-tests/integration-tests-quarkus-predictions/src/main/resources/PMMLRegression.pmml, quarkus/integration-tests/integration-tests-quarkus-predictions/src/main/resources/PMMLTree.pmml, springboot/integration-tests/integration-tests-springboot-decisions-it/src/main/resources/PMMLRegression.pmml, springboot/integration-tests/integration-tests-springboot-decisions-it/src/main/resources/PMMLTree.pmml, springboot/integration-tests/integration-tests-springboot-norest-it/src/main/resources/PMMLRegression.pmml
Address copyright issue from the apache/incubator-kie-issues/issues/1634:
- https://github.com/apache/incubator-kie-issues/issues/1634#issuecomment-2505506658
This PR is not for adding license headers into files as no such file was marked as blocker from Apache KIE 10 release.
<details>
<summary>
</summary> …
=> kie-issues#1634: Fix pmml files licensing

kogito-maven-plugin-test/pom.xml, kogito-maven-plugin-test/src/main/resources/TrafficViolation.dmn, kogito-maven-plugin-test/src/main/resources/traffic-rules-dmn.bpmn
Fixes missing license hedaers
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests …
=> [NO_ISSUE] Fix license headers

NOTICE
- https://github.com/apache/incubator-kie-issues/issues/1618
=> [incubator-kie-issues-1618] Fix NOTICE year

NOTICE
- https://github.com/apache/incubator-kie-issues/issues/1618
=> [10.0.x] [incubator-kie-issues-1618] Fix NOTICE year

NOTICE
- https://github.com/apache/incubator-kie-issues/issues/1618
=> [incubator-kie-issues-1618] Fix NOTICE year with range

NOTICE
- https://github.com/apache/incubator-kie-issues/issues/1618
=> [10.0.x] [incubator-kie-issues-1618] Fix NOTICE year with range

addons/common/persistence/postgresql/pom.xml, kogito-build/kogito-dependencies-bom/pom.xml, springboot/integration-tests/integration-tests-springboot-processes-persistence-it/integration-tests-springboot-processes-postgresql/pom.xml
Closes/Fixes/Resolves [kie-issues#1632](https://github.com/apache/incubator-kie-issues/issues/1632)
Update postgres to 15.9 version
=> [Fix_#1632] Update postgres to 15.9 version

NOTICE
Part of https://github.com/apache/incubator-kie-issues/issues/1747
=> kie-issues#1747: Updating the year range in the NOTICE file

kogito-build/kogito-dependencies-bom/pom.xml
Updated version mvel from 2.5.0.Final to 2.5.2.Final
Link to the kie issue: https://github.com/apache/incubator-kie-issues/issues/1772
=> [kie-issues#1772] Upgrade mvel to 2.5.2.Final

addons/common/jobs/api/src/test/java/org/kie/kogito/jobs/api/JobCallbackResourceDefTest.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/event/JobCloudEvent.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/event/serialization/JobCloudEventDeserializer.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/event/serialization/JobCloudEventSerializer.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/recipient/sink/SinkRecipient.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/serialization/DeserializationException.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/serialization/SerializationUtils.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/serialization/SpecVersionDeserializer.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/serialization/SpecVersionSerializer.java, api/kogito-jobs-service-api/src/main/java/org/kie/kogito/jobs/service/api/utils/ReflectionUtils.java, api/kogito-jobs-service-api/src/test/java/org/kie/kogito/jobs/service/api/event/serialization/JobCloudEventDeserializerTest.java, api/kogito-jobs-service-api/src/test/java/org/kie/kogito/jobs/service/api/serialization/SpecVersionDeserializerTest.java, api/kogito-jobs-service-api/src/test/java/org/kie/kogito/jobs/service/api/serialization/SpecVersionSerializerTest.java, api/kogito-jobs-service-api/src/test/java/org/kie/kogito/jobs/service/api/utils/ReflectionUtilsTest.java, quarkus/addons/jobs/management/runtime/src/main/java/org/kie/kogito/jobs/management/quarkus/AddonObjectMapperCustomizer.java, quarkus/addons/jobs/management/runtime/src/main/java/org/kie/kogito/jobs/management/quarkus/VertxJobsService.java, springboot/addons/jobs/src/main/java/org/kie/kogito/jobs/management/springboot/AddonObjectMapperBuilderCustomizer.java, springboot/addons/jobs/src/test/java/org/kie/kogito/jobs/management/springboot/SpringRestJobsServiceTest.java
Closes https://github.com/apache/incubator-kie-issues/issues/1801
This PR fixes some typos in package names :)
Ensemble:
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3839
https://github.com/apache/incubator-kie-kogito-apps/pull/2187
<details>
<summary>
</summary> …
=> kie-issues#1801: Fix ClassNotFoundException when Registering classes for Reflection

jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/NodeInstanceFactoryRegistry.java
Closes https://github.com/apache/incubator-kie-issues/issues/1793
=> [kie-issues-1793] NodeInstanceFactoryRegistry generates a lot of logging on each call

addons/common/explainability/src/test/java/org/kie/kogito/explainability/ExplainabilityServiceTest.java, drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/AbstractDecisionModels.java, drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/DMNKogito.java, drools/kogito-dmn/src/test/java/org/kie/kogito/dmn/DMNKogitoTest.java, drools/kogito-dmn/src/test/java/org/kie/kogito/dmn/DecisionTestUtils.java, kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java, kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionContainerGenerator.java, kogito-codegen-modules/kogito-codegen-decisions/src/test/java/org/kie/kogito/codegen/decision/CodegenUtilsTest.java, kogito-codegen-modules/kogito-codegen-decisions/src/test/java/org/kie/kogito/codegen/decision/DecisionCodegenTest.java, kogito-codegen-modules/kogito-codegen-decisions/src/test/java/org/kie/kogito/codegen/decision/DecisionContainerGeneratorTest.java, kogito-serverless-workflow/kogito-serverless-workflow-dmn-parser/src/main/java/org/kie/kogito/serverless/workflow/parser/types/DMNTypeHandler.java, springboot/addons/explainability/src/test/java/org/kie/kogito/explainability/ApplicationMock.java, springboot/addons/tracing-decision/src/test/java/org/kie/kogito/tracing/decision/BaseSpringBootDecisionTracingTest.java
Fixes https://github.com/apache/incubator-kie-issues/issues/1825
Needed by: https://github.com/apache/incubator-kie-kogito-examples/pull/2070
<details>
<summary>
</summary> …
=> [incubator-kie-issues#1825] Implementing retrieval and usage of org.kie.dmn.runtime.typecheck property.

springboot/addons/events/kafka/src/main/java/org/kie/kogito/events/spring/KafkaEventPublisher.java
Fix https://github.com/apache/incubator-kie-issues/issues/1817
=> [incubator-kie-issues#1817] Check that topic is disabled

api/kogito-api/src/main/java/org/kie/kogito/usertask/lifecycle/UserTaskLifeCycle.java, jbpm/jbpm-usertask/src/main/java/org/kie/kogito/usertask/impl/UserTaskServiceImpl.java, jbpm/jbpm-usertask/src/main/java/org/kie/kogito/usertask/impl/lifecycle/DefaultUserTaskLifeCycle.java, quarkus/integration-tests/integration-tests-quarkus-usertasks/src/test/java/org/jbpm/userTask/jpa/it/UserTaskLifeCycleIT.java, springboot/integration-tests/integration-tests-springboot-usertasks-it/src/test/java/org/jbpm/userTask/jpa/it/UserTaskLifeCycleIT.java
Fixes https://github.com/apache/incubator-kie-issues/issues/1837
Ensemble:
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3848
https://github.com/apache/incubator-kie-kogito-examples/pull/2075
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross …
=> incubator-kie-issues#1837: Ensure `DefaultUserTasksLifeCycle` checks the user Identity calculating the `allowedTransitions`

kogito-codegen-modules/kogito-codegen-decisions/src/test/resources/decision/models/vacationDays/vacationDays.dmn
Fixes https://github.com/apache/incubator-kie-issues/issues/1834
Needed by: https://github.com/apache/incubator-kie-drools/pull/6259
<details>
<summary>
</summary> …
=> [incubator-kie-issues#1834] Fixing model

springboot/archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/resources/index.html
Relates to https://github.com/apache/incubator-kie-kogito-examples/pull/2078
=> NO-ISSUE: Bump jQuery to 3.5.1

jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/impl/NodeIoHelper.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/WorkItemNodeInstance.java, jbpm/process-workitems/src/main/java/org/kie/kogito/process/workitems/impl/KogitoWorkItemImpl.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/functions/FunctionDefinitionEx.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/functions/TriFunction.java, kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/main/java/org/kie/kogito/serverless/workflow/executor/StaticFunctionWorkItemHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/test/java/org/kie/kogito/serverless/workflow/executor/StaticFluentWorkflowApplicationTest.java, kogito-serverless-workflow/kogito-serverless-workflow-fluent/src/main/java/org/kie/kogito/serverless/workflow/fluent/ActionBuilder.java, kogito-serverless-workflow/kogito-serverless-workflow-fluent/src/main/java/org/kie/kogito/serverless/workflow/fluent/FunctionBuilder.java, kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/WorkflowWorkItemHandler.java
Adds the possibility of referencing a function with two and/or three parameters in java method of the SWF fluent API
=> Adding bifunction and trifunction support to fluent api

kogito-build/kogito-dependencies-bom/pom.xml
In this PR, we upgrade Quarkus OpenAPI Generator to 2.8.2-lts. See the details here: https://github.com/quarkiverse/quarkus-openapi-generator/releases/tag/2.8.2-lts
<details>
<summary>
</summary> …
=> NO-ISSUE: Upgrade quarkus-openapi-generator to 2.8.2-lts

kogito-build/kogito-dependencies-bom/pom.xml
This fixes important vulnerabilities.
=> [No-issue] Upgrade to Spring Boot 3.4.3

README.md
Update README.md to with most recent information.
Replaces https://github.com/apache/incubator-kie-kogito-runtimes/pull/3847
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each …
=> NO_ISSUE: Update README with most recent information

quarkus/addons/pom.xml, quarkus/addons/python/integration-tests/pom.xml, quarkus/addons/python/pom.xml
This reverts commit d6fc5cffb70c2dfc0d9c0e499a8618213c988e2a.
<details>
<summary>
</summary>
[build-chain …
=> Revert "Updating Python modules (#3863)"

kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqExpression.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/ServerlessWorkflowParsingTest.java, kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/resources/exec/jqDelExpression.sw.json
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3877
=> [Fix #3877] Only propagate function not found when evaluating JQ expr

jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/LightProcessRuntimeServiceProvider.java, quarkus/extensions/kogito-quarkus-workflow-extension-common/kogito-quarkus-workflow-common/src/main/java/org/kie/kogito/quarkus/workflow/KogitoBeanProducer.java
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3869
=> [Fix #3869]  Using the same work and event manager

api/kogito-api/src/main/java/org/kie/kogito/internal/process/runtime/KogitoProcessInstance.java, api/kogito-api/src/main/java/org/kie/kogito/uow/events/UnitOfWorkProcessEventListener.java, api/kogito-events-core/src/main/java/org/kie/kogito/event/impl/adapter/AbstractDataEventAdapter.java, api/kogito-events-core/src/main/java/org/kie/kogito/event/impl/adapter/ProcessStartedEventDataEventAdapter.java
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3883
=> [Fix #3883] Fix event start date

api/kogito-events-api/src/main/java/org/kie/kogito/event/process/KogitoMarshallEventFlag.java, api/kogito-events-api/src/main/java/org/kie/kogito/event/process/KogitoMarshallEventSupport.java, api/kogito-events-api/src/main/java/org/kie/kogito/event/process/ProcessInstanceErrorEventBody.java, api/kogito-events-api/src/main/java/org/kie/kogito/event/process/ProcessInstanceNodeEventBody.java, api/kogito-events-api/src/main/java/org/kie/kogito/event/process/ProcessInstanceSLAEventBody.java, api/kogito-events-api/src/main/java/org/kie/kogito/event/process/ProcessInstanceStateEventBody.java, api/kogito-events-api/src/main/java/org/kie/kogito/event/process/ProcessInstanceVariableEventBody.java, api/kogito-events-core/src/main/java/org/kie/kogito/event/process/MultipleProcessInstanceDataEvent.java, api/kogito-events-core/src/main/java/org/kie/kogito/event/serializer/KogitoDataEventSerializationHelper.java, api/kogito-events-core/src/main/java/org/kie/kogito/event/serializer/MultipleProcessDataInstanceConverterFactory.java, api/kogito-events-core/src/main/java/org/kie/kogito/event/serializer/MultipleProcessInstanceDataEventDeserializer.java, api/kogito-events-core/src/main/java/org/kie/kogito/event/serializer/MultipleProcessInstanceDataEventSerializer.java, api/kogito-events-core/src/main/java/org/kie/kogito/event/serializer/ProcessInstanceDataEventExtensionRecord.java, api/kogito-events-core/src/test/java/org/kie/kogito/event/process/ProcessEventsTest.java, quarkus/addons/events/process/runtime/src/main/java/org/kie/kogito/events/process/GroupingMessagingEventPublisher.java
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3893
=> [Fix #3893] Fixing serialization issue when using binary mode

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/EndNodeVisitor.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/SwitchStateEventConditionBasedIT.java
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3902
The search algorithm for this visitor was too restrictive
=> [Fix #3902] Using SWFProduceEventAction for EndNodeVisitor

addons/common/jbpm-usertask-storage-jpa/src/main/java/org/jbpm/usertask/jpa/JPAUserTaskInstances.java, addons/common/jbpm-usertask-storage-jpa/src/main/java/org/jbpm/usertask/jpa/mapper/TaskInputsEntityMapper.java, addons/common/jbpm-usertask-storage-jpa/src/main/java/org/jbpm/usertask/jpa/mapper/TaskMetadataEntityMapper.java, addons/common/jbpm-usertask-storage-jpa/src/main/java/org/jbpm/usertask/jpa/mapper/TaskOutputsEntityMapper.java, addons/common/jbpm-usertask-storage-jpa/src/main/java/org/jbpm/usertask/jpa/model/AttachmentEntity.java, addons/common/jbpm-usertask-storage-jpa/src/main/java/org/jbpm/usertask/jpa/model/TaskDeadlineEntity.java, addons/common/jbpm-usertask-storage-jpa/src/main/java/org/jbpm/usertask/jpa/model/TaskDeadlineTimerEntity.java, addons/common/jbpm-usertask-storage-jpa/src/main/java/org/jbpm/usertask/jpa/model/TaskInputEntity.java, addons/common/jbpm-usertask-storage-jpa/src/main/java/org/jbpm/usertask/jpa/model/TaskMetadataEntity.java, addons/common/jbpm-usertask-storage-jpa/src/main/java/org/jbpm/usertask/jpa/model/TaskOutputEntity.java, addons/common/jbpm-usertask-storage-jpa/src/main/java/org/jbpm/usertask/jpa/model/TaskReassignmentEntity.java, addons/common/jbpm-usertask-storage-jpa/src/main/java/org/jbpm/usertask/jpa/model/TaskReassignmentTimerEntity.java, addons/common/jbpm-usertask-storage-jpa/src/main/java/org/jbpm/usertask/jpa/model/UserTaskInstanceEntity.java, addons/common/jbpm-usertask-storage-jpa/src/main/java/org/jbpm/usertask/jpa/repository/BaseRepository.java, addons/common/jbpm-usertask-storage-jpa/src/main/java/org/jbpm/usertask/jpa/repository/UserTaskInstanceRepository.java, addons/common/jbpm-usertask-storage-jpa/src/test/java/org/jbpm/usertask/jpa/JPAUserTaskInstancesTest.java, addons/common/jbpm-usertask-storage-jpa/src/test/java/org/jbpm/usertask/jpa/mapper/utils/TestUtils.java, jbpm/jbpm-usertask-workitem/src/main/java/org/kie/kogito/jbpm/usertask/handler/UserTaskKogitoWorkItemHandler.java, jbpm/jbpm-usertask/src/main/java/org/kie/kogito/usertask/impl/DefaultUserTaskInstance.java, quarkus/addons/jbpm-usertask-storage-jpa/runtime/src/test/java/org/jbpm/usertask/jpa/quarkus/BaseQuarkusJPAUserTaskInstancesTest.java, quarkus/integration-tests/integration-tests-quarkus-usertasks/src/main/resources/application.properties
Closes https://github.com/apache/incubator-kie-issues/issues/1928
<details>
<summary>
</summary>
[build-chain …
=> incubator-kie-issues#1928: UserTasks JPA Storage Reduce number of queries when storing named data

addons/common/kubernetes/src/main/java/org/kie/kogito/addons/k8s/KnativeRouteEndpointDiscovery.java, kogito-build/kogito-dependencies-bom/pom.xml, springboot/bom/pom.xml
fix for [CVE-2025-22228](https://github.com/advisories/GHSA-mg83-c7gq-rv5c), [CVE-2025-22223](https://github.com/advisories/GHSA-hh3m-g4qj-4835)
Closes https://github.com/apache/incubator-kie-issues/issues/1931
=> [kie-issues#1931] Upgrade Springboot to 3.4.5

jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java
Closes https://github.com/apache/incubator-kie-issues/issues/1964
Thanks @elguardian for spotting this issue!
=> [kie-issues#1964] Fix locking mechanism to use processinstanceid instead of workitemid

kogito-build/kogito-dependencies-bom/pom.xml
https://github.com/apache/incubator-kie-kogito-runtimes/issues/3913
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build …
=> Upgrade flyway to 11.8.0

addons/common/process-management/src/main/java/org/kie/kogito/process/management/BaseProcessInstanceManagementResource.java, addons/common/process-management/src/main/java/org/kie/kogito/process/management/ProcessInstanceManagement.java, addons/common/process-management/src/test/java/org/kie/kogito/process/management/BaseProcessInstanceManagementResourceTest.java, api/kogito-api/src/main/java/org/kie/kogito/internal/process/runtime/KogitoNodeInstance.java, api/kogito-api/src/main/java/org/kie/kogito/internal/process/runtime/KogitoWorkflowProcessInstance.java, api/kogito-api/src/main/java/org/kie/kogito/jobs/JobsService.java, api/kogito-api/src/main/java/org/kie/kogito/jobs/TimerDescription.java, api/kogito-api/src/main/java/org/kie/kogito/process/ProcessInstance.java, jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/ProcessHandler.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/timer/Timer.java, jbpm/jbpm-flow/src/main/java/org/jbpm/ruleflow/core/RuleFlowProcessFactory.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/core/node/AsyncEventNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/NodeInstanceImpl.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/WorkflowProcessInstanceImpl.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/EventNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateBasedNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/TimerNodeInstance.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcessInstance.java, quarkus/addons/process-management/integration-tests/src/main/resources/timers.bpmn, quarkus/addons/process-management/integration-tests/src/test/java/org/kie/kogito/quarkus/workflows/ProcessManagementIT.java, quarkus/addons/process-management/runtime/src/main/java/org/kie/kogito/process/management/ProcessInstanceManagementResource.java, springboot/addons/process-management/src/main/java/org/kie/kogito/process/management/ProcessInstanceManagementRestController.java, springboot/integration-tests/integration-tests-springboot-processes-it/src/main/resources/timers.bpmn, springboot/integration-tests/integration-tests-springboot-processes-it/src/test/java/org/kie/kogito/integrationtests/springboot/ManagementAddOnTest.java, springboot/integration-tests/integration-tests-springboot-processes-it/src/test/java/org/kie/kogito/integrationtests/springboot/TaskTest.java
Closes https://github.com/apache/incubator-kie-issues/issues/1975
Ensemble:
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3933
https://github.com/apache/incubator-kie-kogito-apps/pull/2225
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross …
=> [incubator-kie-issues#1975] Provide mechanism to fetch the list of timers associated to a Process Instance.

kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/transaction/ExceptionHandlerTransactionQuarkusTemplate.java, kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/transaction/ExceptionHandlerTransactionSpringTemplate.java
Closes https://github.com/apache/incubator-kie-issues/issues/1989
<details>
<summary>
</summary>
[build-chain …
=> [incubator-kie-issues#1989] Fix `NullPointerException` in `ExceptionHandlerTransaction` when setting the ProcessInstance into error state

jbpm/process-serialization-protobuf/src/main/java/org/jbpm/flow/serialization/impl/ProtobufProcessInstanceReader.java, jbpm/process-serialization-protobuf/src/main/java/org/jbpm/flow/serialization/impl/ProtobufProcessInstanceWriter.java
Fixes https://github.com/apache/incubator-kie-issues/issues/1904
=> [Fix apache/incubator-kie-issues#1904] Logging headers

quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/src/main/java/org/kie/kogito/serverless/workflow/openapi/OpenApiWorkItemHandler.java
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3947
=> [Fix #3947] Ensuring proper filter priority

addons/common/process-management/src/main/java/org/kie/kogito/process/management/BaseProcessInstanceManagementResource.java
<details>
<summary>
</summary> …
=> NO-ISSUE: Fix the log message typo: 'intances' -> 'instances'

kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegenUtils.java, kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionValidation.java, kogito-codegen-modules/kogito-codegen-decisions/src/test/java/org/kie/kogito/codegen/decision/DecisionCodegenUtilsTest.java, quarkus/addons/messaging/common/src/test/java/org/kie/kogito/addon/quarkus/messaging/common/QuarkusEventThreadPoolTest.java
Fixes https://github.com/apache/incubator-kie-issues/issues/1973
Needed by: https://github.com/apache/incubator-kie-drools/pull/6367
Needed by: https://github.com/apache/incubator-kie-benchmarks/pull/294
@fjtirado FYI: I add a timeout inside `QuarkusEventThreadPoolTest` because, for some reason, that test hanged up indefinetely while running on my local machine.
Please let me know if the timeout I set (5 minutes) is too long or too short
<details>
<summary>
</summary> …
=> [incubator-kie-issues#1973] Adapt to benchmark-related refactoring

kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/main/java/org/kie/kogito/serverless/workflow/executor/StaticEventRegister.java, kogito-serverless-workflow/kogito-serverless-workflow-executor-core/src/main/java/org/kie/kogito/serverless/workflow/executor/StaticWorkflowApplication.java
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3976
=> [Fix #3976] Allow passing ExecutorService to StaticWorkflowApplication

kogito-build/kogito-build-no-bom-parent/pom.xml, kogito-build/kogito-dependencies-bom/pom.xml, springboot/archetype/pom.xml, springboot/archetype/src/test/groovy/org/kie/kogito/springboot/archetypes/AddDependencyToPomWithTextReplaceTest.groovy, springboot/archetype/src/test/groovy/org/kie/kogito/springboot/archetypes/AddDependencyToPomWithXmlTest.groovy, springboot/bom/pom.xml
Upgrades to Spring Boot 3.4.7. 
Should be merged together with:
https://github.com/apache/incubator-kie-drools/pull/6392
=> Upgrade to Spring Boot 3.4.7. 

addons/common/jbpm-usertask-storage-jpa/src/main/resources/kie-flyway/db/user-tasks/h2/V1.0.3__jBPM_user_tasks_additional_indexes.sql, addons/common/jbpm-usertask-storage-jpa/src/main/resources/kie-flyway/db/user-tasks/postgresql/V1.0.3__jBPM_user_tasks_additional_indexes.sql
Closes https://github.com/apache/incubator-kie-issues/issues/1877
=> [kie-issues#1877] Add additional indexes to User Tasks schema to improve performance

jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ActionNodeVisitor.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/builtin/JavaConstraintEvaluatorBuilder.java, jbpm/jbpm-flow-builder/src/main/java/org/jbpm/process/builder/action/JavaActionCompiler.java, jbpm/jbpm-flow-builder/src/test/java/org/jbpm/compiler/canonical/ProcessToExecModelGeneratorTest.java
Closes: https://github.com/apache/incubator-kie-issues/issues/2004
=> [incubator-kie-issues#2004] Handle scripts that end with a comment line

addons/common/persistence/jdbc/src/test/java/org/kie/persistence/jdbc/AbstractProcessInstancesIT.java, jbpm/jbpm-usertask-workitem/src/main/java/org/kie/kogito/jbpm/usertask/handler/UserTaskKogitoWorkItemHandlerProcessListener.java
Closes https://github.com/apache/incubator-kie-issues/issues/2014
=> [kie-issues#2014] Ensure user tasks gets completed after PIM

springboot/archetype/src/main/resources/archetype-resources/src/main/resources/META-INF/resources/index.html
This PR upgrades the Bootstrap used in index.html webpage in Spring Boot archetype. The version in this PR is the latest available.
=> [NO-ISSUE] Upgrade Bootstrap in Spring Boot archetype webpage.

kogito-serverless-workflow/kogito-serverless-workflow-openapi-parser/src/main/java/org/kie/kogito/serverless/workflow/parser/rest/DescriptorRestOperationHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-openapi-parser/src/main/java/org/kie/kogito/serverless/workflow/parser/rest/JsonNodeResultHandlerSupplier.java, kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandler.java, kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandlerUtils.java, kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/resulthandlers/DefaultRestWorkItemHandlerResult.java, kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/resulthandlers/JsonNodeResultHandler.java, kogito-workitems/kogito-rest-workitem/src/test/java/org/kogito/workitem/rest/JsonResultHandlerTest.java, kogito-workitems/kogito-rest-workitem/src/test/java/org/kogito/workitem/rest/RestWorkItemHandlerTest.java, quarkus/addons/dynamic/integration-tests/src/test/java/org/kie/kogito/process/dynamic/DynamicCallResourceTest.java
Fix https://github.com/serverlessworkflow/sdk-java/issues/478
=> [Fix #3995] Overriding ResultHandler for OpenAPIParser

.gitignore, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/pom.xml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/specs/token-exchange-external-service.yaml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/token-exchange.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/KeycloakServiceMock.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/TokenExchangeExternalServicesMock.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/TokenExchangeIT.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/pom.xml, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/src/main/java/org/kie/kogito/serverless/workflow/openapi/OpenApiCustomCredentialProvider.java
Closes/Fixes/Resolves: apache/incubator-kie-issues#1894
introduce OAUTH2 token exchange
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a …
=> apache/incubator-kie-issues#1894: introduce OAUTH2 token exchange

kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/usertask/RestResourceUserTaskSpringTemplate.java
=> [incubator-kie-issues#4030]Spring Boot userTask APIs differ from Quarkus userTask APIs

addons/common/monitoring/core/src/main/java/org/kie/kogito/monitoring/core/common/process/MetricsProcessEventListener.java
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/4036
=> [Fix #4036] Restoring milliseconds fraction in seconds metric

addons/common/persistence/mongodb/src/main/java/org/kie/kogito/mongodb/MongoDBProcessInstances.java, addons/common/persistence/mongodb/src/main/java/org/kie/kogito/mongodb/utils/DocumentConstants.java, addons/common/persistence/mongodb/src/test/java/org/kie/kogito/mongodb/MongoDBProcessInstancesIT.java
Provide findByBusinessKey implementation for MongoDB
Closes/Fixes/Resolves #4038 
**Description:** Missing optimized implementation of findByBusinessKey in Mongo DB Process Instances class.
- [x ] You have read the [contributors guide](CONTRIBUTING.md)
- [ x] Your code is properly formatted according to [this configuration](https://github.com/apache/incubator-kie-kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class …
=> Fix for issue #4038 Provide optimized look up by business key for Mongo DB implementation

kogito-serverless-workflow/kogito-serverless-workflow-executor-tests/src/test/java/org/kie/kogito/serverless/workflow/executor/OpenAPIWorkflowApplicationTest.java, kogito-serverless-workflow/kogito-serverless-workflow-executor-tests/src/test/resources/spec.yaml, kogito-serverless-workflow/kogito-serverless-workflow-executor-tests/src/test/resources/stringResource.sw.json, kogito-serverless-workflow/kogito-serverless-workflow-openapi-parser/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/openapi/MediaTypeUtils.java, kogito-serverless-workflow/kogito-serverless-workflow-openapi-parser/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/openapi/OpenAPIDescriptor.java, kogito-serverless-workflow/kogito-serverless-workflow-openapi-parser/src/main/java/org/kie/kogito/serverless/workflow/parser/rest/DescriptorRestOperationHandler.java, kogito-serverless-workflow/kogito-serverless-workflow-rest-runtime/src/main/java/org/kie/kogito/serverless/workflow/rest/JsonNodeResultHandler.java, kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandler.java, kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandlerUtils.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/java/org/kie/kogito/workflows/services/StringResource.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/application.properties, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/specs/stringResource.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/stringResource.sw.json, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/ConversionFlowIT.java, quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/test/java/org/kie/kogito/quarkus/workflows/StringOpenAPIIT.java
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/4007
=> [Fix #4007] Add content type support to openapi parser

api/kogito-services/src/main/java/org/kie/kogito/services/jobs/impl/InMemoryProcessJobExecutorFactory.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/LightProcessRuntime.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/LightProcessRuntimeContext.java, jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessRuntimeContext.java, jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcess.java, jbpm/jbpm-tests/src/test/java/org/jbpm/bpmn2/StartEventTest.java, kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/java/org/kie/kogito/codegen/tests/TimerEventIT.java
This remove the duplciation of start events.
=> [NO_ISSUE] remove duplicate start events

api/kogito-api/src/main/java/org/kie/kogito/jobs/descriptors/ProcessJobDescription.java
ensemble: 
https://github.com/apache/incubator-kie-kogito-apps/pull/2259
=> [NO_ISSUE] fix_reschedule_race_condition

kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/usertask/UserTasksContainerQuarkusTemplate.java, kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/usertask/UserTasksContainerSpringTemplate.java
Lower logging level for UserTask registration from INFO to DEBUG
=> [NO-ISSUE] Lower logging level for UserTask registration

kogito-bom/pom.xml, quarkus/addons/common/kogito-addons-quarkus-common-health/.gitignore, quarkus/addons/common/kogito-addons-quarkus-common-health/pom.xml, quarkus/addons/common/kogito-addons-quarkus-common-health/src/main/java/org/kie/kogito/addon/quarkus/common/config/AbstractAliasConfigSource.java, quarkus/addons/common/kogito-addons-quarkus-common-health/src/main/java/org/kie/kogito/addon/quarkus/common/config/AbstractAliasConfigSourceFactory.java, quarkus/addons/common/kogito-addons-quarkus-common-health/src/main/java/org/kie/kogito/addon/quarkus/common/health/AbstractAvailabilityHealthCheck.java, quarkus/addons/common/kogito-addons-quarkus-common-health/src/test/java/org/kie/kogito/addon/quarkus/common/health/AbstractAvailabilityHealthCheckTest.java, quarkus/addons/common/kogito-addons-quarkus-data-index-health/.gitignore, quarkus/addons/common/kogito-addons-quarkus-data-index-health/pom.xml, quarkus/addons/common/kogito-addons-quarkus-data-index-health/src/main/java/org/kie/kogito/addon/quarkus/index/health/DataIndexAvailabilityHealthCheck.java, quarkus/addons/common/kogito-addons-quarkus-data-index-health/src/main/java/org/kie/kogito/addon/quarkus/index/health/DataIndexAvailabilityHealthCheckConfigSource.java, quarkus/addons/common/kogito-addons-quarkus-data-index-health/src/main/java/org/kie/kogito/addon/quarkus/index/health/DataIndexAvailabilityHealthCheckConfigSourceFactory.java, quarkus/addons/common/kogito-addons-quarkus-data-index-health/src/main/resources/META-INF/beans.xml, quarkus/addons/common/kogito-addons-quarkus-data-index-health/src/main/resources/META-INF/services/io.smallrye.config.ConfigSourceFactory, quarkus/addons/common/kogito-addons-quarkus-data-index-health/src/test/java/org/kie/kogito/addon/quarkus/index/health/DataIndexServiceAvailabilityHealthCheckTest.java, quarkus/addons/common/kogito-addons-quarkus-jobs-service-health/.gitignore, quarkus/addons/common/kogito-addons-quarkus-jobs-service-health/pom.xml, quarkus/addons/common/kogito-addons-quarkus-jobs-service-health/src/main/java/org/kie/kogito/addon/quarkus/jobs/health/JobsServiceAvailabilityHealthCheck.java, quarkus/addons/common/kogito-addons-quarkus-jobs-service-health/src/main/java/org/kie/kogito/addon/quarkus/jobs/health/JobsServiceAvailabilityHealthCheckConfigSource.java, quarkus/addons/common/kogito-addons-quarkus-jobs-service-health/src/main/java/org/kie/kogito/addon/quarkus/jobs/health/JobsServiceAvailabilityHealthCheckConfigSourceFactory.java, quarkus/addons/common/kogito-addons-quarkus-jobs-service-health/src/main/resources/META-INF/beans.xml, quarkus/addons/common/kogito-addons-quarkus-jobs-service-health/src/main/resources/META-INF/services/io.smallrye.config.ConfigSourceFactory, quarkus/addons/common/kogito-addons-quarkus-jobs-service-health/src/test/java/org/kie/kogito/addon/quarkus/jobs/health/JobsServiceAvailabilityHealthCheckTest.java, quarkus/addons/common/pom.xml, quarkus/addons/jobs/knative-eventing/runtime/pom.xml, quarkus/addons/knative/eventing/runtime/pom.xml
- restores data-index and jobs service availabitly checks that 1) works fine, 2) are diabled by default and only used in the knative-eventing addon, and 3) where removed by notifying nobody
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and …
=> [NO-ISSUE] restore Kogito data-index and job-service availability health checks
